### ISSUE TITLE
Immediate SIGABRT/dyld`__abort_with_payload after integrating 3.8.0 with SPM only on iOS versions < iOS15

### ISSUE THREAD

**Issue by crow** [OneSignal/OneSignal-iOS-SDK#1002]
**Description:**
I get an immediate dyld`__abort_with_payload: crash when I add the OneSignal package to my project - but only when running on devices using iOS 14 and 13 (Not on iOS 15). I'm able to get the integration working without any issues as long as I run on an iOS15 device. I was able to back out all the changes and track the issue to the SDK installation via SPM.

**Environment**
1. What version of the iOS SDK are you using?
3.8.0
2. How did you add the SDK to your project (eg. cocoapods)
SPM

**Steps to Reproduce Issue:**
  1. Install iOS SDK version 3.8.0 with SPM into a mixed Swift/ObjC project
  2. Run application on an iOS 15 device and observe successful launch
  3. Run application on an iOS 14 device and observe an immediate dyld`__abort_with_payload:

**Anything else:**
The entirety of the in-Xcode trace:
![image](https://user-images.githubusercontent.com/2199816/134585714-0330d049-2cda-4b5a-9ecf-2e476090fbf1.png)
![image](https://user-images.githubusercontent.com/2199816/134585737-35050689-f470-4570-a3ce-e21926db5345.png)
![image](https://user-images.githubusercontent.com/2199816/134585764-6570a1e6-eff9-4b5f-adaf-40de0d8306d8.png)

Errors and faults on launch:
![image](https://user-images.githubusercontent.com/2199816/134586082-3c001697-3f09-4f15-a4df-caabb3ca3b74.png)

**Comment by emawby** [comment]
@crow Hello thank you for reporting. Does the issue go away if you use an earlier version of OneSignal? I am not able to reproduce this issue on my own devices that are on iOS 14

**Comment by crow** [comment]
Same thing with 3.6.1 and 2.16.6 integrated via SPM. 

- iPad Pro iOS 13.5.1: Immediate SIGABRT as described
- iPhone X iOS 15.0.0: launches and runs fine

Is there any particular previous SDK I should try that still supports SPM?

I'll try manually integrating an SDK version or two to see if it's an SPM thing.

**Comment by emawby** [comment]
@crow No they all should work and I have not heard of this issue before. Have you confirmed that removing OneSignal entirely fixes the issue? Do you have an example project with this issue that I could test with?

**Comment by crow** [comment]
Removing OneSignal fixes the issue, it's pretty clear that the addition of the framework causes the problem (and only for <iOS15, on iOS15 it works fine). I don't have an example project to give you because it appears that the issue is caused by a combination of dependencies that's unique to the complete project. Same thing occurs with the OneSignalXCFramework package.

**Comment by crow** [comment]
@emawby The issue appears to be with Xcode 13.0.0. If I rebuild my app in 12.5.1 the issue resolves.
