### ISSUE TITLE
Getting errors while uploading to the App Store

### ISSUE THREAD

**Issue by boryst** [OneSignal/OneSignal-iOS-SDK#1004]
**Description:**
After switching from cocoapods to SPM I'm getting errors when uploading to the AppStore. I did "pod install" to remove the pod files before adding SPM. Issue happens when I have OneSignal framework added for the notification extension. If I remove it - extension wont compile. 
![Issue](https://user-images.githubusercontent.com/1310397/135148104-b78f1924-35ae-43b3-b814-65acbf0ccb93.png)

**Environment**
Xcode 13.0
iOS SDK 3.8.0 and I tried with 3.8.1.
Added through SPM
Other frameworks in the project:
SPM: Kingfisher, SkeletonView, Firebase, NVActivityIndicatorView, Reachability
Pods: KYDrawerController, SwiftLint, TLKit

**Steps to Reproduce Issue:**

1. Follow "Swift Package Manager Setup" https://documentation.onesignal.com/docs/swift-package-manager-setup
2. Try to upload build to the app store

**Comment by emawby** [comment]
@boryst Hello please see the pinned issue in our [OneSignal-XCFramework](https://github.com/OneSignal/OneSignal-XCFramework/issues/10) repository for a fix for this
