### ISSUE TITLE
In app local notifications

### ISSUE THREAD

**Issue by kamendo** [OneSignal/OneSignal-iOS-SDK#101]
Can I use the SDK to present local notifications while the app is in foreground?

**Comment by soheilbm** [comment]
I believe you can add "**kOSSettingsKeyInAppAlerts**" into your OneSignal LaunchOption. 

```
OneSignal.initWithLaunchOptions(nil,
                                        appId: "ID",
                                        handleNotificationAction: nil,
                                        settings: [kOSSettingsKeyAutoPrompt:true, 
                         kOSSettingsKeyInAppAlerts: false, 
                         kOSSettingsKeyInFocusDisplayOption: OSNotificationDisplayType.inAppAlert.rawValue])`

**Comment by JKalash** [comment]
Hi there,

kOSSettingsKeyInAppAlerts has been deprecated. You should use instead `kOSSettingsKeyInFocusDisplayOption : @(InAppAlert)`. More details found [here](https://documentation.onesignal.com/docs/ios-native-sdk#section--kossettingskeyinfocusdisplayoption-).
