### ISSUE TITLE
CocoaPods iOS Deployment Target

### ISSUE THREAD

**Issue by Petr-Kubista** [OneSignal/OneSignal-iOS-SDK#1011]
**Description:**

When building a project including OneSignalXCFramework pod, I'm getting these warnings:
`warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99.`
even though your readme says support is from 9.0 up.

**Environment**

Project's deployment target is set to 11.0
Integrating OneSignal via CocoaPods

**Steps to Reproduce Issue:**

1. Install iOS SDK version 3.8.1 with CocoaPods into a project
2. Build/see Pods.xcodeproj OneSignalXCFramework target's build settings for iOS Deployment Target

**Comment by emawby** [comment]
@Petr-Kubista Hello can you please share your podfile

**Comment by Petr-Kubista** [comment]
Hello @emawby, I have since moved from CocoaPods to SPM, so I can't really check any more. Sorry I couldn't help investigating any more.

**Comment by emawby** [comment]
Closing for now!
