### ISSUE TITLE
"Apns Delegate Never Fired" while using Firebase Auth with and without swizzling 

### ISSUE THREAD

**Issue by moonvader** [OneSignal/OneSignal-iOS-SDK#1025]
I have issue with OneSignal push notifications for iOS app after I added Firebase Auth with phone. All iOS devices listed in OneSignal are marked with "Apns Delegate Never Fired" label and notifications can be sended but app don't receive them.

I found two similar issues

[Firebase Phone Auth - OneSignal Compatibility Conflict OneSignal-iOS-SDK#790](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/790)
[Conflict between OneSignal and Firebase Phone Auth #245](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/245)

As I understand the problem might be with swizzling that is used by Firebase Auth. I disabled swizzling using info.plist file as it suggested in the official firebase docs. But issue remains, so I think that I am missing something and OneSignal SDK still not being called.

My AppDelegate file looks like

```
override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
           Auth.auth().setAPNSToken(deviceToken, type: AuthAPNSTokenType.unknown)
 }

 override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {

           if Auth.auth().canHandleNotification(userInfo) {
               completionHandler(.noData)
               return
           }
}
```

**Comment by emawby** [comment]
@moonvader I apologize for the late reply in this. As a debugging step can you tell me if the status for those devices is different if you comment out:
```
override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
           Auth.auth().setAPNSToken(deviceToken, type: AuthAPNSTokenType.unknown)
 }
```

**Comment by emawby** [comment]
Closing for now. Please feel free to reopen if this is still an issue
