### ISSUE TITLE
Onesignal - IOS device not receive Notification

### ISSUE THREAD

**Issue by realx94** [OneSignal/OneSignal-iOS-SDK#1038]
**Description:**

Hello everyone, I try to implement OneSignal Notification for IOS
I had followed OneSignal document but the IOS device didn't receive the notification.
Please help me!! Thanks

I added Notification Service Extension
I added Required Capabilities
I added App Groups
I added certification
Ref: document https://documentation.onesignal.com/docs/ios-sdk-setup

**Environment**
I used SDK 3.10

**Steps to Reproduce Issue:**
Ref: document https://documentation.onesignal.com/docs/ios-sdk-setup

below attachment is code i was implement and the log
https://notepad.vn/1JXTcry53
Password: 1JXTcry53
![Screen Shot 2022-01-06 at 14 36 08](https://user-images.githubusercontent.com/12102840/148350191-2d50818e-e8b2-45b2-a6c9-2d7eaabae39f.png)
<img width="1408" alt="Screen Shot 2022-01-06 at 14 36 37" src="https://user-images.githubusercontent.com/12102840/148350214-de6ed19e-8e2c-4cae-ad11-85e8d50768d5.png">

**Comment by emawby** [comment]
@realx94 Hello, thank you for reaching out! Are you seeing your device in the Audience -> All Users tab of the OneSignal dashboard? If so is the device subscribed? Also note that iOS simulators cannot receive push notification so make sure you are using a physical device

**Comment by realx94** [comment]
> @realx94 Hello, thank you for reaching out! Are you seeing your device in the Audience -> All Users tab of the OneSignal dashboard? If so is the device subscribed? Also note that iOS simulators cannot receive push notification so make sure you are using a physical device

I can see the device in all users, it has push token and the device was subscribed. My d> @realx94 Hello, thank you for reaching out! Are you seeing your device in the Audience -> All Users tab of the OneSignal dashboard? If so is the device subscribed? Also note that iOS simulators cannot receive push notification so make sure you are using a physical device.

I can see the device in all users, it has push token ​and the device was subscribed. My device is physical device.
When i push notification to device then delivery status is always fail.
Thanks.

**Comment by realx94** [comment]
- Updated
I use pod 'OneSignal' then the notification works. But follow the document OneSignalXCFramework then it isn't work

**Comment by emawby** [comment]
@realx94 I am glad you got it working using OneSignal at least. Can you provide more information on what you changed? Did you just change the pod name from OneSignalXCFramework to OneSignal?

**Comment by realx94** [comment]
@emawby I don't know. I do a lot of stuff. 
But I think when I change to OneSignal then the normal notification works.
And when I implement VoIP then I miss sending a request to add the second device with a VoIP token.
Anyway, Thank you for helping.
I will close this topic.
