### ISSUE TITLE
Background Task was created over 30 seconds ago

### ISSUE THREAD

**Issue by piroznoe** [OneSignal/OneSignal-iOS-SDK#1047]
**Description:**

SDK works fine, but console throws error 

> [BackgroundTask] Background Task 25 ("Called by OneSignal, from +[OneSignalLocation beginTask]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

**Environment**
1. 3.9.1, 3.10.1
2. pod 'OneSignalXCFramework'

**Steps to Reproduce Issue:**
1. run application with SDK installed 
2. move application from foreground 
3. console throws issue after 30 sec

**Comment by emawby** [comment]
@piroznoe Thank you for reporting. Is this resulting in the app being terminated in the background or is it just a console error?
