### ISSUE TITLE
OneSignal blocks app's -[UIApplicationDelegate application:handleActionWithIdentifier:forLocalNotification:withResponseInfo:completionHandler:]

### ISSUE THREAD

**Issue by nixxcode** [OneSignal/OneSignal-iOS-SDK#105]
With the OneSignal SDK installed and running on iOS 10, the app's `-[UIApplicationDelegate application:handleActionWithIdentifier:forLocalNotification:withResponseInfo:completionHandler:]` implementation is not called when a user uses the iOS 9+ inline reply feature to interact with a `UILocalNotification`.

This happens because OneSignal sets itself as the `UNUserNotificationCenter`'s delegate - which means iOS no longer calls the now-deprecated `-[UIApplicationDelegate application:handleActionWithIdentifier:forLocalNotification:withResponseInfo:completionHandler:]`

**Comment by jkasten2** [comment]
@nixxcode We strive to prevent event behavior changes to apps when our SDK. We will see what we can do to fix this in a future release.

In the mean time a believe you can use the following new iOS 10 selector.
`userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:`
https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter?language=objc

Thanks.

**Comment by jkasten2** [comment]
@nixxcode Just fixed this in commit 381c5ac8486e54ea1bffd39d73515bab9a977cbc which is now released in version 2.2.2.
