### ISSUE TITLE
How to avoid open Launch URL using http prefix in webview?

### ISSUE THREAD

**Issue by sidneivl** [OneSignal/OneSignal-iOS-SDK#1051]
**Description:**
Hi,

Today OneSignal SDK open Launch URL in App WebView or on Safari using setLaunchURLsInApp(false).

But I want intercept any URL through Launch URL to redirect to specific screen into my App.

Today I need use a custom prefix to intercept it:

```
blockHanderNotification = { [weak self] (result) in
  let notification: OSNotification? = result.notification
            
  if let appUrl = notification?.launchURL {
    let urlString = appUrl.replacingOccurrences(of: "app", with: "https")
      self?.showArticle(with: urlString, publicUrl: urlString)
    } else {
      debugPrint("PUSH URL not found! \(#function)")
    }
}
```

Is There way to do something like that?

Thanks

**Environment**
SDK version 3.10.0
integration via cocoapods

**Comment by jkasten2** [comment]
@sidneivl It sounds like you want to completely control what launch URL does. You can prevent OneSignal from processing the URL at all by setting `OneSignal_suppress_launch_urls` to `true` in your `.plist`. See this doc for more details:
https://documentation.onesignal.com/docs/links#launch-url

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool supporting ios15 and ios16
Support the removal of dylib dynamic library
Completely free, permanently free!
https://urlzs.com/44zCx

**Comment by sidneivl** [comment]
@jkasten2 that's it!
I Didn't know about this parameter, we were using old version of lib, now we updated and work like a charm!
Thanks
