### ISSUE TITLE
ERROR ITMS-90085: No architectures in the binary.

### ISSUE THREAD

**Issue by sidneivl** [OneSignal/OneSignal-iOS-SDK#1052]
**Description:**
I've replaced old lib OneSignal to use XCFramework in more than one project, both in SPM and cocoapods when try to upload to TestFlight using Fastlane I got the same error:

```
[!] Error uploading ipa file: 
[Transporter Error Output]: ERROR ITMS-90085: No architectures in the binary. Lipo failed to detect any architectures in the bundle executable.
[Transporter Error Output]: Return status of iTunes Transporter was 1: ERROR ITMS-90085: No architectures in the binary. Lipo failed to detect any architectures in the bundle executable.
[Transporter Error Output]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

I tried remove and add again the extension, the lib, reintegrate CocoaPods, clean derivate data and I got same error.

If I return to old branch or remove OneSignal from the project everything works

Anyone know about this issue?

**Environment**
1. OneSignalXCFramework (3.10.1)
2. In Both SPM and CocoaPods
3. Xcode 13.2 (13C90)

**Steps to Reproduce Issue:**
 1. Install XCFramework
  2. Added Extension
  3. Try to upload using fastlane using this command:
  
```
build_app(scheme: app_target, export_options:{ manageAppVersionAndBuildNumber: false })
upload_symbols_to_crashlytics(dsym_path: app_dSYM)
upload_to_testflight(skip_waiting_for_build_processing: true)
```

**Comment by emawby** [comment]
@sidneivl Thank you for reaching out can you explain how you are using both Cocoapods and SPM at the same time? Which are you using to add the OneSignal dependency?

**Comment by sidneivl** [comment]
@emawby I have more than one project, to be clear, today I maintain 3 project using cocoapods and a new one using just SPM.

In cocoas I'm using to add dependency:
`pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'`
And
```
abstract_target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  
  target 'OneSignalNotificationServiceExtension_GloboMaisDEV' do
  end
  
  target 'OneSignalNotificationServiceExtension_GloboMaisPROD' do
  end
end
```

And the app using SPM I'm using:
https://github.com/OneSignal/OneSignal-XCFramework range 3.0.0 - 4.0.0

Both in one and the other I'm facing this issue
I've tried change the bitcode, added exclude archs and nothing change the situation.

Read a lot of "solutions" but anyone resolve it.

**Comment by sidneivl** [comment]
I found the problem.

I've moved the file Notification service to other folder and try change the NSExtensionPrincipalClass to new path, but it not worked.

So, the solution was move back the file to folder created when you add an extension.
