### ISSUE TITLE
functional testing of additional data using simulator

### ISSUE THREAD

**Issue by musatrtr** [OneSignal/OneSignal-iOS-SDK#1053]
I am trying to test notifications with simulator. I create an apns file, notification appears properly but _OSNotificationOpenedBlock_ is not triggered. What is missing? How can I achieve getting additional data in apns?

Here is the .apns file that I created;

```
{
    "Simulator Target Bundle": "com.app.bundleID",
    "aps": {
        "alert": {
            "title": "Test Push Notification Title",
            "subtitle": "Test Push Notification Subtitle",
            "body" : "Test Push Notifications Body",
        }
    },
    "custom": {
        "i": "notificationId",
        "a": { "key": {"key": "value"} },
        "collapse_id": "collapseId",
    }
}
```

I save this as push.apns, then drag over the simulator. It shows the notification and when I tap the notifications, the app is opened. However, I cannot get this payload anywhere in the app.

**Comment by jkasten2** [comment]
@musatrtr Thanks for reporting. Just to confirm this is the Apple iOS testing feature you are using to generate the notification?
https://developer.apple.com/documentation/watchkit/notifications/testing_custom_notification_interfaces

If so the OneSignal SDK does validate the payload, it must include `"custom": { "i": "UUID" }`. Make sure `notificationId` is a UUID. It is possible something else is being checked, and you would have to check the SDK source to confirm this.

The other possibility is that this method of testing does not set the type of notification as remote, this is something I believe the OneSignal SDK might check.

**Comment by musatrtr** [comment]
Thank you @jkasten2 I was not trying that feature to generate the notification. I created an apns. Then, I drag & drop over the simulator. But you are right, it was only including "a": "additional data" but not "I". I added "i" and it worked. I also published how I made it in [this article](https://medium.com/plus-minus-one/testing-onesignal-push-notifications-on-the-simulator-ee23ceb1e9f1).
