### ISSUE TITLE
hello, use M1 simulator build

### ISSUE THREAD

**Issue by Xcode123456** [OneSignal/OneSignal-iOS-SDK#1058]
error ld: in /Users/pohanlee/Desktop/git/OKEx/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/pohanlee/Desktop/git/OKEx/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by emawby** [comment]
@Xcode123456 Hello please use our XCFramework version of the Cocoapod (OneSignalXCFramework) instead of OneSignal to fix this issue. If you are using SwiftPM please use the OneSignal-XCFramework repository instead of OneSignal-iOS-SDK
