### ISSUE TITLE
3.9.1 introduced issue with subscriptions, not present in 3.8.1

### ISSUE THREAD

**Issue by pdswllc** [OneSignal/OneSignal-iOS-SDK#1059]
Well, I have not had time to root cause the exact tag but I do know that the issue is in 3.9.1 but not 3.8.1

**Description:**
`OneSignal.disablePush(false` not working on 3.9.1. User not automatically set to subscribed after prompting either.

Hello, I noticed that after prompting the user for a notification in 3.9.1, 

(your description here)

**Environment**

cocoapods

**Steps to Reproduce Issue:**

```
Note the two methods:
```
func isUserSubscribedToPushNotifications() -> Bool {
    let status = OneSignal.getDeviceState()
    return status?.isSubscribed ?? false
}

func doesUserHaveNotificationsPermission() -> Bool {
    let status = OneSignal.getDeviceState()
    return status?.hasNotificationPermission ?? false
}

On 3.9.1

```

OneSignal.promptForPushNotifications(userResponse: { accepted in
                                if accepted {
                                    print("User accepted notifications: \(accepted)")
                                    OneSignal.disablePush(false)
                                    dailyNotificationsEnabled = isUserSubscribedToPushNotifications()
                                } else {
                                    dailyNotificationsEnabled = isUserSubscribedToPushNotifications()
                                }
                            })
```
After calling this method and accepting the prompt, the following was found via breakpoints in the above completion block

```
po isUserSubscribedToPushNotifications() -> false
po doesUserHaveNotificationsPermission() -> true
```

On 3.8.1, the `OneSignal.disablePush(false)` actually does work, and after doing so the output is

```
po isUserSubscribedToPushNotifications() -> true
po doesUserHaveNotificationsPermission() -> true
```

**Comment by pdswllc** [comment]
Err actually I see a similar issue on 3.8.1, is there any guidance on how to call the subscription methods from SwiftUI views?

**Comment by Jay-Deshpande** [comment]
Having the same issue...any advice/fix?

**Comment by emawby** [comment]
@pdswllc Thank you for reaching out. What is the behavior if you do not call `OneSignal.disablePush(false)` in the user response block. Is push not be automatically enabled in that case?

**Comment by pdswllc** [comment]
@emawby thanks for the reply.

I just tried with the 3.9.1 library installed, and not calling `OneSignal.disablePush(false)`.

This is essentially the code that I placed a Breakpoint inside:

```
OneSignal.promptForPushNotifications(userResponse: { accepted in
                                if accepted {
BP ->                             print("User accepted notifications: \(accepted)")
//                                    DispatchQueue.main.async {
//                                        OneSignal.disablePush(false)
//                                    }
                                }
                                dailyNotificationsEnabled = isUserSubscribedToPushNotifications()
                            })
```


```
(lldb) po isUserSubscribedToPushNotifications()
false

false

(lldb) po accepted
true

(lldb) po accepted
true

(lldb) po doesUserHaveNotificationsPermission()
true
```

**Comment by pdswllc** [comment]
It just started working for me after I cleaned and restarted. I had already tried the same a few times, but for some reason this time it worked. I am not entirely sure what was happening but I will close this for now
