### ISSUE TITLE
Unrecognized selector sent to instance with Windev Mobile

### ISSUE THREAD

**Issue by tplantepgsolutions** [OneSignal/OneSignal-iOS-SDK#1063]
**Description:**
When I create a app with Windev Mobile 27, I have an error in the main.m when I integrate Onesignal with cocoapod.
I have a "uncaught exception 'NSInvalidArgumentException', reason: '-[OSUNUserNotificationCenterDelegate appStarted]: unrecognized selector sent to instance" error

**Environment**
1. SDK Version 3.10.1
2. Added via cocoapods
3. iOS Device 13.2.3
4. Xcode version : 13.2
5. Windev Mobile 27 for create my project
6. In Windev Mobile use method GPSState or PushNotifActive

**Steps to Reproduce Issue:**
  1. Install iOS SDK version 3.10.1 with Cocoapods into a project
  2. Initialize the SDK in didFinishLaunchingWithOptions
  3. Integrate GPSState or PushNotifActive in Windev Mobile
  4. App crash when open my app when my main.m is called

When I create a app with Windev Mobile 27, I have an error in the main.m when I integrate Onesignal with cocoapod. I read all documentation in ios sdk and I put exacly the same code I have this problem when I use GPSState or PushNotifActive

Documentation of Windev Mobile for GPSState
[https://doc.windev.com/en-US/?1000019207&verdisp=160](url)
Documentation of Windev Mobile for PushNotifActive
[https://doc.windev.com/en-US/?1000020816&verdisp=160](url)

My code of my main.m

`
  #import <UIKit/UIKit.h>
  
  int main(int argc, char *argv[]) {
      NSAutoreleasePool * pool = [[NSAutoreleasePool alloc] init];
      int retVal = UIApplicationMain(argc, argv, nil, @"WDAppDelegate");
      [pool release];
      return retVal;
  }
`

My code didFinishLaunchingWithOptions in my WDAppDelagate.mm:
#import <UIKit/UIKit.h>

int main(int argc, char *argv[]) {
    NSAutoreleasePool * pool = [[NSAutoreleasePool alloc] init];
    NSLog(@"Enter Main");
    int retVal = UIApplicationMain(argc, argv, nil, @"WDAppDelegate");
    [pool release];
    NSLog(@"End Main");
    return retVal;
}

This is code of my RunApplication in WDAppDelagate.mm generate by Windev mobile:
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions 
{
	bBackground = NO;
	[self RunApplication :launchOptions];
    NSLog(@"didFinishLaunchingWithOptions");
    // Remove this method to stop OneSignal Debugging
	[OneSignal setLogLevel:ONE_S_LL_VERBOSE visualLevel:ONE_S_LL_NONE];
	 
	// OneSignal initialization
	[OneSignal initWithLaunchOptions:launchOptions];
	[OneSignal setAppId:@"MYAPPID"];

	// promptForPushNotifications will show the native iOS notification permission prompt.
	// We recommend removing the following code and instead using an In-App Message to prompt for notification permission (See step 8)
	[OneSignal promptForPushNotificationsWithUserResponse:^(BOOL accepted) {
	  NSLog(@"User accepted notifications: %d", accepted);
	}];
	
    
    return YES;
}

This is code of my RunApplication in WDAppDelagate.mm generate by Windev mobile:

- (void)RunApplication:(NSDictionary *)launchOptions {
    if(bBackground)
	{
		[self TerminateApplication];
	}
	InitAppLaunchOptions(launchOptions);
	InitInstance();
	InitInternalLanguage(12);
	InitModule(&gstMyModuleInfo1);
	InitModule(&gstMyModuleInfo3);
	InitModule(&gstMyModuleInfo4);
	InitModule(&gstMyModuleInfo5);
	InitModule(&gstMyModuleInfo6);
	InitModule(&gstMyModuleInfo7);
	InitModule(&gstMyModuleInfo8);
	InitModule(&gstMyModuleInfo9);
	InitModule(&gstMyModuleInfo10);
	InitModule(&gstMyModuleInfo26);
	InitModule(&gstMyModuleInfo28);
	InitModule(&gstMyModuleInfo29);
	InitModule(&gstMyModuleInfo37);
	InitModule(&gstMyModuleInfo42);
	InitModule(&gstMyModuleInfo59);
	InitModule(&gstMyModuleInfo60);
	InitModule(&gstMyModuleInfo61);
	InitModule(&gstMyModuleInfo68);
	InitModule(&gstMyModuleInfo69);
	DEVICE_InitNotification();
	InitModule(&gstMyModuleInfo70);
	InitExec();
	InitNativeCall(NativeCalls,8);
	LoadWDLFile(@"MyProjectName");

	CGRect screenBounds = [ [ UIScreen mainScreen ] bounds ];
	window = [ [ UIWindow alloc ] initWithFrame: screenBounds ];
	OBJ_InitIOS(window);
	[window makeKeyAndVisible];
	bBackground = NO;
    
}

Trace with my real device
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[OSUNUserNotificationCenterDelegate appStarted]: unrecognized selector sent to instance 0x282b802c0'

Trace with the simulator
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[OSUNUserNotificationCenterDelegate appStarted]: unrecognized selector sent to instance 0x600000d0c2b0'
terminating with uncaught exception of type NSException

Sorry for my formatted code, the tag not work for me.

Thank's

**Comment by emawby** [comment]
@tomsawyer34 Hello I am not familiar with Windev mobile, but do you know where the appStarted call is coming from? There are no references to appStarted in this repository that I can find, nor in Apple's documentation

**Comment by emawby** [comment]
closing for now. Please feel free to reopen if you are still having issues!
