### ISSUE TITLE
Update Badge Number after clearing notification area

### ISSUE THREAD

**Issue by raysango** [OneSignal/OneSignal-iOS-SDK#107]
When clearing the notification from the notifications area it doesn't update the badge count, It is working correctly on Android but not on iOS

**Comment by jkasten2** [comment]
@raysango Badges are controlled fundamentally different between the two platforms. On iOS the badge value is sent with each notification (only when the option is enabled) and does not match the current number of notifications shown.

On Android there currently isn't an option to have the SDK set a number like iOS. The SDK simply tacks the number of notifications internally and updates the badge value on each notification status change.

Thanks.

**Comment by raysango** [comment]
@jkasten2 got it, thanks.
