### ISSUE TITLE
Issue while migrating app from `2.12.5` to `3.11.0`

### ISSUE THREAD

**Issue by taraspasichnyk** [OneSignal/OneSignal-iOS-SDK#1084]
**Description:**
1. Our old Cordova application uses a version `2.12.5`.
2. We are migrating to native instead.
3. We install `3.11.0` on top of it and it crashes after launch every time right after calling:
`OneSignal.initWithLaunchOptions(launchOptions)`
4. When using `3.4.3` instead of `3.11.0`, it does not crash.

(your description here)

**Environment**
1. `2.12.5`, `3.11.0`, `3.4.3`
2. SDK is added via cocoapods `pod 'OneSignalXCFramework'`, currently specifying a `3.4.3` as exact version because it does not crash.
3. Steps: 
  1. Install iOS SDK version `2.12.5` with Cocoapods into a project
  2. Initialize the SDK in didFinishLaunchingWithOptions:
  3. Register for push notifications
  4. Close the app and install iOS SDK version `3.11.0` with Cocoapods
  5. Launch the app and call `OneSignal.initWithLaunchOptions`

**Anything else:**
```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1d08 objc_msgSend + 8
1  OneSignal                      0x42300 +[OneSignalLocation internalGetLocation:fallbackToSettings:] + 332
2  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
3  libdispatch.dylib              0x3bab8 _dispatch_continuation_pop$VARIANT$armv81 + 432
4  libdispatch.dylib              0x4d16c _dispatch_source_invoke$VARIANT$armv81 + 1560
5  libdispatch.dylib              0x457ac _dispatch_main_queue_drain + 716
6  libdispatch.dylib              0x454d0 _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 36
7  CoreFoundation                 0x4dab4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
8  CoreFoundation                 0xafd8 __CFRunLoopRun + 2544
9  CoreFoundation                 0x1dc30 CFRunLoopRunSpecific + 572
10 GraphicsServices               0x1988 GSEventRunModal + 160
11 UIKitCore                      0x4e5c50 -[UIApplication _run] + 1080
12 UIKitCore                      0x27f3d0 UIApplicationMain + 336
13 GrabNGo                        0x482a4 main + 16 (AppDelegate.swift:16)
14 ???                            0x1050783d0 (Missing)
```

**Comment by MohammedBadr20s** [comment]
same happens with me

**Comment by emawby** [comment]
@MohammedBadr20s Are you also using cordova? Could you post a stack trace?

**Comment by taraspasichnyk** [comment]
@emawby , we are migrating from cordova to native. Added a stacktrace that finally got to Firebase to original message.

**Comment by jkasten2** [comment]
@taraspasichnyk Do you also get this crash if you first uninstall the app before upgrading your app to 3.11.0? This will help rule out if this has to do with upgrading logic in the SDK.

**Comment by dsmailes** [comment]
@jkasten2 can confirm I'm seeing similar behaviour in our SwiftUI application. Uninstalling the app first does prevent the crash. Happy to help with more details if needed.

**Comment by tadegol** [comment]
> @jkasten2 can confirm I'm seeing similar behaviour in our SwiftUI application. Uninstalling the app first does prevent the crash. Happy to help with more details if needed.

that's correct, it's a hotfix in simulator and device.
