### ISSUE TITLE
No such module 'OneSignal'

### ISSUE THREAD

**Issue by ahmedsafadii** [OneSignal/OneSignal-iOS-SDK#1085]
**Description:**
I follow the guide about setup the Onesignal using SPM and it works good, but when i start archive the version, i got an error which is 'No such module 'OneSignal'' for the extension target and not for the main target

**Steps to Reproduce Issue:**
  Install iOS SDK version with SPM master branch
  2. Initialize the SDK in didFinishLaunchingWithOptions:
  3. Follow the guide here 
  4. https://documentation.onesignal.com/docs/swift-package-manager-setup
  5. Then archive

  (write below this line) -->

  1. Install iOS SDK version with SPM master branch
  2. Initialize the SDK in didFinishLaunchingWithOptions:
  3. Follow the guide here 
  4. https://documentation.onesignal.com/docs/swift-package-manager-setup
  5. Then archive

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by emawby** [comment]
@ahmedsafadii Thank you for reaching out. The Swift Package recently changed so it would be helpful to see more details about your setup.
1. Are you using this repository or the OneSignal-XCFramework repository?
2. In your NotificationService file are you importing OneSignal or OneSignalExtension?
3. In your Notification Service Extension's Frameworks and Libraries did you add OneSignal or OneSignalExtenion?
4. If not did you updated the runpath search paths as mentioned in the guide?

**Comment by ahmedsafadii** [comment]
1- Yes
2- I try both and both are not working for the archive.
3- Yes
4- Yes I update it.

**Comment by emawby** [comment]
Hmmm I am not able to reproduce this. Could you clarify for question 3 which you are using? OneSignal or OneSignalExtension? And can you show your "frameworks and libraries" for the Notification Service Extension target as well as the runpath search paths?

**Comment by buluoray** [comment]
I ran into the same issue, I can build and run on device but can't archive it due to module not found on notification extension

**Comment by personafiGuy** [comment]
Might have to do with the versioning of 13.2 for xcode @emawby. Can you see if that might be the issue?

**Comment by emawby** [comment]
@personafiGuy When using xcode 13.2.1 I am not having issues archiving, but maybe upgrading Xcode would help. I have a suspicion that updating xcode versions just cleaned all cached and derived data, but it could be that they made a change
