### ISSUE TITLE
[question]: Need help with cocoapods integration

### ISSUE THREAD

**Issue by Sergozh** [OneSignal/OneSignal-iOS-SDK#1093]
### How can we help?

I have pods file like this:

```
target 'Main iOS App' do
    pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'

  target 'OneSignalNotificationServiceExtension' do
    use_frameworks!
    pod 'OneSignalXCFramework/OneSignalExtension', '>= 3.0.0', '< 4.0'
  end

    pod 'Moya'
    pod 'KeychainAccess'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/RemoteConfig'
    pod 'Amplitude', '~> 8.0'
    pod 'Firebase/Analytics'
end
```

And I meet issue when all pods where integrated onto nested `OneSignalNotificationServiceExtension` target. Could you help to resolve this issue?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@Sergozh Could you provide the error or exact issue you are seeing? Please also share your the full contains of your `Podfile` and `Podfile.lock` files.

One suggestion is you may need to move `use_frameworks!` to the main target.

**Comment by Sergozh** [comment]
Sure I'll create test project to show issue

**Comment by Sergozh** [comment]
Here is my test environment: [Project](https://sprend.com/download?C=f98267b40b5c45e9bf09895a02a067fb)

**Comment by Sergozh** [comment]
Update project link

**Comment by emawby** [comment]
@Sergozh I am getting errors in that project even after removing all OneSignal references, however I see what you mean where by nesting the targets the Notification Service Extension now also depends on all of the pods in your app target. You can try removing all of the dependencies from the Pods-OneSignalNotificationServiceExtension framework except for `OneSignalXCFramework`
![image](https://user-images.githubusercontent.com/13123372/171259352-38b88829-3531-4258-a7f1-e28545017491.png)

**Comment by Dodalun** [comment]
> @Sergozh Could you provide the error or exact issue you are seeing? Please also share your the full contains of your `Podfile` and `Podfile.lock` files.
> 
> 
> 
> One suggestion is you may need to move `use_frameworks!` to the main target.

**Comment by Sergozh** [comment]
@emawby unfortunately having the same error after removing all dependencies except `OneSignalXCFramework`. Could I revert to previous structure of pod file without nesting or not after update 3.11.0?

**Comment by emawby** [comment]
@Sergozh You can yes, but don't use the OneSignalExtension submodule just use the OneSignalXCFramework in both the podfile and code

**Comment by umarfarooqitgcuf** [comment]
i have also faced the same issue thats in release 3.11.1 thats the issue in pod release.
i have solved the issue by downgrading the pod for onesignal pod 'OneSignal', '= 3.10.2'  and changing code related to pod version 3.10.2.

**Comment by ansafdev** [comment]
Hi @umarfarooqitgcuf 
Last several days not resolve this issue. But now i have successfully done this issue. I appreciate your effort.

**Comment by Dodalun** [comment]
> ### How can we help?
> 
> 
> 
> I have pods file like this:
> 
> 
> 
> ```
> 
> target 'Main iOS App' do
> 
>     pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
> 
> 
> 
>   target 'OneSignalNotificationServiceExtension' do
> 
>     use_frameworks!
> 
>     pod 'OneSignalXCFramework/OneSignalExtension', '>= 3.0.0', '< 4.0'
> 
>   end
> 
> 
> 
>     pod 'Moya'
> 
>     pod 'KeychainAccess'
> 
>     pod 'Firebase/Crashlytics'
> 
>     pod 'Firebase/RemoteConfig'
> 
>     pod 'Amplitude', '~> 8.0'
> 
>     pod 'Firebase/Analytics'
> 
> end
> 
> ```
> 
> 
> 
> And I meet issue when all pods where integrated onto nested `OneSignalNotificationServiceExtension` target. Could you help to resolve this issue?
> 
> 
> 
> ### Code of Conduct
> 
> 
> 
> - [X] I agree to follow this project's Code of Conduct

**Comment by Dodalun** [comment]
> Sure I'll create test project to show issue

**Comment by Dodalun** [comment]
> Here is my test environment: [Project](https://www.dropbox.com/s/ncmuyh17rx4pz6k/Test%20OneSignal%20Pod.zip?dl=0)

**Comment by vinczebalazs** [comment]
Also facing the same issue.

**Comment by ansafdev** [comment]
Please install the pod with specific version pod 'OneSignal', '= 3.10.2'. It will be helpful for you.
thanks

**Comment by yunustek** [comment]
`pod 'OneSignal', '= 3.10.2'` not working for me. My other pods doing error when I added to extension
