### ISSUE TITLE
[Bug]: IAM message not being displayed when a trigger is included.

### ISSUE THREAD

**Issue by parvez-keeptruckin** [OneSignal/OneSignal-iOS-SDK#1106]
### What happened?

IAM message not being displayed on the app. 
Xcode console shows logs specific to IAM message but IAM UI not being displayed. There is a trigger specified in IAM message setup on OneSignal dashboard such that IAM message is supposed to show when trigger is satisfied. When we do not use this trigger then IAM message is properly being displayed but with the trigger enabled it is not showing up.
We have made sure that OneSignal.addTrigger() method is being called with same key-value pairs as the one used while configuring IAM message on dashboard.

### Steps to reproduce?

```Markdown
1. Xcode 13.2.1
2. Run iOS app on iPhone 8 Simulator (iOS 12.4)
3. Navigate to the screen where IAM is supposed to show and made sure that `addTrigger` method with proper key-value pairs is called.
4. Check in Xcode console and it contains logs specific to IAM message but the message itself not show up on UI.
5. When we remove that trigger in IAM message on dashboard then message is displayed properly on the app.
```

### What did you expect to happen?

An IAM message should be displayed

### OneSignal iOS SDK version

Release 3.10.1

### iOS version

12

### Specific iOS version

```Markdown
* iOS 12.4
```

### Relevant log output

```Shell
Request <OSRequestRegisterUser: 0x6000008101b0> success result {
    id = "81e039b2-260d-46ef-a0a6-917d0bb993c5";
    "in_app_messages" =     (
                {
            "end_time" = "<null>";
            id = "72547a62-22e4-4dbc-8173-47737c884c54";
            redisplay =             {
                delay = 0;
                limit = 2147483647;
            };
            triggers =             (
                                (
                                        {
                        id = "1871a6ee-80c8-4965-a632-68f831d9fd73";
                        kind = custom;
                        operator = equal;
                        property = MainListPage;
                        value = true;
                    }
                )
            );
            variants =             {
                all =                 {
                    default = "c32df46e-6304-4733-99d0-f08b6b3ab967";
                };
            };
        }
    );
    success = 1;
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@parvez-keeptruckin I was not able to reproduce this in my testing. If possible could you turn on verbose logging and see what OneSignal logs after calling the addTrigger method?

**Comment by parvez-keeptruckin** [comment]
@emawby The issue is fixed now but it has taken a while to figure it out. The trigger I am adding on iOS client side has a bool value `true` but in OneSignal's in app message on dashboard we do not have a way to specify data type for value being given to a key. I have to change the value to a string and now it started working.

**Comment by jkasten2** [comment]
@parvez-keeptruckin Good to hear that fixed it for you, thanks for letting us know the details!
