### ISSUE TITLE
[bug]: How can we make use of external user Id in IAM (in app messages) ?

### ISSUE THREAD

**Issue by parvez-keeptruckin** [OneSignal/OneSignal-iOS-SDK#1107]
### How can we help?

Is it possible to make use of external user ids to generate in app messages that can be sent to selected users and not to all ? I used `Import User List` csv template to upload a list of users with given external user ids. I used this segment in the in app message's Audience section. . I am able to set external user id from iOS Client app but the in app message is not showing up on UI though in Xcode console I can see the logs that in app message data is being received so I am wondering if this is the correct way to get in app messages for specific users based on external user ids ? if this is not the right way to do it, can anyone suggest how to achieve this functionality ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@parvez-keeptruckin Thanks for your question. Using a Segment on your IAM with an "Import User List" filter should work as expected, that IAM should show to users in that list.

> ...Xcode console I can see the logs that in app message data is being received...

By this do you mean the IAM in the `in_app_messages` in the JSON payload in the log? Do you have any triggers on it that might be preventing it from showing? Are other IAMs showing in your app?

**Comment by parvez-keeptruckin** [comment]
Yes the Xcode console logs is showing `in_app_messages` information. There is a trigger present in that IAM. I have noticed that if I do not use the segment but keeping the trigger as it is then it works and IAM shows up on UI. When we Include the segment then it is not working.
In the CSV that I am uploading to OneSignal, I have only provided `external_user_id` and `first_name` columns with values. Here `external_user_id` is a numeric value. Also the `player_id` column is empty. Does this makes any difference ?

**Comment by jkasten2** [comment]
@parvez-keeptruckin hmm, so how IAMs work is if the player is in the Segment it will be included in the `in_app_messages` list send to the SDK. In other words the Segment only effects the manifest of IAMs the SDK can see. The Triggers are only evaluated by the SDK.

So in other words if you see your specific IAM in the `in_app_messages` list in the Xcode log it already passed the Segment check.

**Comment by parvez-keeptruckin** [comment]
@jkasten2 
Is there a way to debug it to see what is restricting IAM to not show up on UI ?

**Comment by emawby** [comment]
@parvez-keeptruckin Are you sure that In App Messages are not paused? That app has them paused by default

**Comment by parvez-keeptruckin** [comment]
@emawby Yes the IAM message under question is in active state.

**Comment by parvez-keeptruckin** [comment]
When I add `Subscribed Users` segment also in the Audience then only I am seeing the below in app message json as shown below:

`Request <OSRequestRegisterUser: 0x600000cccccc> success result {
    id = <some_id>;
    "in_app_messages" =     (
                {
            "end_time" = "<null>";
            id = <some_id>;
            redisplay =             {
                delay = 0;
                limit = 2147483647;
            };
            triggers =             (
                                (
                                        {
                        id = <some_id>;
                        kind = custom;
                        operator = equal;
                        property = <some_value>;
                        value = true;
                    }
                )
            );
            variants =             {
                all =                 {
                    default = <some_id>;
                };
            };
        }
    );
    success = 1;`
When we do not include `Subscribed Users` segment then it seems the above json is not being received.

**Comment by parvez-keeptruckin** [comment]
@jkasten2 @emawby 
When we upload a CSV containing the list of external_user_id values then OneSignal dashboard gives us option to automatically create a segment that can be used in Audience section of an IAM. Once that segment is generated When I select `View Users` then the loaded page do not show any user information. is it an expected behaviour ?
