### ISSUE TITLE
OneSignal IdsAvailable callback never getting called

### ISSUE THREAD

**Issue by ajaybeniwal** [OneSignal/OneSignal-iOS-SDK#111]
OneSignal IdsAvailable callback never getting called 
'OneSignal', '~> 2.1.0'

The issue is Im trying to get token and player id using Ids Available method but the method never gets called and application is not able to get the token and player id

**Comment by jkasten2** [comment]
@ajaybeniwal Can update to 2.1.16? Also ensure you are calling `idsAvailable` after `initWithLaunchOptions`

**Comment by jkasten2** [comment]
@ajaybeniwal We haven't been able to reproduce this issue or have seen any other reports of it. Feel free to reopen this issue if you are still seeing an issue after updating to our 2.2.1 version.
