### ISSUE TITLE
Support for Live Activities

### ISSUE THREAD

**Issue by fruitcoder** [OneSignal/OneSignal-iOS-SDK#1111]
### How can we help?

The beta documentation of Live Activities was released and it seems we need separate push tokens to support live activity updates alongside new types of push payloads: https://developer.apple.com/documentation/activitykit/displaying-live-data-on-the-lock-screen-with-live-activities

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@fruitcoder Thanks letting us know, looks like Apple just released the details on this today!
https://developer.apple.com/news/?id=hi37aek8

We will take a look and provide updates after we have evaluated it.

**Comment by vinamelody** [comment]
Hi, can someone update this guide https://documentation.onesignal.com/reference/live-activities-api
what is the right way to send the content-state ? is it inside event_updates ?
