### ISSUE TITLE
iOS16 beta :: warning This method can cause UI unresponsiveness if invoked on the main thread.

### ISSUE THREAD

**Issue by dklt** [OneSignal/OneSignal-iOS-SDK#1113]
maybe already reported, dunno...

**XCode 14b4 build generates this warning, call-stack suggests invoked by oneSignal iOS SDK 3.11.2:**

**Environment**
1. SDK 3.11.2
2. XCode 14b4 on iOS16b
3. via cocoapods 

**Steps to Reproduce Issue:**
1. Build project, XCode 14b4 generate a warning in purple (see to attach img)
2. Run App, after OneSignal SDK initialize success, purple warning icon appear
 <img src=https://user-images.githubusercontent.com/5556344/182349235-bd7b4782-2e7a-4674-aefa-d5470b1e4cf4.png width=700>

**Anything else:**

---
(edit: add run app step)

**Comment by jkasten2** [comment]
@dklt Thanks for reporting, we will look into addressing this in the future.

**Comment by JuFa512** [comment]
Any solutions on this? Having the same issues and none of my apps work anymore under iOS 16

**Comment by rursache** [comment]
@jkasten2 we reached iOS 16 RC and Xcode 14 RC, when will this be fixed?

**Comment by JUSTINMKAUFMAN** [comment]
Also experiencing this on the Xcode 14 public release

**Comment by sabiland** [comment]
I get this warning but it seems there are no issues with my app(s).

**Comment by yunustek** [comment]
I have same warning

**Comment by sabiland** [comment]
Is this solution ok to use?

**Comment by cal-os** [comment]
+1, the XC14 release build has been out already for a few days. @jkasten2 is there any update on whether or not this will be addressed?

**Comment by dlewandaDK** [comment]
+1 for getting this fixed, as it's still present in the Xcode 14.1 betas

**Comment by jdeyrson** [comment]
Still getting the same issue as shown in the image below.
Xcode Version 14.0.1 (14A400)
I appreciate any advice of possible solution.
<img width="1525" alt="Screenshot 2022-10-28 at 8 11 57 AM" src="https://user-images.githubusercontent.com/59494903/198601551-3913e61b-e320-4a9c-a33f-28d6003af4ae.png">

**Comment by mehmetdelikaya** [comment]
> I have same warning
> 
> EDIT: This way is works for me
> 
> Add this code: `OneSignal.setLocationShared(false)` before `OneSignal.initWithLaunchOptions(launchOptions)`

worked for me, nice catch
