### ISSUE TITLE
[question]: Questions about in app message deliveries

### ISSUE THREAD

**Issue by parvez-keeptruckin** [OneSignal/OneSignal-iOS-SDK#1119]
### How can we help?

Using OneSignal iOS SDK v3.11.2. We are setting `externalUserId` for a user when logged in and removing it on logout. We are using MixPanel - OneSignal integration to consume MixPanel cohorts in OneSignal as user segment. The in app message is supposed to show only once when a given trigger and user segment condition matches. Sometimes it happens that even when a given in app message is supposed to show only once, it is repeatedly appearing whenever app is run. 

Let's suppose user **A** login on an iOS device and able to see a `show only once` in app message. 
Will this message appear again when same user login on an Android device ? 
Will message come again when uninstalling the app and reinstall it again and login with same user ?
Will in app message shows up again when re-export the cohort to OneSignal ?

Ideally for a same user who already received a given in app message on one device should not receive it on another device.

What's the behaviour on Android device with regard to all above
questions ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@parvez-keeptruckin Unfortunately currently our SDK will still display the IAM once per device even if they have the same external id. This is a known issue with external id and we are working on overhauling our behavior around "users" to behave in the way you expect.

**Comment by emawby** [comment]
We have captured this enhancement request internally and will close this issue.
