### ISSUE TITLE
OneSignal not found on Mackbook Pro M1 Apple 

### ISSUE THREAD

**Issue by Abrar-ios** [OneSignal/OneSignal-iOS-SDK#1124]
**Description:**
I run pod install as i'm doing on my old mac but getting error on M1 machine but working fine on my old mac i also tried all given possible steps like
used pod 'pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0''
but still unable to resolve it. 
anyone can help me on it. Thanks

(your description here)

**Environment**
1. i'm using one siginal 2.12.5 also i tried with latest one.
2. using cocoapods

**Comment by emawby** [comment]
@Abrar-ios Thank you for reaching out. OneSignal 2.12.5 does not support M1 Macs (there isn't an XCFramework but your pod script looks like it was looking for versions >=3.0.0).

Is the error occurring on both your main app target and your Notification Service Extension target or just 1 of the two? Could you provide your podfile?
