### ISSUE TITLE
[Bug]: Cannot build OneSignal module

### ISSUE THREAD

**Issue by no-toodate** [OneSignal/OneSignal-iOS-SDK#1146]
### What happened?

Hello !

I installed OneSignal (3.11) on my IOS app and I have two errors. 
"Could not build OneSignal Module" and (the cause of the problem) 
" OneSignalCore/OneSignalCore.h file not fond"

Step to reproduce:

Install Cocoapods
Install OneSignal,
open generated .xcworkspace file.

Versions:
Cocoapods : 1.11.3
Xcode: 14

Has anyone had the same problem?

Have been having this problem for days and I am slowly slipping into madness. 

Thank you! :) 

### Steps to reproduce?

```Markdown
1 Install Cocoapods
2 Install OneSignal,
3 Open generated .xcworkspace file.
```

### What did you expect to happen?

I just expected the module to build and the app to work normally. 

### OneSignal iOS SDK version

3.11

### iOS version

11 or below

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @no-toodate,

Can you share the exact version of the OneSignal-iOS-SDK you are using? You mention it is 3.11 but which 3.11.x release is it?

Thank you

**Comment by no-toodate** [comment]
I am kinsa confused. When I install the cordova plugin, I get version 3.2.0. When I follow the https://documentation.onesignal.com/docs/cordova-sdk-setup tutorial, I get the 3.11.5 release.

**Comment by didierboka** [comment]
Work with version 3.4.0
