### ISSUE TITLE
[question]: Why `setInAppMessageClickHandler` is not override the default action?

### ISSUE THREAD

**Issue by duong-xendit** [OneSignal/OneSignal-iOS-SDK#1147]
### How can we help?

Recently I integrated my app using OneSignal SDK, the app uses In-app messaging. The problem is I want to handle the actions for in-app messaging myself. There is a method from SDK, indicated [here](https://documentation.onesignal.com/docs/iam-sdk-methods#in-app-message-click-handler), but I did see the SDK still handle the default action which navigate to browser

Should `setInAppMessageClickHandler` override the default handling from SDK?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@duong-xendit If all IAM actions should be done by the app you can change the action of the IAM on the dashboard to custom action id
