### ISSUE TITLE
OneSignal_suppress_launch_urls not working

### ISSUE THREAD

**Issue by Bengua27** [OneSignal/OneSignal-iOS-SDK#1166]
**Description:**
Setting OneSignal_suppress_launch_urls to true in the .plist file is not working

**Environment**
1. SDK 3.12.3
2. Swift package manager

**Steps to Reproduce Issue:**
1. Set OneSignal_suppress_launch_urls to turn in the .plist file of the target
2. Sending an inapp message with a launch url
3. Clicking on the button from the inapp view
4. It automatically opens an inapp web view

**Comment by emawby** [comment]
@Bengua27 Hello the behavior you are describing is the expected behavior [documented here](https://documentation.onesignal.com/docs/links#suppressing-launch-urls). What is the behavior you are hoping to achieve?

**Comment by Bengua27** [comment]
Thanks. I misunderstood the workflow.
