### ISSUE TITLE
Crash OneSignalHelper.m line 513

### ISSUE THREAD

**Issue by ARFAOUI** [OneSignal/OneSignal-iOS-SDK#118]
crash after receiving an iOS 10 Push when the app is in the background. attached the crash log 

[issue_4_crash_ffff3d51bc9040acb770ecab55fd324c.txt](https://github.com/OneSignal/OneSignal-iOS-SDK/files/563473/issue_4_crash_ffff3d51bc9040acb770ecab55fd324c.txt)

**Comment by jkasten2** [comment]
@ARFAOUI Could you include the OneSignal SDK version you have in your app?

Please also include the JSON payload you used the create the notification or if you created it from the dashboard include all the options you have set.

**Comment by jkasten2** [comment]
@ARFAOUI We haven't had any other reports of an issue around this stack trace you submitted. Please feel free to reopen this issue if you are still seeing it on our 2.3.1 SDK.
