### ISSUE TITLE
[question]: IOS not receiving notification

### ISSUE THREAD

**Issue by Haider-Ali-7** [OneSignal/OneSignal-iOS-SDK#1184]
### How can we help?

Hello,
User is Subscribed. But i'm not receiving notification on iPhone. On android it works fine. I'm testing it on real device. Please help. Thanks!
I have followed:
1 - [https://documentation.onesignal.com/docs/generate-an-ios-push-certificate#321-request-a-certificate-from-a-certificate-authority](url)
2 - [https://documentation.onesignal.com/docs/react-native-sdk-setup](url)

`IOS version: 15.2`

**Environment**
```
"react": "17.0.2",
"react-native": "0.66.4",
"react-native-onesignal": "^4.5.0",
```

**Attachments**
<img width="1436" alt="Screenshot 2022-12-13 at 5 25 05 PM" src="https://user-images.githubusercontent.com/97217972/207317576-dd76b00f-3b73-4086-aa58-b43160d0f348.png">

On Android i'm getting notification
<img width="319" alt="Screenshot 2022-12-13 at 5 24 39 PM" src="https://user-images.githubusercontent.com/97217972/207317867-1a84ae13-b75e-4fe5-9a25-c252a10e0721.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@Haider-Ali-7 If you uninstall then reinstall the app on the device you will get a different OneSignal player id. Can you confirm the device's player id matches what is on the dashboard?

If you background the app and then send a notification do you see it on the iOS device? If you don't see notifications only when the app is in the foreground then there might be another Notification SDK / library preventing it from displaying.

**Comment by Haider-Ali-7** [comment]
1 - Yes, I also tested by reinstalling the app. Player id does match in dashboard and i do get a different player id.
2 - I don't see notification in background/foreground. I have only onesignal sdk for notification related library.

**Comment by emawby** [comment]
@Haider-Ali-7 Are you using a .p12 certificate or the p8 token based authentication for your app in the OneSignal dashboard? Are you seeing any errors in the dashboard?

**Comment by Haider-Ali-7** [comment]
I'm using .p12 certificate. I just connected old iPhone device which have iOS 13.5 installed. Player id captured but in onesignal dashboard, it said Apns delegate never fired. I again connected previous device on which i was testing. It showed check mark. But still no notification received. I revoked .p12 cert and re-upload it. It worked for test msg sent from onesignal. But not from device. 
Iphone to android => android got notification
android to iphone => no notification  
Onesignal to iphone/android => both received notification

**Comment by Haider-Ali-7** [comment]
So I investigate the issue on backend side. We are pushing notification based on notificationEnabled parameter. Turns out notificationEnabled was `false` so it was not sending the notification to ios device. After making notificationEnabled to `true`. No i'm receiving notification.🎉
