### ISSUE TITLE
Setting kOSSettingsKeyAutoPrompt to false does not disable auto prompt

### ISSUE THREAD

**Issue by nlabhart** [OneSignal/OneSignal-iOS-SDK#119]
My code below seems correct. However, my app is still prompting to register for push notifications upon launch. Is there anything else I should be setting or doing? I'm using OneSignal iOS SDK, with cocoapods, 2.1.15.

    let stngs = [kOSSettingsKeyAutoPrompt : false]
    OneSignal.initWithLaunchOptions(launchOptions, appId: Constants.OneSignal.key, handleNotificationAction: nil, settings: stngs)

**Comment by jkasten2** [comment]
@nlabhart Just to confirm you are seeing a notification permission prompt in your app when opening it or is just `application:didRegisterForRemoteNotificationsWithDeviceToken:` firing? The selector will still fire even if you set this key however it should not be prompting the user.

Can you also try our latest 2.2.0 SDK? Please also report the iOS version if you are still seeing an issue.

Lastly make sure you don't have any other code or plugins that could be triggering the notification prompt.

**Comment by nlabhart** [comment]
@jkasten2 thanks so much for your reply. Feel very foolish, i was manually asking for permissions right underneath my onesignal init (slaps forehead). All good here!
