### ISSUE TITLE
[question]: I was rejected due to OneSignal (OneSignalWebView)

### ISSUE THREAD

**Issue by bigMOTOR** [OneSignal/OneSignal-iOS-SDK#1190]
### How can we help?

Hi there,

I am using OneSignal 3.11.2.
Just got a reject from Apple with the explanation:
`We discovered that your app contains hidden features. Specifically, it would be appropriate to remove any and all functionality in this app to load injected web content before resubmitting for review, such as this app’s OneSignalWebView and OSMessagingController.`

I don't see any option to turn it off. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@bigMOTOR Thanks for reporting! Are you using OneSignal In-App Messages at all in your app? Check the OneSignal dashboard to confirm if you have any present and enabled.

If you do use OneSignal In-App Messages Apple probably wants you to make sure you include that use such as feature in your app based on the rules noted here:
> 2.3.1 Don’t include any hidden, dormant, or undocumented features in your app; your app’s functionality should be clear to end users and App Review. All new features, functionality, and product changes must be described with specificity in the Notes for Review section of App Store Connect (generic descriptions will be rejected) and accessible for review.

_source: https://developer.apple.com/app-store/review/guidelines#2.3.1_

If you are not using OneSignal In-App Messages (and never had any enabled durning the review period) let us know.

**Comment by bigMOTOR** [comment]
@jkasten2 hi! Thanks for your reply. I don't use in-app messages. Actually I am using OS in a vary base way to show push and nothing more. 

Is there any way to exclude this classes which trigger Apple?

**Comment by bigMOTOR** [comment]
I tried to pass Apple review again. Here is the answer I've got:
`Specifically, it would be appropriate to remove any and all functionality in this app to load injected web content before resubmitting for review, such as this app’s OneSignalWebView and OSMessagingController.`

**Comment by bigMOTOR** [comment]
@OlegGrizzly Hi! Unfortunately no. I am thinking to move away from OneSignal now.

**Comment by emawby** [comment]
If anyone is still experiencing this issue it can be resolved by not including OneSignalInAppMessages when importing OneSignal into your app with cocoapods or swift package manager

**Comment by BrightPlay-Dev** [comment]
> If anyone is still experiencing this issue it can be resolved by not including OneSignalInAppMessages when importing OneSignal into your app with cocoapods or swift package manager

Could you please elaborate on how to do this? the OneSignalInAppMessages is automatically imported when compiling to iOS in Unity but there isn't any explicit import for it in Podfile. Is removing the reference for OneSignalInApMessages from Xcode enough in this case?
