### ISSUE TITLE
[question]: really needing help :(( >> OneSignalPush.h:32:9 'OneSignal/OneSignal.h' file not found

### ISSUE THREAD

**Issue by natsantis** [OneSignal/OneSignal-iOS-SDK#1195]
### How can we help?

hey, guys! 

when I open xcode and I'm going to build the project, it's giving an error like: _OneSignalPush.h:32:9 'OneSignal/OneSignal.h'_ file not found

has anyone gone through this or know how can I solve it to upload the app?
![onesignal](https://user-images.githubusercontent.com/66394109/209403160-ed681fec-6cf0-49d3-a4be-dc2b9e85923f.jpeg)
 
thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@natsantis Hello what version of the iOS SDK are you using?
