### ISSUE TITLE
[question]: How to add iOS Service Extensions ('OneSignal/OneSignal.h' file not found)

### ISSUE THREAD

**Issue by IgorSamer** [OneSignal/OneSignal-iOS-SDK#1196]
### How can we help?

I'm migrating my Ionic + Capacitor 2 app to Capacitor 4 but I'm having trouble configuring the iOS Service Extensions using OneSignal.

I'm following all the steps described in [https://documentation.onesignal.com/docs/ionic-sdk-setup#step-5-configure-your-xcode-project-ios-only](https://documentation.onesignal.com/docs/ionic-sdk-setup#step-5-configure-your-xcode-project-ios-only) however, Xcode always shows the error `'OneSignal/OneSignal.h' file not found`.

After each failed attempt, I deleted the iOS platform folder and recreated it using `ionic capacitor add ios` to be able to redo the attempts in a completely clean code and thus avoid possible conflicts, but I always get the same problem.

These are exactly the steps I'm doing:

1. `ionic capacitor add ios` (recreating the iOS project after deleting it)
2. `xed ios/App` (in Capacitor 4 this is the project structure)
3. Enable `Push Notifications` and `Remote Notifications` (inside of `Background Modes`) in `Signing & Capabilities`
4. Go to `File > New > Target...`, insert the name `OneSignalNotificationServiceExtension`, select `Objective-C` as language and then click on `Finish` and then `Cancel`
5. With `OneSignalNotificationServiceExtension` selected in the target list, I select the `Deployment Target` as iOS 13 (just like I'm using in the `Main Application Target`)
6. Open the `NotificationService.m` file inside the newly created `OneSignalNotificationServiceExtension` folder and then replace all its contents with Objective-C code
7. Select the `OneSignalNotificationServiceExtension` target, enter the `Build Settings` tab and make sure that the values of `Debug` and `Release` within `Code Signing Entitlements` are already blank
8. Close Xcode
9. Open `ios/App/Podfile`
10. Include the following code at the end of `Podfile`:
```
target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end
```
11. Return to the terminal and then `pod repo update` and `pod install`, which returns the following:
```
Analyzing dependencies
Downloading dependencies
Installing OneSignalXCFramework 3.12.3
Generating Pods project
Integrating client project
Pod installation complete! There are 23 dependencies from the Podfile and 33 total pods installed.
```
12. `xed ios/App` and wait for Xcode to open and index files
13. Keep getting the error `'OneSignal/OneSignal.h' file not found`

As I already said I've followed every single step in [https://documentation.onesignal.com/docs/ionic-sdk-setup#step-5-configure-your-xcode-project-ios-only](https://documentation.onesignal.com/docs/ionic-sdk-setup#step-5-configure-your-xcode-project-ios-only) and redone these steps numerous times until I came to the conclusion that I didn't make any mistakes and followed all the steps as recommended, so how can I resolve this?

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pettomartino** [comment]
@IgorSamer did you find a solution to this problem? I run into the same issue can't find a solution.
