### ISSUE TITLE
Upgrading from 3.12.3 to alpha02, the player_id/subscription_id stopped being updated

### ISSUE THREAD

**Issue by jfishman1** [OneSignal/OneSignal-iOS-SDK#1217]
### What happened?

Using Cocoapods, I updated from 3.12.3 to alpha02
My player_id stayed the same.
I noticed none of the data in the OneSignal dashboard updated for this device anymore.
SDK version was still 3.12.3
Last Active never updated
Click events stopped being tracked for this device.

### Steps to reproduce?

```Markdown
1. Run version 3.12.3 using Cocoapods
2. Get the player_id and send notifications to yourself, everything should work
3. Update to alpha02 following the migration guide
4. Run the app, you should still have the same player_id but last active and sdk version will not update.
5. Send your player_id a notification with the "include_player_ids" property on the API. You should get the push. Click it and no click event will register.
```

### What did you expect to happen?

Upon update, I expected the player_id to stay the same, which it does.
I expected the SDK and last active data to update, it does not.
I expected to be able to continue sending push through the api targeting the player_id, which it does.
I expected the clicks to get registered, which it does not.

### OneSignal iOS SDK version

alpha02

### iOS version

15

### Specific iOS version

```Markdown
ios 15.4.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Thanks for reporting these, 
The work to migrate existing app installs to `v5.0.0` is still yet to be figured out and implemented.
