### ISSUE TITLE
IAM with Push Permission Prompt continues to show after being subscribed

### ISSUE THREAD

**Issue by jfishman1** [OneSignal/OneSignal-iOS-SDK#1218]
### What happened?

IAM with Push Permission Prompt action continues to show after being subscribed. This shouldn't happen according to the dashboard when selecting that action it says:

Entire In-App Message will not be shown to users who have already allowed notifications
If user has previously denied permission in the native prompt, this will open your app’s device settings
Must use Android SDK 4.8.0+ to reach Android 13+ users

### Steps to reproduce?

```Markdown
1. Create an In-App Message (IAM) with the "Push Permission Prompt" action.
My trigger is set to "On app open"
I selected "Every time trigger conditions are satisfied"
2. Set it live.
3. Run the app on a device that is not subscribed to push notifications.
4. The IAM will trigger (correctly).
5. Subscribe to push.
6. Put the app into the background for 30+ seconds.
7. Open the app again and the IAM will appear again.
```

### What did you expect to happen?

The IAM should not have appeared on devices that are subscribed to push.

### OneSignal iOS SDK version

alpha02

### iOS version

15

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi, we have had no further reports of this. Please upgrade the OneSignal SDK if you or anyone is still having this issue. If this is still an issue, please open a new report with updated information.
