### ISSUE TITLE
[Feedback]: PhoneUri's generated by onesignal not "random enough"

### ISSUE THREAD

**Issue by Webrow** [OneSignal/OneSignal-iOS-SDK#1220]
### What's on your mind?

There doesn't seem to be a better way for me to get into contact with the developers. So I hope you can get it into the right channels within the company. While looking through our user tables something caught my eye which seemt very unlikely and its the following: 
![index](https://user-images.githubusercontent.com/3177853/215476968-523a798b-3798-4b94-8faf-eae0a236347f.jpg) for one of our apps we have 8 entries which have zeros for the last segement of the phoneuri. 
This being a guid I went into the spec and saw a reaonable explanation. in UUIv1 the last segement is the MAC address of the host creating the UUID. In a lot of environments this is hidden (with good reason) but it reduces the amount of phone uri's with ~12 bits. 
Which ofcourse in an enormous amount of use cases is still enough. Nevertheless I'd like to address the issue, and hope that internally it gets upgraded to uuiv4 or 7. 

I know this post should not be here, but as I said,
 no Idea where I could send this feedback. 

![index](https://user-images.githubusercontent.com/3177853/215476968-523a798b-3798-4b94-8faf-eae0a236347f.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @Webrow sorry for the long delay. 

I don't see that OneSignal has any properties called `PhoneUri`. Are you sure this is generated by OneSignal?
