### ISSUE TITLE
Push notifications not delivered

### ISSUE THREAD

**Issue by psy2k** [OneSignal/OneSignal-iOS-SDK#124]
I have noticed that when sending a push notification via the OneSignal dashboard (all users included), some users do not get the notifications (including me). Most of those users are old users, so through the app lifecycle they have opened it with multiple onesignal versions. Uninstalling and reinstalling the app fixes the issue. 

Any suggestions on why that happens?

**Comment by jkasten2** [comment]
@psy2k We would need to check your account to see what status of the player_ids and push tokens. Please contact OneSignal support and include the notification ids and player ids you are seeing an issue with and we can take a look.

Thanks.

**Comment by psy2k** [comment]
@jkasten2 thanks a lot.
