### ISSUE TITLE
App Store rejection for missing NSLocationWhenInUseUsageDescription

### ISSUE THREAD

**Issue by ghost** [OneSignal/OneSignal-iOS-SDK#1242]
### What happened?

Similar to or same as #368 or #490 .

I'm receiving this warning from Apple: ITMS-90683: Missing purpose string in Info.plist

_The Info.plist file for the “x.app” bundle should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data._

• My app is not using location services.
• My app uses no other 3rd party libraries.
• Background services are not enabled.
• Extensions are not used.
• `OneSignal.setLocationShared(false)` is called before init.

OneSignal Framework version 3.12.4 - Swift package.

### Steps to reproduce?

```Markdown
1. Build app and upload to App Store Connect.
2. After processing, receive warning mail from App Store Connect.
```

### What did you expect to happen?

I expect location services to be disabled so no `NSLocationWhenInUseUsageDescription` is required.

### OneSignal iOS SDK version

3.12.4

### iOS version

15

### Specific iOS version

```Markdown
iOS 16.4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi,

Is this still a warning and your app is still submitted to the app store?
Or does this reject your submission?

The 2 linked issues are pretty thorough and nothing has really changed in the OneSignal-iOS-SDK.

> Parts of the OneSignal iOS SDK allow apps to use location targeting for push notifications (geofence notifications). Apple appears to be scanning apps for any code that uses location services, even if the app doesn’t actually use it.
> 
> I would recommend putting an _NSLocationWhenInUseUsageDescription_ string in your Info.plist even if your app doesn’t actually use it. If your app calls `setLocationShared(false)` our SDK will not prompt the user for location permission.

**Comment by emawby** [comment]
Apple may have updated their logic for detecting location code so even if you are not using it it is included in the OneSignal library. In order to resolve this fully OneSignal will need to provide an SDK version that does not include the location module.

In the meantime you might need to provide a description indicating that you will never prompt or collect this information.

**Comment by altairdeark** [comment]
Same issue:
ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. NSLocationWhenInUseUsageDescription

**Comment by dmax111** [comment]
Is there any progress with this issue?

**Comment by e1block** [comment]
Likewise, still seeing this issue.

**Comment by RMatushkin** [comment]
I described here how I solved this problem for Flutter, but you can adapt this for a native iOS application, since the problem is precisely in the “OneSignalLocation” dependency: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/368#issuecomment-1712945805

**Comment by emawby** [comment]
In the new major version 5.0.0+ the location functionality has been separated into a subspec/separate SwfitPM target so that you may exclude it if it is not needed. For information on how to use the modular setup see the updated documentation [here](https://documentation.onesignal.com/docs/ios-sdk-setup#1-add-sdk)

**Comment by hasanmhallak** [comment]
@emawby I think this only for native iOS but not Flutter. Flutter keep using `OneSignalXCFramework` [here](https://documentation.onesignal.com/docs/en/flutter-sdk-setup#7-add-onesignal-to-the-nse-target)

which still gets the app to be rejected.
