### ISSUE TITLE
How to send user to a specific ViewController when I notification is clicked

### ISSUE THREAD

**Issue by LarsWith** [OneSignal/OneSignal-iOS-SDK#125]
I need to send the user to two different ViewController depending on what notification is clicked.

So where in the code do I place my fire segue, and how do I determine to which VC the user should be send to?

Should I send my segueIdentifierName as Additional Data?

**Comment by jkasten2** [comment]
@LarsWith Correct, you will need to add additional data to your notification and then check in the [OSHandleNotificationActionBlock](https://documentation.onesignal.com/docs/ios-native-sdk#section--oshandlenotificationactionblock-) where you can load the controller you need.

Thanks.

**Comment by jkasten2** [comment]
@LarsWith Feel free to reopen this issue if you are still stuck.
