### ISSUE TITLE
Disabling onesignal push notification listener

### ISSUE THREAD

**Issue by pratikdhody** [OneSignal/OneSignal-iOS-SDK#1269]
### How can we help?

Hi,

I'm using react-native-onesignal but in the underlying code, I want to disable the onesignal push notification listener as it's clashing with expo-notifications as per https://github.com/OneSignal/onesignal-expo-plugin/issues/177

Any advise?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Klyado** [comment]
Looking for the solution too!
Any news guys?

**Comment by nan-li** [comment]
Hello! Apologies that this question has gone stale.
If this question is still a current concern, please ping me.

**Comment by 7six** [comment]
any update?
