### ISSUE TITLE
Shouldn't OSNotificationPayload.actionButtons be an NSArray?

### ISSUE THREAD

**Issue by markbeaton** [OneSignal/OneSignal-iOS-SDK#128]
I'm having a bit of trouble accessing this property from Swift - It's bridging the property as an `Dictionary<AnyHashable, Any>` as per the `NSDictionary` property declaration in the [`OneSignal.h` header file](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignal/OneSignal.h#L131), but it looks like the actual memory points to an `NSArray` (which makes sense).

I noticed the Xamarin wrapper interops [this property as an `NSArray`](https://github.com/OneSignal/OneSignal-Xamarin-SDK/blob/master/OneSignal.iOS.Binding/OneSignal.iOS.Binding/ApiDefinition.cs#L80), and [it's a `List` on Android](https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationPayload.java#L49)...

**Comment by mayurdzk** [comment]
Not sure if this is what you meant but when opening a notification from the payload in 'result' by accessing `result?.notification.payload`, you need to access actionButtons via the `additionalData["actionButtons"]` value. 

I'll illustrate (code is Swift 3):
`OneSignal.initWithLaunchOptions(launchOptions, appId: OneSignalKey) { (result) in
            // This block gets called when the user reacts to a notification received
            let payload = result?.notification.payload
            print("Additional data: \(payload?.additionalData as Any)")
...
}`

The output I see is this:
<img width="530" alt="screen shot 2016-11-19 at 6 25 33 pm" src="https://cloud.githubusercontent.com/assets/10453316/20472485/2266deac-afe0-11e6-872b-b4aee3482156.png">


From the print statement, you see that the "actionButtons" property is an NSArray.

accessing `payload.actionButtons` directly crashes my app for some reason so I found this workaround.

Hope this helps.

**Comment by jkasten2** [comment]
@markbeaton @mayurdzk Thanks for the details. Just corrected this to be `NSArray` in the header in commit e4b70cb08c877aae2e781aba95b4cde1c762068b.
