### ISSUE TITLE
iOS 10 attachments - Downloading runs on the main thread

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-iOS-SDK#130]
Currently when an iOS 10 attachment is added to the notification it downloads on the main thread. This can block the UI if the user is in the app at the time.

Create a new thread for the download to run on to solve this issue.

**Comment by jkasten2** [comment]
Fixed in commit 01620f6df411455fe640acf2fa54c538bf2c16f6

**Comment by rubendura** [comment]
We are just testing this change with the latest SDK release. While we could get it to work on one device it seems to not be working in another. The build is exactly the same and the device configuration is apparently identical.

We can't find an answer for this, but we suspect it might have something to do with iOS not waking the app from suspension in one device for some reason. Background app refresh is enabled in both devices.
While the app is open we receive notifications as expected. When the app is closed notifications will not be received in that device if they have any attachments. If the notification is received while the app is in the background nothing will be displayed until we open the app (we've left the default popups enabled).
The device has been restarted several times. The app has been reinstalled several times and build with different capabilities turned on (notifications, background fetch...).

We are running out of ideas here. :(

**Comment by jkasten2** [comment]
@rubendura The feature uses `content-available` which unfortunately has a number of restrictions / requirements on iOS including not force killing the app. See our [Notifications with action buttons or iOS 10 media not displaying](https://documentation.onesignal.com/docs/troubleshooting-ios#section-notifications-with-action-buttons-or-ios-10-media-not-displaying) section for a full list of them a additional troubleshooting setups.

You can however use a category and/or `mutable-content` with the new iOS 10 Extinctions to handle this in a more reliable way. However you need to create your own code the parse the `aps` payload, download the attachment, and add it to the notification.

**Comment by rubendura** [comment]
After a few hours I managed to get a notification that worked properly without changing absolutely anything. If reliability is going to suffer because of this feature we'll have to find another way to do it (such as mutable-content and service extensions) or simply not use images.

Thanks for your tips. It would be nice if the OneSignal SDK automatically used mutable-content on capable devices to improve reliability of these notifications. The current behaviour is a bit of a hit and miss, so we can't trust it.

**Comment by jkasten2** [comment]
@rubendura Your concerns are understandable. We are looking into adding this to our SDK but it is going to take some additional logic to handle this. Since there are new Xcode build targets for required for this we are looking into what we can due lower the number of steps required to set this up.

I recommend following this issue below to stay up to date on our progress of this.
https://github.com/OneSignal/OneSignal-iOS-SDK/issues/112
