### ISSUE TITLE
[question]: After successfully upgrading to 5.0.1 - it is not working in Simulator anymore?

### ISSUE THREAD

**Issue by sabiland** [OneSignal/OneSignal-iOS-SDK#1303]
### How can we help?

I successfully upgraded to `5.0.1` version. Tested on physical device - everything `OK`. But `version 3 worked in simulator`, `5.0.1` seems `not to be working`?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Thank you for reaching out can you clarify what is not working?

**Comment by sabiland** [comment]
Version 3 worked in simulator:

1. There was shown dialog for accepting APN
2. There was dialog about New Features
3. etc.

Now it seems `nothing of above` works in `Simulator`. I have latest Prod `Xcode 14.3.1`.

**Comment by sabiland** [comment]
1) Yes I am using In App Messages, they are not showing in Simulator. Even for allowing APNs dialog.
2) They are showing correctly on physical device. I have integrated OneSignal via Swift Package Manages with selecting all options.

**Comment by emawby** [comment]
@sabiland Could you turn on verbose logging. Not creating a user is definitely the issue here. What language code could the SDK be trying to send?

**Comment by sabiland** [comment]
@emawby I noticed there are `no problems` on `iOS 17` simulator, only on `iOS 16.4` simulator. On `iOS 17` simulator everything works ok.

**Comment by nan-li** [comment]
@sabiland Perhaps the two simulators are using different language codes. Regardless, since then, wrong language codes will not block user creation anymore, so I will close out this issue. 

Feel free to follow up with any further comments or questions if you have them.
