### ISSUE TITLE
[question]: what happend to setLaunchURLsInApp

### ISSUE THREAD

**Issue by bartoszJaroszEG** [OneSignal/OneSignal-iOS-SDK#1304]
### How can we help?

in documentation method `OneSignal.setLaunchURLsInApp(true)` is still present, however in xcode I have error `Type 'OneSignal' has no member 'setLaunchURLsInApp'`, did this method change name or dissapeared? how to handle it now in onesignal 5?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@bartoszJaroszEG The migration guide has been updated!
