### ISSUE TITLE
[Feedback]: Getting limited to a maximum number of tags error when deleting tags

### ISSUE THREAD

**Issue by cclaflin89** [OneSignal/OneSignal-iOS-SDK#1306]
### What's on your mind?

I have an app that has 40~50 user tags, but due to the new limitation it can have up to 20 tags now, so I'd like to remove some tags, but I'm getting this error when removing tags as well.

`App is limited to a maximum of 20 tags on a given player`

api used:
`OneSignal.deleteTags(tagNames)`

Is this error intended? If so, what is the preferred way to remove tags?

I think it's better to allow deleting tags in this case.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@cclaflin89 Thank you for reaching out. This definitely should allow you to delete the tags we are investigating a fix!

**Comment by sherwinski** [comment]
Hello! Apologies for not circling back on this.
This should be fixed in the most updated release. Please upgrade your SDK version to confirm, and feel free to open a new issue if this is still a concern.
