### ISSUE TITLE
[question]: OneSignal.h file not found

### ISSUE THREAD

**Issue by jward8** [OneSignal/OneSignal-iOS-SDK#1307]
### How can we help?

It seems like this is an issue that people have been having for a very long time and never gets an actual resolution. So I wanted to ask it here again. 

I'm running into an issue in the NotificationService of the app I'm working on. Every time I try to build the app or archive I run into this issue.
![image](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/47757114/7404b804-8f28-4d44-906c-d5bf9057028e)

I'm unsure as to why this is happening now as of two days ago it was working perfectly fine. We were changing the team around under the project signing for both our project and the OneSignalNotificationServiceExtension. Once we got that to the correct team and everything, this started happening, but only happens to me, not anyone else. 

What I've done to try to fix this includes deleting xcode, deleting the repository, googling and looking at different answers, but nothing works. So I propose the question again, how do i fix this? 

EDIT: This is what the podfile looks like

```
target <project> do
...
    pod 'OneSignal', '>= 3.0.0', '< 4.0'
...
target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '>= 3.0.0', '< 4.0'
end
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pettomartino** [comment]
Same here. Was working fine then suddenly broke. 
@jward8 did you find any solution ?

**Comment by jward8** [comment]
> Same here. Was working fine then suddenly broke. 
> 
> @jward8 did you find any solution ?

It ended up being that I was using the wrong Xcode project file (i.e. was XcodeProject vs XcodeWorkspace). I don't remember what I was using, but once I switched to the other, the issue was resolved. So try that?
