### ISSUE TITLE
CocoaPods could not find compatible versions for pod "OneSignalXCFramework"

### ISSUE THREAD

**Issue by clintonimaroo** [OneSignal/OneSignal-iOS-SDK#1308]
### How can we help?

I'm encountering problems every time I attempt to run 'pod install.' Typically, I consistently encounter this error message.

My project's deployment target is set to iOS 12.4

```
!] CocoaPods could not find compatible versions for pod "OneSignalXCFramework":
  In Podfile:
    OneSignalXCFramework (< 4.0, >= 3.0)

    react-native-onesignal (from `../node_modules/react-native-onesignal`) was resolved to 5.0.0, which depends on
      OneSignalXCFramework (= 5.0.1)

Specs satisfying the `OneSignalXCFramework (< 4.0, >= 3.0), OneSignalXCFramework (= 5.0.1)` dependency were found, but they required a higher minimum deployment target.
```

> 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clintonimaroo** [comment]
Even when I have done a $ pod repo update

**Comment by emawby** [comment]
Hello it looks like it is trying to resolve both a `OneSignalXCFramework (< 4.0, >= 3.0) ` version of the pod and a 5.0.1 version of the pod. I see you are on react native and are using the latest major release. Could you show your podfile? It is likely that you will need to change your version numbers to (<6.0, >=5.0)

**Comment by n3omaster** [comment]
Same issue here:

[!] CocoaPods could not find compatible versions for pod "OneSignalXCFramework":
  In Podfile:
    OneSignalXCFramework (< 4.0, >= 3.0)

    react-native-onesignal (from `../node_modules/react-native-onesignal`) was resolved to 5.0.0, which depends on
      OneSignalXCFramework (= 5.0.1)

Specs satisfying the `OneSignalXCFramework (< 4.0, >= 3.0), OneSignalXCFramework (= 5.0.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by hagen00** [comment]
Same problem here after upgrading to `onesignal_flutter` 5.0.0`. 

i will have to revert, since iOS does not build using `flutter run`. Same error output as above.

**Comment by clintonimaroo** [comment]
@n3omaster & @hagen00

What happens if you update OneSignalXCFramework to version >= 5.0.0 < 6.0?

**Comment by hagen00** [comment]
Please excuse my ignorance with most things related to iOS, but there is no reference anywhere in my flutter project to `OneSignalXCFramework`, so I'm unsure where to update the version. 

The expectation is that if I upgrade to `onesignal_flutter 5.0.0` and make the necessary Flutter code changes due to the new API, everything still works.

**Comment by emawby** [comment]
Closing with solutions in comments
