### ISSUE TITLE
[Bug]: Run ios produce error

### ISSUE THREAD

**Issue by AlbanW** [OneSignal/OneSignal-iOS-SDK#1309]
### What happened?

note: Removed stale file '/Users/albanweill/Library/Developer/Xcode/DerivedData/AppFront-edlcilgdulevsthiacmkmfzllsiv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper-Glog.build/OutputFileList-46EB2E0001F110-Flipper-Glog-xcframeworks-output-files-565719c624fa5f97738cda794496af6a-resolved.xcfilelist'

note: Removed stale file '/Users/albanweill/Library/Developer/Xcode/DerivedData/AppFront-edlcilgdulevsthiacmkmfzllsiv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper-DoubleConversion.build/OutputFileList-46EB2E0001F100-Flipper-DoubleConversion-xcframeworks-output-files-dfdd2040eaa90d19c010c7a90cfd9f31-resolved.xcfilelist'

note: Removed stale file '/Users/albanweill/Library/Developer/Xcode/DerivedData/AppFront-edlcilgdulevsthiacmkmfzllsiv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hermes-engine.build/OutputFileList-46EB2E0001F150-hermes-engine-xcframeworks-output-files-3bdc6ef216b5b39df088ab62f2f7cabb-resolved.xcfilelist'

note: Removed stale file '/Users/albanweill/Library/Developer/Xcode/DerivedData/AppFront-edlcilgdulevsthiacmkmfzllsiv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/YogaKit.build/Script-46EB2E0001D170.sh'

note: Removed stale file '/Users/albanweill/Library/Developer/Xcode/DerivedData/AppFront-edlcilgdulevsthiacmkmfzllsiv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/OneSignalXCFramework.build/Script-46EB2E0001F120.sh'

note: Removed stale file '/Users/albanweill/Library/Developer/Xcode/DerivedData/AppFront-edlcilgdulevsthiacmkmfzllsiv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/OpenSSL-Universal.build/Script-46EB2E0001F130.sh'

note: Removed stale file '/Users/albanweill/Library/Developer/Xcode/DerivedData/AppFront-edlcilgdulevsthiacmkmfzllsiv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper-DoubleConversion.build/Script-46EB2E0001F100.sh'

note: Removed stale file '/Users/albanweill/Library/Developer/Xcode/DerivedData/AppFront-edlcilgdulevsthiacmkmfzllsiv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hermes-engine.build/Script-46EB2E0001F150.sh'

note: Removed stale file '/Users/albanweill/Library/Developer/Xcode/DerivedData/AppFront-edlcilgdulevsthiacmkmfzllsiv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Flipper-Glog.build/Script-46EB2E0001F110.sh'

2023-08-31 19:00:52.429 xcodebuild[77123:18833820] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:C2E734D8-7F47-4B67-95EF-DAEF77B9A3BE, OS:16.4, name:Iphone SE }
{ platform:iOS Simulator, id:C2E734D8-7F47-4B67-95EF-DAEF77B9A3BE, OS:16.4, name:Iphone SE }
** BUILD FAILED **

The following build commands failed:
        CompileC /Users/albanweill/Library/Developer/Xcode/DerivedData/AppFront-edlcilgdulevsthiacmkmfzllsiv/Build/Intermediates.noindex/AppFront.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/NotificationService.o /Users/albanweill/Downloads/github/Suport/AppFront/ios/OneSignalNotificationServiceExtension/NotificationService.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'OneSignalNotificationServiceExtension' from project 'AppFront')
(1 failure)

### Steps to reproduce?

```Markdown
1. Install OneSignal from cocoapod as documentation say
2. try project with npm run ios
```

### What did you expect to happen?

Openning application & ask for notification permission

### OneSignal iOS SDK version

5.0.1

### iOS version

14

### Relevant log output

```Shell
no log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Hello could you show your podfile integration with OneSignal? Have you tried` pod cache clean --all` and `pod install --repo-update`

**Comment by AlbanW** [comment]
Thanks, but now i can archive and build project but if i try to start it on emulator with npm start or npm run ios it didn't work (without error, just freezing)

**Comment by AlbanW** [comment]
<img width="1477" alt="Capture d’écran 2023-08-31 à 22 58 42" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/69081308/a1a15ce2-4885-45c6-97e1-8631e5815a4a">

Console stuck like that

**Comment by AlbanW** [comment]
I found error : https://pastebin.com/Mj9Ce1fz but idk hwo to fix it @emawby

**Comment by AlbanW** [comment]
<img width="858" alt="Capture d’écran 2023-09-01 à 02 02 34" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/69081308/11164b2f-7507-4afa-b78a-541cfe2a7c0a">

**Comment by emawby** [comment]
That still looks like an issue with finding the library in your notification service extension. The dynamic linker is failing meaning it can't find the library at run time. Without knowing your Cocoapods setup it is hard to debug

**Comment by AlbanW** [comment]
Here is my podfile: https://pastebin.com/42xaRApY

**Comment by emawby** [comment]
Ah this is a react native project! It likely is either an issue with derived data or the `runpath_search_paths` build setting, but to make it less flaky you can actually remove the OneSignalXCFramework from your podfile completely (it will still be included by the react native dependency in your main target). Then in Xcode navigate to the Notification Service Extension project settings and add the following XCFrameworks as dependencies:
OneSignalCore.xcframework
OneSignalOutcomes.xcframework
OneSignalExtension.xcframework

Previously you would see a framework like this 
<img width="626" alt="image" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/13123372/50ff38e0-59f5-4450-acef-76fb7e650472">

It should now look like this
<img width="658" alt="image" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/13123372/058c4399-c5e1-4911-ada0-bae3ceca92f7">

**Comment by AlbanW** [comment]
Uploading Enregistrement de l’écran 2023-09-01 à 02.35.13.mov…

seems build but, now when i try to open my app it stay frozen

**Comment by AlbanW** [comment]
seems build but, now when i try to open my app it stay frozen

https://github.com/OneSignal/OneSignal-iOS-SDK/assets/69081308/5a03a0e1-19a0-4a22-bc3c-0fa51991a523

**Comment by emawby** [comment]
Can you run with verbose logging or retrieve a stack trace to try to see what is happening?

**Comment by nan-li** [comment]
Closing due to no response to getting logs
