### ISSUE TITLE
[question]:   If you turn off notifications at startup, a dialog called "Open Setting" will now appear.

### ISSUE THREAD

**Issue by ynmain** [OneSignal/OneSignal-iOS-SDK#1318]
### How can we help?

If you turn off push notifications at startup, a dialog will appear. Is it possible to avoid this by setting something?

SDK version is latest.

![IMG_1782](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/8251604/92dc7767-7d4f-4cdf-b769-7b09ce8a54d4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@ynmain Can you share your code you are using to prompt for push? By turn off do you mean call `optOut` or reject push permissions?

**Comment by ynmain** [comment]
Thank you for your reply. The code is below

```
func setupOneSignal(launchOptions: [UIApplication.LaunchOptionsKey: Any]?) {
        // Remove this method to stop OneSignal Debugging
        // OneSignal.setLogLevel(.LL_VERBOSE, visualLevel: .LL_NONE)
        // OneSignal initialization
        OneSignal.initialize("xxxxxxxx", withLaunchOptions: launchOptions)
          // requestPermission will show the native iOS notification permission prompt.
          // We recommend removing the following code and instead using an In-App Message to prompt for notification permission
        OneSignal.Notifications.requestPermission({ accepted in
            print("User accepted notifications: \(accepted)")
        }, fallbackToSettings: true)
    }
```

**Comment by ynmain** [comment]
This is the cause

> fallbackToSettings: true

This is a very disappointing feature and should be removed immediately.
I pasted the official document as is.
This is a feature that no one wants.

**Comment by ynmain** [comment]
Moreover, it is a very disappointing SDK that the official cannot answer immediately.

I will be removing this SDK in the near future.

**Comment by Harsha221** [comment]
@ynmain  : Any update on this,
If user click cancel for notification still the dialog is open , which one erating the user & application flow. 
Could you plz update me how can handel this

**Comment by sagararora** [comment]
Any solution for this

**Comment by apcxiii** [comment]
hello @ynmain, Do you receive any response about that issue?
