### ISSUE TITLE
kOSSettingsKeyInAppAlerts deprecation

### ISSUE THREAD

**Issue by alexandre-g** [OneSignal/OneSignal-iOS-SDK#132]
The documentation states that `kOSSettingsKeyInFocusDisplayOption` defaults to `InAppAlert` for IOS 9 and below.

I've found a way to avoid the alert for iOS 9 via the `kOSSettingsKeyInAppAlerts` flag, but found information in one of the issue tickets that it will be deprecated in the next major release.

Will there be a way still to prevent the alert showing on iOS 9 when the app is in focus?

I also think that even though the field is to be deprecated it should still be present in the documentation, as it took me, and I am sure takes others quite a bit of time to find a way to do something this simple..

**Comment by black-lotus** [comment]
i use this

`kOSSettingsKeyInFocusDisplayOption: OSNotificationDisplayType.none.rawValue`

**Comment by jkasten2** [comment]
@alexandre-g I recommend passing a different value for `kOSSettingsKeyInFocusDisplayOption` at runtime based on the version of iOS your app is running on.

**Comment by alexandre-g** [comment]
Hi, thanks for your replies. I've got it working like we need to back at the time of posting the question, but was asking something else - if the setting is to be deprecated, I imagine that it will also be removed sooner or later. When this happens, will there still be a way to prevent the alert showing on iOS 9 when the app is in focus? In other words, what is the deprecated setting going to be replaced with, if anything?

**Comment by jkasten2** [comment]
@alexandre-g Nothing solid yet, we will introduce a new method before removing this flag though.
