### ISSUE TITLE
[Bug]: Inconsistent Badge Count Incrementation after Reset

### ISSUE THREAD

**Issue by bilalBakhrom** [OneSignal/OneSignal-iOS-SDK#1324]
### What happened?

Problem:
I have successfully integrated the OneSignal iOS SDK into my project, and push notifications are working as expected. I've followed the setup guidelines provided in the [official documentation](https://documentation.onesignal.com/docs/ios-sdk-setup) and have also configured [iOS SDK App Groups](https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup) accordingly.

Issue Details:
I'm encountering an issue with the badge count incrementation behavior. Here's the problem in more detail:

1. When a user receives a notification, the badge count is correctly incremented.
2. To reset the badge count, I'm using the following code:
```swift
if #available(iOS 17.0, *) {
    UNUserNotificationCenter.current().setBadgeCount(0)
    OneSignal.Notifications.clearAll()
} else {
    UIApplication.shared.applicationIconBadgeNumber = 0
    OneSignal.Notifications.clearAll()
}
```
This code effectively resets the badge count to zero.
3. The problem arises when the user receives another notification after resetting the badge count. Instead of starting from 1, the badge count increments from the previous number. For example, if the count was two before resetting, it will go forward and show 3.

### Steps to reproduce?

```Markdown
1. Integrate OneSignal into an iOS project.
2. Send a notification to the device.
3. Observe the badge count increment correctly.
4. Reset the badge count using the provided code.
5. Send another notification and observe that the badge count increments from the previous count, not from 1 as expected.
```

### What did you expect to happen?

I expect the badge count to start from 1 after reset rather than continuing from the previous count. The behavior should be consistent with the user's perception, where a reset should mean starting from scratch.

### OneSignal iOS SDK version

5.0.2

### iOS version

15

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@bilalBakhrom Thank you for reporting we will investigate. Your code should work as the SDK attempts to intercept calls to `applicationIconBadgeNumber ` to be notified it was reset, but there is also the `OneSignal.Notifications.clearAll` method. Does it work properly when using that method?

**Comment by bilalBakhrom** [comment]
@emawby Here's my code to clear the badge count:

```swift
if #available(iOS 17.0, *) {
    UNUserNotificationCenter.current().setBadgeCount(0)
    OneSignal.Notifications.clearAll()
} else {
    UIApplication.shared.applicationIconBadgeNumber = 0
    OneSignal.Notifications.clearAll()
}


Alternatively, I attempted to let the OneSignal framework clear notifications by setting `OneSignal_disable_badge_clearing` to NO. However, OneSignal is clearing it without displaying the notification. I can only hear the notification sound. So, I set it to YES to manually clear the badge using the code above.

**Comment by bilalBakhrom** [comment]
@emawby
 I'm reaching out to inquire about the status of the issue. OneSignal plays a significant role in our ongoing project, and the management team is eagerly anticipating an update. If your team can fix it quickly, we can wait. But if it takes longer, I'll have to find other ways to solve it. I'd really appreciate it if you could respond as soon as possible.

**Comment by emawby** [comment]
@bilalBakhrom Ah I was not able to reproduce this issue because I had `OneSignal_disable_badge_clearing` is set to false and was not getting the issue you mentioned with it. I am working on a fix for the issue with incrementing when `OneSignal_disable_badge_clearing` is set to true.

Could you clarify the issue you are seeing with the setting set to NO? With the setting as NO I am seeing the badge and the alert when the notification is received.

**Comment by bilalBakhrom** [comment]
Inside the info.plist file, you'll find the following key-value pair:
```
<key>OneSignal_disable_badge_clearing</key>
<true/>
```

Additional Information:
We have two primary targets: Production and Staging.

| ![Screenshot 2023-10-27 at 12 28 14](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/42291322/92e70f17-8c5b-48b9-854d-133bb0cd9c9a) | ![schemes](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/42291322/2f13964d-b498-4cbb-8bfd-7286aabbaae3) |

**Comment by bilalBakhrom** [comment]
@emawby were you able to reproduce the issue?

**Comment by emawby** [comment]
I was! The attached PR #1328 fixes the issue and will be available in the next release.

**Comment by austinGENEreeve** [comment]
Still an issue. I'm using the latest React Native SDK and there is no way to reset the badge count.
