### ISSUE TITLE
Notifications with action buttons are being duplicated after they're opened

### ISSUE THREAD

**Issue by mayurdzk** [OneSignal/OneSignal-iOS-SDK#133]
Opening a standard iOS notification (one with action buttons) opens the app and then shows the same notification (message, title, action buttons and all) as an alert view most-likely due to a duplication of the notification.
My environments: OneSignal 2.2.2, Swift 3, Xcode 8.1, testing on an iPhone 6S running iOS 10.1.1.

The temporary workaround I've found for this problem is to pass `[kOSSettingsKeyInAppAlerts : false]` for the settings (referenced from the sample code provided alongside OneSignal's v2.2.2 source.

**Comment by jkasten2** [comment]
Fixed in commit d0241ba6010b3eb6d35a3cdadc465945a08dd422
