### ISSUE TITLE
iOS attachments do not work if URL doesn't end in certain extensions

### ISSUE THREAD

**Issue by rubendura** [OneSignal/OneSignal-iOS-SDK#134]
I've found an issue where we are trying to set an attachment pointing to a url that doesn't end in .jpg.

The actual url is something like
https://xxxxxx.cloudfront.net/optimised/c528c899-edff-42a0-a9f1-facc520dc6d4_720_960

We couldn't get the iOS SDK to download the attachment when setting ios_attachments to {"id": "https://xxxxxx.cloudfront.net/optimised/c528c899-edff-42a0-a9f1-facc520dc6d4_720_960"}.

We tried other urls and the only difference with those was the extension. When we added it it worked. Digging into the code we found this method
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/94a967d258b45056c981ffc0fda5f8a335663f37/iOS_SDK/OneSignal/OneSignalHelper.m#L642
performing a string split on '.', taking the last component and checking against certain extensions. 
This directly conflicts with our way of handling images.

So far we've had no problems with our url schemes and changing this could mean renaming lots of files and repointing database records for the sole purpose of supporting the OneSignal SDK.

**Comment by jkasten2** [comment]
@rubendura Can you add `?filename=file.png` to the end of your URLs? As long as your server ignores the url query string this should work around this limitation for the time being.

**Comment by mikestalker** [comment]
Any news with this issue?

**Comment by jkasten2** [comment]
@mikestalker We haven't change the code around this yet but we are planning on removing this restriction. Does the work around work I noted above work for the time being?

**Comment by mikestalker** [comment]
@jkasten2 yep. It works, but any way waiting for fix.

**Comment by jkasten2** [comment]
Unfortunately removing file extension didn't work in our testing. iOS doesn't discover the file format on its own and it seems `UNNotificationAttachmentOptionsTypeHintKey` needs to be set if their isn't an extension on the file name.

It most likely possible to check for know binary file heads to set this, however it would be tricky to implement. Something we will still consider adding but don't have an eta for starting this.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
