### ISSUE TITLE
[Bug]: incomplete migration guide to 5.

### ISSUE THREAD

**Issue by raphaels17** [OneSignal/OneSignal-iOS-SDK#1341]
### What happened?

I am trying to migrate from 3. to 5. 

this is how i used to initialize // handle notifications

`OneSignal.initWithLaunchOptions(aunchOptions, appId: "my beautiful app id", handleNotificationReceived: { (notification) in

                guard let payload = notification?.payload else {
                    return
                } // do things 

                
            }
        },
            handleNotificationAction: {  (result) in
            // do things
            
           
        }, settings: [kOSSettingsKeyAutoPrompt : true, kOSSettingsKeyInFocusDisplayOption : OSNotificationDisplayType.notification.rawValue])`

now i see import OneSignalFramework

OneSignal.initialize("YOUR_ONESIGNAL_APP_ID", withLaunchOptions: launchOptions) on the doc
OneSignal.Notifications.addForegroundLifecycleListener(self)

about  handleNotificationReceived, **handleNotificationAction** and **setting** ? 

In particular, I am afraid this will not work in the background any longer

Can anyone help ?

### Steps to reproduce?

```Markdown
migrate from 3 to 5. sdk
```

### What did you expect to happen?

to have documentation for such change.

### OneSignal iOS SDK version

5.0

### iOS version

15

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Hello we appreciate feedback and are working on improving our migration guide. It sounds like you are migrating from the version 2 not version 3 since `initWithLaunchOptions(launchOptions, appId: "my beautiful app id", handleNotificationReceived)` does not exist in version 3. 
In version 3 we changed the notification events methods to:
`setNotificationWillShowInForegroundHandler` and
`setNotificationOpenedHandler`

The notification received handler was renamed since that handler does not fire if the app has been killed. There is no OneSignal callback for a notification being received in the background unless it is opened.

**Comment by michaelhenry** [comment]
Also noticed that some callbacks for the result state has been removed, for example `OneSignal.setExternalUserId` with `login()`, `OneSignal.User.addTags` and etc. So just to clarify, OneSignal will not provide the result state anymore for those methods? thanks

**Comment by michaelhenry** [comment]
Hi @emawby any update? Thanks

**Comment by michaelhenry** [comment]
and also for https://documentation.onesignal.com/docs/data-tag-implementation#getting-tags, can't access it from the static `User` instance.

**Comment by michaelhenry** [comment]
@nan-li 
how about the `getDeviceState`? thanks

https://github.com/OneSignal/OneSignal-iOS-SDK/blob/edfd4151c5a85bd68826f5c44743dd34490b30ce/iOS_SDK/OneSignalSDK/SwiftPM/Public/Headers/OneSignal/OneSignal.h#L482

**Comment by nan-li** [comment]
Hi @michaelhenry, the information returned in `OSDeviceState` has been split up into their own sections. What piece of information are you looking for?

For example, if you are looking for the push subscription ID, it can be retrieved via `OneSignal.User.pushSubscription.id` or if you're looking for what the native permission is, it is available via `let permissionNative: OSNotificationPermission = OneSignal.Notifications.permissionNative`

**Comment by raphaels17** [comment]
I am on  5 now and followed documentation for  UNNotificationServiceExtension and  but still i dont get how to get silent notification. 

The document mention that i should get it in onwilldisplay  and I have found in place to used  func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void), none of it works

**Comment by TofPlay** [comment]
I'm also trying to migrate from 3.11.2 to 5.1.5.
With version 3.11.2 I could use setNotificationOpenedHandler
What is the equivalent with 5.1.5?
