### ISSUE TITLE
iOS notifications with attachments can't be dismissed

### ISSUE THREAD

**Issue by rubendura** [OneSignal/OneSignal-iOS-SDK#135]
Self explanatory. Following the guide in the docs whenever I send a notification to an iOS device that contains an image attachment (as a URL that the SDK downloads) it is properly displayed but whenever the notification is dismissed (either from the lock screen or the iOS notification centre) it automatically reappears. The only way to dismiss it is to open our app.

**Comment by jkasten2** [comment]
Fixed in commit 2d7accf0b118818983957ac65e4fd1e2068e4b41
