### ISSUE TITLE
[question]: `macOS` support

### ISSUE THREAD

**Issue by NachoSoto** [OneSignal/OneSignal-iOS-SDK#1350]
### How can we help?

[Your documentation](https://documentation.onesignal.com/docs/establishing-a-connection-to-apns) shows that `macOS` notifications are supported, as well as your preferences:

![Screenshot 2023-12-13 at 10 38 07](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/685609/53c49cf2-9d62-4638-9e14-34642df99f90)

However, at least when integrating the SDK with SPM, the `XCFramework` doesn't have binaries for it:

![image](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/685609/1c6b9cfe-221b-4f63-b1db-02987eb4f956)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@NachoSoto Thank you for the feedback on our documentation it has been noted internally.
