### ISSUE TITLE
Provide setting to disable the sending of the user location.

### ISSUE THREAD

**Issue by tschob** [OneSignal/OneSignal-iOS-SDK#136]
It seems that the sending of the users location to the field `Location Point` can't be disabled with the iOS SDK.

This doesn't match the requirements of most of our - german ;) - projects.

When will this be implemented? Does https://github.com/OneSignal/OneSignal-iOS-SDK/pull/109 solve the problem?

**Comment by jkasten2** [comment]
@tschob Just added this in commit d28928d0afed4b4bfd8c519a5e9817a15779c92b
