### ISSUE TITLE
Handle tap on push notification

### ISSUE THREAD

**Issue by igorsquadra** [OneSignal/OneSignal-iOS-SDK#1361]
### How can we help?

I need to handle the tap on push notification with launch url. I migrate from 2.5.2 to 5.0.5 and my old code was:
```
OneSignal.initWithLaunchOptions(launchOptions, appId: "appId", handleNotificationReceived: { (notification) in self.open((notification?.payload)!) }, handleNotificationAction: nil, settings: [kOSSettingsKeyInFocusDisplayOption: "None", kOSSettingsKeyInAppLaunchURL: false])
```
Can you please help me with this migration? 
I wasn't able to find something interesting in the documentation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@igorsquadra Hello you will want to use the clickListener method in the [Notification namespace](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/main/MIGRATION_GUIDE.md#notifications-namespace). This listener will be called whenever a notification is tapped including when it is used to launch the app.

**Comment by emawby** [comment]
Closing for now. Feel free to tag me to reopen if you need additional help.
