### ISSUE TITLE
[Bug]: OneSignalUserDefaults Crash

### ISSUE THREAD

**Issue by danhalliday** [OneSignal/OneSignal-iOS-SDK#1365]
### What happened?

iOS app crashed in production with a stack trace showing OneSignal frames.

### Steps to reproduce?

```Markdown
No idea. This is a remote crash report from Crashlytics.
```

### What did you expect to happen?

The library should not cause a crash, regardless of what I may be doing wrong in using it.

### OneSignal iOS SDK version

5.1.0

### iOS version

11 or below

### Specific iOS version

```Markdown
* 17.2.1
```

### Relevant log output

```Shell
Crashed: com.apple.NSURLSession-delegate
0  CoreFoundation                 0x11d18 __CFBasicHashRehash + 112
1  CoreFoundation                 0x119a8 __CFBasicHashAddValue + 100
2  CoreFoundation                 0x1190c CFBasicHashAddValue + 420
3  CoreFoundation                 0x116fc CFDictionaryAddValue + 208
4  CoreFoundation                 0x10c34 _flattenPlist + 308
5  CoreFoundation                 0x10d98 _flattenPlist + 664
6  CoreFoundation                 0x10dfc _flattenPlist + 764
7  CoreFoundation                 0x10d98 _flattenPlist + 664
8  CoreFoundation                 0x107dc __CFBinaryPlistWriteOrPresize + 240
9  Foundation                     0x3c658 -[NSKeyedArchiver finishEncoding] + 640
10 Foundation                     0x6e7714 +[NSKeyedArchiver archivedDataWithRootObject:] + 112
11 OneSignalCore                  0x112b4 -[OneSignalUserDefaults saveCodeableDataForKey:withValue:] + 88
12 OneSignalUser                  0x1c264 block_destroy_helper.32 + 23276
13 OneSignalUser                  0x33970 __swift_noop_void_return + 9644
14 OneSignalCore                  0xdcb4 -[OneSignalClient handleJSONNSURLResponse:data:error:isAsync:withRequest:onSuccess:onFailure:] + 848
15 OneSignalCore                  0xc998 __54-[OneSignalClient executeRequest:onSuccess:onFailure:]_block_invoke + 44
16 CFNetwork                      0xf368 _CFNetworkSetHSTSStoragePath + 28508
17 CFNetwork                      0x2d218 CFHTTPMessageCopySerializedMessage + 13784
18 libdispatch.dylib              0x26a8 _dispatch_call_block_and_release + 32
19 libdispatch.dylib              0x4300 _dispatch_client_callout + 20
20 libdispatch.dylib              0xb894 _dispatch_lane_serial_drain + 748
21 libdispatch.dylib              0xc3f8 _dispatch_lane_invoke + 432
22 libdispatch.dylib              0x17004 _dispatch_root_queue_drain_deferred_wlh + 288
23 libdispatch.dylib              0x16878 _dispatch_workloop_worker_thread + 404
24 libsystem_pthread.dylib        0x1964 _pthread_wqthread + 288
25 libsystem_pthread.dylib        0x1a04 start_wqthread + 8
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ihijazi** [comment]
I'm having the same issue. I've posted also about another issue which might be relevant but still no updated on it: https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/858 

One thing I noted is the crash happens when not using cellular data (i.e not WiFi)

**Comment by kunalzigma** [comment]
@danhalliday am seeing this crash, first time on 5.1.3. Updated app on 30th march, saw this same day. How many crashes can we expect ? like out of 100 or 1000 sessions?

**Comment by dombartenope** [comment]
Hi folks,

Thank you all for your reports here. I am creating an internal ticket to highlight the issue you're all facing here directly with the SDK team. I'll be linking them this thread, so the team can reply or request information as needed. 

Thanks
Dom
OS Technical Support

**Comment by yasht01** [comment]
Hey folks,
Saw this error for the first time on our app using Flutter SDK. Is there any extra info that we can provide to help debug this issue better?

Onesignal Flutter SDK version: `5.1.0`

**Comment by nan-li** [comment]
Hi everyone, thank you for your reports,

We have made a few crash fixes since. Please update to [Release 5.1.6](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.6) or later, and let us know if the crashes are resolved, or what crashes still remain.

**Comment by nan-li** [comment]
Hi @danhalliday thank you for following up with these 3 stacktraces.

**Comment by nan-li** [comment]
Hi @danhalliday I am not sure how these crashes could be happening, so I am still investigating.

Any additional information you can share will be helpful:

1. Do you have updated data on frequency of these crash reports?
2. Do you have data if the app is in the background or foreground?
3. Do you have information about the memory usage or state of the memory at time of the crash? One possibility I am considering is the app being out of memory at the time we are saving information. Particularly if you know that there is high memory usage in the app already.
