### ISSUE TITLE
iOS17 privacy policy

### ISSUE THREAD

**Issue by KKakadiyaKashyap** [OneSignal/OneSignal-iOS-SDK#1384]
Apple required App Privacy manifests until 2025. So GoogleSignIn-iOS SDK that contains an app privacy manifest must be signed.
I would like to know when you adopt this change.

**Comment by emawby** [comment]
@KKakadiyaKashyap Hello the privacy manifests are already available in our latest version of the sdk. We will be doing a release for the 3.X.X version of the SDK soon.
