### ISSUE TITLE
[question]: Release 3.12.8 doesn't contain privacy manifests.

### ISSUE THREAD

**Issue by bleeptools** [OneSignal/OneSignal-iOS-SDK#1389]
### How can we help?

Could you please double check?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @bleeptools thank you for reporting. I'll take a look at why they are not working.

**Comment by nan-li** [comment]
Hi @bleeptools and @eyavorsky-ms we have just released [Release 3.12.9](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.12.9) with complete privacy requirements support.

**Comment by idefen1** [comment]
> Hi @bleeptools and @eyavorsky-ms we have just released [Release 3.12.9](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.12.9) with complete privacy requirements support.

Hi @nan-li, when updating from Release 3.10.1 (working) to 3.12.9 (broken) I get the following errors: 
Error 1. Building for 'iOS', but linking in dylib (/Users/UserName/Library/Developer/Xcode/DerivedData/App_Name-ereglvctbbdscccowdmrvnurayyt/Build/Products/Debug-iphoneos/OneSignal.framework/OneSignal) built for 'iOS-simulator'

Error 2. Linker command failed with exit code 1 (use -v to see invocation)

This occurs when I build with my physical device as the target. 

Any thoughts on this would be greatly appreciated! I'm only updating to get the Privacy Manifests working. 

Thank you.

**Comment by nan-li** [comment]
Hi @idefen1, there was a change in [Release 3.11.0](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.11.0) that modularized the ios SDK.

That may be affecting your build. Can you check the release notes to see if you are able to resolve?

**Comment by idefen1** [comment]
@nan-li thank you for the quick reply! So unfortunately I wasn't able to figure out the pod issue BUT I was able to get Xcode's "package dependencies" working with Version 3.12.9 so I'm good to go. Thank you again for your response!
