### ISSUE TITLE
[question]: Privacy Manifest : Userdefaults and Timestamps

### ISSUE THREAD

**Issue by Nav-3299** [OneSignal/OneSignal-iOS-SDK#1397]
### How can we help?

Hi Team ,

I am using 5.0.5 version of SDK in IOS and facing these issues while uploading . Please guide 

ITMS-91053: Missing API declaration - Your app’s code in the “PlugIns/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “PlugIns/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

<img width="269" alt="image" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/70155782/85f7feaf-fff7-46e6-b0a3-a86251f02730">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @Nav-3299 thank you for reporting.

Can you share what dependencies your `OneSignalNotificationServiceExtension` contains and what code it contains?

![Screenshot 2024-04-16 at 10 14 48 AM](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/4022291/c41a2750-1d5e-4fc0-9b73-00e98557355f)

The OneSignal iOS SDK does not contain any `NSPrivacyAccessedAPICategoryFileTimestamp` APIs.

**Comment by nan-li** [comment]
A followup question for anyone encountering this, can you confirm you are not using `UserDefaults` or the [Disk space APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278397) in your own source code in your Notification Service Extension?

**Comment by Nav-3299** [comment]
<img width="1087" alt="image" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/70155782/bb15543e-d6cd-411b-91b3-be8ebba50ced">


I am using this Extension please

**Comment by Nav-3299** [comment]
Hi @nan-li 
 
Since the e-mail reads that OneSignaExtension is using userdefaults and CategoryFileTimestamp related Apis , I would not be able to upload my app in from May 1 .I would rather request you to kindly get in touch with Apple support Team to provide clarifications on the same 

For my upcoming builds on appstore I would attach this thread in order for them to know that OneSignal is not using any of these apis.

I also want to confirm you that in previous e-mails I was also notified about Userdefaults and Other Categories about my application (that is Sportslocker) which I had fixed by placing proper columns in Privacy Manifest File(mail attached below) . Now I only get that of One Signal .

I would be great if we find out a way 

Thanks 



Hello,

We noticed one or more issues with a recent submission for App Store review for the following app:

Sports.com
Version 4.0.0
Build 3
Although submission for App Store review was successful, you may want to correct the following issues in your next submission for App Store review. Once you've corrected the issues, upload a new binary to App Store Connect.

ITMS-91053: Missing API declaration - Your app’s code in the “PlugIns/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “PlugIns/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “Sports.com” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “Sports.com” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategorySystemBootTime. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “Sports.com” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryDiskSpace. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “Sports.com” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

Apple Developer Relations

**Comment by nan-li** [comment]
Hi @Nav-3299, thank you for following up,

The warnings are for `OneSignalNotificationServiceExtension`. Please note that `OneSignalNotificationServiceExtension` is just the name for your app's own Notification Service Extension. You could name it anything else such as `MyNotificationServiceExtension` and the code and dependencies would be the same.

Your Notification Service Extension does use `OneSignalExtension` framework, which is part of our SDK. However, the warnings are unclear if the issue is:
- The OneSignal dependency
- Your own code in your Notification Service Extension are using these APIs
- The `FirebaseMessaging` dependency is using these APIs

I would recommend you confirm your `FirebaseMessaging` dependency version includes Privacy Manifest support.
In addition, you can scan your own code for these APIs. Here is [a simple text search](https://github.com/Wooder/ios_17_required_reason_api_scanner) implementation.

**Comment by lobanovD** [comment]
This problem is relevant even without using firebase

**Comment by nan-li** [comment]
@lobanovD Can you share all your dependencies your Notification Service Extension uses?
Additionally, have you confirmed your own code is not calling those APIs?

**Comment by lobanovD** [comment]
> @lobanovD Can you share all your dependencies your Notification Service Extension uses? Additionally, confirm your own code is not calling those APIs?

![Снимок экрана 2024-05-08 в 23 21 11](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/64478115/53fb6d95-8beb-458e-8049-568850c61ed4)

I'm using UserDefaults. And described this in my privacy manifest.
Removing OneSignal from the project solves the problem of submitting the build to the App Store, but this is clearly not the solution I need.

**Comment by nan-li** [comment]
Hi @lobanovD, 

> Removing OneSignal from the project solves the problem of submitting the build to the App Store, but this is clearly not the solution I need.

When you removed OneSignal from our project, what API error(s) did it resolve?

**Comment by lobanovD** [comment]
this
![Снимок экрана 2024-05-09 в 01 46 14](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/64478115/57bb4ed4-efa2-4929-8c27-a60c22dcedd4)

**Comment by lobanovD** [comment]
> Hi @lobanovD,
> 
> > Removing OneSignal from the project solves the problem of submitting the build to the App Store, but this is clearly not the solution I need.
> 
> When you removed OneSignal from our project, what API error(s) did it resolve?

this
![Снимок экрана 2024-05-09 в 01 46 14](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/64478115/4c19dab7-475c-4423-beb2-102d2cc03b33)

after OneSignal was uninstalled, the application was reviewed

**Comment by nan-li** [comment]
Hi @lobanovD thank you for following up, your error about code signatures is different than the Privacy Manifest APIs reported by Nav-3299.

I believe you are using Swift Package Manager. I am not sure when you added the dependency but we did release version 5.1.6 to SPM without signatures, but updated them the next day. 

This happened 7 days ago. Can you pull the package again?

I am confused about the `RxSwift` error because `OneSignalOutcomes` has no dependency on RxSwift and is an Objective-C only framework.

**Comment by lobanovD** [comment]
reinstalled this today according to the instructions https://documentation.onesignal.com/docs/ios-sdk-setup

however, the library does not contain a manifest file and I think this is the problem

![Снимок экрана 2024-05-10 в 13 04 52](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/64478115/47242506-23e5-4ad1-8c3b-8ae8c72d9b32)

for example, it is present in the Realm library
![Снимок экрана 2024-05-10 в 13 05 12](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/64478115/86d9cdcd-d543-4dbf-b3eb-11b0f14a4ded)

**Comment by nan-li** [comment]
Hi @lobanovD, the way the sources for the SDK are packaged, the privacy manifests will not show up in the file hierarchy.

You can generate your App's privacy by following instructions [Create your app’s privacy report](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests#4239187) and you should see it includes the Privacy Manifest information from the OneSignal SDK.

**Comment by nan-li** [comment]
We just released [Release 5.2.0](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.0) in which we added Privacy Manifests to all of our sub-packages as well. 

This may resolve the issue for you, can you try?

**Comment by lobanovD** [comment]
I'll check this on the next build of the application and get back to you with an answer.

**Comment by Nav-3299** [comment]
Hi @nan-li 
Its fixed 

Thanks 👍🏻
