### ISSUE TITLE
Carthage build fails with the newest version 2.2.3

### ISSUE THREAD

**Issue by mkowalski87** [OneSignal/OneSignal-iOS-SDK#141]
I'm receiving following error

"_OBJC_CLASS_$_OneSignalAppDelegate", referenced from:
      objc-class-ref in OneSignal.o

**Comment by jkasten2** [comment]
@mkowalski87 Could you include the version of Xcode you are using?

**Comment by mkowalski87** [comment]
@jkasten2 Version 8.1 (8B62)

**Comment by jkasten2** [comment]
@mkowalski87 Thanks for the details. We have fixed this in commit b673b3f395178a7800079689367832e8cb6e5969 and f680e2042e04b1c000bf55d722e206c49570d6c5. These will be include in the next release.
