### ISSUE TITLE
[question]: Apple privacy API declaration for User Defaults in OneSignal correct?

### ISSUE THREAD

**Issue by liamjones** [OneSignal/OneSignal-iOS-SDK#1426]
### How can we help?

I'm going through the Apple privacy manifest stuff currently.

We're currently behind and I realise I should update the OneSignal SDK dependencies on our project to get the releases that include the `PrivacyInfo.xcprivacy` files for your SDK.

However, can I confirm that the current one for your SDK is correct? For example Core & the Extension currently only list User Defaults reason `CA92.1`: https://github.com/OneSignal/OneSignal-iOS-SDK/blob/5e3d8e4c073ddc7333f62123fc6a2c354c2cfb7f/iOS_SDK/OneSignalSDK/OneSignalExtension/PrivacyInfo.xcprivacy#L39

Shouldn't they also declare `1C8F.1` since defaults in app groups are being used? https://github.com/OneSignal/OneSignal-iOS-SDK/blob/5e3d8e4c073ddc7333f62123fc6a2c354c2cfb7f/iOS_SDK/OneSignalSDK/OneSignalExtension/OneSignalExtensionBadgeHandler.m#L63

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @liamjones, thanks for reporting this find. 

You are correct, the information in User Defaults is used in app groups and app extension. We will make this update. I'll follow up once it is released.

**Comment by nan-li** [comment]
This is now in [Release 5.2.0](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.0)

**Comment by liamjones** [comment]
@nan-li is this going to be backported to the 3.x SDK line which also has the privacy manifest additions?

We're using this SDK via react-native-onesignal and can't upgrade to 5.x yet because we use identity verification.
