### ISSUE TITLE
[question]: Cannot add SDK to new app.

### ISSUE THREAD

**Issue by kunalzigma** [OneSignal/OneSignal-iOS-SDK#1428]
### How can we help?

Screenshots attached on what we are seeing. Tried resetting package caches, resolve package versions. Not working. 
<img width="1395" alt="File1714804982218" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/22952744/74ad998a-ea8e-4e0f-b493-824f0c4cb07c">
<img width="746" alt="File1714812336222" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/22952744/68a84c67-8bbc-4ff7-a62f-64e2953d3399">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @kunalzigma thank you for reporting. This is already tracked at https://github.com/OneSignal/OneSignal-iOS-SDK/issues/1424. Please see the other GitHub post for updates.
