### ISSUE TITLE
handleNotificationReceived is called when app is in background

### ISSUE THREAD

**Issue by allaire** [OneSignal/OneSignal-iOS-SDK#143]
I get double callbacks now on latest version. I did some debugging and it looks like `handleNotificationReceived` is now getting triggered when app is in background as well and the user press the notification? This goes against the note here: https://documentation.onesignal.com/docs/ios-native-sdk#section--oshandlenotificationreceivedblock-

`handleNotificationReceived` is not triggered when I receive the notification when the app is in the background, but right after I click on it, in that order:

```
handleNotificationAction
handleNotificationReceived
```

```swift
        // Push Notifications
        let oneSignalSettings: [AnyHashable: Any] = [
            kOSSettingsKeyAutoPrompt: false,
            kOSSettingsKeyInFocusDisplayOption: OSNotificationDisplayType.none.rawValue
        ]
        
        if Router.environment() == "production" {
            OneSignal.initWithLaunchOptions(launchOptions, appId: Constant.Vendor.oneSignalProdAppId, handleNotificationReceived: { (notification) in
                self.didReceiveRemoteNotification(notification: notification!)
            }, handleNotificationAction: { (result) in
                self.didReceiveRemoteNotification(notification: (result?.notification)!)
            }, settings: oneSignalSettings)
        } else {
            OneSignal.initWithLaunchOptions(launchOptions, appId: Constant.Vendor.oneSignalDevAppId, handleNotificationReceived: { (notification) in
                print("handleNotificationReceived")
                self.didReceiveRemoteNotification(notification: notification!)
            }, handleNotificationAction: { (result) in
                print("handleNotificationAction")
                self.didReceiveRemoteNotification(notification: (result?.notification)!)
            }, settings: oneSignalSettings)
            OneSignal.setLogLevel(.LL_DEBUG, visualLevel: .LL_ERROR)
        }```

**Comment by allaire** [comment]
@jkasten2 @JKalash  In the past I had to call the same method in both calback since I was using my own alert when app is in foreground

**Comment by allaire** [comment]
Any update on this?

**Comment by jkasten2** [comment]
@allaire Thanks for the details. I was able to reproduce the issue and fix it in commit 74e5ea31f02bbec089c829f67e81e12a533f532a. It will be included in the next release.

Feel free to reopen this issue if you see an issue after the update.

**Comment by allaire** [comment]
@jkasten2 I have a release that is in review,  am I fine with it or I should cancel and update the SDK? I used the solution at the bottom of my initial post (checking .active)

**Comment by jkasten2** [comment]
@allaire From a quick look I don't see any issue with using your code and using our 2.2.3 SDK to fix the extra firing of the `handleNotificationReceived` block.
