### ISSUE TITLE
[question]: Are you planning to add Privacy Manifest to version 2.16.x.?

### ISSUE THREAD

**Issue by P3troD** [OneSignal/OneSignal-iOS-SDK#1434]
### How can we help?

we are currently on 2.16.x version of OneSignal , and we need the privacy manifest update but to not want to be forced to update 3 major versions at this time

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @P3troD,

We don't have plans for continued support of the `v2.x.x` version. The next major versions are v3 and v5 (the SDK skips v4 to align versioning across other OneSignal SDKs such as Android).

Here is the v2 to v3 upgrade guide: https://documentation.onesignal.com/v9.0/docs/step-by-step-ios-native-2x-to-300-upgrade-guide. v3 has support for the Apple privacy requirements.

**Comment by hojatdelfan** [comment]
Hi @nan-li,
I am currently using version 3 of OneSignal, but I couldn't find a match with the Privacy Manifest. Could you please share the xcframework?
