### ISSUE TITLE
[question]: Embedded binary is not signed with the same certificate as the parent app. Verify the embedded binary target's code sign settings match the parent app's.

### ISSUE THREAD

**Issue by M2dL1fe** [OneSignal/OneSignal-iOS-SDK#1435]
### How can we help?

![image](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/8074125/8da13d7f-b00c-4c03-895b-bd0b55811e2c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @M2dL1fe, can you provide more details for your question, as it is not clear what this error is about and how it is related to the SDK.

- What exactly is the entire error message and stacktrace if any?
- Reproduction steps?
- Version of the OneSignal iOS SDK?

Also check out this stackoverflow discussion that looks like it may be of help: https://stackoverflow.com/questions/27906188/ios-error-embedded-binary-is-not-signed-with-the-same-certificate-as-the-parent

**Comment by M2dL1fe** [comment]
![image](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/8074125/9636427d-8c29-4d11-bebe-9235bd019d0d)
Occurs when Archive is executed. Version 5.1.6

**Comment by nan-li** [comment]
Hi @M2dL1fe, your screenshot shows an issue with "Build input file cannot be found..", a different issue than your original post for "Embedded binary is not signed with the same certificate as the parent app..."

Did you try deleting the Derived Data folder, and cleaning the build folder?

**Comment by M2dL1fe** [comment]
Deleted, still, is a problem OneSignal has had since signing

**Comment by emawby** [comment]
@M2dL1fe I am not able to reproduce this issue. Was this working on an older version of OneSignal for you and now it is not working on 5.1.6? Are you using automatic signing for your notification service extension target? If not do the signing certificates match? This error is typically because your notification service extension target and main application target are not signing with the same certificate.

**Comment by M2dL1fe** [comment]
only 5.1.6 , Yes, an autosignature was used @emawby

**Comment by M2dL1fe** [comment]
Upgrade to Xcode 16 Beta fix
