### ISSUE TITLE
FATAL: OneSignal AppId: (null) - AppId is null or format is invalid, stopping initialization. Example usage: 'b2f7f966-d8cc-11e4-bed1-df8f05be55ba'[question]: 

### ISSUE THREAD

**Issue by Mytrailpals** [OneSignal/OneSignal-iOS-SDK#1442]
[iosone-signal.docx](https://github.com/OneSignal/OneSignal-iOS-SDK/files/15476848/iosone-signal.docx)
### How can we help?

Hello OneSignal Team,
Integrating one signal push notification SDK with flutter.

Running into this Fatal in Xcode. Tried all I could found through search..  not sure Why app ID is null.

Seems like a bug to me, appreciate help.

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @Mytrailpals, thanks for reaching out to us. Since you are using Flutter, this is a misleading error message that prints from the integration of our Flutter SDK with our native iOS SDK.

I see shortly after that error log, the App ID is successfully set, so you can safely ignore the error log.

> VERBOSE: setAppId called with appId: 3a8cdf44-xxxxxxxxxxx
> VERBOSE: launchOptions is set and appId of 3a8cdf44-xxxxxxxxxxx is set, initializing OneSignal...

**Comment by Mytrailpals** [comment]
Thank you!
