### ISSUE TITLE
[question]: How can I proceed further with the one signal push android integration beyond this?

### ISSUE THREAD

**Issue by Mytrailpals** [OneSignal/OneSignal-iOS-SDK#1443]
### How can we help?

Sharing the android log, not able to find solution for this. Need help recolving it.
Attached the complete log file.

[androidone-signal-log.txt](https://github.com/OneSignal/OneSignal-iOS-SDK/files/15476868/androidone-signal-log.txt)

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @Mytrailpals thanks for reaching out, it looks like you have Identity Verification turned on for your app in the dashboard, but the v5.x.x of the OneSignal SDKs do not currently support Identity Verification.

**Comment by Mytrailpals** [comment]
Ok, thanks!
Would be really helpful if this was captured in Doc.
