### ISSUE TITLE
[Bug]: Mac Catalyst Build Breaks with Latest Release 

### ISSUE THREAD

**Issue by webbpage** [OneSignal/OneSignal-iOS-SDK#1445]
### What happened?

Release 5.2.0 build breaks for Mac Capacitor apps since there is no way to remove OneSignalLiveActivities.  

### Steps to reproduce?

```Markdown
Install OneSignal 5.2.0 with OneSignalXCFramework 5.2.0 (Capacitor App)
Try to deploy to Mac Catalyst. 
Errors occur related to OneSignalLiveActivities.
```

### What did you expect to happen?

I expected the ability to turn off OneSignalLive, vs resorting to previous release. 

### OneSignal iOS SDK version

Release 5.2.0

### iOS version

16

### Specific iOS version

```Markdown
iOS 16.2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jesus-mg-ios** [comment]
Same issue here

**Comment by nan-li** [comment]
Hi @webbpage and @jesus-mg-ios thanks for reporting this. We will take a look at this version and Mac Catalyst.

**Comment by nan-li** [comment]
@webbpage can you share the _Errors occur related to OneSignalLiveActivities_ you see?

@jesus-mg-ios are you using the native iOS SDK or a cross-platform SDK?

**Comment by jesus-mg-ios** [comment]
The native one, `While building for Mac Catalyst, no library for this platform was found in '/Volumes/workspace/DerivedData/SourcePackages/artifacts/onesignal-xcframework/OneSignalLiveActivities/OneSignalLiveActivities.xcframework'.`

**Comment by webbpage** [comment]
Same error received in cross-platform Capacitor SDK.

**Comment by nan-li** [comment]
Thanks I reproduced this and will add Mac Catalyst to supported destinations

**Comment by nan-li** [comment]
Hi everyone, the fix for this is in [Release 5.2.1](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.1). We will need to still update our cross-platform SDKs with this update.

**Comment by webbpage** [comment]
I'm still getting this error with 5.2.1. 

Are we suppose to do anything different our end for catalyst? iOS still works after the update.

**Comment by nan-li** [comment]
Hi @webbpage thanks for following up. There shouldn't be any additional steps. I'll take a look.

**Comment by webbpage** [comment]
Thank you for looking. Once confirmed, can you please put this bug back into open status? Please do not hesitate to reach out if you need anything from me.

**Comment by webbpage** [comment]
@jesus-mg-ios were you able to confirm you still had an issue with 5.2.1 ?

**Comment by nan-li** [comment]
Hi @webbpage thanks for your patience, we updated the Cordova SDK in [Release 5.2.3](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/5.2.3) to fix the mac catalyst build error.

**Comment by jesus-mg-ios** [comment]
@nan-li the problem persists out of Cordova SDK.

**Comment by nan-li** [comment]
Hi @jesus-mg-ios can you shared your errors on version 5.2.3?

**Comment by webbpage** [comment]
5.2.3 is working for me. I did have to re-add the OneSignalNotificationServiceExtension target in Xcode
<img width="395" alt="Screenshot 2024-07-08 at 12 51 03 PM" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/523477/696dfb6a-0d43-45b7-91a7-e227c67e61d9">
