### ISSUE TITLE
APNS Delegate never fired

### ISSUE THREAD

**Issue by ersp71** [OneSignal/OneSignal-iOS-SDK#1459]
### What happened?

With the in house production build onesignal displaying 'APNS Delegate never fired' status. This happen suddenly after we deployed new version. In previous version its working fine. Please suggest solution. We are using onesignal SDK 5.0.4 and we are not using any other SDK for push. We are unable to reproduce this with our test device.

### Steps to reproduce?

```Markdown
no step to reproduce.
```

### What did you expect to happen?

status should be subscribed.

### OneSignal iOS SDK version

5.0.4

### iOS version

17

### Specific iOS version

```Markdown
iOS 17.5.1
and some other older version
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@ersp71 What percentage of your subscription have this status?

There is only two ways that 'APNS Delegate never fired' can happen.
1. The device can't get a connection to Apple's push servers for over 30 seconds.
2. Some other library is interfering with the AppDelegate and OneSignal is not able to get events from it any more. The library doesn't necessarily have to support push to interfere with this.
   * Normally if this is the problem then it's consistent but it's possible there is a race condition with another library so it can't be rule out if your not always seeing the problem.

**Comment by nan-li** [comment]
Closing due to no response
