### ISSUE TITLE
[Bug]: Documentation lacking "Suppressing Launch URLs" section

### ISSUE THREAD

**Issue by Kwasow** [OneSignal/OneSignal-iOS-SDK#1462]
### What happened?

The old documentation had instructions on how to prevent notification URLs from launching in the default web browser: https://documentation.onesignal.com/v9.0/docs/links#suppressing-launch-urls

The v11 docs lack this section and do not explain how to prevent the default behavior.

### Steps to reproduce?

```Markdown
N/A
```

### What did you expect to happen?

N/A

### OneSignal iOS SDK version

Release 5.2.2

### iOS version

17

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @Kwasow 
Thanks for reaching out with your question. Here is the new [URLs, Links and Deep Links](https://documentation.onesignal.com/docs/links) 

For launch URL in particular, please see [Deep Linking](https://documentation.onesignal.com/docs/deep-linking) for details.
