### ISSUE TITLE
[Bug]: OSPropertyOperationExecutor update properties request failed with error alue of type 'string', received value of type 'number' instead

### ISSUE THREAD

**Issue by jesus-mg-ios** [OneSignal/OneSignal-iOS-SDK#1463]
### What happened?
```
ERROR: OSPropertyOperationExecutor update properties request failed with error: Optional(Error Domain=OneSignalError Code=400 "(null)" UserInfo={returned={
    errors =     (
                {
            title = "Field deltas.purchases.amount was expecting value of type 'string', received value of type 'number' instead";
        }
    );
    httpStatusCode = 400;
}})
```
### Steps to reproduce?

```Markdown
..
```

### What did you expect to happen?

No error

### OneSignal iOS SDK version

5.1.6

### iOS version

17, 16

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @jesus-mg-ios thank you for reporting. This bug was fixed in [Release 5.2.1](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.1).
