### ISSUE TITLE
UNNotifiactions deleted

### ISSUE THREAD

**Issue by juanjoguevara** [OneSignal/OneSignal-iOS-SDK#147]
I use UNUserNotificationCenter to send local notifications to my user.
If i add Onesignal for remote notifications my local notifiaction is deleted when the app go to foreground.
I see when the app enter in foreground Onesignal delete the badge of the app and all my notifications dissapear.

**Comment by jkasten2** [comment]
@juanjoguevara Our SDK by default clears badges when the app is opened or resumed. iOS has a know side effect of clearing all notifications for the app when the badge value to set to 0.

You can prevent our SDK from clear badges by setting `OneSignal_disable_badge_clearing` to `YES` in your `.plist`.
https://documentation.onesignal.com/docs/appearance#section-badges
