### ISSUE TITLE
[question]: Handling local notifications (in app)

### ISSUE THREAD

**Issue by rahatmodi** [OneSignal/OneSignal-iOS-SDK#1471]
### How can we help?

We use local notifications for some other features in the app. 
How do I 

- control notification presentation options when the local one is presented when app is in foreground
- get local notification response when selected

I am using addForegroundLifecycleListener and addClickListener but they don't fire for local notifications.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @rahatmodi thanks for reaching out.

You can set up and use local notifications, but that will be entirely managed by you.

The OneSignal SDK will only handle OneSignal-originated notifications.

**Comment by rahatmodi** [comment]
Yes I know that and I am trying to integrate the 2 worldsSince we are using your SDK for remote notifications we are are using your API's to receive 

onWillDisplayNotification

onClickNotification

It is here that I would usually look at it and determine that it is a local notification and deal with it hereHowever if it is a local notification these callbacks don't happen at all so I cannot take care of it.Looks like they only come if it is a OneSignal push..I could be wrong - can u verify this and  if what I am saying is indeed the case suggest what I need to do to receive them.
ThanksRahat Modi
    On Thursday, August 22, 2024 at 11:18:06 AM PDT, Nan ***@***.***> wrote:  
 
 


Hi @rahatmodi thanks for reaching out.

You can set up and use local notifications, but that will be entirely managed by you.

The OneSignal SDK will only handle OneSignal-originated notifications.
