### ISSUE TITLE
[question]: ...xcframework is not signed with the expected identity and may have been compromised

### ISSUE THREAD

**Issue by jward8** [OneSignal/OneSignal-iOS-SDK#1475]
### How can we help?

I'm currently trying to resolve some build issues with our iOS app and when adding the following
![image](https://github.com/user-attachments/assets/ca17ab20-d737-4a1b-930a-3ad109d9f30e)
into the frameworks and libraries of our OneSignalNotificationSerivceExtension, I've been getting the following errors:

`“OneSignalExtension.xcframework” is not signed with the expected identity and may have been compromised.
        “OneSignalCore.xcframework” is not signed with the expected identity and may have been compromised.
        “OneSignalOutcomes.xcframework” is not signed with the expected identity and may have been compromised.`

When looking and inspecting each framework in XCode I see that each framework is missing a signature and is unsigned. 
![image](https://github.com/user-attachments/assets/cfdd25de-5d2d-4ce1-b692-5421839f7525)

Is there a way that I can resolve this? I haven't been able to find any documentation on how to fix this so far.

Any help would be appreciated!

EDIT: XCode Version is 15.4 (15F31d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by obyadur-rahman-tsc** [comment]
Having the same issue here in Xcode Version 15.4 (15F31d)

**Comment by stefandbd** [comment]
Same issue here on Xcode Version 15.4 (15F31d)

**Comment by josancamon19** [comment]
Same issue here Version 15.3 (15E204a)

**Comment by jward8** [comment]
I was on 3.12.3. I ended up updating to the most recent version of OneSignal (5.1.3). It resolved the issue, however now I get a different issue related one of the frameworks. I added in the OneSignal.xcframework and now I get this error: 
`error: There is no XCFramework found at '/Users/distiller/project/Pods/OneSignal/iOS_SDK/OneSignalSDK/OneSignal_XCFramework/OneSignal.xcframework'. (in target 'OneSignalNotificationServiceExtension' from project`

**Comment by emawby** [comment]
@jward8 Good to hear that upgrading resolved it. It seems like the new issue is related to your NotificationServiceExtension and you are using cocoapods. If you have previously had it working then you could trying clearing derived data and your cocoapods cache then reinstalling pods. If it has never worked then if you could share your Podfile and target settings that would be helpful!
