### ISSUE TITLE
Action callback not working when the App is on foreground

### ISSUE THREAD

**Issue by ggallotti** [OneSignal/OneSignal-iOS-SDK#153]
iOS 10.
App is in foreground.

When a Push Notifications (with button actions) arrives,  if the user attempts to press an action within the Notification, the Action callback is not beign executed.

**Comment by jkasten2** [comment]
@ggallotti Thanks for the report. I have confirmed the issue when `OSNotificationDisplayTypeNotification` is set.

We will get a fix for this in the next release. Can you let us know if you were able to reproduce the the issue with another `kOSSettingsKeyInFocusDisplayOption` other than this?

**Comment by ggallotti** [comment]
We've tested with:
- OSNotificationDisplayTypeNotification 
- OSNotificationDisplayTypeInAppAlert 

In both modes we can reproduce the Issue.

**Comment by jkasten2** [comment]
@ggallotti I was only able to reproduce the issue with iOS 10 and the `OSNotificationDisplayTypeNotification` setting when tapping on the notification before it goes to the notification center. However commit e1aa421485996f3833337dcb248c9dc9f6ab44a6 should fix any cases where action callback may have not fired.
