### ISSUE TITLE
Disable clearBadgeCount

### ISSUE THREAD

**Issue by tspecht** [OneSignal/OneSignal-iOS-SDK#155]
Hey,

is there a possibility to turn off `clearBadgeCount`? I tried setting the `ios_badgeType` to `None` but my badge number is still disappearing when the app is not running. I'm also sending `content-available` if that should influence things in any way.

Thanks!

**Comment by jkasten2** [comment]
@tspecht Just tested this with SDK 2.3.3, it seems `content-available` is triggering a badge clear event in the SDK. The clear should only happen when opening / resuming the app.

#### Work around
To prevent our SDK from automatically clearing badges set `OneSignal_disable_badge_clearing` to `YES` as a `Boolean` type in your `.plist` in Xcode.

**Comment by tspecht** [comment]
Hey @jkasten2 thanks for confirming this! Just to make this clear: Are you talking about the `Info.plist` or do I need to create some separate configuration file for the SDK?

In any case, when can we expect that to be fixed?

**Comment by jkasten2** [comment]
@tspecht The `Info.plist`.

I'll include the fix in our next release. Will be shooting for the end of next week.

**Comment by tspecht** [comment]
Awesome, thanks a lot! Can you quickly ping us here once the release is out so we can update?

**Comment by jkasten2** [comment]
@tspecht Sure, I'll @ you in a comment and close this issue once released.

**Comment by jkasten2** [comment]
@tspecht After commit c184c4de82e32a2d82a4cb7857d5485b8942493e I was no longer able to reproduce this issue. It is part of the 2.3.4 release.
