### ISSUE TITLE
iOS 10 does not run my app notification extension when my app is not running 

### ISSUE THREAD

**Issue by yaroslav-tytarenko** [OneSignal/OneSignal-iOS-SDK#157]
Send notification with image url -> My app is active = success load image and show notification with image 
Send notification with image url -> My app is in background = success load image and show notification with image 
Send notification with image url -> My app is terminated = nothing 

Also I have tested sending notifications from bash script and when my app was  terminated, I always get notifications. 

I send notification from bash script, iPhone shows notification with image and I go to Xcode Debug -> Attach to process and I see MyAppExtension process but I do not see this process if I send notification from One Signal and my app is shutdown

**Comment by jkasten2** [comment]
@yaroslav-tytarenko Our iOS 10 media attachment feature actually uses `content-available` which won't trigger an extension. This does have the limitation where force closing the app prevents this from working. See our [Notifications with action buttons or iOS 10 media not displaying](https://documentation.onesignal.com/docs/troubleshooting-ios#section-notifications-with-action-buttons-or-ios-10-media-not-displaying) for a full list of requirements.

You can follow updates on using extensions below in issue #112.

Also note that [`UNNotificationServiceExtension`](https://developer.apple.com/reference/usernotifications/unnotificationserviceextension) and [`UNNotificationContentExtension`](https://developer.apple.com/reference/usernotificationsui/unnotificationcontentextension) do not work if an iOS media attachment is included as our back end will remove the `mutable-content` and `category` settings from the notification.
