### ISSUE TITLE
Disabling kOSSettingsKeyAutoPrompt is always firing registration

### ISSUE THREAD

**Issue by appcelerate** [OneSignal/OneSignal-iOS-SDK#163]
Hi, i want to trigger the prompt by myself and not after the startup and if i set kOSSettingsKeyAutoPrompt to false. The promt will come again :/

any ideas?

```
//One Signal Settings
NSDictionary * settings = @{kOSSettingsKeyAutoPrompt : @false};
[OneSignal initWithLaunchOptions:launchOptions appId:ONE_SIGNAL_APP_ID handleNotificationAction:nil settings:settings];
```

asked before here: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/103

**Comment by jkasten2** [comment]
@appcelerate Can you make sure you using the latest 2.3.4 version of the SDK?

I wasn't able to reproduce an issue with prompting the user for notifications when `kOSSettingsKeyAutoPrompt` is set to `false`. Do you have any other code in your app calling `registerUserNotificationSettings` or other notification plugins?

**Comment by jkasten2** [comment]
Closing due to inactively. Feel free to reopen this issue if you are still seeing this problem.
