### ISSUE TITLE
App kept running by OneSignal SDK due to location services

### ISSUE THREAD

**Issue by siburb** [OneSignal/OneSignal-iOS-SDK#164]
We noticed that our app was staying active much longer than it should be after it is put into the background. We do use the `significantLocationChanges` API for location updates when the app is in the background, but not standard location services.

Some digging around (by @adamdarton) demonstrated the following behaviour when in the background:
![pasted image at 2016_12_22 02_20 pm](https://cloud.githubusercontent.com/assets/1744275/21447389/0bb89c52-c90f-11e6-882a-85f25a3629e8.png)

And the following when we commented out the OneSignal init:
![pasted image at 2016_12_22 02_21 pm](https://cloud.githubusercontent.com/assets/1744275/21447396/1c8e2114-c90f-11e6-9ae8-cab34f0d6b05.png)

In order to use the `significantLocationChanges` API, we have to request "always" permission from the user. It seems that the OneSignal SDK is checking that we have that permission, and then continuously accessing location information. Obviously in cases where an app was using standard location services in the background then this would not be a problem.

![pasted image at 2016_12_22 11_22 pm](https://cloud.githubusercontent.com/assets/1744275/21447455/d39bc050-c90f-11e6-8a8c-7cc4faff30cc.png)

The best solution I can think of would be to allow us an option to manually set the location with the OneSignal SDK whenever we get a location update ourselves, rather than the SDK gathering the information itself. As it currently is, we're going to have to disable `shareLocation`, but we'd much rather we could allow the SDK to have the location as we get it.

**Comment by jkasten2** [comment]
Thanks for the detailed information. We will look into using `significantLocationChanges` in a future update when a flag is set.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
