### ISSUE TITLE
iOS crash by initializing OneSignal from Unity SDK

### ISSUE THREAD

**Issue by khindemit** [OneSignal/OneSignal-iOS-SDK#165]
We got a crash on iOS device after we cancelled a payment in sandbox and tried to restart our application.

OneSignalTrackIAP adds a subscription in init:
`[[skPaymentQueue performSelector:@selector(defaultQueue)] performSelector:@selector(addTransactionObserver:) withObject:self];`

but it does not hafe unsubscribe code:
```
- (void)dealloc {
    if (skPaymentQueue) {
        [[skPaymentQueue performSelector:@selector(defaultQueue)] performSelector:@selector(removeTransactionObserver:) withObject:self];
    }
}
```
In Unity SDK the method `OneSignal initWithLaunchOptions` is called two times (see the comment abofe this method) 
the line `trackIAPPurchase = [[OneSignalTrackIAP alloc] init]; `is called two times too. When it is called second time the 'trackIAPPurchase' reference is overrided and first subscription to skPaymentQueue become invalid.
I never created pull requests and do not know how to do it, that is why I wrote here.

**Comment by turkenh** [comment]
I am trying to use UnitySDK and my app keeps crashing after second launch. 
And it looks like it is due to the problem you mentioned.

I built with dealloc function you provided and it looks like the issue gone.
Thank you very much !!!

I will create a PR for this.

**Comment by turkenh** [comment]
By the way,
I took a build with version 2.3.2 (the one currently included in UnitySDK) and replaced the lib file with Assets/OneSignal/Platforms/iOS/libOneSignal.a
If anyone need it: https://www.dropbox.com/s/0qaheavck14d6ps/libOneSignal.a?dl=0
