### ISSUE TITLE
access Additional data in func didReceive(_ notification: UNNotification) {

### ISSUE THREAD

**Issue by appcelerate** [OneSignal/OneSignal-iOS-SDK#170]
How can I access in 
`func didReceive(_ notification: UNNotification) {`
the additional data from the payload?

**Comment by jkasten2** [comment]
@appcelerate You should setup a [OSHandleNotificationActionBlock](https://documentation.onesignal.com/docs/ios-native-sdk#section--oshandlenotificationactionblock-) block which will give you a Object where this has been parsed for you. See [initWithLaunchOptions](https://documentation.onesignal.com/docs/ios-native-sdk#section--initwithlaunchoptions-) for an example of setting one up.

**Comment by jkasten2** [comment]
Closing due to inactively. Feel free to reopen if you have more questions on this callback.

**Comment by ADevelopStudio** [comment]
@appcelerate if you still need it: 
        guard let customData = notification.request.content.userInfo["custom"] as? Dictionary<String,Any> else { return }
        guard let oneSignalAdditionalData = customData["a"]  as? Dictionary<String,String> else { return }
