### ISSUE TITLE
OneSignalLocation crashes app when method +[OneSignalLocation sendLocation] is called

### ISSUE THREAD

**Issue by smit-sonani-stl** [OneSignal/OneSignal-iOS-SDK#171]
In app delegate, I have disabled the location sharing to OneSignal by calling:
`OneSignal.setLocationShared(false)`
I have attached crash report on Thread 0 to have better Idea about this crash.
I am using Swift 3/Xcode 8.1 for building app.
![crashreport_min](https://cloud.githubusercontent.com/assets/22004563/21802860/7ffee4ee-d74d-11e6-9a9a-ca0af9b6d803.png)

**Comment by jkasten2** [comment]
@smit-sonani-stl Thanks for the report. Could you add which SDK version you are using? As well as the line number and exception of the crash.
