### ISSUE TITLE
actionSelected added to additionalData when it should be nil

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-iOS-SDK#172]
Even when no additional data or action button is added to the notification the following is set as `additionalData` in the opened block's `result`.
`actionSelected = "com.apple.UNNotificationDefaultActionIdentifier"; `

**Comment by nicolechen819** [comment]
I got the same issue on iOS 10.X device

**Comment by jkasten2** [comment]
@nicolechen819 This has been fixed in commit 597a4a374ea693ffc9d61d14b823494b47ca00c4 and will be included in the next release.
