### ISSUE TITLE
Double Push

### ISSUE THREAD

**Issue by evfemist** [OneSignal/OneSignal-iOS-SDK#18]
I used tags to define push receivers and when I send push notification I see that notification appears twice on iOS device, but everywhere it looks like notification was send only once. Here is the link that demonstrates issue: https://www.dropbox.com/s/97auh8w5ggaq67u/OneSignal_issue.mov?dl=0
Let me know if you need some additional info
I am using version 1.11.3

**Comment by jkasten2** [comment]
Thanks for the video, that that is very odd that the notification shows 2 times on the top then only shows a single one when you view the notification in the notification center. What version of iOS is your device running? Do you have any other SDKs or plugins in your app?

Are you sending this notification with our REST API? Could you post the JSON payload you're using to create the notification?

Thanks.

**Comment by evfemist** [comment]
iOS 9.2.1 - by the way on iOS 8 - it works correct
I have next SDK's: OneSignal, Parse, Crashlytics, FBSDKCoreKit
I am using REST API, and here is my dictionary for json:
`{
    "app_id" = "id_here";
    contents =     {
        en = "Testtest has requested to be your friend.";
    };
    data =     {
        alert = "Testtest has requested to be your friend.";
        badge = Increment;
        data =         {
            type = "post_user";
        };
    };
    "ios_badgeCount" = 1;
    "ios_badgeType" = Increase;
    isIos = 1;
    tags =     (
                {
            key = "lp_personId";
            relation = "=";
            value = 402;
        }
    );
}`

**Comment by evfemist** [comment]
Maybe it is a bug in ios 9, but not sure… https://forums.developer.apple.com/thread/13414

**Comment by marcelosalloum** [comment]
Hi guys,

I'm also getting the double notifications and the ios console prompts the following message:

`Mar 15 18:41:30 Marcelos-iPhone SpringBoard[58] <Warning>: SBLockScreenNotificationListController: Attempting to remove a bulletin I don't have`

**Comment by marcelosalloum** [comment]
Hey guys, I managed to solve it by just rebooting the phone, so it's probably an iOS bug.

BTW, I am also running on iOS 9.2.1

**Comment by lmrkllc** [comment]
We are seeing this in iOS 10.x as well.  Any other solution besides rebooting the phone?

**Comment by jkasten2** [comment]
@lmrkllc Are you currently able to reproduce the issue on a test device? Is it double showing only on the top of the screen or when you open the notification center as well?

Could you grab the full device log from Window > Devices in Xcode when the issue happens?

**Comment by lmrkllc** [comment]
hi @jkasten2, thanks for quick response!  Yes, we are able to reproduce the issue on a test device.  It is double showing only when we are running our app.  Will get the device log for you.

**Comment by jkasten2** [comment]
@lmrkllc When the app is in focus or even just in the background?

Can you reproduce the issue with a basic notification with just a message body set? With iOS 10 media attachments or action buttons.

Also are you able to reproduce the issue with our latest 2.3.6 SDK?

**Comment by lmrkllc** [comment]
@jkasten2 when app is in focus.  Currently on 2.3.4.  Will upgraded to 2.3.6 and see if I can duplicate.

**Comment by lmrkllc** [comment]
@jkasten2 Attached log.  Upgraded to OneSignal 2.3.4
[log.txt](https://github.com/OneSignal/OneSignal-iOS-SDK/files/817977/log.txt)
![screen shot 2017-03-03 at 4 33 35 pm](https://cloud.githubusercontent.com/assets/889021/23569796/305553fa-002f-11e7-8445-c979f0992860.png)

**Comment by lmrkllc** [comment]
@jkasten2 hi josh, any update on our issue?  if known issue, can you point us to your code where it occurs?  thanks, Kenny - Stash

**Comment by jkasten2** [comment]
@lmrkllc Sorry about the delay. I reviewed the log but only seen one notification being shown on the device. However the log only covers a 15 second window. How much time passed between seeing the first vs the 2nd notification?

Also can you let us if you see the duplicate at the top of the screen as a banner or in the notification center when you swipe down from the top of the screen.

I see you also have AppBoy in your app, can you try removing it to see if it also fixes the issue.

Lastly could you send this link to support and include the notification ids that produced a duplicate notification on the device?

**Comment by lmrkllc** [comment]
@jkasten2 no worries.  thank you!  
1.   It was instant between the 2 notifications
2.  No duplicate at top of screen banner or notification center
3.  Yes, we just added Appboy
     - When we send a notification via Appboy we get the duplicate notifications when app is running in foreground
    - When we comment out OneSignal, the Appboy notification comes in with no issues
    - When we dont have Appboy and just send message via OneSignal it works (no duplicates)

OneSignalHelper.m 
    isRemoteSilentNotification  <<===== looks like it meets this criteria so in OneSignal.m
    causes the 2 Alerts (Line 995)

Thank you,
Kenny

**Comment by jkasten2** [comment]
@lmrkllc Ah, you are seeing to alert boxes, not 2 notifications. By default we show an alert box when the app is in focus instead of showing a notification.

Do you have code in your app also displaying an alert? Either in your `AppDelegate`, `UNUserNotificationCenterDelegate`, or the OneSignal open / received blocks?

**Comment by lmrkllc** [comment]
@jkasten2 No we do not have code displaying an alert.  The notifications are coming from Appboy but OneSignal is swizzling and displaying the alerts?  Any way we can turn that off if not an notification coming from OneSignal?

- (void)installOneSignalWithLaunchOptions:(NSDictionary*)launchOptions  {
    NSDictionary *settings = @{
                               kOSSettingsKeyAutoPrompt:[NSNumber numberWithBool:NO]
                               };
    NSString *appId = ([[APIEndpointManager endpoint] isEqualToString:PRODUCTION_API_ENDPOINT]) ? STI_ONESIGNAL_PROD_APP_ID : STI_ONESIGNAL_STAGING_APP_ID;
    [OneSignal initWithLaunchOptions:launchOptions appId:appId handleNotificationAction:^(OSNotificationOpenedResult *result) {
        OSNotificationPayload* payload = result.notification.payload;
        NSLog(@"\nOSNotificationPayload : %@\n", [payload debugDescription]);
    } settings:settings];
    [OneSignal IdsAvailable:^(NSString *userId, NSString *pushToken) {
        if ([STIAuthController isLoggedIn] && [STIUser currentUser]) {
            [[[STIUserController alloc] init] postPushToken:pushToken andPlayerId:userId IdWithBlock:^(id response, NSError *error) {
                if (error) {
                    NSLog(@"%s, %@", __PRETTY_FUNCTION__, error);
                }
            }];
        }
    }];
}

Thanks,

Kenny

**Comment by jkasten2** [comment]
@lmrkllc You can add the [`kOSSettingsKeyInFocusDisplayOption`](https://documentation.onesignal.com/docs/ios-native-sdk#section--kossettingskeyinfocusdisplayoption-) key to the setting dictionary. You can set this to `OSNotificationDisplayTypeNone` to prevent our SDK from showing an alert or a notification.

**Comment by lmrkllc** [comment]
@jkasten2 You da man!!  That solved our issue!!!  Thank you very much!!!  - Stash Team

**Comment by jkasten2** [comment]
@evfemist Glad I could help!
