### ISSUE TITLE
"Apns Delegate Never Fired" status when OneSignal in the abstract_target in a Podfile

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-iOS-SDK#180]
Devices will have a "Apns Delegate Never Fired" status on the All Users page on the OneSignal dashboard when OneSignal is in the `abstract_target` in a `Podfile`. They may only happen when it also contains library project that gets embed into the app.

```Podspec
abstract_target 'AppNameApp' do
  use_frameworks!
  # some pods

  pod 'OneSignal', '~> 2.3.5'

  # more pods

  # This is the target for building the actual app
  target 'AppName' do
  end

  target 'AppNameTests' do
  end

  # AppNameLibrary is a framework we build and embed into the AppName app
  target 'AppNameLibrary' do
  end
end
```

Changing the `Podspec` like this fixes the issue.

```Podspec
abstract_target 'AppNameApp' do
  use_frameworks!

  # fewer pod definitions
  
  target 'AppName' do
    # more pod definitions
    pod 'OneSignal', '~> 2.3.5'
  end

  target 'AppNameTests' do
  end

  # AppNameLibrary is a framework we build and embed into the AppName app
  target 'AppNameLibrary' do
  end
end
```

**Comment by razvanpaul** [comment]
+1

This happens for me without the abstract_target thing. Using the 2.3.5 version.

**Comment by razvanpaul** [comment]
Switched back to 2.1.6 and everything works again.

**Comment by jkasten2** [comment]
@razvanpaul Could you share your `Podfile` reproducing the issue? Or a xcode project reproducing the issue? We should be able to find a fix once we are able to reproduce the issue. The above was from a client but we haven't been able reproduced it our selves yet.

Thanks.

**Comment by jkasten2** [comment]
@razvanpaul Fixed a `"Apns Delegate Never Fired"` error when "Background modes" > "remote notifications" were disabled and the user declined notifications. Can you check this in your project?

This was fixed in commit 9f51c127f1565d52b4a38f88930e250bd0eee099 and will be included in the next release.

**Comment by jkasten2** [comment]
@razvanpaul The commit noted above was released in 2.3.6. Can you try our latest 2.4.1 SDK to see if you still have this issue?

**Comment by jkasten2** [comment]
@razvanpaul I have made a number of changes in our 2.5.0 SDK around handling the current subscribed state and added a number of unit tests to ensure we are not reporting an inaccurate subscription state.

Let us know if you continue to see an issue after updating to the 2.5.1 SDK.

Thanks.

**Comment by MilotH2** [comment]
I am using Ionic with Capacitor on the latest versions, I had configured wrongly the steps, I did everything from beginning but slowly and reading everything as the documentation was saying. Now it is working.
