### ISSUE TITLE
Crash on -[OneSignalHTTPClient requestWithMethod:path:]

### ISSUE THREAD

**Issue by genadyo** [OneSignal/OneSignal-iOS-SDK#181]
Hey,

Any idea what is going on here?

http://crashes.to/s/983df30a38e
http://crashes.to/s/f8de7cc9c5d

**Comment by jkasten2** [comment]
@genadyo Thanks for the crash logs. We will look into it.

**Comment by genadyo** [comment]
http://crashes.to/s/c2082877587
http://crashes.to/s/44f89989c6c

**Comment by jkasten2** [comment]
Thanks for the additional logs.

This one is crashing on initializing our HTTP class.
http://crashes.to/s/c2082877587
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/2.3.5/iOS_SDK/OneSignal/OneSignal.m#L165

Seems odd as well as the oject is already created at this point, it is just returning it.
http://crashes.to/s/983df30a38e
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/2.3.5/iOS_SDK/OneSignal/OneSignalHTTPClient.m#L57

Seems like it might be related to the above.
http://crashes.to/s/f8de7cc9c5d

This one isn't a network related crash like the others.
http://crashes.to/s/44f89989c6c

We gotten any other crash reports like these. They all seem to be happening when your app is cold started. I wasn't able to see anything consistent on the other threads between your 4 crash logs but it seems like it might be caused from another SDK. Could you list all the other SDKs in your app and the Swift version and Xcode version you built your app with as well?

Are you able to reproduce a crash on your test devices?

**Comment by genadyo** [comment]
```  - Amplitude-iOS (3.12.1)
  - AppsFlyerFramework (4.6.3)
  - Armchair (0.1.1)
  - AWSCore (2.4.16)
  - AWSS3 (2.4.16):
    - AWSCore (= 2.4.16)
  - Bolts (1.8.4):
    - Bolts/AppLinks (= 1.8.4)
    - Bolts/Tasks (= 1.8.4)
  - Bolts/AppLinks (1.8.4):
    - Bolts/Tasks
  - Bolts/Tasks (1.8.4)
  - Crashlytics (3.8.3):
    - Fabric (~> 1.6.3)
  - Fabric (1.6.11)
  - FBSDKCoreKit (4.18.0):
    - Bolts (~> 1.7)
  - FBSDKMessengerShareKit (1.3.2)
  - FBSDKShareKit (4.18.0):
    - FBSDKCoreKit
  - JDStatusBarNotification (1.5.5)
  - JLRoutes (2.0.1)
  - Kingfisher (3.3.2)
  - OneSignal (2.3.5)
  - Smooch (5.4.3)``

Xcode 8.2.1 with the default Swift version.

Didn't happen for me when testing, it's a very rare crash but still the top one for me.

**Comment by jkasten2** [comment]
@genadyo Thanks for the list. We will compare it to others if they also run into the same issue.

Can you ensure you are not calling `OneSignal.initWithLaunchOptions` more than once in your app? It is possible the could be creating the crashes.

**Comment by genadyo** [comment]
yeah, 100% sure.

**Comment by jkasten2** [comment]
@genadyo We have made a number of internal changes to our SDK in 2.5.X to use serial queues which should fix any sort of rare race contains that may have been happening before. Can you try out this latest version to see if it fixes the issue for your app?

**Comment by genadyo** [comment]
Looks like its ok now, not sure if its because of you or me but lets close it.
