### ISSUE TITLE
how notification alert disable swift

### ISSUE THREAD

**Issue by kavoskhajavi** [OneSignal/OneSignal-iOS-SDK#182]
When my app is opened and it receives push notification alert is disable But when app close show alert

```
          OneSignal.initWithLaunchOptions(launchOptions, appId: "appid", handleNotificationReceived:             { (notification) in
         let payload: OSNotificationPayload? = notification?.payload
          
    
         let fullMessage: String? = payload?.body
   
         print("Recived no" + fullMessage!)
         
         print("Received Notification - \(notification?.payload.notificationID) - \(notification?.payload.title)")
         
          }, handleNotificationAction: nil, settings: [kOSSettingsKeyAutoPrompt : false, kOSSettingsKeyInAppAlerts : false])
```

**Comment by jkasten2** [comment]
@kavoskhajavi I recommend using [kOSSettingsKeyInFocusDisplayOption](https://documentation.onesignal.com/docs/ios-native-sdk#section--kossettingskeyinfocusdisplayoption-) instead as `kOSSettingsKeyInAppAlerts` is now depercated. Theses options only affect how notifications show when one is received when your app is in focus. Notifications received while the app is in the background / not running will always show in the notification center.

**Comment by jkasten2** [comment]
@kavoskhajavi Feel free to reopen this thread if this didn't work for you.

**Comment by kavoskhajavi** [comment]
Notifications received while the app is in the background / not running will always Hidden User and insert data to sqlite 

what do I do؟

**Comment by jkasten2** [comment]
@kavoskhajavi If you need to do background processing when a notification is received I recommending setting up a [`UNNotificationServiceExtension`](https://developer.apple.com/reference/usernotifications/unnotificationserviceextension) and setting `mutable_content` to `true` on your OneSignal notifications notifiations. This only works on iOS 10 so if you need support for older versions of iOS you can set `content_available` to `true`. Then our `handleNotificationReceived` will also fire in the background / when you're app is not running. However `content-available` won't work if the app has been `force-quit` such as swiping away the app from the recent app list.
