### ISSUE TITLE
Crash when opening Local Notification 

### ISSUE THREAD

**Issue by goyalsaurabh1988** [OneSignal/OneSignal-iOS-SDK#183]
I have implemented Push notifications using One Signal , but my app has local notifications as well .
whenever Local notification is clicked , One signal crashes the app. 
It says crash in "submit notification opened" method.
Please help .

**Comment by jkasten2** [comment]
@goyalsaurabh1988 Are you using the standard iOS methods or another SDK to setup local notifications?

Can you share the full crash log as well as the code you are using to create the local notification? Let us know the version of the OneSignal SDK you are using as well.

**Comment by goyalsaurabh1988** [comment]
@jkasten2  I am using the standard ios methods to schedule local notifications .
One signal version (2.3.5) is used 

log for crash

ScoreBell`-[swizzleUNUserNotif onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:]:
    0x10405f1c0 <+0>:   pushq  %rbp
    0x10405f1c1 <+1>:   movq   %rsp, %rbp
    0x10405f1c4 <+4>:   pushq  %r14
    0x10405f1c6 <+6>:   pushq  %rbx
    0x10405f1c7 <+7>:   subq   $0xb0, %rsp
    0x10405f1ce <+14>:  leaq   -0x28(%rbp), %rax
    0x10405f1d2 <+18>:  movq   %rdi, -0x18(%rbp)
    0x10405f1d6 <+22>:  movq   %rsi, -0x20(%rbp)
    0x10405f1da <+26>:  movq   $0x0, -0x28(%rbp)
    0x10405f1e2 <+34>:  movq   %rax, %rdi
    0x10405f1e5 <+37>:  movq   %rdx, %rsi
    0x10405f1e8 <+40>:  movq   %rcx, -0x60(%rbp)
    0x10405f1ec <+44>:  movq   %r8, -0x68(%rbp)
    0x10405f1f0 <+48>:  callq  0x104070206               ; symbol stub for: objc_storeStrong
    0x10405f1f5 <+53>:  leaq   -0x30(%rbp), %rax
    0x10405f1f9 <+57>:  movq   $0x0, -0x30(%rbp)
    0x10405f201 <+65>:  movq   -0x60(%rbp), %rcx
    0x10405f205 <+69>:  movq   %rax, %rdi
    0x10405f208 <+72>:  movq   %rcx, %rsi
    0x10405f20b <+75>:  callq  0x104070206               ; symbol stub for: objc_storeStrong
    0x10405f210 <+80>:  leaq   -0x38(%rbp), %rax
    0x10405f214 <+84>:  movq   $0x0, -0x38(%rbp)
    0x10405f21c <+92>:  movq   -0x68(%rbp), %rcx
    0x10405f220 <+96>:  movq   %rax, %rdi
    0x10405f223 <+99>:  movq   %rcx, %rsi
    0x10405f226 <+102>: callq  0x104070206               ; symbol stub for: objc_storeStrong
    0x10405f22b <+107>: movl   $0x6, %r9d
    0x10405f231 <+113>: movl   %r9d, %edx
    0x10405f234 <+116>: leaq   0xe8175(%rip), %rax       ; @"onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: Fired!"
    0x10405f23b <+123>: movq   0x168dfe(%rip), %rcx      ; (void *)0x00000001041db8e8: OneSignal
    0x10405f242 <+130>: movq   0x168267(%rip), %rsi      ; "onesignal_Log:message:"
    0x10405f249 <+137>: movq   %rcx, %rdi
    0x10405f24c <+140>: movq   %rax, %rcx
    0x10405f24f <+143>: callq  0x1040701b2               ; symbol stub for: objc_msgSend
    0x10405f254 <+148>: movq   0x169a15(%rip), %rax      ; (void *)0x00000001041db758: swizzleUNUserNotif
    0x10405f25b <+155>: movq   -0x30(%rbp), %rdx
    0x10405f25f <+159>: movq   0x168532(%rip), %rsi      ; "processiOS10Open:"
    0x10405f266 <+166>: movq   %rax, %rdi
    0x10405f269 <+169>: callq  0x1040701b2               ; symbol stub for: objc_msgSend
->  0x10405f26e <+174>: movq   -0x18(%rbp), %rax
    0x10405f272 <+178>: movq   0x1684ff(%rip), %rdx      ; "onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"
    0x10405f279 <+185>: movq   0x15f600(%rip), %rsi      ; "respondsToSelector:"
    0x10405f280 <+192>: movq   %rax, %rdi
    0x10405f283 <+195>: callq  0x1040701b2               ; symbol stub for: objc_msgSend
    0x10405f288 <+200>: testb  $0x1, %al
    0x10405f28a <+202>: jne    0x10405f28e               ; <+206> at UNUserNotificationCenter+OneSignal.m:143
    0x10405f28c <+204>: jmp    0x10405f2b2               ; <+242> at UNUserNotificationCenter+OneSignal.m:146
    0x10405f28e <+206>: movq   -0x18(%rbp), %rax
    0x10405f292 <+210>: movq   -0x28(%rbp), %rdx
    0x10405f296 <+214>: movq   -0x30(%rbp), %rcx
    0x10405f29a <+218>: movq   -0x38(%rbp), %r8
    0x10405f29e <+222>: movq   0x1684d3(%rip), %rsi      ; "onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"
    0x10405f2a5 <+229>: movq   %rax, %rdi
    0x10405f2a8 <+232>: callq  0x1040701b2               ; symbol stub for: objc_msgSend
    0x10405f2ad <+237>: jmp    0x10405f47b               ; <+699> at UNUserNotificationCenter+OneSignal.m:157
    0x10405f2b2 <+242>: movq   0x1699b7(%rip), %rax      ; (void *)0x00000001041db758: swizzleUNUserNotif
    0x10405f2b9 <+249>: movq   -0x30(%rbp), %rdx
    0x10405f2bd <+253>: movq   0x1684dc(%rip), %rsi      ; "isDismissEvent:"
    0x10405f2c4 <+260>: movq   %rax, %rdi
    0x10405f2c7 <+263>: callq  0x1040701b2               ; symbol stub for: objc_msgSend
    0x10405f2cc <+268>: testb  $0x1, %al
    0x10405f2ce <+270>: jne    0x10405f45c               ; <+668> at UNUserNotificationCenter+OneSignal.m:157
    0x10405f2d4 <+276>: leaq   0xe80f5(%rip), %rax       ; @"UNTextInputNotificationResponse"
    0x10405f2db <+283>: movq   -0x30(%rbp), %rcx
    0x10405f2df <+287>: movq   %rax, %rdi
    0x10405f2e2 <+290>: movq   %rcx, -0x70(%rbp)
    0x10405f2e6 <+294>: callq  0x104070098               ; symbol stub for: NSClassFromString
    0x10405f2eb <+299>: movq   0x15f346(%rip), %rsi      ; "isKindOfClass:"
    0x10405f2f2 <+306>: movq   -0x70(%rbp), %rcx
    0x10405f2f6 <+310>: movq   %rcx, %rdi
    0x10405f2f9 <+313>: movq   %rax, %rdx
    0x10405f2fc <+316>: callq  0x1040701b2               ; symbol stub for: objc_msgSend
    0x10405f301 <+321>: andb   $0x1, %al
    0x10405f303 <+323>: movb   %al, -0x39(%rbp)
    0x10405f306 <+326>: movb   -0x39(%rbp), %al
    0x10405f309 <+329>: movb   $0x0, -0x51(%rbp)
    0x10405f30d <+333>: testb  $0x1, %al
    0x10405f30f <+335>: je     0x10405f344               ; <+388> at UNUserNotificationCenter+OneSignal.m:148
    0x10405f311 <+337>: leaq   0xe80d8(%rip), %rax       ; @"userText"
    0x10405f318 <+344>: movq   -0x30(%rbp), %rcx
    0x10405f31c <+348>: movq   0x160945(%rip), %rsi      ; "valueForKey:"
    0x10405f323 <+355>: movq   %rcx, %rdi
    0x10405f326 <+358>: movq   %rax, %rdx
    0x10405f329 <+361>: callq  0x1040701b2               ; symbol stub for: objc_msgSend
    0x10405f32e <+366>: movq   %rax, %rdi
    0x10405f331 <+369>: callq  0x1040701e2               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x10405f336 <+374>: movq   %rax, -0x50(%rbp)
    0x10405f33a <+378>: movb   $0x1, -0x51(%rbp)
    0x10405f33e <+382>: movq   %rax, -0x78(%rbp)
    0x10405f342 <+386>: jmp    0x10405f34e               ; <+398> at UNUserNotificationCenter+OneSignal.m:148
    0x10405f344 <+388>: xorl   %eax, %eax
    0x10405f346 <+390>: movl   %eax, %ecx
    0x10405f348 <+392>: movq   %rcx, -0x78(%rbp)
    0x10405f34c <+396>: jmp    0x10405f34e               ; <+398> at UNUserNotificationCenter+OneSignal.m:148
    0x10405f34e <+398>: movq   -0x78(%rbp), %rax
    0x10405f352 <+402>: movq   %rax, %rdi
    0x10405f355 <+405>: callq  0x1040701d0               ; symbol stub for: objc_retain
    0x10405f35a <+410>: movq   %rax, -0x48(%rbp)
    0x10405f35e <+414>: testb  $0x1, -0x51(%rbp)
    0x10405f362 <+418>: jne    0x10405f366               ; <+422> at UNUserNotificationCenter+OneSignal.m:148
    0x10405f364 <+420>: jmp    0x10405f36f               ; <+431> at UNUserNotificationCenter+OneSignal.m:149
    0x10405f366 <+422>: movq   -0x50(%rbp), %rdi
    0x10405f36a <+426>: callq  0x1040701ca               ; symbol stub for: objc_release
    0x10405f36f <+431>: movq   0x1698fa(%rip), %rax      ; (void *)0x00000001041db758: swizzleUNUserNotif
    0x10405f376 <+438>: movq   -0x30(%rbp), %rcx
    0x10405f37a <+442>: movq   0x16829f(%rip), %rsi      ; "notification"
    0x10405f381 <+449>: movq   %rcx, %rdi
    0x10405f384 <+452>: movq   %rax, -0x80(%rbp)
    0x10405f388 <+456>: callq  0x1040701b2               ; symbol stub for: objc_msgSend
    0x10405f38d <+461>: movq   %rax, %rdi
    0x10405f390 <+464>: callq  0x1040701e2               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x10405f395 <+469>: movb   -0x39(%rbp), %dl
    0x10405f398 <+472>: movq   -0x30(%rbp), %rcx
    0x10405f39c <+476>: movq   0x168405(%rip), %rsi      ; "actionIdentifier"
    0x10405f3a3 <+483>: movq   %rcx, %rdi
    0x10405f3a6 <+486>: movq   %rax, -0x88(%rbp)
    0x10405f3ad <+493>: movb   %dl, -0x89(%rbp)
    0x10405f3b3 <+499>: callq  0x1040701b2               ; symbol stub for: objc_msgSend
    0x10405f3b8 <+504>: movq   %rax, %rdi
    0x10405f3bb <+507>: callq  0x1040701e2               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x10405f3c0 <+512>: xorl   %r8d, %r8d
    0x10405f3c3 <+515>: movq   -0x48(%rbp), %r9
    0x10405f3c7 <+519>: movq   -0x38(%rbp), %rcx
    0x10405f3cb <+523>: movq   0x1683be(%rip), %rsi      ; "callLegacyAppDeletegateSelector:isTextReply:actionIdentifier:userText:fromPresentNotification:withCompletionHandler:"
    0x10405f3d2 <+530>: movq   -0x80(%rbp), %rdi
    0x10405f3d6 <+534>: movb   -0x89(%rbp), %dl
    0x10405f3dc <+540>: andb   $0x1, %dl
    0x10405f3df <+543>: movq   -0x88(%rbp), %r10
    0x10405f3e6 <+550>: movb   %dl, -0x8a(%rbp)
    0x10405f3ec <+556>: movq   %r10, %rdx
    0x10405f3ef <+559>: movb   -0x8a(%rbp), %r11b
    0x10405f3f6 <+566>: movzbl %r11b, %ebx
    0x10405f3fa <+570>: movq   %rcx, -0x98(%rbp)
    0x10405f401 <+577>: movl   %ebx, %ecx
    0x10405f403 <+579>: movl   %r8d, -0x9c(%rbp)
    0x10405f40a <+586>: movq   %rax, %r8
    0x10405f40d <+589>: movl   $0x0, (%rsp)
    0x10405f414 <+596>: movq   -0x98(%rbp), %r14
    0x10405f41b <+603>: movq   %r14, 0x8(%rsp)
    0x10405f420 <+608>: movq   %rax, -0xa8(%rbp)
    0x10405f427 <+615>: callq  0x1040701b2               ; symbol stub for: objc_msgSend
    0x10405f42c <+620>: movq   -0xa8(%rbp), %rax
    0x10405f433 <+627>: movq   %rax, %rdi
    0x10405f436 <+630>: callq  0x1040701ca               ; symbol stub for: objc_release
    0x10405f43b <+635>: movq   -0x88(%rbp), %rax
    0x10405f442 <+642>: movq   %rax, %rdi
    0x10405f445 <+645>: callq  0x1040701ca               ; symbol stub for: objc_release
    0x10405f44a <+650>: xorl   %ecx, %ecx
    0x10405f44c <+652>: movl   %ecx, %esi
    0x10405f44e <+654>: leaq   -0x48(%rbp), %rax
    0x10405f452 <+658>: movq   %rax, %rdi
    0x10405f455 <+661>: callq  0x104070206               ; symbol stub for: objc_storeStrong
    0x10405f45a <+666>: jmp    0x10405f479               ; <+697> at UNUserNotificationCenter+OneSignal.m:157
    0x10405f45c <+668>: movq   -0x38(%rbp), %rax
    0x10405f460 <+672>: movq   %rax, %rcx
    0x10405f463 <+675>: movq   %rcx, %rdi
    0x10405f466 <+678>: movq   %rax, -0xb0(%rbp)
    0x10405f46d <+685>: movb   $0x0, %al
    0x10405f46f <+687>: movq   -0xb0(%rbp), %rcx
    0x10405f476 <+694>: callq  *0x10(%rcx)
    0x10405f479 <+697>: jmp    0x10405f47b               ; <+699> at UNUserNotificationCenter+OneSignal.m:157
    0x10405f47b <+699>: xorl   %eax, %eax
    0x10405f47d <+701>: movl   %eax, %esi
    0x10405f47f <+703>: leaq   -0x38(%rbp), %rcx
    0x10405f483 <+707>: movq   %rcx, %rdi
    0x10405f486 <+710>: callq  0x104070206               ; symbol stub for: objc_storeStrong
    0x10405f48b <+715>: xorl   %eax, %eax
    0x10405f48d <+717>: movl   %eax, %esi
    0x10405f48f <+719>: leaq   -0x30(%rbp), %rcx
    0x10405f493 <+723>: movq   %rcx, %rdi
    0x10405f496 <+726>: callq  0x104070206               ; symbol stub for: objc_storeStrong
    0x10405f49b <+731>: xorl   %eax, %eax
    0x10405f49d <+733>: movl   %eax, %esi
    0x10405f49f <+735>: leaq   -0x28(%rbp), %rcx
    0x10405f4a3 <+739>: movq   %rcx, %rdi
    0x10405f4a6 <+742>: callq  0x104070206               ; symbol stub for: objc_storeStrong
    0x10405f4ab <+747>: addq   $0xb0, %rsp
    0x10405f4b2 <+754>: popq   %rbx
    0x10405f4b3 <+755>: popq   %r14
    0x10405f4b5 <+757>: popq   %rbp
    0x10405f4b6 <+758>: retq

**Comment by goyalsaurabh1988** [comment]
I checked more and it seems to crash on iOS 10 and above when the app is in foreground .
Could you please help .

**Comment by goyalsaurabh1988** [comment]
PFA for exact crash report 

[com.scorebell_issue_38_crash_9448762e5afc4c939baaaaa0e125c7c2_ad77edfbbfc8409c92337126f5efde10_0_v1.txt](https://github.com/OneSignal/OneSignal-iOS-SDK/files/777401/com.scorebell_issue_38_crash_9448762e5afc4c939baaaaa0e125c7c2_ad77edfbbfc8409c92337126f5efde10_0_v1.txt)

**Comment by jkasten2** [comment]
@goyalsaurabh1988 Thanks for the crash log. I see `onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:` listed a number of times in a row one after another. This seems to be a sizzling issue but it could also happen if your displaying another notification from this event right away.

We haven't had any other reports like this with sizzling this method. Can you reproduce the issue in a new project? You can share it as a github repo or attach a zip of the full project here.

Thanks.

**Comment by goyalsaurabh1988** [comment]
The issue is coming when the app is in foreground and I receive the notification and click on it on IOS 10 .
It is coming normally , like in case of general push from one signal also crashes is the app is not in closed state .
is there any method of receiving push if the app is not closed  .

**Comment by goyalsaurabh1988** [comment]
Please let me know any update on this  ?

**Comment by jkasten2** [comment]
@goyalsaurabh1988 I tried to display a local notification with your category but wasn't able to reproduce an issue on iOS 10.2.1. The issue is most likely dependent on other code in your app like the AppDelegate selectors and if you setup a `UNUserNotificationCenterDelegate`.

Can you include this to as well as the code displaying the local notification itself? If possible please send us a project so we can reproduce the issue quicker.

**Comment by stepchud** [comment]
Hi, I'm having a very similar problem. I'm on version 2.3.5 (iOS 10.2) and my app crashes on launch if I use `kOSSettingsKeyDisplayOption` *OR* `kOSSettingsKeyInAppAlerts` keys in the settings:

```
        OneSignal.initWithLaunchOptions(
            options,
            appId: "xxxxx-xxx-xxx-xxx-xxxxxx",
            handleNotificationReceived: { (notification) in
                print("handleNotificationReceived: \(notification)")

            }, handleNotificationAction: { (result) in
                print("handleNotificationAction: \(result)")
                // Called when the user clicks a push notif they received
                let payload = result?.notification.payload
                // fetch the selected action or event
                if let additionalData = payload?.additionalData {
                    self.handleNotificationAction(additionalData as! [String : Any])
                }
            }, settings: [
                kOSSettingsKeyInFocusDisplayOption: OSNotificationDisplayType.none
            ]
        )
```

This also crashes if I try to use `OSNotificationDisplayType.inAppAlert`. The same initWithLaunchOptions implementation works correctly if I use:
```
settings: [
                kOSSettingsKeyAutoPrompt : false
]
```

The crash message in the xcode log isn't very helpful:
`libc++abi.dylib: terminating with uncaught exception of type NSException`

I'd like to use GSMessages for in app messages instead of the default one, but this is still broken even when I remove GSMessages from the app.

**Comment by stepchud** [comment]
@jkasten2 ^^ Should I create a new issue since my stacktrace is a bit different? This is affecting the UX for me since I can't choose anything other than the default message option.

**Comment by jkasten2** [comment]
With Swift you need to use `OSNotificationDisplayType.none.rawValue` instead of `OSNotificationDisplayType.none`.

Since this thread is about a creating a local notification issue please create another issue for this setting issue. Also the way you captured the crash log didn't provide source line numbers. Please follow our guide below when creating a new thread to for the crash log.
https://documentation.onesignal.com/docs/troubleshooting-ios#section-how-to-get-a-crash-log-from-an-ios-device

**Comment by goyalsaurabh1988** [comment]
Hello @jkasten2 The issue is resolved . 
and it was  occuring as the delegate for notification was being set on clicking on the notiifcation as well . 
So it was causing the issue .
Thanks anyways .:)

**Comment by jkasten2** [comment]
@goyalsaurabh1988 Good to hear your up and running now. Thanks for the information. Just to confirm the issue in case others run into it. You were seetting `UNUserNotificationCenter.current().delegate` from the delegate's `userNotificationCenter(_:didReceive:withCompletionHandler:)` method?

**Comment by ANMOLRATTANAA** [comment]
0x106250c68 <+159>: movq   0xe7f729(%rip), %rbx      ; (void *)0x00000001058a1d20: objc_release
