### ISSUE TITLE
Provide example for notification priming

### ISSUE THREAD

**Issue by intonarumori** [OneSignal/OneSignal-iOS-SDK#184]
I've been starting to use the OneSignal iOS SDK and I found it very outdated in terms of modern iOS application needs.
- almost all applications these days will try to explain first why remote notifications are needed
Please check couple of examples here: https://www.useronboard.com

- the default `kOSSettingsKeyAutoPrompt = true` is not a sensible choice any more as most people will not allow notifications for a new app

A new example with proper notification priming could help developers to more easily integrate the OneSignal SDK. Right now it's really hard to figure out the details.

**Comment by jkasten2** [comment]
@intonarumori We have updated our iOS setup guide to recommend setting `kOSSettingsKeyAutoPrompt ` to `false` and prompt at a later time.
https://documentation.onesignal.com/docs/ios-sdk-setup#section-4-add-required-code

In the next major version (3.0.0) we plan to default to auto prompting to false to simplify the required code.
