### ISSUE TITLE
kOSSettingsKeyInFocusDisplayOption setting not working

### ISSUE THREAD

**Issue by hugoerg56** [OneSignal/OneSignal-iOS-SDK#185]
Every time I receive a new notification the show an alert with the title of the push notification, 

my setting is on OSNotificationDisplayTypeNone

sdk version 2.1.16

**Comment by jkasten2** [comment]
@hugoerg56 There have been a number of release after 2.1.16 that could have fixed this issue. Can you try our latest 2.3.5?

If you are still seeing an issue please make sure you are calling OneSignal initWithLaunchOptions from `application:didFinishLaunchingWithOptions:`

**Comment by ogres** [comment]
I have the same problem with 2.3.5 ,

I am using `kOSSettingsKeyInFocusDisplayOption: @(OSNotificationDisplayTypeNone)` but OneSignal still shows Alert.

When I enable logs via `setLogLevel`, it also alerts all the logs.

Although it does not happen always. 
But if the device has the problem, the only solution is to re-install the app, restarting/disabling-enabling permissions wont have effect.

**Comment by ogres** [comment]
I could not reproduce the issue since then, but if it still happens, I will let you know the details.

**Comment by bowenisdum** [comment]
I am getting this none stop today, for no reason :/ tried both 2.3.5 and 2.3.7 same issue.

```OneSignal.initWithLaunchOptions(launchOptions, appId: App.oneSignalAppID, handleNotificationReceived: { (notification) in
            PushNotificationRouter.sharedInstance.handleNotificationReceived(notification: notification!)
        }, handleNotificationAction: { (result) in
            PushNotificationRouter.sharedInstance.handleNotificationAction(result: result!)
        }, settings: [
            kOSSettingsKeyInFocusDisplayOption:OSNotificationDisplayType.none.rawValue,
            kOSSettingsKeyAutoPrompt:false,
            kOSSettingsKeyInAppAlerts: false
            ])```

**Comment by jkasten2** [comment]
@hugoerg56 Was this after a fresh install on the device? Where else in your code did you print `ONESIGNAL_ALERT_OPTION`?

**Comment by ogres** [comment]
It happened again and I checked `ONESIGNAL_ALERT_OPTION`, its set to `1`.
It was fresh install.

I still have the affected device, please let me know if you need more information.

**Comment by ogres** [comment]
I think I found a way to reproduce the issue.

1. Launch the app with `kOSSettingsKeyInFocusDisplayOption = OSNotificationDisplayTypeNone`
2. Verify that `ONESIGNAL_ALERT_OPTION` is set to `0`
3. Clear user defaults ( for example UserDefaults.standard.removePersistentDomain )
4. Verify that Standard UserDefaults no longer contains `ONESIGNAL_ALERT_OPTION`
5. Send push notification to the device. ( Don't restart app during between steps )

Now you will see Push notification alert and if you check UserDefaults, it will contain `ONESIGNAL_ALERT_OPTION=1`

**Comment by jkasten2** [comment]
@ogres Thanks for the details. This is expected since `UserDefaults.standard.removePersistentDomain` will clear all of OneSignal's setting and stored data. You won't normally call this in a released app so I don't think this should be a concern.

**Comment by ogres** [comment]
I can't agree.

It does not seem right, that OneSignal takes configuration and then overrides it on the fly. There is no need for this at all, because only place to configure OneSignal is during init.
I think it should not read `ONESIGNAL_ALERT_OPTION` or configuration each time notification is received. Instead it should always use whatever was given in configuration.

Also, It's not rare to clear UserDefaults when user wants to logout/delete all the data.

**Comment by bendodson** [comment]
I agree with @ogres as I've just seen this issue appear in one of my apps and I use `UserDefaults.standard.removePersistentDomain` as it is the best way of ensuring the defaults have been cleared (otherwise, you'd need to manually track and delete every key you used).

**Comment by bendodson** [comment]
Would it be possible to get a method added to the SDK so that the `kOSSettingsKeyInFocusDisplayOption` flag can be set manually outside of the initiation? That way, I can re-set my display option after I've cleared the defaults...

**Comment by ogres** [comment]
@bendodson  workaround would be to save it in UserDefaults again

**Comment by jkasten2** [comment]
@ogres @bendodson This setting doesn't need to be saved to storage so I'll change this to be a used from from a variable only.

Ultimately we I am looking at creating a mechanism to control this on a per notification bases so the payload can used as part of the logic. Similar to [`userNotificationCenter:willPresentNotification:withCompletionHandler:`](https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc). However in the mean time we can expose a public method to set the in focus display option.

I'll keep in mind that `removePersistentDomain` will be used in production app when making future changes to the SDK.

**Comment by jkasten2** [comment]
@ogres @bendodson Made these changes in commit 7862d527f147fc527672d529a046bd39e19b6627 which will got out with our 2.5.0 release.

**Comment by UtkuDalmaz** [comment]
It still shows notifications when the app in focus even though I set OneSignal.inFocusDisplayType = OSNotificationDisplayType.none 

The latest version of ios sdk via cocoapods
