### ISSUE TITLE
Linker Command Failed using Cocoapod

### ISSUE THREAD

**Issue by EgaSetya** [OneSignal/OneSignal-iOS-SDK#187]
I'm using XCode 8.1. 

Below is my error log:
**Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_OneSignal", referenced from:
      objc-class-ref in ASAppDelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

How I can fix this?

**Comment by jkasten2** [comment]
@EgaSetya Could you make sure you are using the latest version of Cocoapods? Also make sure you have opened the new `.xcworkspace` Cocoapods creates instead of your original project file.

**Comment by EgaSetya** [comment]
Yes I use the latest version of Cocoapods. I actually solved my problem with adding **$(inherited**) on other linker flags

**Comment by jkasten2** [comment]
@EgaSetya Good to hear you got it working, I believe `$(inherited)` is default with a new Xcode project.
