### ISSUE TITLE
XCode6.4 linker error : "_UIUserNotificationActionResponseTypedTextKey", referenced from:

### ISSUE THREAD

**Issue by JohnnyWanna** [OneSignal/OneSignal-iOS-SDK#191]
**XCode 6.4 , Cocoapods 1.2.0 , SDK 2.3.5**

**Hi, I Setup the SDK follow the option A. But when it complied，I met the Apple Mach-O linker Error.**

`**Undefined symbols for architecture arm64:
  "_UIUserNotificationActionResponseTypedTextKey", referenced from:
      +[swizzleUNUserNotif callLegacyAppDeletegateSelector:isTextReply:actionIdentifier:userText:fromPresentNotification:withCompletionHandler:] in OneSignal(UNUserNotificationCenter+OneSignal.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)**` 

**I have added '$(inherited)' flags in OTHER_LINKER_FLAGS and  tried other solution but don't work :( 
Until I download the new version of XCode7.2.1, It complies well with the same Project.** 

**Does the sdk not support xcode6.4 ? Can someone explain this?**

**Best Thanks**

**Comment by jkasten2** [comment]
@JohnnyWanna Sorry we only support Xcode 7.3.1 and newer. However it may still work with older versions of Xcode that we don't test with. I know that any Xcode 6.X version won't compile due to it missing the symbols you listed above.

**Comment by JohnnyWanna** [comment]
Thanks for replying , Xcode7.2.1 also works well :)
