### ISSUE TITLE
Communicating notifications within two apps

### ISSUE THREAD

**Issue by Ptidou** [OneSignal/OneSignal-iOS-SDK#193]
Hi,
Is it possible to add a second iOS application to an existing OneSignal project. I have 2 applications and I have created two OneSignal projet but when I send a notification to a user who belong to the second application, I get this error "All included players are not subscribed". I want to merge these two applications to have 1 big database of pushToken (playerID).

**Comment by jkasten2** [comment]
@Ptidou Just to confirm. You have 2 different iOS apps with 2 different bundle ids and a different OneSignal app_id for each?

If this is the case how are you sending notifications? With our `postNotification` SDK method or with our REST API? The `postNotification` only works to send notifications to other users on the same OneSignal app_id. You will to use the REST API with the correct 1app_id1 set that the target `include_player_ids` are on to send a notification.

**Comment by jkasten2** [comment]
@Ptidou We are adding support allow overriding the `app_id` on our `postNotification` in our 2.5.0.

Please let us know if you need more information on the above.

**Comment by Andriiklymiuk** [comment]
So, to be clear, if I have 2 iOS apps with 2 different ids and 2 android apps, I can sent from whomever I want (from this apps) to other apps? How exactly it can be done?

like that in swift?
OneSignal.postNotification(["contents": ["en": "Test Message"], "app_id": ["my_one_signal_app_id"]])
or like that in android?
try {
  OneSignal.postNotification(new JSONObject("{'contents': {'en':'Test Message'}, 'app_id': ['" + my_one_signal_app_id + "']}"), null);
} catch (JSONException e) {
  e.printStackTrace();
}

I just so desperate to figure out, how to do it and if it is possible, can you please say how? Would really appreciate your help)

**Comment by farpoint1968** [comment]
Hello, I Have exactly the same issue, is someone found out a solution? 

Thanks

**Comment by MohNage7** [comment]
any solution for this ?

**Comment by Nightsd01** [comment]
I am not sure why exactly you would want to do such a thing. I would recommend implementing the two apps separately and sending the notifications in question from your backend using the REST API. 

You can send push notifications using the `postNotification()` method to any app as long as you supply both the user ID (AKA playerID) and the app ID.

**Comment by Shivoham0526** [comment]
Does anybody have an example call to onesignal PostNotification that includes appid?  One Signal documentation has the following example that does not include appid.

OneSignal.postNotification(["contents": ["en": "Test Message"], "include_player_ids": ["3009e210-3166-11e5-bc1b-db44eb02b120"]])

**Comment by FayyazAliKhan1** [comment]
I want to clarify please lemme know about this
I have 2 IOS apps with 2 different bundle ids & 1 Onesignal app
1 IOS app was connected with the that onesignal app, & now I want to use the same onesignal app for the other IOS app
will it work or not with the new IOS app I mean would I be able to get notifications in the second app as well?

**Comment by jkasten2** [comment]
@FayyazAliKhan1 OneSignal only supports 1 .p12 push certificate for iOS notifications. You must use a different OneSignal App Id for each iOS bundle id you have. Otherwise notifications will fail to send due to a mismatch bundle id error.

**Comment by FayyazAliKhan1** [comment]
@jkasten2 Thanks dude,
what about the same procedure in android ? won't it work on android as well?
