### ISSUE TITLE
Some of the devices cannot receive notification with error other APNS 3000

### ISSUE THREAD

**Issue by JohnnyWanna** [OneSignal/OneSignal-iOS-SDK#195]
Hi, 
I test app's notification function  in many devices. Most of them works well, but there're a few devices (**one of it is rooted**) can't receive  notification with error **other Apns 3000**.I'm pretty sure I have enabled Push Notifications and and cross-check everything but can't get any progress.

Unfortunately, i don't have any wrong devices at hand.

sdk version: 2.3.5
xcode: 8.2.1

**Comment by jkasten2** [comment]
@JohnnyWanna The 3000 error means that the app couldn't find the `.entitlements` file in your app or it is missing the key `aps-environment`. You will only see this specific error on iOS 10 devices. The device being rooted could be a factor, it is hard to say.

We would need a device log to be able to look into the issue.

**Comment by JohnnyWanna** [comment]
@jkasten2 ,Thank your replying. I did add .entitlements file  and set the aps-environment.

All of the problem devices are in my parter‘s hand. Until now, I knew he resigned my ipa. =。=
I want to know, Would OngSianal work well with the resigned App that changed the provisioning file?   Now the situation is some of his devices working well , but others can't.

**Comment by jkasten2** [comment]
@JohnnyWanna The resigning would most likely create an issue. Certainly if the app's Bundle Identifier changed.

Can you try using Apple's testflight so you are testing with the same build on all your devices? Test flights are considered production builds.

**Comment by JohnnyWanna** [comment]
@jkasten2  It's very appreciated for your help ! ! !

**Comment by kierandesmond** [comment]
Just a quick question. In a production build - would the entitlements file be present vs exporting an archive? Getting this problem too.
