### ISSUE TITLE
I would need a getLocation from User

### ISSUE THREAD

**Issue by Lukaris** [OneSignal/OneSignal-iOS-SDK#196]
Hi, 
I know, the user location is tracked on the dashboard.. there is only a "setLocation" .. however, in my case I am tracking the location also in my app. so in this case if I prompt.. OneSignal and my app would track the location.  

I know how to set up when user enters a certain tag - defined area..
however, I would love to read a users geolocation   (get the others onesignal users from firebase, where i save them after registration with onesignal)

// - Request and track user's location
+ (void)promptLocation;
+ (void)setLocationShared:(BOOL)enable;

what do you think ?

thanks,
Peter

**Comment by jkasten2** [comment]
@Lukaris I recommend keeping your own location in code in your app. The location stored in our system is designed to be used to target users within a specific area.
