### ISSUE TITLE
Typos in NotificationService code

### ISSUE THREAD

**Issue by jamesfzhang** [OneSignal/OneSignal-iOS-SDK#207]
In the new `NotificationService`, there are multiple typos:

- Property `recievedRequest` should be `receivedRequest`
- Class method `didReceiveNotificatioExtensionnRequest` should be `didReceiveNotificationExtensionRequest`

**Comment by jkasten2** [comment]
@jamesfzhang Thanks for reporting this! Fixed this in commit acf8d3b13167c3c3c9008b0b60187043a618f67a. Framework release header will be updated in 2.4.2 with this fix.
