### ISSUE TITLE
Chinese (Traditional) is showing up as Chinese (Simplified)

### ISSUE THREAD

**Issue by yishus** [OneSignal/OneSignal-iOS-SDK#21]
Phones with traditional chinese locale are showing up as `"language":"zh-Hans"`. Unable to target users on zh-Hant

**Comment by jamesstout** [comment]
Are you running on iOS9?

[OneSignal.m](https://github.com/one-signal/OneSignal-iOS-SDK/blob/4e7ed24c9dd0d8409fbef0931203f18fd9a693ab/iOS_SDK/OneSignal/OneSignal.m#L404) uses:

`[[NSLocale preferredLanguages] objectAtIndex:0], @"language"`

However, there is an [Apple Tech Note](https://developer.apple.com/library/ios/technotes/tn2418/_index.html) that says:

> With iOS 9, the results returned by NSLocale.preferredLanguages() can differ from previous releases

But that shouldn't switch zh-Hant to zh-Hans though...

Probably need to know a littlebit more about your device. iOS version, phone language setting, and region, and if the app you are running is localised or not.

Maybe the output from some of these:

```objc
NSArray *languages = [[NSUserDefaults standardUserDefaults] objectForKey:@"AppleLanguages"];
NSString *currentLanguage = [languages objectAtIndex:0];
NSLog(@"Current language: %@", currentLanguage);
	
NSArray* preferredLanguages = [NSLocale preferredLanguages];
NSLog(@"preferredLanguages: %@", preferredLanguages);
	
NSString* localeID = [NSLocale currentLocale].localeIdentifier;
NSDictionary* components = [NSLocale componentsFromLocaleIdentifier:localeID];
NSString* languageID = components[NSLocaleLanguageCode];
	
NSLog(@"localeID: %@", localeID);
NSLog(@"components: %@", components);
NSLog(@"languageID: %@", languageID);
```

**Comment by yishus** [comment]
Thanks for your reply.

iOS version: 9.3.1
App running is localised for Chinese Traditional.

```
Current language: zh-Hant-SG
preferredLanguages: ["zh-Hant-SG", "en-SG"]
localeID: zh-Hant_SG
components: ["kCFLocaleCountryCodeKey": "SG", "kCFLocaleLanguageCodeKey": "zh", "kCFLocaleScriptCodeKey": "Hant"]
languageID: zh
```

I run into a problem when I try to send a push to a segment on the dashboard. If you see the image below
![screen shot 2016-05-10 at 3 12 56 pm](https://cloud.githubusercontent.com/assets/5773874/15138419/51cbdace-16c2-11e6-9878-dc07eea51bff.png)

The device is appearing under the Chinese Simplified segment when it should be in Chinese Traditional.

**Comment by yishus** [comment]
@jamesstout any update on this?

**Comment by jamesstout** [comment]
Not really. Everything looked OK. I think we need a OneSignal dev to check what their server is doing.

**Comment by jkasten2** [comment]
@yishus @jamesstout We just deployed a server side fix for this. "zh-Hant-SG" should be mapping to "zh-Hant" correctly now after you force kill your app and open it again.

**Comment by yishus** [comment]
@jkasten2 thanks!
