### ISSUE TITLE
Request: expose currentReachabilityStatus

### ISSUE THREAD

**Issue by jamesstout** [OneSignal/OneSignal-iOS-SDK#210]
Most people have some sort of reachability monitoring in their app, either homegrown or from an open source project. Since this SDK does the monitoring, it would be nice maybe to expose the network status so people can use that instead of their own. Maybe a method that exposes line [533](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/06f6e14c8e2b9439a466a0a4afd68ce281fe1519/iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m#L533)

````objc
+(NSNumber*)getNetType {
    OneSignalReachability* reachability = [OneSignalReachability reachabilityForInternetConnection];
    NetworkStatus status = [reachability currentReachabilityStatus];
    if (status == ReachableViaWiFi)
        return @0;
    return @1;
}
````

**Comment by jkasten2** [comment]
@jamesstout Thanks for the suggestion and I agree this would be a nice to have. However I feel this is out of scope for this project to provide a public interface for even though it is already part of the library.

Apple does have an official library for this as well as a side note.
https://developer.apple.com/library/content/samplecode/Reachability/Introduction/Intro.html
