### ISSUE TITLE
UNUserNotificationCenterDelegate willPresent does't work with OneSignal

### ISSUE THREAD

**Issue by alexsanderkhitev** [OneSignal/OneSignal-iOS-SDK#214]
I'm using OneSignal to send Push Notification, I ran into the problem that on iOS 10 the method` func userNotificationCenter (_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)` does not work, and `UIAlertController` appears, Instead of the standard Banner. What do I need to do to make this method work on iOS 10 and to display the standard banner?

Alert looks like this now 
![img_0823](https://cloud.githubusercontent.com/assets/12511909/24283058/d6d457f0-107c-11e7-8fa0-d47a843b193d.PNG)

**Comment by jkasten2** [comment]
@alexsanderkhitev You can set [`kOSSettingsKeyInFocusDisplayOption`](https://documentation.onesignal.com/docs/ios-native-sdk#section--kossettingskeyinfocusdisplayoption-) to `Notification`. Pass this to the `settings` of [`initWithLaunchOptions`](https://documentation.onesignal.com/docs/ios-native-sdk#section--initwithlaunchoptions-) to always show an notificaiton / top screen banner.

You should still be able to use [`user​Notification​Center(_:​will​Present:​with​Completion​Handler:​)`](https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter) if you wish conditionally control how the notificaiton is displayed. Just make sure you set `kOSSettingsKeyInFocusDisplayOption` to `None` in this case so the OneSignal SDK does not not display its own alert alongside your setting.

If you still are seeing an issue please make sure you are using our latest 2.4.3 SDK and share your code in your `user​Notification​Center(_:​will​Present:​with​Completion​Handler:​)` method.

**Comment by alexsanderkhitev** [comment]
@jkasten2 thanks for quick response.

I set it this way, but so notifications do not come when the application is in foreground

```
    OneSignal.initWithLaunchOptions(launchOptions, appId: appID, handleNotificationAction: { (notificationResult) in

        }, settings: [kOSSettingsKeyInFocusDisplayOption : "Notification"])
```

**Comment by jkasten2** [comment]
@alexsanderkhitev It is a type so it should the following in Swift.
```Swift
OSNotificationDisplayType.notification.rawValue
```

**Comment by alexsanderkhitev** [comment]
@jkasten2 
thank you so much!
