### ISSUE TITLE
Cancel button title on the default in-app alert is not localizable

### ISSUE THREAD

**Issue by vzsg** [OneSignal/OneSignal-iOS-SDK#215]
As the title says, the string `"Close"` is hardcoded at [this line in OneSignal.m](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L1110) as the cancel button title.

It would be nice to be able to customize this (either by simply loading it with NSLocalizedString, or by any other mechanism) without having to rewrite this function in the embedding project.

**Comment by vzsg** [comment]
With 2.5.0 shuffling things around, the new location of the hardcoded string is [here in OneSignalAlertViewDelegate.m](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Source/OneSignalAlertViewDelegate.m#L52).

I can confirm that changing `@"Close"` to `NSLocalizedString(@"Close", @"")` fixes this.

**Comment by jkasten2** [comment]
@vzsg This is now part of the 2.5.4 Release
