### ISSUE TITLE
Since 2.4.0 Action buttons no longer appear

### ISSUE THREAD

**Issue by hawkeye64** [OneSignal/OneSignal-iOS-SDK#216]
Tested 2.35, 2.36, 2.3.7 all work as expected. 2.4.0, 2.4.1, 2.4.2 and 2.4.3 the Action button as described by the web interface doing the push do not work.

In the attached images, the ones with action button 'VIEW' are all working in 2.3.x version. The same code, in 2.4.x versions is not working (images with just "Close").
![img_1910](https://cloud.githubusercontent.com/assets/10262924/24518922/b1d4c476-1540-11e7-8ab9-4fb677a6406a.PNG)
![img_1907](https://cloud.githubusercontent.com/assets/10262924/24518932/bbc0fb4e-1540-11e7-8eeb-13a7519caa83.PNG)

**Comment by jkasten2** [comment]
@hawkeye64 Thanks for the report. This was only affecting the in-app alert display version. Normal notification shown when the app is out of focus are displayed ok.

Fixed in fcfa60bedee02b929dc378363f06b153a4b78456. This fix will be included in the 2.5.0 release.

**Comment by hawkeye64** [comment]
Thanks! Looking forward to it.
