### ISSUE TITLE
handleNotificationReceived behaviour inconcistency compared to Android's notificationReceived when app is in background

### ISSUE THREAD

**Issue by Talkless** [OneSignal/OneSignal-iOS-SDK#218]
Hi,

Imagine this scenario on Android:

- App moved to background.
- Two notifications received.
- User clicks one of them, so app is moved back to foreground.
- App receives  `notificationReceived`, `notificationReceived`, **and** `notificationOpened` events.

That's fine. App "knows" that there is still one notification left "unopened" - one of them was received and opened, so we don't care about that any longer.

Now, on iOS (iPhone 5 with iOS 10, OneSignal 2.4.3):
- App moved to background (same).
- Two notifications received (same).
- User clicks one of them, so app is moved back to foreground (same).
- App receives **only** `handleNotificationAction` event!

Both iOS and Android has foreground notifications are set to be silent using `OSNotificationDisplayTypeNone`/`OneSignal.OSInFocusDisplayOption.None`, so I can show my own widget for notifying/counting notifications in-app. But, since in iOS case I do not get `notificationReceived` when app raises from background, so it produces inconsistent behavior...

Is this iOS-specific behavior, or I have missed some detail and and doing something wrong?

**Comment by jkasten2** [comment]
@Talkless The `handleNotificationReceived` iOS block will only fire if your app is in focus at the time of receiving the notification. Or if you set `content_available` to `true` through the OneSignal REST API or dashboard it will also fire when receiving it even in the background. This matches your scenario above.

The Android behavior you noted above is actually the unexpected one. The `notificationReceived` should fire at the time the received instead of when a notification is opened / on resume. You repeated `notificationReceived` but I amuse you mean `onNotificationProcessing` on `NotificationExtenderService`?

Feel free to open a separate Android issue for this.

**Comment by Talkless** [comment]
>   Or if you set content_available to true through the OneSignal REST API or dashboard it will also fire when receiving it even in the background.

Thanks, I'll try that, or will just change design to always use native system notification handling when in foreground on all systems.

> The notificationReceived should fire at the time the received instead of when a notification is opened / on resume.

It's Qt specific I guess. I get "signal" only when app is (returned to) in foreground, because Qt by default stops event handling in it's separate GUI thread to avoid crashes when in background (as OpenGL context is unavailable).

>but I amuse you mean onNotificationProcessing on NotificationExtenderService?

No, [Androids NotificationReceivedHandler](https://documentation.onesignal.com/docs/android-native-sdk#section--notificationreceivedhandler-) has it's `notificationReceived` method called.

**Comment by Talkless** [comment]
>  You repeated notificationReceived

Oh I guess I misunderstood that comment.
I've repeated `notificationReceived` twice because there was actually two notifications received, and only one of them opened, invoking only one `notificationOpened`.

**Comment by jkasten2** [comment]
@Talkless I see, thanks for the clarification.

The received event was added with the intent of being able to update your app's UI when a notification is received while the app is in use. This is why the block passed to `handleNotificationReceived` doesn't fire after opening a notification. However if you do set `content_available` to `true` it does fire to mimic what how iOS's AppDelegate [`application:​did​Receive​Remote​Notification:​fetch​Completion​Handler:​`](https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623013-application?language=objc) method works for developer who need background support.

You noted to you needed silent notification support however if you need to do background work when a notification is about to be displayed I recommend setting up a Notification Service Extension. You can see how to setup one with our guide below.
https://documentation.onesignal.com/docs/ios-sdk-setup

This is recommend over `content-available` as it works even if your app has been force-quite from swiping it away.
See Apple's [UNNotification​Service​Extension](https://developer.apple.com/reference/usernotifications/unnotificationserviceextension) documentation for more details.

If you need me to look into the Android behavior you can create an issue on the that repo. I am switching my focus to that SDK this week.

**Comment by Talkless** [comment]
Thanks @jkasten2 , `content_available` works for me fine, no need for Notification Service Extension.
