### ISSUE TITLE
Type 'AppDelegate' does not conform to 'OSPermissionObserver'

### ISSUE THREAD

**Issue by HackShitUp** [OneSignal/OneSignal-iOS-SDK#221]
Added
```Swift
        OneSignal.add(self as OSPermissionObserver)
```

in `AppDelegte.swift` [like the documentation](https://documentation.onesignal.com/v3.0/docs/ios-native-sdk#section--getpermissionsubscriptionstate-) under "addPermissionObserver." Doesn't work.

**Comment by jkasten2** [comment]
@HackShitUp The error means you didn't add the following function to your `AppDelegate` class.
```Swift
func onOSPermissionChanged(_ stateChanges: OSPermissionStateChanges!) {
}
```
