### ISSUE TITLE
Notifications are not working on Safari

### ISSUE THREAD

**Issue by stockstatus** [OneSignal/OneSignal-iOS-SDK#223]
Hello,
please cloud someone give me a hint why notifications are not working on Safari? It's strange because i have 2 servers - TEST,PROD, but it's working only on TEST server. Those servers have same configurations and my code is also same. All id's - appId, safari_web_id are same. Thank you.

**Comment by jkasten2** [comment]
@stockstatus With OneSignal you need a different `safari_web_id` and OneSignal app for each domain. Note that Safari only has a production push certificate, no sandbox. Lastly Apple does not support Safari or any web push on iOS.

If you continue to have issues with Safari please contact OneSignal support while signed into the dashboard.

Thanks.
