### ISSUE TITLE
setting for notification 

### ISSUE THREAD

**Issue by adelbios** [OneSignal/OneSignal-iOS-SDK#225]
Hi I have chat application, now how I handle setting for every viewcontrollerl 
Example viewcontroller A notification style = alert 
viewController B notification style none ,,, how I can do this?

**Comment by jkasten2** [comment]
@adelbios You can call [`OneSignal.inFocusDisplayType`](https://documentation.onesignal.com/docs/ios-native-sdk#section--infocusdisplaytype-) with `None` or `InAppAlert` each time your app changes view controllers.

**Comment by jkasten2** [comment]
@adelbios Feel free to reopen this issue if my reply didn't solve your issue.

**Comment by adelbios** [comment]
thanks a lot  for help me ❤️❤️
