### ISSUE TITLE
China support

### ISSUE THREAD

**Issue by joeltay17** [OneSignal/OneSignal-iOS-SDK#227]
Hi Onesignal Devs,

Does iOS push notification works in China? It seems that builds that were deployed in China has reported that they do not receive push notifications.

**Comment by jkasten2** [comment]
@joeltay17 There shouldn't be an issue as both OneSignal and Apple aren't known to be blocked in China. Are the devices not being registered to OneSignal, registering as not subscribed, or just not reeving push notifications?

You can contact OneSignal support while logged in and we can check the above from our end. Please include player_ids and notification ids of the problem devices / messages if you have them. I also recommend checking our troubleshooting guide if you haven't done so already.
https://documentation.onesignal.com/docs/troubleshooting

**Comment by joeltay17** [comment]
Okay thanks, my bad on my part. Somehow they need to manually go to iOS settings and trigger the push notification to on. As of now I'm not sure whether the **Allow push notification** iOS dialog appeared at the start of the app, nevertheless they can receive it once they changed the option in iOS Settings.

Thanks again for the really swift response.

**Comment by sbmaggarwal** [comment]
With regards to Android. does this have any link to Google Play being banned in China? Will OneSignal work without Google Play support?

**Comment by jkasten2** [comment]
For Android, OneSignal relies on Google's GCM / FCM servers and Google Play services on the device for push notifications. I believe Google's servers are blocked in most of China.

Your Android app actually doesn't have to be on the Google Play store for FCM / GCM notifications to work.

**Comment by sbmaggarwal** [comment]
But this does mean that OneSignal won't work in China as Google Play services are not available on the devices sold there.

**Comment by jkasten2** [comment]
@sbmaggarwal Right, OneSignal for Android won't work for devices sold there as they don't come the with "Google Play services" app. Even it was on the device had it installed it won't work as in most of China network connections to Google are blocked.
