### ISSUE TITLE
Dylib unsafe error for NotificationServiceExtension using Carthage

### ISSUE THREAD

**Issue by inPhilly** [OneSignal/OneSignal-iOS-SDK#228]
: Linking against a dylib which is not safe for use in NotificationServiceExtension: .../Carthage/Build/iOS/OneSignal.framework/OneSignal

Can you please tell me why I am getting  this error and what I can do to avoid it? I could only find a single OneSignal.framework in my Carthage folder and I used it for both the app and the NotificationServiceExtension. I think this was probably wrong, but I can't find a separate 'safe' OneSignal.framework for NotificationServiceExtensions. Please advise. Thank you.

**Comment by jkasten2** [comment]
@mommyme We tested our notification service extension with Carthage and it fires without an issue. We will research if there is a way to clean up this warning.

**Comment by mommyme** [comment]
Have you found anything? I still have the warning.

**Comment by jkasten2** [comment]
@mommyme We haven't seen any side effects to this warning however you try turn on "Require Only App-Extension-Safe API" in the build settings in Xcode.

**Comment by hixfield** [comment]
I have the same issue, indeed the extension works as expected however if I research the issue on the web there seams to be a chance that the app will be rejected due to this... better get this fixed...

**Comment by creativeblends** [comment]
Same issue here. Does my app get rejected because of that? The "Require Only App-Extension-Safe API" of "OneSignalNotificationServiceExtension" is automatically set to YES. When I turn it to NO then the warning goes away. Anyone who solved this?

**Comment by jeffc-kpcc** [comment]
I can confirm that this is still happening (Xcode 8, Xcode 9) with a manual integration of OneSignal (not using Carthage), and has been for a few months now.

Like others, I'm a bit concerned about App Store rejection.

**Comment by inPhilly** [comment]
jkasten2 Can you change your settings and see that this error is present? It is not about making error 'go away'. There is a reason for the error - could be something like the possibility of the code trying to access the app delegate from an extension - Apple doesn't take these things very lightly, and they are ESPECIALLY cracking down on things in iOS 11. This is an AMAZING service and I am excited to use it, but this is actually a big deal, since we are required to create an app extension to use OneSignal. Can you please address this?

**Comment by inPhilly** [comment]
jkasten2 - this is still an issue - are you at all interested in getting it fixed?

**Comment by Coolncamp** [comment]
inPhilly  Yes please

**Comment by Nightsd01** [comment]
We have never seen an app get rejected because of this warning. I would suggest ignoring it for the time being as it doesn't cause any issues/rejections.
