### ISSUE TITLE
Crash deleteTags:

### ISSUE THREAD

**Issue by Krusheuski** [OneSignal/OneSignal-iOS-SDK#230]
In versions of sdk above 2.3, the application crashes when the **deleteTags:** method is called! Tags transmitted valid.

> [__NSCFBoolean isEqualToString:]: unrecognized selector sent to instance

**Comment by jkasten2** [comment]
@Krusheuski Thanks for the report. Could you attach the full stack trace?

**Comment by Krusheuski** [comment]
@jkasten2 
I delete 20+ tags. 
[stack.txt](https://github.com/OneSignal/OneSignal-iOS-SDK/files/959664/stack.txt)

**Comment by jkasten2** [comment]
@Krusheuski Thanks for the stack trace. It looks like your passing a bool instead of a string for one of your sendTag values. Can you correct this to only use strings as tags?

We will add type handling for this in a future SDK update.

**Comment by Krusheuski** [comment]
@jkasten2 
Excluded - only strings!
The same code works correctly with SDK 2.3

**Comment by jkasten2** [comment]
@Krusheuski Just fixed this issue in the commit above. It will be included in the next release.
