### ISSUE TITLE
Notification not delivered in react native ios 

### ISSUE THREAD

**Issue by csooraj** [OneSignal/OneSignal-iOS-SDK#232]
I have configured onesignal react native sdk for ios and I can see the devices listed on the dashboard but the notifications are not delivered, the delivery statistics shows invalid  and sometimes it shows unreachable.

I have installed onesignal plugin on wordpress site and whenever any post get updated, the notification is sent from there to the ios and android app. The notification is working fine in android.

I followed this https://medium.com/@xeo_it/how-to-debug-ios-push-notifications-33b0b209bdf3 to 
debug. I was able to receive the notification through the pusher app.

I tried sending messages directly from the dashboard, but still it shows invalid or unreachable.

How to debug this could you please help.

**Comment by jkasten2** [comment]
@csooraj The invalid status normally means Apple responded with a mismatch environment or a mismatch bundle id error. Could you message use from the small chat bubble in the bottom right when signed into the OneSignal dashboard? We can check the status of these and provide more details.

**Comment by csooraj** [comment]
@jkasten2  But I am using the same certificate for both  onesignal and  pusher app , if there was some issue with bundle id or environment I wont be able to get notification from pusher app.

**Comment by jkasten2** [comment]
@csooraj The "Unreachable" status means the the iOS device token (AKA push token) is no longer valid. This happens when the app is uninstalled. Apple will **always** give out a new device token in this case. Note that the OneSignal player / user id will also be different in most cases.

**Comment by csooraj** [comment]
@jkasten2  Is there any way to know whether notification send from from onesignal wordpress plugin has reached Apn ?

**Comment by jkasten2** [comment]
@csooraj You can check the notifications list on the dashboard and select REST API notifications from the drop down. This will show notifications sent from the Wordpress plugin however it is not split up per platform. OneSignal support can look into specific notifications if you contact them from the dashboard.
