### ISSUE TITLE
Setting kOSSettingsKeyInFocusDisplayOption

### ISSUE THREAD

**Issue by GKHerping** [OneSignal/OneSignal-iOS-SDK#233]
According to docs setting kOSSettingsKeyInFocusDisplayOption should be like:

`kOSSettingsKeyInFocusDisplayOption = OSNotificationDisplayType.notification or .none`

To set it, it is required to add .rawValue at the end. If not the app crashes

OneSignal (2.5.2)

**Comment by jkasten2** [comment]
@GKHerping `OneSignal.inFocusDisplayType` should be used instead in 2.5.0. This new property does not require `rawValue`.

We have removed `kOSSettingsKeyInFocusDisplayOption` from our documentation as this will be dercated in the future.
https://documentation.onesignal.com/docs/ios-native-sdk

Thanks.
