### ISSUE TITLE
Push notifications not delivered even though dashboard shows that they have been sent

### ISSUE THREAD

**Issue by mityakoval** [OneSignal/OneSignal-iOS-SDK#234]
Hello!

I am sending push notifications from Ruby on Rails app via OneSignal gem to a hybrid mobile app. In order to obtain `app_id` and `push_token` I fetch them from OneSignal every time the user hits the index page and update them in the db (Just in case these values change). 

The problems start when users do not use the app in some time. The notifications are never delivered to them, but the Dashboard shows that they were sent and delivered successfully. 

It should be noted that it happens to Ad-hoc distributed apps. Haven't reached the production stage yet.

Any suggestions?

**Comment by jkasten2** [comment]
@mityakoval Could you let us know what SDK version and iOS versions you are seeing this issue on? Are you also setting actions buttons or iOS 10 media attachments on your notifications?

I recommend contacting OneSignal support linking to this issue and so they can check your account to help debug the issue. Please attach OneSignal player ids and notification ids so they can look into it.

**Comment by mityakoval** [comment]
Thanks, @jkasten2 
OneSignal pod version - 2.3.5
iOS version 9+ (most likely 10)

Will contact OneSignal support as well.

**Comment by jkasten2** [comment]
@mityakoval Feel free to reopen this issue if you are still seeing this problem. Or reply with the final solution to help others who may find this thread.

Thanks.
