### ISSUE TITLE
Mark optional fields as Nullable

### ISSUE THREAD

**Issue by bmetitiri** [OneSignal/OneSignal-iOS-SDK#237]
The optional data parameters on push notifications, when accessed through Swift, are marked as implicitly unwrapped. For example, `additionalData` is one such parameter. This is misleading and makes it extremely easy to accidentally write crashing code. All fields that could reasonably be null should be marked as Nullable for maximum code safety. See Apple's [relevant blog article](https://developer.apple.com/swift/blog/?id=25).

**Comment by Nightsd01** [comment]
@bmetitiri We will be adding this in our next major release (3.0) and have been implementing new features using nullability specifiers. Thank you for opening this issue.
