### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by kamendo** [OneSignal/OneSignal-iOS-SDK#240]
<img width="1400" alt="screen shot 2017-05-22 at 15 53 25" src="https://cloud.githubusercontent.com/assets/6680528/26309787/09e31326-3f07-11e7-8007-87081bb09b8a.png">

I get this from time to time, what could it be?

**Comment by jkasten2** [comment]
@kamendo It could be a conflict with another plugin / library / SDK. Could you list all the ones you are using in your project? Please include the version of iOS you are testing on as well.

**Comment by DaveWoodCom** [comment]
I'm also seeing this crash in 2.5.4.

Crashes (randomly) on the following line in my app delegate:

```UNUserNotificationCenter.current().delegate = myDelegateObject```

Doesn't look like a conflict with another library though, I'm not using any others for push handling.
It looks like `UNUserNotificationCenter` has been swizzled to `OneSignalUNUserNotificationCenter` and the crash is happening when `setOneSignalUNDelegate` is called.

**Comment by vitalii-tym** [comment]
I have exactly this issue. Probably appeared either after switching to Xcode 9/Swift 4 or after clearing CocoaPods cache (this could result in OneSignal SDK version update). 
Happens every third app launch on simulator.
![screenshot 2017-10-06 12 27 26](https://user-images.githubusercontent.com/5410835/31272003-0dc52d48-aa92-11e7-8db1-428aacbbba6f.png)

**Comment by DaveWoodCom** [comment]
@vitalii-tym Have you upgraded to the new version they released today? Version 2.5.5?

**Comment by vitalii-tym** [comment]
Thanks for the info. I'm updated to the 2.5.5 now per your suggestion.
I've also found there was a deprecated OneSignal.idsAvailable in the project. Changed that to OneSignal.getPermissionSubscriptionState()
I will need some time to see if the crash is gone or not.

**Comment by jkasten2** [comment]
Closing this issue in favor of #278, to keep the discussion on one thread.

For completeness of linking, issue #274 was another duplicate thread.
