### ISSUE TITLE
Could not cast value of type 'AppDelegate' (0x101577418) to 'OSPermissionObserver' (0x101492628)

### ISSUE THREAD

**Issue by mukyasa** [OneSignal/OneSignal-iOS-SDK#242]
`OneSignal.add(self as! OSPermissionObserver)`

The app is crashing when  i am trying to add observer in Swift 3.

I checked the documentation but i am not able to set `OneSignal.add(self as OSPermissionObserver)` it is giving me error

**Comment by syedaamair** [comment]
for me also getting same error..please help me out

**Comment by mukyasa** [comment]
hello syedaamir add `OSPermissionObserver`

`class AppDelegate: UIResponder,OSPermissionObserver`

**Comment by syedaamair** [comment]
Thank you mukyasa
