### ISSUE TITLE
Release 2.5.4 does not compile on Xcode 7.3.1

### ISSUE THREAD

**Issue by adambolcsfoldi** [OneSignal/OneSignal-iOS-SDK#243]
The latest release `2.5.4` does not compile on Xcode 7 due to the `class` property not being supported by the compiler. 

```
OneSignal.h:292:12: Unknown property attribute 'class'
```

Is iOS 7 still meant to be supported?

Thanks!

**Comment by jkasten2** [comment]
@adambolcsfoldi As of the [2.4.0 Release](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.4.0) of this SDK you must use Xcode 8.

We currently support iOS 7, even with the latest 2.5.4 SDK, but might drop it once it's iOS market share is around 1%.

**Comment by adambolcsfoldi** [comment]
Alright, thanks! I should have seen it in the changelog, sorry.

Just FYI we've been using `2.4.1` with Xcode 7 for a while and it seems to be working.
