### ISSUE TITLE
Show both an Open and Close button when displaying an InAppAlert when launch URL is set

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-iOS-SDK#249]

**Comment by nfek** [comment]
Hi, can I get any help with this? I would like to have in app notification to show as a banner or as an app dialog alert with close or open button. But the banner notification is not working for me so I am looking for another alternative to display the alert dialog with open and close buttons.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
