### ISSUE TITLE
How to send schedule  notification

### ISSUE THREAD

**Issue by Sachinyadav6500** [OneSignal/OneSignal-iOS-SDK#250]

**Comment by jkasten2** [comment]
@Sachinyadav6500 A notification can be schedule from the OneSignal dashboard, through the OneSignal REST API, or with the [postNotification](https://documentation.onesignal.com/docs/ios-native-sdk#section--postnotification-). Could you provide more details on what you're looking for?

**Comment by Sachinyadav6500** [comment]
Thx I found what I m looking for
