### ISSUE TITLE
Notification not working in any browser on Mac

### ISSUE THREAD

**Issue by Kpaetschow23** [OneSignal/OneSignal-iOS-SDK#251]
I have all the cert files up and everything works great on PC but the second I use a Mac I get nothing. I've tried updating my laptop adding the p12 file and still nothing. No errors in the console, not sure where to go from here.

Thanks,
Kyle

**Comment by jkasten2** [comment]
@Kpaetschow23 This repo is for the iOS Native SDK and your question would be better answered on the Web SDK repo below.
https://github.com/OneSignal/OneSignal-Website-SDK/issues

However if you can message OneSignal support while signed in your account the dashboard they will be able to help you better by looking  at your account.

**Comment by jasonpang** [comment]
@Kpaetschow23 Please email us at support@onesignal.com with your website and OneSignal email login we'll take a look.
