### ISSUE TITLE
Issue with pod 2.5.4

### ISSUE THREAD

**Issue by Hsanka6** [OneSignal/OneSignal-iOS-SDK#253]
<img width="1241" alt="screen shot 2017-07-01 at 11 50 36 pm" src="https://user-images.githubusercontent.com/5545840/27767842-2ec10d84-5eb9-11e7-905f-29ca1723fe4d.png">
<img width="963" alt="screen shot 2017-07-01 at 11 55 25 pm" src="https://user-images.githubusercontent.com/5545840/27767843-3051f528-5eb9-11e7-88f5-49e0d9094290.png">

What is the latest stable release for OneSignal iOS sdk pods? Because these are the issues I ran across with the pods to use suggested in the documentation.

**Comment by jkasten2** [comment]
@Hsanka6 Your errors don't seem to related to OneSignal. Are you trying to call these methods from a OneSignal event from a notification app extension?

**Comment by jkasten2** [comment]
@Hsanka6 Feel free to reopen this issue if you have more details. Thanks.
