### ISSUE TITLE
OneSignal 2.5.4 crash

### ISSUE THREAD

**Issue by genadyo** [OneSignal/OneSignal-iOS-SDK#255]
Hi,

Any idea what is going here:
http://crashes.to/s/0f1bf3fa46a

Thanks!

**Comment by jkasten2** [comment]
@genadyo The crash is happening after a network call from `sendAsynchronousRequest:queue:completionHandler:` it possible that the device was having networking issues at the time.

Are you able to reproduce an issue on your test devices?

**Comment by genadyo** [comment]
I have no idea, it's one random user.

**Comment by jkasten2** [comment]
@genadyo Seems to be a one off crash as we haven't see any other reports of this. Feel free to reopen if you see this again or have more details.

Thanks.
