### ISSUE TITLE
Type 'OneSignal' has no member 'initWithLaunchOptions'

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [OneSignal/OneSignal-iOS-SDK#258]
Getting error in AppDelegate

![screen shot 2017-08-01 at 2 59 37 pm](https://user-images.githubusercontent.com/21377276/28818893-1bd05382-76ca-11e7-932d-cea1d4d7e9ae.png)

Please help

**Comment by jkasten2** [comment]
@vaibhav-varshaaweblabs Make sure you have `import OneSignal` at the top of your `.swift` file. Also make sure you are not redefining `OneSignal` any where in your code.

**Comment by vaibhav-varshaaweblabs** [comment]
@jkasten2  I have already added the import line. Also, there is no duplication/repetition of the code

**Comment by ADevelopStudio** [comment]
@vaibhav-varshaaweblabs how did you solve it?

**Comment by vaibhav-varshaaweblabs** [comment]
@ADevelopStudio It was a mistake of mine. I had created a helper class of the same name.
