### ISSUE TITLE
Updating badge number with postNotification

### ISSUE THREAD

**Issue by TeamFactory** [OneSignal/OneSignal-iOS-SDK#261]
I'm having trouble figuring out how to update the icon badge number of the receiving device. 
At the one hand I'm sending the notification with this function: 

`func sendMessageToDevices(to oneSignalIds: [String], with text: String) {
        
        OneSignal.postNotification(["contents": ["en": text], "include_player_ids": oneSignalIds])
        
    }`

And in the AppDelegate in the didReceiveRemoteNotification() function I'm calling

`        application.applicationIconBadgeNumber += 1
`

When I send messages through the dashboard, I have the possibility to specify even the amount of the badge number. Do you know how this works?

Thanks for every answer!

**Comment by jkasten2** [comment]
@TeamFactory See the Badge guide below.
https://documentation.onesignal.com/docs/appearance

Note, if you set `applicationIconBadgeNumber` in your app code however you won't be able to use the `Increase` option as the value won't be insync.

**Comment by TeamFactory** [comment]
@jkasten2 Sorry, but I can't find any information on how to change the icon badge number in this guide... That's sure, I removed this line but it doesn't work either. What do I exactly have to change so that the icon badge count is increased with every notification?

**Comment by jamesstout** [comment]
You add fields:

ios_badgeType = “SetTo”
ios_badgeCount = 1

or, to increase with every notification:

ios_badgeType = “ Increase”
ios_badgeCount = 1

**Comment by TeamFactory** [comment]
Ok all right! Thank you! @jamesstout @jkasten2
