### ISSUE TITLE
Get Firebase Token From OneSignal?

### ISSUE THREAD

**Issue by farshadjahanmanesh** [OneSignal/OneSignal-iOS-SDK#264]
hi thanks for everything
is there any way to get firebase token from onesignal? can i send notification from firebase Console?
can i see analytics from firebase console?

**Comment by jkasten2** [comment]
@farshadjahanmanesh OneSignal does not rely on Firebase for iOS push notifications, APNs is used directly. To get the APNs token or the OneSignal player / user Id from the SDK you can use [getPermissionSubscriptionState](https://documentation.onesignal.com/docs/ios-native-sdk#section--getpermissionsubscriptionstate-) or  [addSubscriptionObserver](https://documentation.onesignal.com/docs/ios-native-sdk#section--addsubscriptionobserver-).
