### ISSUE TITLE
postNotification function - how to add a subtitle?

### ISSUE THREAD

**Issue by TeamFactory** [OneSignal/OneSignal-iOS-SDK#266]
Hey!

My question is how to add a subtitle to my one signal notification that I send with the following line:

`        OneSignal.postNotification(["contents": ["en": text], "include_player_ids": oneSignalIds, "ios_badgeType":"Increase", "ios_badgeCount":1])`

Is there maybe some kind of overview or documentation on which keys I can use in the dictionary? Thank you!

**Comment by jkasten2** [comment]
@TeamFactory You can set `subtitle` as part of the notification payload. This is noted on the OneSignal documentation page for the create notification REST API call under the [Content & Language](https://documentation.onesignal.com/v3.0/reference#section-content-language) section. It is the same format as `contents`.
