### ISSUE TITLE
ld: warning: linking against a dylib which is not safe for use in application extensions: ../Carthage/Build/iOS/OneSignal.framework/OneSignal

### ISSUE THREAD

**Issue by TofPlay** [OneSignal/OneSignal-iOS-SDK#272]
Hi,
With Xcode 9 Beta 6 I have this warning for the notification service extension:
`ld: warning: linking against a dylib which is not safe for use in application extensions: ../Carthage/Build/iOS/OneSignal.framework/OneSignal`
It's like Apple doesn't like the `import OneSignal` under the notification service extension.

My Cartfile:
```
github "OneSignal/OneSignal-iOS-SDK" == 2.5.4
```

**Comment by jkasten2** [comment]
@TofPlay There is an open issue for this Carthage warning on issue #228. It isn't related to Xcode 9, happens on Xcode 8 as well.
