### ISSUE TITLE
Disable code coverage

### ISSUE THREAD

**Issue by TofPlay** [OneSignal/OneSignal-iOS-SDK#273]
Code coverage has to be disabled for Carthage to work with Xcode 9.

Check Carthage/Carthage#2056 and Carthage/Carthage#2057.

**Comment by jkasten2** [comment]
@TofPlay We doesn't include the `enableCodeCoverage` so OneSignal shouldn't be trigger this.

I tested our SDK on a new Xcode 9 project and it passed the validations Under Xcode's Archives > Validate menu without an issue.

If you are still seeing an issue can you verify you followed step 10 an beyond correctly?
https://documentation.onesignal.com/docs/carthage-setup

**Comment by TofPlay** [comment]
@jkasten2 you doesn't include enable coverage but by default is set to `Yes`. As you can see on Xcode you must set to `No`
![image](https://user-images.githubusercontent.com/1082222/30906078-0004c848-a377-11e7-87dc-3ca3eaf7701f.png)

**Comment by jkasten2** [comment]
@TofPlay Thanks for the details. Just added disable the setting in commit d81d70f5721bd995f30dae88c5971df98efc5a7f
