### ISSUE TITLE
Project is not Carthage compatible

### ISSUE THREAD

**Issue by dirkoswanepoel** [OneSignal/OneSignal-iOS-SDK#28]
Making the project Carthage compatible requires a few minor changes. 

[https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework)

**Comment by TofPlay** [comment]
Hi,
For iOS and OS X projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods] (http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/)

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-4BC51D.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by justjoeyuk** [comment]
Please do allow Carthage compatibility. We don't all want to be controlled by Cocoapods.

**Comment by jkasten2** [comment]
@justjoeyuk We now have support for Carthage in our [OneSignal 2.0 Beta SDK](https://documentation.onesignal.com/docs/ios-10-beta). It only works with Xcode 8 Beta as it also includes support for iOS 10. Let us know if you have any feedback on it.

Thanks.

**Comment by justjoeyuk** [comment]
@jkasten2 Thanks a lot, great work peeps!

**Comment by JKalash** [comment]
@justjoeyuk Thought of letting you know that our main sdk (2.0 beta version) is available through carthage and is compatible with non-beta Xcode (7.3 and prior), as long as the iOS deployment target >= 8.0 for dynamic frameworks. Refer to: [iOS SDK Installation: Carthage](https://documentation.onesignal.com/docs/installing-the-onesignal-ios-sdk#or-import-the-framework-into-your-xcode-project-wi)

Thanks!
