### ISSUE TITLE
Pod error 'shared' is unavailable. use viewcontroller based solutions 

### ISSUE THREAD

**Issue by fnrbh** [OneSignal/OneSignal-iOS-SDK#288]
Hello,
I followed the instructions on IOS sdk setup page. After 'pod install', i cleaned and built my project and got "'shared' is unavailable: Use view controller based solutions where appropriate instead" errors on my other pods.

When i remove onesignal from podfile and install, the errors disappear.
Anybody has seen this error? 
thanks...

**Comment by jkasten2** [comment]
@fnrbh Is this the full exact error?
Could you attach your `Podfile` contains so we can look into reproducing the issue?

**Comment by fnrbh** [comment]
@jkasten2 thank you for your response.

The error is : 'shared' is unavailable: use view controller based solutions where appropriate instead. TwitterPagerTabStripSettings.swift

My podfile is as follows:

 platform :ios, '9.0'

target 'mopa' do
  use_frameworks!

  # Pods for mopa
	pod 'Alamofire', '~> 4.4'
	pod 'FSPagerView'
	pod 'SDWebImage'
	pod 'SwiftKeychainWrapper'
	pod 'CHIPageControl', '~> 0.1.3'
	pod 'XLPagerTabStrip', :git => 'https://github.com/xmartlabs/XLPagerTabStrip.git'
	pod 'ActiveLabel'
	pod "Koloda"
	pod 'RxSwift',    '~> 3.0'
	pod 'RxCocoa',    '~> 3.0'
	pod 'RxDataSources', '~> 1.0'
	pod 'RxAlamofire'
	pod 'RSKImageCropper'
	pod 'OneSignal', '>= 2.5.2', '< 3.0'


  target 'mopaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneSignalNotificationServiceExtension' do
  	pod 'OneSignal', '>= 2.5.2', '< 3.0'
  end	

end

**Comment by ahbou** [comment]
I have the same error when pods aren't extension compliant.
So far found 2 Siesta/UI and Quantcast

**Comment by fnrbh** [comment]
I solved the problems of other pods. I didn't use "shared" directly but used different ways to achieve the same result.

**Comment by vanessaguapo** [comment]
i don't think this should have been closed. thats not a really solution, just a workaround. Anytime you update your pods, all your changes would be lost, otherwise one has to manually import all of the non compliant pods to the project itself.

**Comment by zachwhelchel** [comment]
Also seeing this error. Surely OneSignal doesn't expect all of your other pods to be extension compliant in order to use it?

**Comment by vanessaguapo** [comment]
I solved it the other way around and imported the OneSignal framework locally to the project.  Since i have several pods that were not extension compliant, it was easier this way. But if there's an update i'll have to do it manually, so it's not a great solution, just a quick fix.

**Comment by black-lotus** [comment]
I am facing same issue.. 
has anybody solve this by cocoapods ?

**Comment by Komal2905** [comment]
I had same problem . So setting **require only app-extension-safe api** to **No** to other pod setting helped

**Comment by RishiRaj27** [comment]
Any one got the solution?

**Comment by Nightsd01** [comment]
Hi, we are planning to fix this - there is already an open issue for the app-extension-unsafe code (#396) and we will be addressing it by making our extension-specific code its own subspec framework.

In the mean time, setting the `require only app-extension safe api` in your Notification Service Extension's build settings should temporarily allow you to build.

**Comment by RishiRaj27** [comment]
Hi @Nightsd01 ! 
Thanks for your response. But the require only app-extension safe api in Notification Service Extension's build settings couldn't help me to resolve the error. Can you suggest me any thing else.

**Comment by vanessaguapo** [comment]
Hi @RishiRaj27 , i could't solve it that way either. As i said above I ended up importing the onesignal pod content to my project and using it inside instead of using a pod.  Not an ideal solution, but it did the job.

**Comment by Nightsd01** [comment]
@RishiRaj27 can you post your Podfile?

**Comment by RishiRaj27** [comment]
@Nightsd01 

# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'POD' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for POD
pod 'TPKeyboardAvoidingSwift'
pod 'JKCalendar'
pod 'NVActivityIndicatorView'
pod 'DeviceKit'
pod 'ObjectMapper', '~> 3.1'
pod 'Alamofire', '~> 4.7'
pod 'Kingfisher', '~> 4.0'
pod 'AlamofireObjectMapper', '~> 5.0'
pod 'PKHUD', '~> 5.0'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod 'ImagePicker'
pod 'CountryPickerView'
pod 'Socket.IO-Client-Swift'
pod 'TweeTextField'
pod 'RealmSwift'
pod 'SwipeCellKit'
pod 'Fabric'
pod 'Crashlytics'


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '4.1'
            
        end
    end
end
end

**Comment by RishiRaj27** [comment]
Thanks @Nightsd01 and @vanessaguapo !
I have followed these steps and got the solution.
1. Download or clone thi repo.
2. Drop and drag iOS_SDK/OneSignalSDK/Framework/OneSignal.framework into your Xcode project.  Make sure to check the copy option.
3. Add SystemConfiguration, UIKit, and UserNotifications to your framework list.
4. You can then follow our full setup guide for the code setup.
5. If you need the features provided by the Notification Service Extension you will need to repeat steps 2 and 3 above for this target.

**Comment by Nightsd01** [comment]
@RishiRaj27 we have been working on a 3.0 release that will resolve this issue entirely. In the mean time manually including the framework should also resolve the problem

**Comment by rozeridilar** [comment]
I am having the same problem here

**Comment by ZakSingh** [comment]
Any update here? Running into the same issue and none of the provided fixes resolve the issue.

**Comment by dharmeshec5** [comment]
> Any update here? Running into the same issue and none of the provided fixes resolve the issue.

Go to your App's target -> Build Setting -> Require Only AppExtension-Safe API -> set to NO
Error will disappear. It's worked for me. Good Luck!

<img width="565" alt="Screenshot 2019-04-07 at 5 35 57 PM" src="https://user-images.githubusercontent.com/20013779/55683283-a3696480-595b-11e9-9534-eea96d183f37.png">

**Comment by lukebrandonfarrell** [comment]
Hey All,

Flagging "Require Only App-Extension-Safe API" did not work for me. I solved this by putting the following code at the bottom of my Pods file:

```
...

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
     end
  end
end
```

Also, making sure my OneSignalNotificationServiceExtension target is a child of my app target:

```
target 'MyAwesomeApp' do
  ...


  target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '>= 2.9.3', '< 3.0'
  end
end
```

People still facing this issue? @ZakSingh @RishiRaj27 @vanessaguapo

**Comment by SogoGolf** [comment]
had this problem today too what a royal pain. thanks @lukebrandonfarrell that script saved having to manually update a bunch of pod files Build Settings.

**Comment by hugoh59** [comment]
None of these solutions works for me. The issue for me comes from React-Core.

**Comment by abhishek-gangwar** [comment]
Still facing the same issue with the Onesignal version (2.11.2). Using Xcode 11 and swift.

**Comment by wilz05** [comment]
@abhishek-gangwar  I too had similar issue spent 2 days to figure it out...ended by adding 
use_frameworks! outside 

for example 

`platform :ios, '10.0'
use_frameworks!
target 'mopa' do

        pod 'Alamofire', '~> 4.4'
	pod 'FSPagerView'
	pod 'SDWebImage'
        pod 'OneSignal'
# other pods
  target 'mopaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneSignalNotificationServiceExtension' do
  	pod 'OneSignal'
  end	

end`

this should work, do not forget to update OneSignal SDK, it has the latest iOS13.2 notification bug fix

**Comment by danial096** [comment]
any better solution yet?

**Comment by Samuelford24** [comment]
@danial096 I had the same problem and solved it by removing additional pods that dealt with notifications. For example, I had OneSignal, Firebase Messaging, and Firebase InAppMessaging all in my podfile. I removed the 2 Firebase pods and then my project worked.

**Comment by danial096** [comment]
@Samuelford24 i dont have other pod that handle notification. The problem appear after I install onesignal pod to my notification extension. for now i just set 
APPLICATION_EXTENSION_API_ONLY = NO. Hope can find a better solution soon

**Comment by lawgimenez** [comment]
It's 2020 and I just got this error today after setting up using Swift. The script worked.

**Comment by houmie** [comment]
@lawgimenez I have the same issue. Which script worked for you?

**Comment by lawgimenez** [comment]
@houmie the one below sir, with the most upvotes


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
     end
  end
end

**Comment by houmie** [comment]
@lawgimenez Thank you. I missed that somehow. That worked for me too.

**Comment by GleidsonDaniel** [comment]
> Hey All,
> 
> Flagging "Require Only App-Extension-Safe API" did not work for me. I solved this by putting the following code at the bottom of my Pods file:
> 
> ```
> ...
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
>      end
>   end
> end
> ```
> 
> Also, making sure my OneSignalNotificationServiceExtension target is a child of my app target:
> 
> ```
> target 'MyAwesomeApp' do
>   ...
> 
> 
>   target 'OneSignalNotificationServiceExtension' do
>     pod 'OneSignal', '>= 2.9.3', '< 3.0'
>   end
> end
> ```
> 
> People still facing this issue? @ZakSingh @RishiRaj27 @vanessaguapo

Finally something that worked!!!
Thank you very much!

**Comment by gaganyadav80** [comment]
For anyone facing the issue and no provided solutions worked then try this.

1. Put your `OneSignalNotificationServiceExtension` target **outside** of my app target. (Yes, outside).
2. If your my app target has `use_framework` then also add that in your `OneSignalNotificationServiceExtension` target.
```Podfile
target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
end
```
3. Now `flutter clean && flutter pub get` and then `cd ios && pod install && cd ..`
4. If you get **_circular dependency_** error then you need to move the "Embed Foundation Extensions" build phase to run before the CocoaPods and FlutterFire scripts. Here's what you need to do:
5. Open your `Runner.xcworkspace` in Xcode
6. **Select the Runner target** in the project navigator
7. **Go to Build Phases tab**
8. **Drag the "Embed Foundation Extensions" phase** to be positioned right after **"Embed Frameworks"** (step 7 in the list above) and before **"Thin Binary"**

Finally,
```bash
cd /Users/gagan/Developer/thirty_sundays_mobile
flutter clean
cd ios
rm -rf Pods Podfile.lock
pod install
cd ..
flutter run
```
