### ISSUE TITLE
Eror compile with OneSignal 2.5.6 with bitcode enabled

### ISSUE THREAD

**Issue by YurchukV** [OneSignal/OneSignal-iOS-SDK#289]
When you try to compile a project, an error occurs
"could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer:' 900.0.37.0_0 'Reader:' 802.0.42_0 ')', using libLTO version 'LLVM version 8.1.0, (clang-802.0.42) 'for architecture arm64 " using xcode 8.3.3 OneSignal 2.5.6

**Comment by jkasten2** [comment]
@YurchukV This is due to the OneSignal SDK being compiled with Xcode 9.  We will compile with Xcode 8 in the next version yet to keep compatibility yet.

**Comment by bauloc** [comment]
same here

**Comment by jkasten2** [comment]
@YurchukV @bauloc This is now fixed in release 2.5.7.
https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.5.7
