### ISSUE TITLE
error: using bridging headers with framework targets is unsupported

### ISSUE THREAD

**Issue by TofPlay** [OneSignal/OneSignal-iOS-SDK#29]
Hi
I try to use OneSignal under a Swift Framework and I can not 😭
Can you change your pod that we can use your SDK as a true Swift module where we don't need to use a bridge file. 😢
Or better you can change your SDK to be compatible with Carthage 😉

**Comment by TofPlay** [comment]
May be you should take a look at this article:
[Wrapping a C Library in a Swift Framework](http://colindrake.me/2015/10/05/wrapping-a-c-library-in-a-swift-framework/)

If you define a module map we can see your framework as a swift Module

**Comment by jkasten2** [comment]
Thanks for the suggestions, we haven't added Carthage support yet as we need to still support iOS 7. We will be looking to how to support both before moving forward.

**Comment by TofPlay** [comment]
If I check on [iOS Version stats](https://david-smith.org/iosversionstats/) iOS 7 is just 5.6% of the device!
 I'm 99% sure they will never move to iOS 8 or above until theirs devices break. 😋

**Comment by jkasten2** [comment]
@TofPlay 5% is high enough where many of our developers will want to continue to support these users. Once it is around 1% to 2% we can consider dropping support.

This repo is used in our Unity, Corona (Ionic, Intel XDK, PGB), Cordova, react native, Xamarin, and Marmalade SDKs as well so we need to consider compatibility with these platforms as well.

My plan is to use the same code but have 2 different Xcode projects pointing to the same code. However I still have to research the best options to do this.

**Comment by TofPlay** [comment]
> My plan is to use the same code but have 2 different Xcode projects pointing to the same code. However I still have to research the best options to do this.

Just create one projet with 2 Targets. The first set to iOS 7 and the other to iOS 8 or above. Same sources but different setting. 
May this article will help too: [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods](http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/)

**Comment by jkasten2** [comment]
@TofPlay Thanks for the suggestions, I'll try that out after I release 2.4.0 our Android SDK next week.

**Comment by jkasten2** [comment]
@TofPlay You can try out our Beta SDK with iOS 10 support which is written is Swift as has Carthage support.
https://documentation.onesignal.com/docs/ios-10-beta

**Comment by TofPlay** [comment]
It's on my todo list 😉
But I can not take care of it right away. I'm already full busy to maintain projects on Swift 2 and prepare for migration on Swift 3 for other projects. 
But I'm glad OneSignal supports Swift 3 and Carthage 👍 😍
It will help me a lot 😋

**Comment by TofPlay** [comment]
Hi @jkasten2 I just tested your version and I have some errors. See ticket #62.

**Comment by JKalash** [comment]
Couple modifications:
1- There's now a module.modulemap file in the OneSignal.framework that gets imported either manually or from CocoaPods / Carthage. Make sure not to use any branch besides the master (no "swift" etc.
2- Drop the iOS 10 beta branch as iOS 10 beta support was added to the B version of the main Framework.

Yay! :)

**Comment by TofPlay** [comment]
@JKalash I have an issue on Xcode 7.3.1 Swift 2.2 project (see ticket #73)

**Comment by asad175** [comment]
I have solved it in this way, Detailed steps are here, [Solution to Xcode Error: using bridging headers with module interfaces is unsupported](https://handyopinion.com/xcode-error-using-bridging-headers-with-module-interfaces-is-unsupported/)

Solution:

In your Project Level & Target level Build Settings tab, open the Build Options menu. And then set Build Libraries for Distribution option to No.
