### ISSUE TITLE
NSURLConnection is deprecated, should switch to NSURLSession

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-iOS-SDK#292]
The following methods on `NSURLConnection` are deprecated
* [`+ sendAsynchronousRequest:queue:completionHandler:`](https://developer.apple.com/documentation/foundation/nsurlconnection/1418125-sendasynchronousrequest?language=objc)
* [`+ sendSynchronousRequest:returningResponse:error:`](https://developer.apple.com/documentation/foundation/nsurlconnection/1411393-sendsynchronousrequest?language=objc)

Calls should be switched to use `NSURLSession` instead.

**Comment by jamesstout** [comment]
Also:

- <code>[+ connectionWithRequest:delegate:](https://developer.apple.com/documentation/foundation/nsurlconnection/1569746-connectionwithrequest?language=objc)</code>

**Comment by Nightsd01** [comment]
Thank you for bringing this up. Fixed (#319 )
