### ISSUE TITLE
Hard Crash on Launch

### ISSUE THREAD

**Issue by Infinity-James** [OneSignal/OneSignal-iOS-SDK#293]
<img width="492" alt="onesignalcrash" src="https://user-images.githubusercontent.com/2278922/32069280-90324a06-ba80-11e7-9e12-8d64fd60583a.png">

My configuration on app launch:

```
let identifier = Bundle.main.infoDictionary!["OneSignalID"] as! String
let settings: [String: Any] = [kOSSettingsKeyInFocusDisplayOption: OSNotificationDisplayType.none.rawValue, kOSSettingsKeyAutoPrompt: false ]
OneSignal.initWithLaunchOptions(options, appId: identifier, handleNotificationReceived: notificationReceived, handleNotificationAction: notificationAction, settings: settings)
```

**Comment by michalinas** [comment]
this pr: https://github.com/OneSignal/OneSignal-iOS-SDK/pull/259 might be a solution to your crash

**Comment by Infinity-James** [comment]
That would be a relief. This issue happens randomly and actually resulted
in my app being rejected. I made no changes, updated the version, and
resubmitted - it passed. Needless to say, this was a pain in the arse.

Absolutely unacceptable.

**Comment by jkasten2** [comment]
@michalinas I haven't been able to reproduce this crash. Can you confirm if the pr #259 fixes it for you?

Issue #278 is the same crash as this issue. Can you try the debugging suggestions in the https://github.com/OneSignal/OneSignal-iOS-SDK/issues/278#issuecomment-340644810 and reply with the results on that issue?

**Comment by Alexookah** [comment]
i am experiencing the exact same issue... sometimes i get 2 times in a row crash due to this.
