### ISSUE TITLE
Disable, enable notifications programmatically

### ISSUE THREAD

**Issue by fnrbh** [OneSignal/OneSignal-iOS-SDK#296]
Hi,
Is there a way to disable and enable notifications programmatically using onesignal api?
thanks in advance...

**Comment by jkasten2** [comment]
@fnrbh You can call [setSubscription](https://documentation.onesignal.com/docs/ios-native-sdk#section--setsubscription-) with `false` to turn off OneSignal push notifications.

**Comment by fnrbh** [comment]
Thank you very much @jkasten2 , it worked. But the notification setting on iphone's settings do not change with this call.

**Comment by jkasten2** [comment]
@fnrbh It is not possible to disable the notification permission in the iOS settings programmatically. iOS limits this as it is designed to only be changed by the user.
