### ISSUE TITLE
Link Error on archive project

### ISSUE THREAD

**Issue by starsoheil2007** [OneSignal/OneSignal-iOS-SDK#299]
Hi 
I add OneSignal "OneSignalNotificationServiceExtension" in my project and working by building in my phone and simulator successfully but when i have want archive project for release in AppStore i get this error :

`OneSignalNotificationServiceExtension <br>
     Apple Mach-O Linker (ld) Error <br>
    error: linker command failed with exit code 1 (use -v to see invocation)
` 

Please help me. Tnx

**Comment by starsoheil2007** [comment]
Any one can't help me , I should release this app today !!!

**Comment by jkasten2** [comment]
@starsoheil2007 There should be more details of the error in Xcode. Can you add the full log above `failed with exit code 1`?

**Comment by starsoheil2007** [comment]
Hi , I use XCode 8.3.3 and my log error is "different bit code" . I set "Enable BitCode" to No in project & target then my project archived successfully but my notification not arrived to phone after install my app from TestFlight .

**Comment by jkasten2** [comment]
@starsoheil2007 I recommend fully uninstalling the development version of your app on your device before installing your TestFlight version. I recommend deleting your test device on the OneSignal dashboard to confirm it is resubscribing as a new device.

Make sure you have a production .p12 push certificate uploaded to the OneSignal dashboard, sandbox certificates do not work for TestFlight. If notifications are showing as successful then you have this correct.

For the bitcode issue you can follow this issue for update on support with XCode 8 for it.
https://github.com/OneSignal/OneSignal-iOS-SDK/issues/289

**Comment by jkasten2** [comment]
@starsoheil2007 We fix the bitcode compatibility issue with 2.5.7 of our SDK. If you are still using Xcode 8 updating to this version will fix the different bit code" issue you are seeing. Thanks.
