### ISSUE TITLE
In-app Webview opened via launchURL not refreshed upon device orientation change - content doesn't fit viewport

### ISSUE THREAD

**Issue by robertturrall** [OneSignal/OneSignal-iOS-SDK#306]
I was very happy to see that simply sending a launchURL will cause an in-app Webview to open up in a modal (iOS SDK). Unfortunately, turning the device from portrait to landscape leaves the viewport window width at the original portrait width and doesn't cause the content to resize as would be expected.

The HTML page being loaded has <meta name="viewport" content="width=device-width"> so all should work fine. I have no programmatic access to the Webview so cannot trigger a reload.

Can the Webview be reloaded on device orientation change or should this work as it is?

**Comment by Nightsd01** [comment]
Thank you for reporting this, fixed in #317

**Comment by bekirtaskin** [comment]
is there a way to disable reloading on orientation change?
