### ISSUE TITLE
Possible issue - "Provisioning Profile Missing Push" status when background modes are disabled

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-iOS-SDK#308]
The device can sometimes be reported as (Provisioning Profile Missing Push Permission)" on the first start of the app when "background modes" are disabled in Xcode. It might be related to when the user accepts the notification permission but the SDK isn't waiting for an attempt to get the APNs pushToken to return. The case where this was found on the device it did not have an `identifier` set but had `notification_types` set to `15`. The next time the app was opened a pushToken was set correctly.

**Comment by Nightsd01** [comment]
I've never been able to reproduce this issue - I think it must be quite rare. Closing - if anyone else ever encounters this problem please feel free to reply

**Comment by bjustice-sympatient** [comment]
I just had the case where my first app start, permissions prompt accepted, resulted in "Provisioning Profile Missing Push".
I double checked our entitlements and capabilities in our provisioning profile and Xcode says everythings all right. Found this Post, simply restarted the App and now my Test device is properly subscribed.
iPhone SE @ iOS 12.1.2
OneSignal Unity-SDK 2.7.7 for iOS (I'm assuming it uses the OneSignal iOS SDK)

**Comment by PreludeAndFugue** [comment]
Same steps as ghost account on 8 Jan 2019.

iPhone XR iOS 16.0
OneSignalXCFramewokr 3.11.2

**Comment by HyenaJeremyLin** [comment]
Same problem also encountered, have any idea?

13 pro  iOS 16.5
OneSignal 2.9.1
