### ISSUE TITLE
Blank Modal View in app when opening app from OneSignal Notification where App Store Launch URL is set

### ISSUE THREAD

**Issue by inPhilly** [OneSignal/OneSignal-iOS-SDK#313]
When Launch URL is set in the push notification, the app opens, presents a blank modal view with a 'Done' button in the nav, then launches the url in the App Store. When the user comes back to the app from the App Store, they are faced with a blank view and its done button. This is terrible for user experience, in my opinion. Are there any plans to change this, or is there a way I can keep this from happening?

**Comment by Nightsd01** [comment]
Thanks for reporting this @inPhilly, fixed in #317
