### ISSUE TITLE
Unable to disable notification permission auto prompt on iOS 9

### ISSUE THREAD

**Issue by rohitpal440** [OneSignal/OneSignal-iOS-SDK#316]
On iOS9, OneSignal ask notification permission from user even if `kOSSettingsKeyAutoPrompt` is set to `false` in `settings` dictionary of `initWithLaunchOptions`.

**Comment by Nightsd01** [comment]
Hi @rohitpal440 

Can you post your OneSignal initialization code from your AppDelegate? 

Also, can you search your codebase for usage of the `requestAuthorizationWithOptions:completionHandler:` method? Could a different framework or part of your application be calling this method? 

Lastly, are you saying this issue is specific to iOS 9 and you've tested it on other versions of iOS?

**Comment by rohitpal440** [comment]
Hi @Nightsd01 ,
We are not using/calling `requestAuthorizationWithOptions:completionHandler:` method upfront.
I'm facing this issue only on iOS9 devices.

Here is the code in AppDelegate's `didFinishLaunchingWithOptions` method

```
// Onesignal: Initialise with kOSSettingsKeyInAppAlerts = false
// and disable auto prompt
  
let dict: [AnyHashable: Any] = [kOSSettingsKeyAutoPrompt: false, kOSSettingsKeyInAppAlerts: false]
  
OneSignal.initWithLaunchOptions(launchOptions, appId: PractoConstants.Keys.kOneSignalAPIKeyTest, handleNotificationReceived: nil, handleNotificationAction: nil, settings: dict )
```

**Comment by Nightsd01** [comment]
@rohitpal440 My mistake, in iOS 9 it's actually an older call with UIUserNotificationSettings. 

Currently in the OneSignal SDK there is no way that UIApplication.shared.registerUserNotificationSettings().. would get called unless you specifically set **kOSSettingsKeyAutoPrompt** to true during initialization, or call `OneSignal.promptForPushNotificationsWithUserResponse()..`

I would check your own code and your dependencies to see if the `registerUserNotificationSettings` function is getting called somewhere.

**Comment by rohitpal440** [comment]
@Nightsd01 you were right one of our dependency was calling `registerUserNotificationSettings` method.
Thanks for the help.
