### ISSUE TITLE
Can't get player id

### ISSUE THREAD

**Issue by black-lotus** [OneSignal/OneSignal-iOS-SDK#328]
I got an error like this when trying to get player id

`ERROR: Error registering with OneSignal: Error Domain=OneSignalError Code=0 "(null)" UserInfo={error=Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9802, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x1c46404e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://onesignal.com/api/v1/players, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamPropertySSLClientCertificateState=0, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., _kCFStreamErrorDomainKey=3, NSErrorFailingURLKey=https://onesignal.com/api/v1/players, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://onesignal.com/api/v1/players, NSErrorFailingURLStringKey=https://onesignal.com/api/v1/players, _kCFStreamErrorDomainKey=3}}`

i had update Info.plist to be like this, but still got same error

```
<key>onesignal.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                <string>TLSv1.0</string>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
            </dict>
```

Any help ?

**Comment by Nightsd01** [comment]
Is the date & time correct on your device? Are you using some VPN/proxy service on your device?

The correct way to add an exception to your plist for OneSignal is this (you shouldn't actually have to do this but I would be interested in seeing if it would fix your problem). It shouldn't be at the root of your plist, the OneSignal exception domain should be inside of `NSAppTransportSecurity` -> `NSExceptionDomains`

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSExceptionDomains</key>
  <dict>
    <key>onesignal.com</key>
    <dict>
      <key>NSIncludesSubdomains</key>
      <true/>
      <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <key>NSTemporaryExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
    </dict>
  </dict>
</dict>
```

**Comment by Nightsd01** [comment]
@black-lotus  Please let me know if that doesn't fix your issue.

**Comment by black-lotus** [comment]
Halo, sorry for late response

When i used my plist config, it won't work

```
<key>onesignal.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                <string>TLSv1.0</string>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
            </dict>
```

When i try yours it working
```
<key>onesignal.com</key>
    <dict>
      <key>NSIncludesSubdomains</key>
      <true/>
      <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <key>NSTemporaryExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
    </dict>
```

By the way my user use AdBlock App that cause i can't get player id

**Comment by Nightsd01** [comment]
@black-lotus Great to hear, if you have any further issues please feel free to ask.

**Comment by ztpr0035** [comment]
Hi @Nightsd01, I have same issue in a Cordova based application and I don't even have any Adblock app.
