### ISSUE TITLE
OneSignal_disable_badge_clearing disables the "wakeup" function triggered by content_available

### ISSUE THREAD

**Issue by gisngocthach** [OneSignal/OneSignal-iOS-SDK#335]
Preventing the badge resetting by OneSignal through turning on the OneSignal_disable_badge_clearing property in the plist makes the code handling the notification received event not being invoked as the app is running in the background.

**Comment by Nightsd01** [comment]
@gisngocthach are you saying the `handleNotificationReceived` completion block _is_ being called when you don't have `OneSignal_disable_badge_clearing` = true?

**Comment by gisngocthach** [comment]
Nope, when I set have `OneSignal_disable_badge_clearing = true`, the `handleNotificationReceived` completion block is not called  when the app is in the background. It should be working when having `content_available = true` in the Notification.

**Comment by Nightsd01** [comment]
@gisngocthach  Can you show me your info.plist contents?

We've attempted to reproduce the behavior you are seeing and haven't been successful so far - it's quite bizarre since `OneSignal_disable_badge_clearing` doesn't have anything to do with background execution & whether or not the `handleNotificationReceived` block gets called.

**Comment by Nightsd01** [comment]
And just to be clear, you are saying that when `OneSignal_disable_badge_clearing` = false, the `handleNotificationReceived` block _does_ get called in your application?

**Comment by gisngocthach** [comment]
When I don't have `OneSignal_disable_badge_clearing` in the plist, the block is called.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>English</string>
    <key>CFBundleDisplayName</key>
    <string>IntraKrea</string>
    <key>CFBundleExecutable</key>
    <string>${EXECUTABLE_NAME}</string>
    <key>CFBundleIcons</key>
    <dict/>
    <key>CFBundleIcons~ipad</key>
    <dict/>
    <key>CFBundleIdentifier</key>
    <string>com.krea.intranet</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>${PRODUCT_NAME}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>OneSignal_disable_badge_clearing</key>
    <true/>
    <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSExceptionDomains</key>
      <dict>
        <key>localhost</key>
        <dict>
          <key>NSExceptionAllowsInsecureHTTPLoads</key>
          <true/>
        </dict>
        <key>192.168.0.105</key>
        <dict>
          <key>NSExceptionAllowsInsecureHTTPLoads</key>
          <true/>
        </dict>
        <key>192.168.1.8</key>
        <dict>
          <key>NSExceptionAllowsInsecureHTTPLoads</key>
          <true/>
        </dict>
        <key>192.168.16.106</key>
        <dict>
          <key>NSExceptionAllowsInsecureHTTPLoads</key>
          <true/>
        </dict>
      </dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
    </dict>
    <key>NSCameraUsageDescription</key>
    <string>This app needs camera access</string>
    <key>NSMainNibFile</key>
    <string/>
    <key>NSMainNibFile~ipad</key>
    <string/>
    <key>NSMicrophoneUsageDescription</key>
    <string>This app needs microphone access</string>
    <key>NSPhotoLibraryAddUsageDescription</key>
    <string>This app needs write-access to photo library</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>This app needs read/write-access photo library access</string>
    <key>UIBackgroundModes</key>
    <array>
      <string>remote-notification</string>
    </array>
    <key>UILaunchStoryboardName</key>
    <string>CDVLaunchScreen</string>
    <key>UIRequiresFullScreen</key>
    <true/>
    <key>UISupportedInterfaceOrientations</key>
    <array>
      <string>UIInterfaceOrientationPortrait</string>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
      <string>UIInterfaceOrientationPortrait</string>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationPortraitUpsideDown</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
  </dict>
</plist>

```

**Comment by Nightsd01** [comment]
@gisngocthach Your `info.plist` looks fine. How do you know that the block isn't being called, are you printing to the debugger console?

**Comment by gisngocthach** [comment]
I am debugging by Safari

**Comment by Nightsd01** [comment]
@gisngocthach  I am not sure what you mean? How are you debugging with Safari? How do you know, for example, that the `handleNotificationReceived` block does not execute?

**Comment by gisngocthach** [comment]
Open the app on the device and turn on the WebInspector configuration, then just open Safari and enable the Develop option. That's all for setting up.The next thing is adding a debug point in the `_handleNotificationReceived_` block. Sending message from OneSignal in two cases: The app is in focus and the app is running background.

**Comment by Nightsd01** [comment]
Are you using Cordova?

**Comment by gisngocthach** [comment]
Yes, ionic

**Comment by gisngocthach** [comment]
@Nightsd01 I just test the app again and a magical thing happened. It works perfectly :-). I am 100% sure that yesterday it didn't. Thank you so much for looking at my problem.

**Comment by Nightsd01** [comment]
@gisngocthach Generally our wrapper SDK's don't support background execution. You would have to write native Objective-C/Swift code to handle the background execution as it won't load the entire Cordova runtime.

If you have any further issues, please feel free to open an issue on the [Cordova OneSignal SDK repo](https://github.com/OneSignal/OneSignal-Cordova-SDK) and we are glad to hear you got it working!
