### ISSUE TITLE
Crashing on Simulator with Linker Errors

### ISSUE THREAD

**Issue by ovais-panjwani** [OneSignal/OneSignal-iOS-SDK#337]
I understand that you can't have notifications on your simulator but that shouldn't prevent me from running the simulator. I'm using Xcode 9.2, have version 2.7.0 for OneSignal, and I'm using a MacBook Pro late-2015 edition. These are the linker errors I'm getting:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_OneSignal", referenced from:
      objc-class-ref in AppDelegate.o
  "_kOSSettingsKeyAutoPrompt", referenced from:
```

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Please help me resolve this issue so I can continue using my simulator.

**Comment by Nightsd01** [comment]
Hi @ovais-panjwani 

How did you add the OneSignal-iOS-SDK to your project as a dependency? Did you use cocoapods or something else?

**Comment by ovais-panjwani** [comment]
Wow you guys are fast! 

I used Cocoapods to add it. Initially I got this warning after install:
```
[!] The <ProjectName>[Staging] target overrides the ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES build setting defined in Pods/Target Support Files/Pods-<ProjectName>/Pods-<ProjectName>.staging.xcconfig'. This can lead to problems with the CocoaPods installation
```
So then I changed the Always Embed Swift Standard Libraries to be $(inherited) and I no longer received the warning. Not sure if that has anything to do with this but I figured I should let you know.

**Comment by Nightsd01** [comment]
@ovais-panjwani does this issue still occur for you if you use version 2.6.2 of the SDK instead?

**Comment by ovais-panjwani** [comment]
Sorry for the late response, but yes it still happens with version 2.6.2 of the SDK.

**Comment by ovais-panjwani** [comment]
So I just realized that I get the same crash on an actual iOS device.

**Comment by ovais-panjwani** [comment]
Okay I was able to fix it by adding the framework to the Linked Frameworks and Libraries.
