### ISSUE TITLE
Add iOS 10 support

### ISSUE THREAD

**Issue by AlbertoGuerreroMartin** [OneSignal/OneSignal-iOS-SDK#34]
Push notifications are not being received by devices with iOS 10 first beta (14A5261v).

Although it may just be an issue due to the beta state of the OS, maybe it'd be necessary to review the latest news that would be shown in the [WWDC 2016 event](https://developer.apple.com/videos/play/wwdc2016/724/), and update the SDK if needed.

**Comment by AlbertoGuerreroMartin** [comment]
Well, looks like notification was just delaying, my iPhone finally received it (after about 25 minutes). Seems like it can be an error caused by the beta version of iOS 10.

**Comment by gdeglin** [comment]
Thanks for trying this out and for the report!

Was your iPhone low on battery by chance? It might have entered a power saving mode that could delay notifications.

**Comment by AlbertoGuerreroMartin** [comment]
No :/ it was fully charged, and also connected to my MacBook. I'll be developing for iOS 10 using your platform, so if I detect any issue, I'd open it here.

**Comment by AlbertoGuerreroMartin** [comment]
Not sure if it's caused by iOS 10 beta, but suddenly APNS registration is failing without changing anything.

The error displayed is:
{code}
ERROR: Error registering for Apple push notifications. Error: Error Domain=NSCocoaErrorDomain Code=3000 "falta la clave de autorización “aps-environment” válida para la aplicación" UserInfo={NSLocalizedDescription=falta la clave de autorización “aps-environment” válida para la aplicación}
{code}

**Comment by jkasten2** [comment]
@AlbertoGuerreroMartin The messing is saying your provisioning profile is missing `aps-environment` which is required for push notifications. Did you change this or your bundle id?

**Comment by AlbertoGuerreroMartin** [comment]
I didn't change my bundle id, and my provisioning profile associated with an App-ID that has push notifications enabled and configured for both development and distribution cases. I've check it all, and it looks like everything is correct...

**Comment by jkasten2** [comment]
@AlbertoGuerreroMartin You can also try enabling the below setting on your app build target.
![image](https://cloud.githubusercontent.com/assets/645861/16397314/757a5e4c-3c78-11e6-8c1c-95c5b40d2122.png)

The `aps-environment` isn't related to our SDK, it being thrown by iOS. If you are still seeing an issue I recommend trying a new project and bundle id to test with. You can also try our example Xcode project found in this repo.

We have been testing with Xcode 8 beta and iOS 10 and haven't run into this issue.

**Comment by AlbertoGuerreroMartin** [comment]
@jkasten2 that's it! after enabling _Push Notification_ capability, it all worked correctly.

Thanks!!

**Comment by burhanyldz** [comment]
@jkasten2 YES YES YES. You my friend are my hero! **(emoji with dancing monkeys)**
