### ISSUE TITLE
one signal notification opened block issue

### ISSUE THREAD

**Issue by irzadhuzaen** [OneSignal/OneSignal-iOS-SDK#341]
I added code to pass to view controller when a notification with additional data clicked.It works well if app is in running state and when app is closed when notification clicked crashes and app closes

**Comment by Nightsd01** [comment]
@irzadhuzaen how are you creating/instantiating this view controller and what data are you passing to passing to it?

This is likely an issue with your code and not the SDK, but if you share your code & the exception I can help.

**Comment by irzadhuzaen** [comment]
let notificationOpenedBlock: OSHandleNotificationActionBlock = { result in
            // This block gets called when the user reacts to a notification received

            let payload: OSNotificationPayload? = result?.notification.payload
            
            print(">onesignal...Message = \(payload!.body)")
            print(">onesignal...badge number = \(String(describing: payload?.badge))")
            print(">onesignal...notification sound = \(String(describing: payload?.sound))")
            
            print("add---->",result!.notification.payload!.additionalData)
            
            
            let mainStoryboard = UIStoryboard(name: "Main" , bundle: nil)
            let protectedPagenotif = mainStoryboard.instantiateViewController(withIdentifier: "afterlogvc") as! HomeViewController
            
           
            
            
            
            
            
            if let additionalData = result!.notification.payload!.additionalData {
            
                print("additionalData = \(additionalData)")
  
                
                
                
                let name: String? = additionalData["name"] as? String
                let mobile: String? = additionalData["mobile"] as? String
                let latitude: String? = additionalData["latitude"] as? String
                let longitude: String? = additionalData["longitude"] as? String
                let blood: String? = additionalData["blood"] as? String
                let playerid: String? = additionalData["playerid"] as? String
                UserDefaults.standard.set(name, forKey: "namenotification")
                UserDefaults.standard.set(mobile, forKey: "mobilenotification")
                UserDefaults.standard.set(latitude, forKey: "latitudenotification")
                UserDefaults.standard.set(longitude, forKey: "longitudenotification")
                UserDefaults.standard.set(blood, forKey: "bloodnotification")
                UserDefaults.standard.set(playerid, forKey: "playeridnotification")
                UserDefaults.standard.synchronize()
                print("Notifiedname============>",UserDefaults.standard.string(forKey:"namenotification")!)
                print("Notifiedmobile============>",UserDefaults.standard.string(forKey:"mobilenotification")!)
                print("Notifiedblood============>",UserDefaults.standard.string(forKey:"bloodnotification")!)
                print("Notifiedlatitude============>",UserDefaults.standard.string(forKey:"latitudenotification")!)
                print("Notifiedlongitude============>",UserDefaults.standard.string(forKey:"longitudenotification")!)
                print("Notifiedplayerid========>",UserDefaults.standard.string(forKey: "playeridnotification")!)
                
                
                self.window!.rootViewController = protectedPagenotif
                self.window!.makeKeyAndVisible()
                
                
                
                
                // DEEP LINK and open url in RedViewController
                // Send notification with Additional Data > example key: "OpenURL" example value: "https://google.com"
                //let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
               // let instantiateRedViewController : RedViewController = mainStoryboard.instantiateViewController(withIdentifier: "RedViewControllerID") as! RedViewController
               // instantiateRedViewController.receivedURL = additionalData["OpenURL"] as! String!
               // self.window = UIWindow(frame: UIScreen.main.bounds)
               // self.window?.rootViewController = instantiateRedViewController
               // self.window?.makeKeyAndVisible()
           
            }
        }
@Nightsd01

**Comment by irzadhuzaen** [comment]
I told it works well when notification tapped in-app running state. That why I posted issue here

**Comment by irzadhuzaen** [comment]
@jkasten2 can you help on this

**Comment by Nightsd01** [comment]
@irzadhuzaen can you provide a stack trace? If you use something like Crashlytics, it should be relatively easy to get a stack trace in this situation. 

I’ll investigate your crash tomorrow. In the mean time please do post a stack trace.

**Comment by irzadhuzaen** [comment]
@Nightsd01 Thank you for responding. I Found the issue and have solved it.While appdidlaunch I made to instantiate to a view controller if a user is logged in state.Now I removed it, Now it works fine
