### ISSUE TITLE
SDK crashes on notifyChange

### ISSUE THREAD

**Issue by agordeev** [OneSignal/OneSignal-iOS-SDK#342]
Version `2.6.2`. Happens occasionally.

Call stack:
![](https://user-images.githubusercontent.com/2883524/36353349-92412d20-14d6-11e8-9d78-b4a9cf076932.png)

My suspicion is this is happening when I call

```
OneSignal.remove(self as OSSubscriptionObserver)
```

Because here's my method:

```
    var resolve: Promise<NotificationPermissionsScene.PermissionsResult>.Resolved = { _ in }

    func onOSSubscriptionChanged(_ stateChanges: OSSubscriptionStateChanges!) {
        Logger.verbose("OS state changed: \(stateChanges.to.userId) \(stateChanges.to.pushToken)")
        if let playerId = stateChanges.to.userId, let deviceToken = stateChanges.to.pushToken {
            let result = NotificationPermissionsScene.PermissionsResult(playerId: playerId, deviceToken: deviceToken)
            self.result = result
            Logger.verbose("Resolved")
            resolve(result)
            OneSignal.remove(self as OSSubscriptionObserver)
        }
    }
```

and here's what I see in console output:

```
18:05:47.991 💜 VERBOSE NotificationPermissionsWorker.onOSSubscriptionChanged():54 - OS state changed: Optional("7277d471-9c39-4091-969a-d2eea933b05c") Optional("6738a1fad21f5dc7ada7a87205bb741ef8df8114163edcc6c2ffb18911cbaa68")
18:07:00.857 💜 VERBOSE NotificationPermissionsWorker.onOSSubscriptionChanged():58 - Resolved
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by Nightsd01** [comment]
@agordeev thank you for reporting this issue. It appears that, in rare circumstances, if you call `remove(OSSubscriptionObserver)` inside of the `onOSSubscriptionChanged()` method, it can cause a crash because it is mutating an NSHashTable while iterating through it.

I have recently mad a commit to fix this issue and it will be resolved in the next iOS SDK update.

**Comment by agordeev** [comment]
@Nightsd01 sounds great, thanks! When should we expect the next release to test?

**Comment by Nightsd01** [comment]
@agordeev this PR (#344) is in review now and we should have it released as an update within the next 24 hours. Thank you for your patience!

**Comment by Nightsd01** [comment]
@agordeev Forgive the delay, the reviewer for the PR has been quite busy today. If the update isn't released within the next few hours, it will be tomorrow for sure.

**Comment by Nightsd01** [comment]
This issue should not be resolved, let me know if you encounter any other issues @agordeev
