### ISSUE TITLE
OneSignal.h file not found

### ISSUE THREAD

**Issue by faustoct** [OneSignal/OneSignal-iOS-SDK#346]
Getting this error on xcode `OneSignal.h file not found`. I have expo detached and everything was working fine suddenly it stopped maybe an unexpected update or smth. 

Sometimes I get an error `OSEmailSubscription`.

Any ideia what's going on? how to fix it?

**Comment by Nightsd01** [comment]
@faustoct If you are using the react-native SDK I would suggest creating this issue in the React-Native OneSignal repo.

How did you include OneSignal as a dependency in your project?

**Comment by Nightsd01** [comment]
Closing because issue was opened in the RN repo.

**Comment by faustoct** [comment]
solved here https://github.com/geektimecoil/react-native-onesignal/issues/405
