### ISSUE TITLE
Collapse occurred in OSRequestSubmitNotificationOpened 

### ISSUE THREAD

**Issue by a455455b** [OneSignal/OneSignal-iOS-SDK#347]
We've found some common crash in the insert nil object to a __NSPlaceholderDictionary.

 Date: 2018-02-22T21:39:00Z
 OS Version: 10.3.1 (14E304)
 Device: iPhone 6s Plus
 RAM Free: 7.8%
 Disk Free: 18.3%

#0. Crashed: com.twitter.crashlytics.ios.exception
0  banggood                       0x100905350 CLSProcessRecordAllThreads (CLSProcess.c:376)
1  banggood                       0x100905350 CLSProcessRecordAllThreads (CLSProcess.c:376)
2  banggood                       0x100905200 CLSProcessRecordAllThreads (CLSProcess.c:407)
3  banggood                       0x1008f4838 CLSHandler (CLSHandler.m:26)
4  banggood                       0x100903334 __CLSExceptionRecord_block_invoke (CLSException.mm:199)
5  (Missing)                      0x18453a9a0 (Missing)
6  (Missing)                      0x184547ee0 (Missing)
7  banggood                       0x100902dcc CLSExceptionRecord (CLSException.mm:206)
8  banggood                       0x100902c04 CLSExceptionRecordNSException (CLSException.mm:102)
9  banggood                       0x100902818 CLSTerminateHandler() (CLSException.mm:259)
10 (Missing)                      0x1840d35d4 (Missing)
11 (Missing)                      0x1840d31a8 (Missing)
12 (Missing)                      0x1840e46f8 (Missing)
13 (Missing)                      0x18555ee00 (Missing)
14 UIKit                          0x18b81c45c -[UIApplication _run] + 652
15 UIKit                          0x18b817130 UIApplicationMain + 208
16 banggood                       0x100122160 main (main.m:16)
17 (Missing)                      0x18456d59c (Missing)

--

Fatal Exception: NSInvalidArgumentException
0  (Missing)                      0x185682fd8 (Missing)
1  (Missing)                      0x1840e4538 (Missing)
2  (Missing)                      0x1855699a4 (Missing)
3  (Missing)                      0x185569814 (Missing)
4  banggood                       0x100a6b6e4 +[OSRequestSubmitNotificationOpened withUserId:appId:wasOpened:messageId:] (Requests.m:143)
5  banggood                       0x100a4851c +[OneSignal submitNotificationOpened:] (OneSignal.m:1266)
6  banggood                       0x100a48020 +[OneSignal handleNotificationOpened:isActive:actionType:displayType:] (OneSignal.m:1229)
7  banggood                       0x100a47cc4 +[OneSignal notificationOpened:isActive:] (OneSignal.m:1205)
8  banggood                       0x100a5bd4c +[OneSignalUNUserNotificationCenter processiOS10Open:] (UNUserNotificationCenter+OneSignal.m:220)
9  banggood                       0x100a5b7ac -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] (UNUserNotificationCenter+OneSignal.m:182)
10 UIKit                          0x18ba457c4 -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:]
11 UIKit                          0x18ba2fd18 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]
12 UIKit                          0x18ba352a8 -[UIApplication _runWithMainScene:transitionContext:completion:]
13 UIKit                          0x18ba49de0 __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke.3151
14 UIKit                          0x18ba3253c -[UIApplication workspaceDidEndTransaction:]
15 (Missing)                      0x18722b884 (Missing)
16 (Missing)                      0x18722b6f0 (Missing)
17 (Missing)                      0x18722baa0 (Missing)
18 (Missing)                      0x185631424 (Missing)
19 (Missing)                      0x185630d94 (Missing)
20 (Missing)                      0x18562e9a0 (Missing)
21 (Missing)                      0x18555ed94 (Missing)
22 UIKit                          0x18b81c45c -[UIApplication _run]
23 UIKit                          0x18b817130 UIApplicationMain
24 banggood                       0x100122160 main (main.m:16)
25 (Missing)                      0x18456d59c (Missing)

#0. Crashed: com.twitter.crashlytics.ios.exception
0  banggood                       0x100905350 CLSProcessRecordAllThreads (CLSProcess.c:376)
1  banggood                       0x100905350 CLSProcessRecordAllThreads (CLSProcess.c:376)
2  banggood                       0x100905200 CLSProcessRecordAllThreads (CLSProcess.c:407)
3  banggood                       0x1008f4838 CLSHandler (CLSHandler.m:26)
4  banggood                       0x100903334 __CLSExceptionRecord_block_invoke (CLSException.mm:199)
5  (Missing)                      0x18453a9a0 (Missing)
6  (Missing)                      0x184547ee0 (Missing)
7  banggood                       0x100902dcc CLSExceptionRecord (CLSException.mm:206)
8  banggood                       0x100902c04 CLSExceptionRecordNSException (CLSException.mm:102)
9  banggood                       0x100902818 CLSTerminateHandler() (CLSException.mm:259)
10 (Missing)                      0x1840d35d4 (Missing)
11 (Missing)                      0x1840d31a8 (Missing)
12 (Missing)                      0x1840e46f8 (Missing)
13 (Missing)                      0x18555ee00 (Missing)
14 UIKit                          0x18b81c45c -[UIApplication _run] + 652
15 UIKit                          0x18b817130 UIApplicationMain + 208
16 banggood                       0x100122160 main (main.m:16)
17 (Missing)                      0x18456d59c (Missing)

#1. io.answers.EventQueue :: NSOperation 0x174448130 (QOS: USER_INTERACTIVE)
0  (Missing)                      0x18467cbf4 (Missing)
1  (Missing)                      0x18467b6a4 (Missing)
2  (Missing)                      0x1845cbbcc (Missing)
3  (Missing)                      0x1860c8ee0 (Missing)
4  banggood                       0x100912be0 +[ANSFileUtils allFilesInDirectory:] (ANSFileUtils.m:21)
5  banggood                       0x10090f91c -[ANSCleanupFilesOperation main] (ANSCleanupFilesOperation.m:41)
6  (Missing)                      0x186086b18 (Missing)
7  (Missing)                      0x186153ba0 (Missing)
8  (Missing)                      0x18453a9a0 (Missing)
9  (Missing)                      0x184548ad4 (Missing)
10 (Missing)                      0x18453e2cc (Missing)
11 (Missing)                      0x18454aa50 (Missing)
12 (Missing)                      0x18454a7d0 (Missing)
13 (Missing)                      0x1847431d0 (Missing)
14 (Missing)                      0x184742d7c (Missing)

#2. Thread
0  (Missing)                      0x184742d78 (Missing)

#3. com.apple.uikit.backgroundTaskAssertionQueue
0  (Missing)                      0x18467da88 (Missing)
1  (Missing)                      0x184747c30 (Missing)
2  (Missing)                      0x18454bcec (Missing)
3  (Missing)                      0x1871b6398 (Missing)
4  UIKit                          0x18ba525c8 ___addBackgroundTask_block_invoke + 152
5  (Missing)                      0x18453a9a0 (Missing)
6  (Missing)                      0x184547ee0 (Missing)
7  UIKit                          0x18b7fda04 _addBackgroundTask + 748
8  UIKit                          0x18ba4e730 -[UIApplication _beginBackgroundTaskWithExpirationHandler:] + 24
9  UIKit                          0x18b80696c -[UIApplication beginBackgroundTaskWithExpirationHandler:] + 72
10 banggood                       0x1007329bc +[PINBackgroundTask start] (PINDiskCache.m:1231)
11 banggood                       0x10072d670 __26+[PINDiskCache emptyTrash]_block_invoke (PINDiskCache.m:260)
12 (Missing)                      0x18453a9e0 (Missing)
13 (Missing)                      0x18453a9a0 (Missing)
14 (Missing)                      0x184548ad4 (Missing)
15 (Missing)                      0x18453e2cc (Missing)
16 (Missing)                      0x18454aa50 (Missing)
17 (Missing)                      0x18454a7d0 (Missing)
18 (Missing)                      0x1847431d0 (Missing)
19 (Missing)                      0x184742d7c (Missing)

#4. com.apple.NSURLConnectionLoader
0  (Missing)                      0x18465f224 (Missing)
1  (Missing)                      0x18465f09c (Missing)
2  (Missing)                      0x185630e88 (Missing)
3  (Missing)                      0x18562eadc (Missing)
4  (Missing)                      0x18555ed94 (Missing)
5  (Missing)                      0x185d6aca4 (Missing)
6  (Missing)                      0x1861762c8 (Missing)
7  (Missing)                      0x18474575c (Missing)
8  (Missing)                      0x18474566c (Missing)
9  (Missing)                      0x184742d84 (Missing)

#5. Thread
0  (Missing)                      0x18467ce1c (Missing)
1  (Missing)                      0x1847448e4 (Missing)
2  (Missing)                      0x18406dac8 (Missing)
3  (Missing)                      0x189f0fc98 (Missing)
4  (Missing)                      0x189f0fc0c (Missing)
5  (Missing)                      0x189f0faec (Missing)
6  (Missing)                      0x189f0fd9c (Missing)
7  (Missing)                      0x18474575c (Missing)
8  (Missing)                      0x18474566c (Missing)
9  (Missing)                      0x184742d84 (Missing)

#6. WebThread
0  (Missing)                      0x18465f224 (Missing)
1  (Missing)                      0x18465f09c (Missing)
2  (Missing)                      0x185630e88 (Missing)
3  (Missing)                      0x18562eadc (Missing)
4  (Missing)                      0x18555ed94 (Missing)
5  WebCore                        0x18a22eb5c RunWebThread(void*) + 456
6  (Missing)                      0x18474575c (Missing)
7  (Missing)                      0x18474566c (Missing)
8  (Missing)                      0x184742d84 (Missing)

#7. com.apple.uikit.eventfetch-thread
0  (Missing)                      0x18465f224 (Missing)
1  (Missing)                      0x18465f09c (Missing)
2  (Missing)                      0x185630e88 (Missing)
3  (Missing)                      0x18562eadc (Missing)
4  (Missing)                      0x18555ed94 (Missing)
5  (Missing)                      0x186078d64 (Missing)
6  (Missing)                      0x186099b34 (Missing)
7  UIKit                          0x18c1a15f8 -[UIEventFetcher threadMain] + 136
8  (Missing)                      0x1861762c8 (Missing)
9  (Missing)                      0x18474575c (Missing)
10 (Missing)                      0x18474566c (Missing)
11 (Missing)                      0x184742d84 (Missing)

#8. com.twitter.crashlytics.ios.binary-images
0  (Missing)                      0x184660ca4 (Missing)
1  banggood                       0x100903d0c __CLSFileWriteWithRetries_block_invoke (CLSFile.m:241)
2  banggood                       0x100903c4c CLSFileLoopWithWriteBlock (CLSFile.m:213)
3  banggood                       0x100903f00 CLSFileWriteToFileDescriptorOrBuffer (CLSFile.m:190)
4  banggood                       0x10090421c CLSFileWriteCollectionEnd (CLSFile.m:450)
5  banggood                       0x10090416c CLSFileWriteSectionEnd (CLSFile.m:427)
6  banggood                       0x1008ebbe4 __CLSBinaryImageChanged_block_invoke (CLSBinaryImage.m:518)
7  (Missing)                      0x18453a9e0 (Missing)
8  (Missing)                      0x18453a9a0 (Missing)
9  (Missing)                      0x184548ad4 (Missing)
10 (Missing)                      0x18453e2cc (Missing)
11 (Missing)                      0x184548fa8 (Missing)
12 (Missing)                      0x18454aa50 (Missing)
13 (Missing)                      0x18454a7d0 (Missing)
14 (Missing)                      0x1847431d0 (Missing)
15 (Missing)                      0x184742d7c (Missing)

#9. Thread
0  (Missing)                      0x184742d78 (Missing)

#10. GAIThread
0  (Missing)                      0x18465f224 (Missing)
1  (Missing)                      0x18465f09c (Missing)
2  (Missing)                      0x185630e88 (Missing)
3  (Missing)                      0x18562eadc (Missing)
4  (Missing)                      0x18555ed94 (Missing)
5  (Missing)                      0x186078d64 (Missing)
6  (Missing)                      0x1860cd6b4 (Missing)
7  banggood                       0x1006bfb60 +[GAI threadMain:] (GAI.m:241)
8  (Missing)                      0x1861762c8 (Missing)
9  (Missing)                      0x18474575c (Missing)
10 (Missing)                      0x18474566c (Missing)
11 (Missing)                      0x184742d84 (Missing)

#11. com.apple.root.user-initiated-qos
0  (Missing)                      0x18467d314 (Missing)
1  (Missing)                      0x18459c8b0 (Missing)
2  (Missing)                      0x184605270 (Missing)
3  banggood                       0x10036ea78 __26-[StartupSerialTasks init]_block_invoke_2 (StartupSerialTasks.m:44)
4  (Missing)                      0x18453a9e0 (Missing)
5  (Missing)                      0x18453a9a0 (Missing)
6  (Missing)                      0x18454abac (Missing)
7  (Missing)                      0x18454a7d0 (Missing)
8  (Missing)                      0x1847431d0 (Missing)
9  (Missing)                      0x184742d7c (Missing)

#12. Thread
0  (Missing)                      0x18467da88 (Missing)
1  (Missing)                      0x184743274 (Missing)
2  (Missing)                      0x184742d7c (Missing)

#13. com.twitter.crashlytics.ios.MachExceptionServer
0  (Missing)                      0x18465f224 (Missing)
1  (Missing)                      0x18465f09c (Missing)
2  banggood                       0x1008ef714 CLSMachExceptionServer (CLSMachException.c:180)
3  (Missing)                      0x18474575c (Missing)
4  (Missing)                      0x18474566c (Missing)
5  (Missing)                      0x184742d84 (Missing)

#14. Thread
0  (Missing)                      0x18467da88 (Missing)
1  (Missing)                      0x184743274 (Missing)
2  (Missing)                      0x184742d7c (Missing)

**Comment by Nightsd01** [comment]
Hi @a455455b ,

This is a strange issue because this specific codepath specifically checks for nil to make sure it _doesn't_ insert nil into a dictionary.

What version of the iOS SDK is your application using? Are these crashes happening only in specific versions of your app, and if so, what version of the iOS SDK were those version/s using?

**Comment by a455455b** [comment]
Hello @Nightsd01 We use the version number 2.7.1 .The crashs on system 11/10/9 . We found 13 crashes in recent months.

**Comment by Nightsd01** [comment]
@a455455b Thank you for reporting this. I resolved this issue a few days ago and it is awaiting review in a PR. It should be released in an update before Friday.

**Comment by a455455b** [comment]
@Nightsd01 Thanks a lot !

**Comment by Nightsd01** [comment]
@a455455b this should now be resolved. Please let me know if you have any further problems, thanks!
