### ISSUE TITLE
crash when open app from notification

### ISSUE THREAD

**Issue by Blankz** [OneSignal/OneSignal-iOS-SDK#349]
i'm using ios 11 and sdk 2.7.2

i got fatal error 
** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x181773164 __exceptionPreprocess
1  libobjc.A.dylib                0x1809bc528 objc_exception_throw
2  CoreFoundation                 0x18170bc9c _CFArgv
3  CoreFoundation                 0x181643fd0 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
4  CoreFoundation                 0x181643e4c +[NSDictionary dictionaryWithObjects:forKeys:count:]
5  Fixzy                          0x101563718 +[OSRequestSubmitNotificationOpened withUserId:appId:wasOpened:messageId:] (Requests.m:211)
6  Fixzy                          0x101538d18 +[OneSignal submitNotificationOpened:] (OneSignal.m:1478)
7  Fixzy                          0x10153881c +[OneSignal handleNotificationOpened:isActive:actionType:displayType:] (OneSignal.m:1441)
8  Fixzy                          0x1015384c0 +[OneSignal notificationOpened:isActive:] (OneSignal.m:1417)
9  Fixzy                          0x101550b30 +[OneSignalUNUserNotificationCenter processiOS10Open:] (UNUserNotificationCenter+OneSignal.m:220)
10 Fixzy                          0x101550590 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] (UNUserNotificationCenter+OneSignal.m:182)
11 UIKit                          0x18afa2064 -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:]
12 UIKit                          0x18af8e124 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]
13 UIKit                          0x18af92a14 -[UIApplication _runWithMainScene:transitionContext:completion:]
14 UIKit                          0x18b22e2a8 __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke
15 UIKit                          0x18b506100 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:]
16 UIKit                          0x18b22df0c -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]
17 UIKit                          0x18b22e76c -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:]
18 UIKit                          0x18b9b37c0 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke
19 UIKit                          0x18b9b3664 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]
20 UIKit                          0x18b7212cc __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke
21 UIKit                          0x18b8ba3cc _performActionsWithDelayForTransitionContext
22 UIKit                          0x18b72117c -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]
23 UIKit                          0x18b505760 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:]
24 UIKit                          0x18af91158 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:]
25 UIKit                          0x18b3a6dbc -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]
26 FrontBoardServices             0x183e361f0 -[FBSSceneImpl _didCreateWithTransitionContext:completion:]
27 FrontBoardServices             0x183e3eaf8 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2
28 libdispatch.dylib              0x1810f2a14 _dispatch_client_callout
29 libdispatch.dylib              0x1810fa200 _dispatch_block_invoke_direct$VARIANT$mp
30 FrontBoardServices             0x183e6a7f8 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
31 FrontBoardServices             0x183e6a49c -[FBSSerialQueue _performNext]
32 FrontBoardServices             0x183e6aa38 -[FBSSerialQueue _performNextFromRunLoopSource]
33 CoreFoundation                 0x18171b77c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
34 CoreFoundation                 0x18171b6fc __CFRunLoopDoSource0
35 CoreFoundation                 0x18171af84 __CFRunLoopDoSources0
36 CoreFoundation                 0x181718b5c __CFRunLoopRun
37 CoreFoundation                 0x181638c58 CFRunLoopRunSpecific
38 GraphicsServices               0x1834e4f84 GSEventRunModal
39 UIKit                          0x18ad915c4 UIApplicationMain
40 Fixzy                          0x100c8c314 main (WebWireFrame.swift:12)
41 libdyld.dylib                  0x18115856c start

**Comment by Nightsd01** [comment]
@Blankz This particular crash was fixed in a recent update.

Are you sure that the users experiencing this crash aren't using an older version of your app that uses an older version of the OneSignal SDK?

**Comment by Blankz** [comment]
@Nightsd01  

Oh sorry i'm misunderstand my app version

**Comment by Nightsd01** [comment]
Glad to hear it!
