### ISSUE TITLE
Infinite loop in swizzled method

### ISSUE THREAD

**Issue by JanC** [OneSignal/OneSignal-iOS-SDK#351]
Hi,
I was giving your SDK a try and I noticed an infinite loop when a push notification is received. I believe it's caused by the swizzled methods in the `UNUserNotificationCenter+OneSignal.m` when there is another SDK also swizzling the same method. In my case, I have the both OneSignal and [Helpshift](https://www.helpshift.com/)

To reproduce:
- Integrate the OneSignal SDK
- Integrate the [Helpshift](https://developers.helpshift.com) SDK (no need to create an account)

```ruby
  pod 'OneSignal', '~> 2.8'
  pod 'Helpshift', '~> 6.4'
```

```swift
HelpshiftCore.initialize(with: HelpshiftAll.sharedInstance())
HelpshiftCore.install(forApiKey: "00000000000000000000000", domainName: "foo.helpshift.com", appID: "foo_platform_00000000000000000-000000000000000")

OneSignal.setLogLevel(.LL_DEBUG, visualLevel: .LL_NONE)
OneSignal.promptForPushNotifications(userResponse: { accepted in
    print("User accepted notifications: \(accepted)")
})
```
- Send a sample push: 
```json
{
  "aps": {
    "alert": "Test",
    "sound": "default"
  }
}
```

On the following call stack, you can see that OneSignal calls the Helpshift's and vice versa. 
<img width="1359" alt="screen shot 2018-03-18 at 15 27 59" src="https://user-images.githubusercontent.com/707703/37567079-ea566038-2ac1-11e8-8420-8a9c003a4e51.png">

Here is a [sample Xcode](https://www.dropbox.com/s/4reffuomk198mdo/OneSignalInfinite.zip?dl=0) project that reproduces it

I _believe_ that when you are swizzling any of the  `UNUserNotificationCenterDelegate` methods you should
- check if the original delegate responds to the selector you are about to swizzle
- if not, swizzle with a method that **does not** call the "original" implementation
- if yes, swizzle with a method that **does** call the original implementation

https://github.com/OneSignal/OneSignal-iOS-SDK/blob/61393b7fc539f318298e5efd198def8f53fa40b8/iOS_SDK/OneSignalSDK/Source/UNUserNotificationCenter%2BOneSignal.m#L122-L135

**Comment by Nightsd01** [comment]
@JanC I have downloaded your example project and I've been unable to reproduce your issue. However I only tried it with the latest version (2.8.1). No changes to this specific code were made from 2.8.0 -> 2.8.1 so I can't imagine why I cannot reproduce the problem.

Since Helpshift's SDK seems to be completely private, I cannot see what their framework is doing either.

**Comment by JanC** [comment]
I've just tried with `2.8.1` and I'm getting the same behaviour. I forgot to mention that the app has to be in foreground when you send the push. Basically any of the `UNNotificationCenterDelegate` methods has to be called in order to reproduce it.

I also cannot see what Helpshift's SDK is doing but it looks like they are also swizzling the same class.

**Comment by Nightsd01** [comment]
I don't know _what_ HelpShift's SDK is doing, but it seems to me like they aren't even doing their swizzling in the `+load` method. 

I am very inclined to think their SDK is causing the loop. Our SDK works just fine with other push notification SDK's that do the same thing, swizzling UNNotificationCenter delegate methods, and it works just fine.

**Comment by JanC** [comment]
yes I agree. As the matter or fact I removed their SDK from my apps as I’ve had only issues with them in general.

Thanks for having a look at this anyway

**Comment by veeranfmq** [comment]
I am getting the same issue when clicking on delivered notification from background on iOS device.

**Comment by jkasten2** [comment]
@veeranfmq Can you describe your environment?
1. What version of the OneSignal SDK are you using?
2. What other plugins and their version are also in your project?
3. Can you share your related `AppDelegate` code and `UNUserNotificationCenterDelegate`?

**Comment by veeranfmq** [comment]
This was related to another 3rd party library which was also used for notification, and I was resetting delegate call for that, removing that fixed the issue. Thanks!

**Comment by jkasten2** [comment]
@veeranfmq Thanks for the details, good to hear you got it working!

> This was related to another 3rd party library which was also used for notification

Could you reply with what library and version? This could help others with this issue.

>   and I was resetting delegate call for that, removing that fixed the issue.

Could you provide more details on that? Where you setting your own delegate or setting it to `nil`? Could you share the code if possible?

**Comment by jkasten2** [comment]
For future reference, [OneSignal 3.11.2](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.11.2) has significant changes to it's swizzling implementation that most likely fixes this issue.
