### ISSUE TITLE
UserId is nil after setting OneSignal.setSubscription(true)

### ISSUE THREAD

**Issue by obianachebe** [OneSignal/OneSignal-iOS-SDK#358]
**Description**

When a user accepts remote notifications I set the subscription status to `true`, but when I attempt to access the userId or pushToken using `OneSignal.getPermissionSubscriptionState()` both values are returned as nil even though the permission status is authorized

**Relevant Code**

`
OneSignal.promptForPushNotifications(userResponse: { accepted in  
                  
                    if accepted {
                        OneSignal.setSubscription(true)
                        let status: OSPermissionSubscriptionState = OneSignal.getPermissionSubscriptionState()
                        let userID = status.subscriptionStatus.userId // reads nil
                    } else {
                        OneSignal.setSubscription(false)
                    }
                })
`

**Environment Details**

SDK version: 2.6.2
Device: iPhone 6s Plus
iOS version: 11.3.0
XCode version: 9.2

**Comment by Nightsd01** [comment]
Hi @obianachebe, thank you for this issue, you've provided a lot of details which is very helpful.

When the user accepts push notification permissions, they will not instantly have a user ID. When the user accepts push notification permissions, the SDK sends out an HTTP request to register with OneSignal's server. Once that request is finished, the user subscription state is updated with a user ID.

I would suggest using the **OSSubscriptionStateObserver** protocol in order to get updated whenever the subscription state changes. You can access the user ID there.

Please feel free to ask if you have any other problems or questions, thanks!

**Comment by obianachebe** [comment]
@Nightsd01 thanks a bunch for the help and quick response. I set up my view controller to conform to **OSSubscriptionObserver** as shown below.

`
override func viewDidLoad() {
    OneSignal.add(self as OSSubscriptionObserver)
}
`

`
extension MyViewController: OSSubscriptionObserver {
    func onOSSubscriptionChanged(_ stateChanges: OSSubscriptionStateChanges!) {
        let playerId = stateChanges.to.userId
        print("playerId: \(playerId)")
    }
}
`

However, **onOSSubscriptionChanged** is not called after the user grants permissions. I looked at issue #238 and uninstalled then reinstalled the app, but the observer  is never notified. Maybe I'm missing something? Thanks in advance for the help!

**Comment by obianachebe** [comment]
After setting the log level to VERBOSE, here's what I'm seeing after a user accepts push notifications. I'm assuming this means we're not getting a response back from APNS and the problem is on that end, and not OneSignal's. 

![simulator screen shot - iphone 6s - 2018-04-16 at 16 49 04](https://user-images.githubusercontent.com/13955058/38840823-53732534-4196-11e8-8973-57d7bc70dadb.png)

**Comment by obianachebe** [comment]
@Nightsd01 thanks for the clarification. Just so I'm clear, OSSubscriptionObserver's onOSSubscriptionChanged delegate method is **not** called when push notifications are permitted in the simulator?

**Comment by obianachebe** [comment]
@Nightsd01 I'm unable to retrieve the playerId even when using a build without the simulator. Any help is much appreciated. See full logs below:

```
2018-04-18 00:20:53.571446-0700 FitGenie[13087:24550681] VERBOSE: Firing registerForRemoteNotifications
2018-04-18 00:20:53.703942-0700 FitGenie[13087:24550681] VERBOSE: HTTP Request (OSRequestGetIosParams) with URL: https://onesignal.com/api/v1/apps/cdb84654-493d-461c-af73-426c9a844a7c/ios_params.js, with parameters: (null)
2018-04-18 00:20:53.915214-0700 FitGenie[13087:24551019] VERBOSE: network response: {}
2018-04-18 00:21:49.249991-0700 FitGenie[13087:24550681] VERBOSE: registerForPushNotifications Called:waitingForApnsResponse: 1
2018-04-18 00:21:58.472718-0700 FitGenie[13087:24550681] VERBOSE: updateNotificationTypes called: 15
2018-04-18 00:21:58.474515-0700 FitGenie[13087:24550681] VERBOSE: startedRegister: 1
2018-04-18 00:21:58.641407-0700 FitGenie[13087:24550681] VERBOSE: getNotificationTypes:mSubscriptionStatus: -1

```

**Comment by Nightsd01** [comment]
Hi @obianachebe 

I'm sorry I never noticed your reply to this thread. Are you still encountering this issue?

**Comment by obianachebe** [comment]
@Nightsd01 no problem. Thank you for following up. We are still encountering this issue. Have there been any related updates made in recent versions?

**Comment by LamourBt** [comment]
This problem still exits has anyone find a solution yet
