### ISSUE TITLE
ERROR 400 Bad Request (badgecount)

### ISSUE THREAD

**Issue by josteph** [OneSignal/OneSignal-iOS-SDK#362]
```
Client error: `POST https://onesignal.com/api/v1/notifications` resulted in a `400 Bad Request`

Response:
{"errors":["Option You must specify a badgecount when setting or increase badges."]}
```

Payload:
```
            'app_id' => $app_id_here,
            'included_segments' => ['all'],
            'contents' => [ "en" => $content ],
            'headings' => [ "en" => $title ],
            'include_player_ids' => array($player_id),
            'ios_BadgeCount' => 1,
            'ios_badgeType' => 'Increase'
```

I also have setup the headers Authorization like `Basic (api_key_here)`.

Referring to [here](https://documentation.onesignal.com/reference#create-notification), there is no `badgecount` option payload.

What am I doing wrong? Thank you for any help.

**Comment by Nightsd01** [comment]
Three things:

First, the badgeCount property is called `ios_badgeCount`, not `ios_BadgeCount`. The B is not capitalized.

Second, please tell me you are not issuing this HTTP request from the client right? The API key is basically like a password and should never be used from iOS/Android.

Third, make sure to follow the following guide to set up the OneSignalNotificationServiceExtension and App Groups in your app to let the 'Increase' or 'Decrease' options work.
https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension
https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup

**Comment by josteph** [comment]
@Nightsd01 Thank you for your reply!

Yes, I just realized that it should be `ios_badgeCount` instead. Sorry for holding up your time!
Oh also I'm sending this from backend with PHP.
