### ISSUE TITLE
Change playerID

### ISSUE THREAD

**Issue by nhatquangz** [OneSignal/OneSignal-iOS-SDK#367]
How i can get new playerID for every time app install?
In my app, user login account and receive push(client send playerID to server), everything work well. But if users delete their app and reinstall. They still receive push because my server saved playerID and not be notified about reinstall.
How i can solve this problem?

**Comment by NhatQuangZ** [comment]
"iOS - If the user does not have any other apps installed that have your IFV (Identifier For Vendor), then uninstalling your app and re-installing it, will give them a new Player ID.
The IFV is used to keep the ID the same after a full re-install, but only if the user has another one of your apps installed.
"
https://documentation.onesignal.com/docs/player-id
if device have IFV, it make the same playerID after reinstall
