### ISSUE TITLE
Binary rejected: Non-public API usage: The app references non-public selectors: valueForQueryParameter:

### ISSUE THREAD

**Issue by skuske** [OneSignal/OneSignal-iOS-SDK#369]
The current release of the framework causes binaries being rejected by Apple:

> Non-public API usage:
> The app references non-public selectors: valueForQueryParameter:

Looks like `valueForQueryParameter` is in conflict with a similar private API.

**Comment by skuske** [comment]
@Nightsd01 

Yep, I downgraded and 2.8.2 fixed it.

**Comment by Nightsd01** [comment]
Thanks for letting me know, we’ve released a new update (2.8.4) that should resolve the issue. 

Unless you intend to send iOS media attachment URL’s that don’t end in a file extension (ie .jpg), I wouldn’t stress about uploading another build. Thanks!
