### ISSUE TITLE
Project having OneSignalNotificationServiceExtension does not allow to archive

### ISSUE THREAD

**Issue by iChirag** [OneSignal/OneSignal-iOS-SDK#371]
![screenshot at may 12 15-00-37](https://user-images.githubusercontent.com/3703405/39955975-72b19836-55f5-11e8-8a99-9a3a6d936f6f.png)

Please see attached image, when I am trying to archive project having ios 10.0 SDK deployment & 11.2 SDK in xCode9.2, it gives an error.

However, when I am running in Simulator or iPhone, it does not have any issue.

Can you please help me here. so I can archive the build prior to push on the app store.

**Comment by Nightsd01** [comment]
This would be a cocoapods issue, not an issue with the OneSignal SDK. I would recommend [deleting the Podfile lock](https://github.com/CocoaPods/CocoaPods/issues/2053) and reinstalling pods.

**Comment by kaseyb002** [comment]
Same problem. I set the OneSignalNotificationServiceExtension Target > Deployment Target = 11.4.

**Comment by Nightsd01** [comment]
@kaseyb002 that means the Extension will only work in iOS 11.4. I would suggest setting the deployment target to be either the same as your main app or iOS 10, depending on which is higher (notification extension service will work only in iOS 10 or later).

Also, please make sure to go to project settings, select the OneSignalNotificationServiceExtension target, and navigate to `Build Settings`. Please make sure it contains `arm64`, `armv7`, and `armv7s`

**Comment by kaseyb002** [comment]
Thanks, bumped it down to 11.0
