### ISSUE TITLE
Crash on +[OneSignalHelper downloadMediaAndSaveInBundle:] + 860 (OneSignalHelper.m:896)

### ISSUE THREAD

**Issue by lsj731965675** [OneSignal/OneSignal-iOS-SDK#374]
It crashed on OneSignal-iOS-SDK which I can't see detail codes,I need someone to help.
This is the crash log:

Last Exception Backtrace:
0   CoreFoundation                	0x183c06d8c __exceptionPreprocess + 228 (NSException.m:166)
1   libobjc.A.dylib               	0x182dc05ec objc_exception_throw + 56 (objc-exception.mm:521)
2   CoreFoundation                	0x183c06c6c +[NSException raise:format:] + 116 (NSException.m:141)
3   Foundation                    	0x1845f7f10 _NSFileHandleRaiseOperationException + 160 (NSFileHandle.m:82)
4   Foundation                    	0x1845f8860 -[NSConcreteFileHandle writeData:] + 204 (NSFileHandle.m:728)
5   OneSignalNotificationServiceExtension	0x1011deb88 -[DirectDownloadDelegate connection:didReceiveData:] + 124 (OneSignalHelper.m:83)
6   CFNetwork                     	0x184404308 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 60 (NSURLConnectionInternal.mm:124)
7   CFNetwork                     	0x1844042ac -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 200 (NSURLConnectionInternal.mm:121)
8   CFNetwork                     	0x184404420 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 56 (NSURLConnectionInternal.mm:139)
9   CFNetwork                     	0x1843bbb2c _NSURLConnectionDidReceiveData(_CFURLConnection*, __CFData const*, long, void const*) + 80 (NSURLConnectionInternalConnection.mm:180)
10  CFNetwork                     	0x1842faab4 invocation function for block in URLConnectionClient_Classic::_delegate_didReceiveDataArray() + 256 (URLConnectionClient.cpp:2020)
11  CFNetwork                     	0x1842f9bf4 invocation function for block in URLConnectionClient_Classic::_withDelegateAsync(char const*, void (_CFURLConnection*, CFURLConnectionClientCurrent_VMax const*) block_pointer) + 108 (URLConnectionClient.cpp:0)
12  libdispatch.dylib             	0x1834f8ae4 _dispatch_client_callout + 16 (object.m:507)
13  libdispatch.dylib             	0x1835001f4 _dispatch_block_invoke_direct$VARIANT$mp + 224 (queue.c:3018)
14  CFNetwork                     	0x1843dbc10 RunloopBlockContext::_invoke_block(void const*, void*) + 36 (CoreSchedulingSet.mm:371)
15  CoreFoundation                	0x183acc680 CFArrayApplyFunction + 80 (CFArray.c:684)
16  CFNetwork                     	0x1843dbad0 RunloopBlockContext::perform() + 128 (CoreSchedulingSet.mm:325)
17  CFNetwork                     	0x1843dcc94 MultiplexerSource::perform() + 312 (CFNRunLoopMultiplexer.c:282)
18  CFNetwork                     	0x1843dc9f4 MultiplexerSource::_perform(void*) + 60 (CFNRunLoopMultiplexer.c:47)
19  CoreFoundation                	0x183baf404 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24 (CFRunLoop.c:1982)
20  CoreFoundation                	0x183baec2c __CFRunLoopDoSources0 + 276 (CFRunLoop.c:2017)
21  CoreFoundation                	0x183bac79c __CFRunLoopRun + 1204 (CFRunLoop.c:2920)
22  CoreFoundation                	0x183accda8 CFRunLoopRunSpecific + 552 (CFRunLoop.c:3245)
23  Foundation                    	0x184541674 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304 (NSRunLoop.m:367)
24  Foundation                    	0x18454151c -[NSRunLoop(NSRunLoop) runUntilDate:] + 148 (NSRunLoop.m:411)
25  OneSignalNotificationServiceExtension	0x1011defbc +[NSURLConnection(DirectDownload) downloadItemAtURL:toFile:error:] + 444 (OneSignalHelper.m:111)
26  OneSignalNotificationServiceExtension	0x1011e9238 +[OneSignalHelper downloadMediaAndSaveInBundle:] + 860 (OneSignalHelper.m:896)
27  OneSignalNotificationServiceExtension	0x1011e8528 +[OneSignalHelper addAttachments:toNotificationContent:] + 588 (OneSignalHelper.m:823)
28  OneSignalNotificationServiceExtension	0x1011dd578 +[OneSignal didReceiveNotificationExtensionRequest:withMutableNotificationContent:] + 584 (OneSignal.m:1562)
29  OneSignalNotificationServiceExtension	0x1011d03e8 -[NotificationService didReceiveNotificationRequest:withContentHandler:] + 268 (NotificationService.m:28)
30  UserNotifications             	0x18d68c8b4 -[_UNNotificationServiceExtensionRemoteContext didReceiveNotificationRequest:withCompletionHandler:] + 464 (_UNNotificationServiceExtensionRemoteContext.m:52)
31  Foundation                    	0x18476e960 __NSXPCCONNECTION_IS_CALLING_OUT_TO_EXPORTED_OBJECT_S2__ + 20 (NSXPCConnection.m:145)
32  Foundation                    	0x18456d6d8 -[NSXPCConnection _decodeAndInvokeMessageWithEvent:flags:] + 2428 (NSXPCConnection.m:628)
33  Foundation                    	0x18458fac0 message_handler + 240 (NSXPCConnection.m:706)
34  libxpc.dylib                  	0x183867220 _xpc_connection_call_event_handler + 68 (connection.c:0)
35  libxpc.dylib                  	0x183864bb4 _xpc_connection_mach_event + 984 (connection.c:1203)
36  libdispatch.dylib             	0x1834f8bb4 _dispatch_client_callout4 + 16 (object.m:547)
37  libdispatch.dylib             	0x18350f4c4 _dispatch_mach_msg_invoke$VARIANT$mp + 352 (mach.c:2169)
38  libdispatch.dylib             	0x1835028f0 _dispatch_queue_serial_drain$VARIANT$mp + 280 (inline_internal.h:2539)
39  libdispatch.dylib             	0x18350ff70 _dispatch_mach_invoke$VARIANT$mp + 508 (mach.c:2467)
40  libdispatch.dylib             	0x1835028f0 _dispatch_queue_serial_drain$VARIANT$mp + 280 (inline_internal.h:2539)
41  libdispatch.dylib             	0x183503380 _dispatch_queue_invoke$VARIANT$mp + 336 (queue.c:5290)
42  libdispatch.dylib             	0x183503d4c _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340 (queue.c:5908)
43  libdispatch.dylib             	0x18350c11c _dispatch_workloop_worker_thread$VARIANT$mp + 668 (source.c:2529)
44  libsystem_pthread.dylib       	0x18382be70 _pthread_wqthread + 860 (pthread.c:2218)
45  libsystem_pthread.dylib       	0x18382bb08 start_wqthread + 4

**Comment by Nightsd01** [comment]
@lsj731965675 what version of the SDK are you using...?

**Comment by lsj731965675** [comment]
@Nightsd01 OneSignal 2.5.7

**Comment by Nightsd01** [comment]
@lsj731965675 this crash was fixed a few versions back. Definitely update. Fortunately it was a bug in the extension service so users wouldn’t notice anything but notifications with no images

**Comment by lsj731965675** [comment]
@Nightsd01 If I upgrade the SDK to 2.8.5 does it disappear?

**Comment by Nightsd01** [comment]
@lsj731965675 yes.

**Comment by lsj731965675** [comment]
@Nightsd01 Many thanks！

**Comment by iwheelbuy** [comment]
Still have plenty of crashes on 2.9.5.

```
Thread 1 name:
Thread 1:
0   CoreFoundation                	0x00000001ff0c84c4 CFHash + 308 (CFRuntime.c:1152)
1   CoreFoundation                	0x00000001ff15ca78 CFBasicHashFindBucket + 208 (CFBasicHash.c:465)
2   CoreFoundation                	0x00000001ff15ca78 CFBasicHashFindBucket + 208 (CFBasicHash.c:465)
3   CoreFoundation                	0x00000001ff0c9aa4 CFSetGetValue + 124 (CFSet.c:413)
4   CoreFoundation                	0x00000001ff0bfa98 __CFRunLoopFindMode + 140 (CFRunLoop.c:923)
5   CoreFoundation                	0x00000001ff0bf9c4 _CFRunLoopFinished + 92 (CFRunLoop.c:2581)
6   Foundation                    	0x00000001ffab6438 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 208 (NSRunLoop.m:363)
7   Foundation                    	0x00000001ffab6304 -[NSRunLoop(NSRunLoop) runUntilDate:] + 88 (NSRunLoop.m:411)
8   Aizel Prod One Signal         	0x00000001023a0100 +[NSURLSession(DirectDownload) downloadItemAtURL:toFile:error:] + 448 (OneSignalHelper.m:124)
9   Aizel Prod One Signal         	0x00000001023a44b8 +[OneSignalHelper downloadMediaAndSaveInBundle:] + 680 (OneSignalHelper.m:739)
10  Aizel Prod One Signal         	0x00000001023a3d28 +[OneSignalHelper addAttachments:toNotificationContent:] + 688 (OneSignalHelper.m:642)
11  Aizel Prod One Signal         	0x00000001023ae224 +[OneSignalNotificationServiceExtensionHandler didReceiveNotificationExtensionRequest:withMutable... + 340 (OneSignalNotificationServiceExtensionHandler.m:55)
12  Aizel Prod One Signal         	0x00000001023999d0 +[OneSignal didReceiveNotificationExtensionRequest:withMutableNotificationContent:] + 56 (OneSignal.m:2102)
13  Aizel Prod One Signal         	0x000000010238e4e8 specialized NotificationService.didReceive(_:withContentHandler:) + 468 (<compiler-generated>:16)
14  Aizel Prod One Signal         	0x000000010238e584 @objc NotificationService.didReceive(_:withContentHandler:) + 72 (<compiler-generated>:0)
15  UserNotifications             	0x00000002095dd720 -[_UNNotificationServiceExtensionRemoteContext didReceiveNotificationRequest:withCompletionHandler:] + 464 (_UNNotificationServiceExtensionRemoteContext.m:53)
16  Foundation                    	0x00000001ffcf9df8 __NSXPCCONNECTION_IS_CALLING_OUT_TO_EXPORTED_OBJECT_S2__ + 20 (NSXPCConnection.m:145)
17  Foundation                    	0x00000001ffb05494 -[NSXPCConnection _decodeAndInvokeMessageWithEvent:flags:] + 2396 (NSXPCConnection.m:628)
18  Foundation                    	0x00000001ffcf9f44 message_handler + 240 (NSXPCConnection.m:706)
19  libxpc.dylib                  	0x00000001fed89090 _xpc_connection_call_event_handler + 68 (connection.c:0)
20  libxpc.dylib                  	0x00000001fed893fc _xpc_connection_mach_event + 864 (connection.c:1241)
21  libdispatch.dylib             	0x00000001feb6e544 _dispatch_client_callout4 + 16 (object.m:551)
22  libdispatch.dylib             	0x00000001feb25020 _dispatch_mach_msg_invoke$VARIANT$mp + 340 (mach.c:2147)
23  libdispatch.dylib             	0x00000001feb15a9c _dispatch_lane_serial_drain$VARIANT$mp + 284 (inline_internal.h:2482)
24  libdispatch.dylib             	0x00000001feb25c10 _dispatch_mach_invoke$VARIANT$mp + 476 (mach.c:2456)
25  libdispatch.dylib             	0x00000001feb15a9c _dispatch_lane_serial_drain$VARIANT$mp + 284 (inline_internal.h:2482)
26  libdispatch.dylib             	0x00000001feb1674c _dispatch_lane_invoke$VARIANT$mp + 484 (queue.c:3805)
27  libdispatch.dylib             	0x00000001feb1eeb8 _dispatch_workloop_worker_thread + 600 (queue.c:5889)
28  libsystem_pthread.dylib       	0x00000001fed510dc _pthread_wqthread + 312 (pthread.c:2371)
29  libsystem_pthread.dylib       	0x00000001fed53cec start_wqthread + 4
```
