### ISSUE TITLE
Ability to customize appearance

### ISSUE THREAD

**Issue by Sergozh** [OneSignal/OneSignal-iOS-SDK#376]
Do you have any options to customize appearance when app in focus?

For example:
I use OneSignal.inFocusDisplayType = OSNotificationDisplayType.notification but I need in-app push without sound.

**Comment by Nightsd01** [comment]
Sorry @Sergozh, I didn't notice your question until now.

You can customize the appearance of the notification, but iOS is quite limited.

You can set the `inFocusDisplayType` to be `.none`, and display your own custom UI. However this will only work when the app is open. Note: the `inFocusDisplayType` parameter only applies to when the app is **open**. If your app is closed/background, iOS will display it like it does with all other notifications.

If all you want is to disable sound, you can set the `ios_sound` property to be nil and there will be no sound/vibration for the notification. If you want there to be vibration, you could also possibly include a silent `wav` file.
