### ISSUE TITLE
[OneSignalTrackIAP canTrack] issues

### ISSUE THREAD

**Issue by amosavian** [OneSignal/OneSignal-iOS-SDK#378]
`[OneSignalTrackIAP canTrack]` method causes memory leak. (a `dispatch_semaphore_t` object detectable in Xcode memgraph)

Furthermore while this method is horribly slow and blocking. it is called in `initWithOptions:` method which dramatically increases my app startup time.

Please remove this function if possible.

**Comment by Nightsd01** [comment]
@amosavian In our profiling, `canTrack` isn't slow. It takes 18ms to complete. All it does is calls a selector on SKPaymentQueue (if it is defined in your project). It _does_ use reflection, which would slow things down a bit, but it should not be _significantly_ slow.

Also, we believe this leak is a bug with StoreKit, not with OneSignal. The leak is only 80 bytes, and will only ever occur one time throughout the lifetime of the app. We do plan to dig deeper into this bug but at the moment we have more pressing concerns.

If you believe OneSignal is causing a slowdown in your app, I'd like to help. Can you send us your instruments trace?

**Comment by amosavian** [comment]
Maybe it's only observable on slow connections. Thanks by the way I swizzled this method with mine.
