### ISSUE TITLE
Why swizzling?

### ISSUE THREAD

**Issue by onmyway133** [OneSignal/OneSignal-iOS-SDK#38]
Hi, this SDK is good. I just wonder why you decide to do the swizzling upon the app delegate? 

We can just explicitly call the relevant methods in the app delegate methods though. 

Firebase allows us to toggle this swizzling, but I think swizzling is not a good idea. What do you think?

**Comment by felixLam** [comment]
+1

**Comment by jkasten2** [comment]
We aim to make our SDK as easy to setup as possible. Swizzling insures everything is setup correctly without the need to add code into all the required app delegate methods. This makes the upgrade process easier as well when Apple makes chances. Lastly it makes it easier for us and the community to add this native SDK to other plugins such as Unity, Cordova, React Native, etc.

Our swizzling code has been well tested to not interfere with other SDK/plugins or your own AppDelegate code. Our SDK ensures the original method is called. Feel free to open another github issue if swizzling is creating any issue for you.
