### ISSUE TITLE
What is OneSignal-Dynamic?

### ISSUE THREAD

**Issue by Grape-from-kai** [OneSignal/OneSignal-iOS-SDK#386]
hi
i use OneSignal-iOS-SDK, carthage instead of cocoapod.
i want to upload myapp to AppStore.

but I got messages "ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value `com.onesignal.OneSignal-Dynamic` under the application `myapp.app` "

**Comment by Nightsd01** [comment]
`OneSignal-Dynamic` is our dynamic framework.

This error indicates that you are somehow including our SDK in your project twice. 

How did you integrate our SDK in your project?

**Comment by Nightsd01** [comment]
Closing due to no response - I assume you managed to figure out how the framework was duplicated in your project. 

Please feel free to respond if you are still encountering this issue and I'll be happy to reopen & investigate

**Comment by Rejiz** [comment]
> Closing due to no response - I assume you managed to figure out how the framework was duplicated in your project.
> 
> Please feel free to respond if you are still encountering this issue and I'll be happy to reopen & investigate

i would like you can helpme to solve the same issue of him, i cant send the app to validate couse has the same problem.

**Comment by karambir8827** [comment]
@Nightsd01 had the same error with same bundle com.onesignal.OneSignal-Dynamic that cause my apps crash. 

my third party is using [iOS OneSignal SDK](https://github.com/OneSignal/OneSignal-iOS-SDK) - ^3.11.2 

In my third party platforms/ios/Podfile ,I change from pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0' to pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'

then run this and i face this error

Please help me
