### ISSUE TITLE
HELLP

### ISSUE THREAD

**Issue by ahmad853** [OneSignal/OneSignal-iOS-SDK#388]
hi

I have two errors in building the application in xcode9 - OneSignal notifications
1- error (used a similar IDD for both purposes but I have a error)

error: Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.Embedded Binary Bundle Identifier: com.iplus85firebase.store.OneSignalNotificationServiceExtensionParent App Bundle Identifier: com.iplus85onesignal.store

2-ERROR

No such module 'OneSignal' IN (AppDelegate.swift +NotificationService.swift)

I AM INSTALL COCOAPODS
I AM CREAT PodfilE

**Comment by Nightsd01** [comment]
Hi @ahmad853,

This means that, somehow, your project wasn’t able to link to the OneSignal SDK correctly. 

Can you copy+paste your Podfile?

**Comment by Nightsd01** [comment]
Assuming you managed to fix the issue.....closing. Please feel free to reply if not and we’ll be happy to reopen and help you.
