### ISSUE TITLE
'IdsAvailable:' is deprecated

### ISSUE THREAD

**Issue by tysun** [OneSignal/OneSignal-iOS-SDK#389]
`[OneSignal IdsAvailable:^(NSString *userId, NSString *pushToken)
	{
		if (pushToken != nil)
			[UserDefaults setObject:userId forKey:ONESIGNALID];
		else [UserDefaults removeObjectForKey:ONESIGNALID];
		UpdateOneSignalId();
	}];`

**Xcode warning:** _'IdsAvailable:' is deprecated: Please use getPermissionSubscriptionState or addSubscriptionObserver and addPermissionObserver instead_

iOS 11.0
pod 'OneSignal', '>= 2.6.2', '< 3.0'

**Comment by Nightsd01** [comment]
@tysun it means what it says. `IdsAvailable` is deprecated. You can use `getPermissionsubscriptionState` to get the user ID instead.
