### ISSUE TITLE
Badge number not auto increase, it's always 1

### ISSUE THREAD

**Issue by nvduc2910** [OneSignal/OneSignal-iOS-SDK#392]
I already set 
"ios_badgeType" : "Increase",
"ios_badgeCount" : 1

then I try to push 10 times but badge number always 1. please check . 

Thank you so much.

**Comment by pophoba** [comment]
same here

**Comment by Nightsd01** [comment]
@nvduc2910 Did you add the notification service extension, and set up an app group for your app + extension?

https://documentation.onesignal.com/docs/ios-sdk-setup

**Comment by pophoba** [comment]
Yes done all of that and when other party send message it work and show “1” but when send anther the badge didnot increment show 1 all the time

**Comment by Nightsd01** [comment]
@pophoba If you send a push notification with an image, does the image show up on the notification?

**Comment by pophoba** [comment]
I do not try i use it my chat application normal scenario  that when you got new message you got a push notification including sender name and message body  “ working fine “ and the app get 1 badge “ already done “ and when push voice sinch call it send a notification “ working fine “ but when you got anther  push every thing working fine except the badge it stay 1 and did not increment  

All the problem not in the push it self only the badge number

**Comment by Nightsd01** [comment]
@pophoba I understand that, I am asking you to send a push notification with an image just as a test, so we can make sure the extension service is actually working. 

The extension service handles the badge logic, so if an image doesn’t show up, we know it’s a problem with the extension service.

**Comment by Nightsd01** [comment]
@pophoba this would definitely be an issue with your extension service then, it means it’s not getting launched. 

Can you try carefully running through our Extension Service setup guide, and follow the App Group setup guide, just to make sure you didn’t miss anything?

https://documentation.onesignal.com/docs/ios-sdk-setup

**Comment by pophoba** [comment]
Ok i will try to review the steps again .

**Comment by Nightsd01** [comment]
@pophoba glad to hear it! Feel free to ask if you run into any other problems

**Comment by pophoba** [comment]
Thank you very much

**Comment by ducnv2910** [comment]
I don't setup  Notification Service Extension so do you think that is problem?

**Comment by ducnv2910** [comment]
it's working now.

**Comment by LumiProj** [comment]
Hi,

I am having the same issue but with Xamarin forms. Can you please the same extension for c#
