### ISSUE TITLE
Delete / Cancel notifications before they are sent

### ISSUE THREAD

**Issue by arguiot** [OneSignal/OneSignal-iOS-SDK#393]
**Description:**

It would be extremely nice to have a method called `cancelNotification(id: String)` that could cancel notifications before they are sent. The server API already supports this kind of operations: https://documentation.onesignal.com/reference#cancel-notification

**Environment**

I'm using the latest version of the iOS SDK, and I'm using Carthage: 
```
github "OneSignal/OneSignal-iOS-SDK"
```

**Steps to Reproduce Issue:**

Well, they are no steps as this is a feature request
**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Nightsd01** [comment]
@arguiot Thanks for your request, it's a good idea and we'll take a look at it. We usually recommend handling notification scheduling & cancellation logic on a backend server, but many users do a lot of this stuff on the client so we've tried to make it as easy as possible.

**Comment by Nightsd01** [comment]
So after considering this a bit more, the server API to cancel a notification requires the REST API key, which you would _not_ want to use client-side for security reasons. The REST API key is essentially a password and you don't want it in your iOS app. You would definitely want to call this API from a backend server, not the client.

**Comment by arguiot** [comment]
And do you think you or one of your colleagues could add the support of this feature on OneSignal's server for the client side? Because of what I understand the issue is more on your side than on the client side right?
