### ISSUE TITLE
method in notification extension not called

### ISSUE THREAD

**Issue by chenkuanhuaian** [OneSignal/OneSignal-iOS-SDK#395]
**Description:**

so i followed the setup tutorial but doesn't work as expected.

the problem is when I send a remote push notification, it does not trigger Notification Service Extension methods.

Steps: 

1. placed breakpoint in didReceive method

2. run the project target on a device

3. send a notification 

4. attached extension process 

5. send a remote notification again

6. notification shows ( but not modified as expected, I replace the title string )

7. extension process crashed (?) with error " Thread 1: signal SigKill"

just like this SO question 

https://stackoverflow.com/questions/49511005/cant-attach-debugger-to-unnotificationserviceextension

I also tried to run the extension target 

when received the remote notification, Xcode shows an warning window says

"could not attach to pid: ensure is not already running and has permission to debug it"

I think it's because the Xcode setting but not sure which one.

please help :(

**Environment**

**Steps to Reproduce Issue:**

Steps: 

1. placed breakpoint in didReceive method

2. run the project target on a device

3. send a notification 

4. attached extension process 

5. send a remote notification again

6. notification shows ( but not modified as expected, I replace the title string )

7. extension process crashed (?) with error " Thread 1: signal SigKill"

**Anything else:**

(crash stacktraces, as well as any other information here)

*I did enable mutable-content to be 1 *

when i look into system log it says

"OneSignalNotificationServiceExtensionDev] Extension will be killed due to sluggish startup
"

**Comment by Nightsd01** [comment]
@chenkuanhuaian Unfortunately it can be quite difficult to attach the Xcode debugger to an extension, it is more of an art than a science. It can take many attempts.

Can you post a link to your `NotificationService.m`?

Also, what kind of attachment are you sending? Keep in mind that if you are sending a large attachment, this can happen because it takes too long to download and the system will terminate the extension.

**Comment by Nightsd01** [comment]
@chenkuanhuaian Can you please post your full `NotificationService.swift`?

Also, how did you add onesignal as a dependency to the extension service, cocoapods?

**Comment by chenkuanhuaian** [comment]
https://gist.github.com/chenkuanhuaian/62989e404f6e00f04085c78921bca3b9

line 17 is the only line I added to the `NotificationService.swift` as I mentioned.

and yes, I am using cocoapods

thanks for helping, been working on this for over 3 days :(

**Comment by Nightsd01** [comment]
@chenkuanhuaian It’s the weekend but I know how frustrating that must be so I’ll keep looking into it with you. 

What is your deployment target for the Extension service?

Could you share your Podfile?

Also, if you comment out the OneSignal related code from `NotificationService.swift`, does it modify the title or still not launch? This will help narrow down what’s causing the issue.

**Comment by chenkuanhuaian** [comment]
I appreciate that ! thanks for replying on weekend.
deployment target for the Extension service and my project is both iOS 10, 
I read some SO questions saying that it has to be iOS 10 so i did so, but still...

here's my podifle gist 
https://gist.github.com/chenkuanhuaian/6e704e69b4b85cf962269ac82aa2e660

When I comment out the OneSignal Related Code, the extension is still not launched.

I do get notifications and notification related delegate method in appDelegate are called.
(I think if I have mutable-content = 1, it should goes into the extension rather than appDelegate, 
 but my extension is kill by OS so... )

Yeah I should tell my environment in the first place,
I am building with Xcode 9.4.1 on iOS 11.4.1 device (iPhone 8 plus) if that matters.

Again, thanks for helping me out,
I've been follow the setup tutorial and other extension tutorial several times,
asked my senior developer fellows but apparently no one has encounter this before. :(

**Comment by avadhutredekar** [comment]
@chenkuanhuaian @Nightsd01 I am also facing the exact same issue.

**Comment by chenkuanhuaian** [comment]
Good to know I’m not the only one.
I don’t know why people have no problem dealing with application extension....
Makes me feel I’m an idiot lol

**Comment by Nightsd01** [comment]
@chenkuanhuaian I think I see what the issue is. App extensions are memory limited. The system won’t grant them much memory. 

Looking at your pod file, it looks like the extension service is a member of `myProject` and it gets all pods installed into it from the `pods` group?

I would suggest making the `OneSignalNotificationServiceExtension` target a top level target and make sure it ONLY gets OneSignal installed. 

If that doesn’t fix it let me know

**Comment by chenkuanhuaian** [comment]
Good Point!

But by `extension service is a member of myPorject`, what do you mean exactly?

As far as I know, application extension is independent from other targets ?
since I do 
```
target 'OSNotificationExtension' do
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
  end
```
In my podfile, I thought OneSignal is the only pod I installed to OSNotificationExtension target right ?

does this help ??
```
target 'myPorject_iOS' do
  pods

  target 'myPorject_iOS_Dev' do
    pods
  end

  target 'myPorject_iOSTests' do
    inherit! :search_paths
    testPods
  end

  target 'myPorject_iOSUITests' do
    inherit! :search_paths
    testPods
  end

end

target 'OSNotificationExtension' do
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
 end
```

thanks for replying :)

**Comment by chenkuanhuaian** [comment]
OMG, that Worked !!!!!!!!!!!!!!!!!!!!!!!
OMG, You just saved my life. 
I didn't even noticed that i place my extension target in the wrong scope.
You are the Sweetest human being on this planet.
You Rock 🥇 
thank you, thank you and thank you!!!!!!!!!!! <3 <3 <3
now I could finally sleep tight :D

**Comment by Nightsd01** [comment]
Glad to hear it! Little misconfigurations with Cocoapods like this can be time consuming to debug. Feel free to ask if you have any other problems

**Comment by vinayak-nickelfox** [comment]
@Nightsd01 Can you or anyone help me to resolve this issue. I wanted to show attached image in the notification but it's not displayed in the notification despite attaching image in the payload along with mutable-content: 1
