### ISSUE TITLE
Don't understand why multiple PlayerID for one user on same device

### ISSUE THREAD

**Issue by Droppix** [OneSignal/OneSignal-iOS-SDK#399]
Hi,

Each time, in the dashboard, I notice, 4 or 5 lines with a different **playerid**, which is impossible, since I use a single device and a single user. (see exported CSV)

Do you have an idea of what's happen?

`
  subscribed,last_active,first_session,channel,device,sessions,player_id,tags,app_version,country,rooted,lat,lon,usage_duration,language_code
Yes,2018-08-17 09:03:09.000000,2018-08-17 09:03:09.333417,iOS,"iPhone10,6 11.4.1",1,1ab2f3d0-b689-466c-XXXX-XXXXXXXXXXXX,{},9364,FR,No,,,0,fr
Yes,2018-08-17 09:25:16.000000,2018-08-17 09:25:16.641721,iOS,"iPhone10,6 11.4.1",1,2affb108-9c73-4ca1-XXXX-XXXXXXXXXXXX,{},9366,FR,No,,,0,fr
Yes,2018-08-17 09:03:39.000000,2018-08-17 09:03:39.311700,iOS,"iPhone10,6 11.4.1",1,55cf5176-1342-43da-XXXX-XXXXXXXXXXXX,"{""customerID"": ""72181""}",9364,FR,No,,,0,fr
Yes,2018-08-17 09:25:46.000000,2018-08-17 09:25:46.223726,iOS,"iPhone10,6 11.4.1",1,6420a627-cbd5-4bed-XXXX-XXXXXXXXXXXX,{},9366,FR,No,48.83456476229,2.38680530260833,0,fr
Yes,2018-08-17 09:05:01.000000,2018-08-17 09:05:01.809651,iOS,"iPhone10,6 11.4.1",1,81dc1fce-e2d6-4b72-XXXX-XXXXXXXXXXXX,{},9364,FR,No,,,0,fr
`

**Environment**
1/ I use the last version of onesignal SDK (compiled with carthage)
2/ XCode 9
3/ iOS 11.4.1

**Steps to Reproduce Issue:**
1/ Initialization
`

     func application(_ application: UIApplication, 
                                    didFinishLaunchingWithOptions launchOptions:  
                                           [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

        let onesignalInitSettings = [kOSSettingsKeyAutoPrompt: false]
        OneSignal.initWithLaunchOptions(launchOptions,
                                        appId: ONESIGNEL_APIKEY,
                                        handleNotificationAction: nil,
                                        settings: onesignalInitSettings)

        OneSignal.inFocusDisplayType = OSNotificationDisplayType.notification;
      }

2/ After user authentication

       OneSignal.promptForPushNotifications(userResponse: { accepted in
            
        })

        OneSignal.setEmail(email);
        OneSignal.sendTag("customerID", value: "\(customerId)")
`

Regards

**Comment by Nightsd01** [comment]
@Droppix When you call `setEmail:`, this is actually creating a separate `playerId` in our system. They're linked, any calls to something like `setTags:` will work for both accounts, but internally the email and push notification subscriptions are treated as separate accounts.

As far as why you're seeing 4, you likely uninstalled and reinstalled the app at some point. Unless you are using the advertising ID, this means a new player ID would get assigned.
