### ISSUE TITLE
registerForPushNotifications from different VC

### ISSUE THREAD

**Issue by skiddle** [OneSignal/OneSignal-iOS-SDK#40]
Hi

We are initialising oneSignal within our AppDelegate, but wish to register for push from an onboarding viewcontroller

As it seems we need to call 'registerForPushNotifications' on an instance of the oneSignal class (rather than a Singleton), I presume we're going to have to reference the appDelegate instance, rather than creating a completely new instance within the onboarding VC?

**Comment by jkasten2** [comment]
@skiddle You can store the OneSignal instance as a static on one of your class or use the `defaultClient` static method on OneSignal.
Example Swift:
```Swift
OneSignal.defaultClient()
```

Example Objective-C:
```Objective-C
[OneSignal defaultClient]
```
