### ISSUE TITLE
Got stuck when onesignal init

### ISSUE THREAD

**Issue by bank18651** [OneSignal/OneSignal-iOS-SDK#405]
**Description:**
I found sometime I got stuck on `OneSignal.initWithLaunchOptions` 
It seem like a main thread stuck. I also debug it by adding breakpoint after onesignal init if it got stuck it is not come to this break point.
Is it have any libraries affect to onesignal?
`
def shared_pod
    # Networking
    pod 'Alamofire'

    # Fabric
    pod 'Fabric'
    pod 'Crashlytics'

    # Firebase
    pod 'Firebase'
    pod 'Firebase/Auth', '5.0.1'
    pod 'Firebase/RemoteConfig'
    pod 'GoogleSignIn', '4.1.2'
    pod 'Firebase/Core'
	pod 'Firebase/MLVision'
	pod 'Firebase/MLVisionBarcodeModel'

	# Maps
	pod 'GoogleMaps'
	pod 'GooglePlaces'
	pod 'PlotPlugin'

    # Facebook
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'

    # Customer Support
    pod 'FreshchatSDK'

    # Analytics
    pod 'GoogleAnalytics'
    pod 'AppsFlyerFramework'
    pod 'NewRelicAgent'

    # Payment gateways
    pod 'Braintree'
    pod 'MidtransCoreKit', '1.0.9'

    # Image handling
    pod 'ImgixSwift'
    pod 'SDWebImage', '~> 4.0'

    # Notifications
    pod 'OneSignal', '>= 2.5.2', '< 3.0'

    # Search
    pod 'AlgoliaSearch-Client-Swift'

    # Extras
    pod 'SwifterSwift'
    pod 'SwiftSpinner'
    pod 'SRMonthPicker'
    pod 'ObjectMapper', '~> 3.1'
    pod 'IQKeyboardManagerSwift'
    pod 'R.swift'
    pod 'i18next'
end
`

**Environment**
iOS 11.4.1 OneSignal (2.8.6)
cocoapods

**Comment by Nightsd01** [comment]
Generally iOS will terminate any apps that block the main thread for a certain amount of time, so you should be getting a stacktrace indicating what is blocking the main thread?

Can you share the output of the logs in your app?

If you _remove_ our SDK and run `pod install`, does your app still hang?

**Comment by bank18651** [comment]
We're using Cocoapods.

<img width="665" alt="screen shot 2561-08-29 at 10 30 25 am" src="https://user-images.githubusercontent.com/5292061/44764015-d05cca00-ab77-11e8-9f8c-05779fd58b68.png">

`Pomelo`+[OneSignalTrackIAP canTrack]:
    0x10e13fec0 <+0>:   pushq  %rbp
    0x10e13fec1 <+1>:   movq   %rsp, %rbp
    0x10e13fec4 <+4>:   subq   $0x20, %rsp
    0x10e13fec8 <+8>:   leaq   0x415a51(%rip), %rax      ; @"SKPaymentQueue"
    0x10e13fecf <+15>:  movq   %rdi, -0x8(%rbp)
    0x10e13fed3 <+19>:  movq   %rsi, -0x10(%rbp)
    0x10e13fed7 <+23>:  movq   %rax, %rdi
    0x10e13feda <+26>:  callq  0x10e144ff2               ; symbol stub for: NSClassFromString
    0x10e13fedf <+31>:  xorl   %ecx, %ecx
    0x10e13fee1 <+33>:  movb   %cl, %dl
    0x10e13fee3 <+35>:  movq   %rax, 0x70b086(%rip)      ; skPaymentQueue
    0x10e13feea <+42>:  cmpq   $0x0, 0x70b07e(%rip)      ; started + 6
    0x10e13fef2 <+50>:  movb   %dl, -0x11(%rbp)
    0x10e13fef5 <+53>:  je     0x10e13ff44               ; <+132> at OneSignalTrackIAP.m:50
    0x10e13fef7 <+55>:  movq   0x70b072(%rip), %rdi      ; skPaymentQueue
    0x10e13fefe <+62>:  movq   0x6525e3(%rip), %rdx      ; "canMakePayments"
    0x10e13ff05 <+69>:  movq   0x63653c(%rip), %rsi      ; "respondsToSelector:"
    0x10e13ff0c <+76>:  callq  0x10e148208               ; symbol stub for: objc_msgSend
    0x10e13ff11 <+81>:  xorl   %ecx, %ecx
    0x10e13ff13 <+83>:  movb   %cl, %r8b
    0x10e13ff16 <+86>:  testb  $0x1, %al
    0x10e13ff18 <+88>:  movb   %r8b, -0x11(%rbp)
    0x10e13ff1c <+92>:  jne    0x10e13ff20               ; <+96> at OneSignalTrackIAP.m:50
    0x10e13ff1e <+94>:  jmp    0x10e13ff44               ; <+132> at OneSignalTrackIAP.m:50
    0x10e13ff20 <+96>:  movq   0x70b049(%rip), %rdi      ; skPaymentQueue
    0x10e13ff27 <+103>: movq   0x6525ba(%rip), %rdx      ; "canMakePayments"
    0x10e13ff2e <+110>: movq   0x639843(%rip), %rsi      ; "performSelector:"
    0x10e13ff35 <+117>: callq  0x10e148208               ; symbol stub for: objc_msgSend
    **0x10e13ff3a <+122>: cmpq   $0x0, %rax**
    0x10e13ff3e <+126>: setne  %cl
    0x10e13ff41 <+129>: movb   %cl, -0x11(%rbp)
    0x10e13ff44 <+132>: movb   -0x11(%rbp), %al
    0x10e13ff47 <+135>: andb   $0x1, %al
    0x10e13ff49 <+137>: movzbl %al, %eax
    0x10e13ff4c <+140>: addq   $0x20, %rsp
    0x10e13ff50 <+144>: popq   %rbp
    0x10e13ff51 <+145>: retq   `

`Pomelo`+[OneSignal initWithLaunchOptions:appId:handleNotificationAction:settings:]:
    0x10e10a900 <+0>:   pushq  %rbp
    0x10e10a901 <+1>:   movq   %rsp, %rbp
    0x10e10a904 <+4>:   subq   $0x80, %rsp
    0x10e10a90b <+11>:  movq   %rdi, -0x8(%rbp)
    0x10e10a90f <+15>:  movq   %rsi, -0x10(%rbp)
    0x10e10a913 <+19>:  movq   $0x0, -0x18(%rbp)
    0x10e10a91b <+27>:  leaq   -0x18(%rbp), %rsi
    0x10e10a91f <+31>:  movq   %rsi, %rdi
    0x10e10a922 <+34>:  movq   %rsi, -0x38(%rbp)
    0x10e10a926 <+38>:  movq   %rdx, %rsi
    0x10e10a929 <+41>:  movq   %r8, -0x40(%rbp)
    0x10e10a92d <+45>:  movq   %rcx, -0x48(%rbp)
    0x10e10a931 <+49>:  movq   %r9, -0x50(%rbp)
    0x10e10a935 <+53>:  callq  0x10e14826e               ; symbol stub for: objc_storeStrong
    0x10e10a93a <+58>:  movq   $0x0, -0x20(%rbp)
    0x10e10a942 <+66>:  leaq   -0x20(%rbp), %rcx
    0x10e10a946 <+70>:  movq   %rcx, %rdi
    0x10e10a949 <+73>:  movq   -0x48(%rbp), %rsi
    0x10e10a94d <+77>:  movq   %rcx, -0x58(%rbp)
    0x10e10a951 <+81>:  callq  0x10e14826e               ; symbol stub for: objc_storeStrong
    0x10e10a956 <+86>:  movq   $0x0, -0x28(%rbp)
    0x10e10a95e <+94>:  leaq   -0x28(%rbp), %rcx
    0x10e10a962 <+98>:  movq   %rcx, %rdi
    0x10e10a965 <+101>: movq   -0x40(%rbp), %rsi
    0x10e10a969 <+105>: movq   %rcx, -0x60(%rbp)
    0x10e10a96d <+109>: callq  0x10e14826e               ; symbol stub for: objc_storeStrong
    0x10e10a972 <+114>: movq   $0x0, -0x30(%rbp)
    0x10e10a97a <+122>: leaq   -0x30(%rbp), %rcx
    0x10e10a97e <+126>: movq   %rcx, %rdi
    0x10e10a981 <+129>: movq   -0x50(%rbp), %rsi
    0x10e10a985 <+133>: movq   %rcx, -0x68(%rbp)
    0x10e10a989 <+137>: callq  0x10e14826e               ; symbol stub for: objc_storeStrong
    0x10e10a98e <+142>: movq   -0x8(%rbp), %rdi
    0x10e10a992 <+146>: movq   -0x18(%rbp), %rdx
    0x10e10a996 <+150>: movq   -0x20(%rbp), %rcx
    0x10e10a99a <+154>: movq   -0x28(%rbp), %r9
    0x10e10a99e <+158>: movq   -0x30(%rbp), %rsi
    0x10e10a9a2 <+162>: movq   0x6870b7(%rip), %r8       ; "initWithLaunchOptions:appId:handleNotificationReceived:handleNotificationAction:settings:"
    0x10e10a9a9 <+169>: movq   %rsp, %rax
    0x10e10a9ac <+172>: movq   %rsi, (%rax)
    0x10e10a9af <+175>: movq   0x39461a(%rip), %rax      ; (void *)0x0000000116b31980: objc_msgSend
    0x10e10a9b6 <+182>: xorl   %r10d, %r10d
    0x10e10a9b9 <+185>: movl   %r10d, %esi
    0x10e10a9bc <+188>: movq   %rsi, -0x70(%rbp)
    0x10e10a9c0 <+192>: movq   %r8, %rsi
    0x10e10a9c3 <+195>: movq   -0x70(%rbp), %r8
    0x10e10a9c7 <+199>: callq  *%rax
    **0x10e10a9c9 <+201>: movq   %rax, %rdi**
    0x10e10a9cc <+204>: callq  0x10e14823e               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x10e10a9d1 <+209>: movq   -0x68(%rbp), %rdi
    0x10e10a9d5 <+213>: movq   -0x70(%rbp), %rsi
    0x10e10a9d9 <+217>: movq   %rax, -0x78(%rbp)
    0x10e10a9dd <+221>: callq  0x10e14826e               ; symbol stub for: objc_storeStrong
    0x10e10a9e2 <+226>: movq   -0x60(%rbp), %rdi
    0x10e10a9e6 <+230>: movq   -0x70(%rbp), %rsi
    0x10e10a9ea <+234>: callq  0x10e14826e               ; symbol stub for: objc_storeStrong
    0x10e10a9ef <+239>: movq   -0x58(%rbp), %rdi
    0x10e10a9f3 <+243>: movq   -0x70(%rbp), %rsi
    0x10e10a9f7 <+247>: callq  0x10e14826e               ; symbol stub for: objc_storeStrong
    0x10e10a9fc <+252>: movq   -0x38(%rbp), %rdi
    0x10e10aa00 <+256>: movq   -0x70(%rbp), %rsi
    0x10e10aa04 <+260>: callq  0x10e14826e               ; symbol stub for: objc_storeStrong
    0x10e10aa09 <+265>: movq   -0x78(%rbp), %rdi
    0x10e10aa0d <+269>: addq   $0x80, %rsp
    0x10e10aa14 <+276>: popq   %rbp
    0x10e10aa15 <+277>: jmp    0x10e14818a               ; symbol stub for: objc_autoreleaseReturnValue`

**Comment by Nightsd01** [comment]
@bank18651 Thank you for the details! We've seen extremely rare, isolated reports of this issue with StoreKit but we've never been able to reproduce it ourselves.
 
I have a few questions for you:

1. What version/s of iOS does this hang on?
2. Can you run `pod update` and verify you have the latest version of our SDK?
3. Does this issue occur on both simulator and actual iOS devices?
4. This is from a debug build, right?

**Comment by bank18651** [comment]
1. What version/s of iOS does this hang on?
OneSignal (2.8.6)
2. Can you run pod update and verify you have the latest version of our SDK?
Yes, I try to reinstall pod and also try to pod update
3. Does this issue occur on both simulator and actual iOS devices?
both
4. This is from a debug build, right?
Yes

I found memory leak. Can you check this please?

![screen shot 2561-08-31 at 07 25 03](https://user-images.githubusercontent.com/5292061/44886295-bf36c900-acef-11e8-8129-5fb1d35d4502.png)

![screen shot 2561-08-30 at 20 51 26](https://user-images.githubusercontent.com/5292061/44886320-d2e22f80-acef-11e8-804b-408f78c164cd.png)

**Comment by Nightsd01** [comment]
@bank18651 there is already an existing issue both for the leak and for the hang/crash in regards to StoreKit. We have reviewed the code in question and at this point we are quite confident that this is actually a bug in StoreKit. 

However we’ve only ever seen reports of this issue happening on App Review devices, we’ve never seen a developer who could reproduce the issue themselves, so this is super interesting. 

If possible, would you be able to provide a sample project that reproduces this issue? You can also go to our dashboard and send a message to us through support and send us your project privately (I’ll get the message).

**Comment by Nightsd01** [comment]
As far as the leak goes, it’s non-recurring and only uses up 80 bytes, it would not be the cause of the hang

**Comment by BennyTheNerd** [comment]
I started having the same issue on a live app. This is killing my business right now. We're getting all sorts of complaints about the app freezing upon launch. ... turns out it's OneSignal.init where it's freezing

**Comment by Nightsd01** [comment]
@BennyTheNerd we haven’t made any major changes to the SDK recently that would cause such an issue...or even make it more likely. 

The issues the above users are describing are not new and have been so rare that we’ve never been able to reproduce. 

Since there are so many issues that can cause this behavior, it’s hard to say that your users are seeing the same issue without crash reports. iOS will kill apps that freeze the main thread and should be sending you crash reports with stack frames. Can you please post some of those?

**Comment by Nightsd01** [comment]
@siburb if you encountered this issue in 2.8.5 you’ll likely still encounter it in 2.8.7 as we have not made major changes to how the SDK initializes, so I wouldn’t recommend updating your app just for this. I’ll investigate this issue today and will get back to you shortly - it would be good if you could open a new issue for this as it’s not related to StoreKit

**Comment by BennyTheNerd** [comment]
@Nightsd01 

I did update the OneSignal pod in our iOS app, to 2.8.7. Previously it was on 2.8.5. This did not solve anything. The app would still not get passed the OneSignal.init line, and the app would not open at all. 

When I woke up this morning, I had multiple reports from users that their app was now magically working on their phones. Meaning, OneSignal.init started magically working again.

Attached are the logs:

[OneSignal_Bug_Init.txt](https://github.com/OneSignal/OneSignal-iOS-SDK/files/2341252/OneSignal_Bug_Init.txt)

**Comment by Nightsd01** [comment]
@siburb that's definitely a thread synchronization issue. It looks to be extremely rare but does happen. Thanks for posting it! I will be creating another issue for that deadlock since it is unrelated to this storekit issue.

**Comment by Nightsd01** [comment]
@bank18651 Thank you a bunch for reporting this but because both issues you mention (the 80 byte leak and the main thread hang on init) are both already existing issues (#248 and #20).

We've never seen an actual developer/user encounter this crash in the wild, so this definitely motivates some deeper investigation and I'll keep you updated.

**Comment by revolter** [comment]
I can successfully reproduce the hang in `-[OneSignalNotificationSettingsIOS10 getNotificationPermissionState] at /Users/bradhesse/onesignal/OneSignal-iOS-SDK/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m:93` that @siburb also mentioned. For us, it only happens on an iPhone 6 Plus and an iPad Mini, both the oldest and slowest devices we have.
