### ISSUE TITLE
Deadlock on Main Thread

### ISSUE THREAD

**Issue by Nightsd01** [OneSignal/OneSignal-iOS-SDK#407]
This is an issue reported by @siburb in a different issue but because it's a different crash that warrants further investigation, I will be creating a separate issue for it here:

@siburb wrote:
---
I'm getting an occasional, but often enough to be a problem hang too - slightly different stack trace. Was on v2.8.5 of the SDK, but will update to the latest and see if that's any better.

![image](https://user-images.githubusercontent.com/1744275/44892566-0b95ff00-ad18-11e8-8d02-b6683f9d6761.png)
---

**Comment by siburb** [comment]
Thanks for letting us know. Any idea of an ETA for the new version?

**Comment by siburb** [comment]
We don't have the new version yet - any news?

**Comment by revolter** [comment]
When does this happen? It is indirectly caused by a bug in Apple's `getNotificationSettingsWithCompletionHandler:` method?
