### ISSUE TITLE
Omit firing handleNotification for non-OneSignal payloads

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-iOS-SDK#41]
The block passed to `handleNotification` on `initWithLaunchOptions` fires for non-OneSignal notifications. The payload should be check for OneSignal fields before firing the block.

**Comment by JKalash** [comment]
Resolved as of [2.0.8](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.0.8)
