### ISSUE TITLE
providesAppNotificationSettings authorisation option is overridden by OneSignal init

### ISSUE THREAD

**Issue by siburb** [OneSignal/OneSignal-iOS-SDK#413]
**Description:**

We've been trying to implement the new "notification settings" deep link in iOS12, and one of the requirements to doing so is adding `providesAppNotificationSettings` as an option when requesting authorization (or `UNAuthorizationOptionProvidesAppNotificationSettings` in ObjC).

Testing, we found that the option was correctly added by us, but then as soon as we init the OneSignal SDK, it is overridden and the option is no longer present.

A work around is re-requesting authorisation immediately after initialising the OneSignal SDK - this doesn't seem to stop the SDK from doing its thing - but is obviously not ideal.

**Environment**

SDK v2.8.8
iOS12 RC built from Xcode 10 RC

**Steps to Reproduce Issue:**

1. Install iOS SDK version 2.8.8 with Cocoapods into a project
2. Request notification authorization from UNNotificationCenter including the new `UNAuthorizationOptionProvidesAppNotificationSettings`.
3. In the completion handler, check `UNNotificationSettings` for the `providesAppNotificationSettings` property - will now be "YES".
4. In the same completion handler, init the OneSignal SDK.
5. Check `UNNotificationSettings` for the `providesAppNotificationSettings` property - will now be "NO".

**Comment by Nightsd01** [comment]
@siburb thanks for reporting this! I’ll investigate and will get back to you shortly

**Comment by Nightsd01** [comment]
Hey @siburb, I've added a new `kOSSettingsKeyProvidesAppNotificationSettings` initialization settings parameter. If set to `true`, the SDK will handle registering this authorization for you. 

https://github.com/OneSignal/OneSignal-iOS-SDK/commit/c9f563c1ecc2bf618e3dd91814c32cbaed0ae81c

I will be releasing an update to our beta SDK shortly!

**Comment by nicolasgomollon** [comment]
Hey @Nightsd01, any timeline for when you think the beta SDK that includes this fix will be released? We’re trying to push an app update to our users soon, and would like to have the option to deep link them into our custom notification settings.

Thanks,
–Nico

**Comment by Nightsd01** [comment]
@siburb @nicolasgomollon Apologies for the delay getting back to you, our beta SDK has these changes. 

To see how to install the beta SDK there are instructions on the beta branch README. We expect to merge this into master and issue an official release sometime early next week!

As a short explanation, you can use the new `providesAppNotificationSettings` option by passing in `kOSSettingsKeyProvidesAppNotificationSettings` set to `true` in the iOS SDK init settings. There's no need to use `UNNotificationCenter` authorizations yourself now.

We're probably going to add an initialization check to see if you've requested any `UNNotificationAuthorization`'s  yourself to make sure our SDK doesn't override them - but currently you'll need to use the kOSSettingsKey

**Comment by Nightsd01** [comment]
By the way, we released the new iOS 12 update yesterday (2.9.0) thanks for your patience!
