### ISSUE TITLE
How to handle VOIP Push issue.

### ISSUE THREAD

**Issue by nomimalik1769** [OneSignal/OneSignal-iOS-SDK#414]
I am having strange in one signal SDK my App required VOIP Push to handle calling feature but some time I get notification from one signal sometime I don't and on Dashboard it's delivered. I have upload VOIP cert on One Signal. I want to add both notification normal and VOIP in my App so how can i manage both certificates.

I will be thankful if anyone could help me.

Regards.

**Comment by Nightsd01** [comment]
@nomimalik1769 https://documentation.onesignal.com/docs/voip-notifications

Please follow our issue template moving forward and try to at least add some basic details to the issue next time.
