### ISSUE TITLE
Issue app badge number

### ISSUE THREAD

**Issue by llKoull** [OneSignal/OneSignal-iOS-SDK#417]
Hello!

I read some posts of people having issues with the badge reset, but i couldn't find a solution to my problem 😟

The issue is that when i send a notification (with an increase of 1 in the badge counter) i works correctly and if i run the application (touching the notification or not), the badge number disappears automatically (so It seems that it's reset. The problem is that in the next notification that i send, the number increases again and i can't reset it to 0.

The flow is this:

    1- I have no badge in my app (it's a new user for example) 🆗 
    2- I receive a notification with the app closed, so the badge indicates 1 🆗 
    3- I receive another notification with the app closed, now the badge says 2 🆗 
    4- I open the App and the i close it 🆗 
    5- Now the badge is gone because i have 0 notifications 🆗 
    6- I receive another notification with the app closed, now the badge says 3 ❌ 

In the 6th step the badge should say 1 but i don't know how to reset this number.

I tried to reset the number manually every time that the apps becomes active:

```
func applicationDidBecomeActive(_ application: UIApplication)
    {
        application.applicationIconBadgeNumber = 0
    }
```

I also tried to enable and disable the automatic badge number management that one signal does, but it doesn't worked either.

Can you help me?

Thanks and best regards!

**Comment by Nightsd01** [comment]
@llKoull this would be an issue where the notification extension service is unable to communicate with your app via App groups, so the badge count becomes unsynchronized. 

Are you sure you enabled the same app group for *both* targets (your app and the extension service)? The name of the group should be `group.(your bundle ID here).onesignal` by default.

**Comment by llKoull** [comment]
Thanks @Nightsd01, you are right!! i didn't saw that last step.

All is working perfect right now 😉

Best regards!
