### ISSUE TITLE
enableInAppAlertNotification displays a blank AlertDialog with content_available

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-iOS-SDK#42]
If `enableInAppAlertNotification` is set to `true` and a `content_available` messages is received while the app is in focus a blank dialog is displayed when it should not.

The issue can be worked around by never setting `enableInAppAlertNotification` in your app or set it to `false` it was set before.

**Comment by JKalash** [comment]
Issue fixed in 2.0 version.
