### ISSUE TITLE
How to get player id in Notification Extension Service?

### ISSUE THREAD

**Issue by chitswe** [OneSignal/OneSignal-iOS-SDK#423]
I would like to implement activity feed as described in [doc](https://documentation.onesignal.com/docs/create-an-activity-feed). I planned to save notification on my server when  received. But I can't get player id. I use `getPermissionSubscriptionState` method and `subscriptionStatus.userId` is always `nil`. Is there any way to get player id inside Notification Extension Service? 

```
@implementation NotificationService

- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {
  self.receivedRequest = request;
  self.contentHandler = contentHandler;
  self.bestAttemptContent = [request.content mutableCopy];
  OSPermissionSubscriptionState* status = [OneSignal getPermissionSubscriptionState];
  NSString* player_id = status.subscriptionStatus.userId; //always got nil
  }
```

**Comment by Nightsd01** [comment]
@chitswe Unfortunately we don't currently support this. We will be separating the extension service logic into its own separate framework this week and will use this as an opportunity to make this possible.

In the mean time, I would recommend using your app group to add this functionality yourself. Set up an `OSSubscriptionObserver` (probably using your AppDelegate) and whenever the ID changes, update `NSUserDefaults` with a suite name so it gets shared between your app & extension.

Objective C:
```objc
//in app - in OSSubscriptionObserver changes method
NSUserDefaults *defaults = [[NSUserDefaults alloc] initWithSuiteName:@"<app group name>"];
[defaults setObject:subscriptionChanges.to.userId forKey:@"os-user-id"];
[defaults synchronize];

//in extension. Make sure to handle nil case
NSString *userId = [defaults stringForKey:@"os-user-id"];
```

Swift:
```swift
// in app - in OSSubscriptionObserver changes method
let defaults = UserDefaults(suiteName: "<app group name>")
defaults["os-user-id"] = subscriptionChanges.to.userId
defaults.synchronize()

//in extension
if let onesignalUserId = defaults.string(for: "os-user-id") {
  
}
```
