### ISSUE TITLE
handleNotificationReceived not called before handleNotificationAction when app was not in foreground or background

### ISSUE THREAD

**Issue by christopheblin** [OneSignal/OneSignal-iOS-SDK#431]
**Description:**

When I set content_available to true and my iOS app is not launched (neither in foreground nor background), then OneSignal never calls handleNotificationReceived

I know that this is because iOS does not call the corresponding method in app delegate (application(_:didReceiveRemoteNotification:fetchCompletionHandler:)).

So far so good. However, the strange thing is that if the user clicks on the notification, the handleNotificationAction is called directly.
So, contrary to Android, we can not rely on the fact that the handleNotificatinReceived has been called before.

Is that intended that I (as a programmer) have to deal with that situation ?

**Comment by Nightsd01** [comment]
Yes, you definitely want to handle cases like this. There are several instances where iOS will not open an app in the background even when it receives a notification with `content-available` set to `true`, such as when the device is low on battery or the user intentionally terminated the app. 

I don’t know what you mean when you say your app is not launched in the foreground? Foreground means your app is in the foreground, meaning your app is open.

**Comment by christopheblin** [comment]
OK, that is weird :(

For ex, we update our local db with remote content during handleNotificationReceived and we assumed that handleNotificationAction will always have the most recent data copy (so this is not true)

It means that we have to implement a mechanism to detect if the notif has been processed by handleNotificationReceived to be sure the info is synced correctly
