### ISSUE TITLE
CR: kOSSettingsKeyInAppLaunchURL

### ISSUE THREAD

**Issue by iDevo** [OneSignal/OneSignal-iOS-SDK#434]
Hi there! 
According to the Issue #231 and [this](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/231#issuecomment-297849900) suggestion, I'd like to kindly ask for a small CR regarding the line [1815 of the OneSignal.m file](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/0e7923bdbd33f49401bf26e8dd195401853b4b88/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L1815). 

It would be great to have the opportunity to set the kOSSettingsKeyInAppLaunchURL property to .none, in order to do a customized handling of the notification URL pushed forward from for example Wordpress. A simple enum and an if condition should be enough for a nice and handy solution! 

This way would gain the same customizability in iOS like Android already provides. 

Cheers!

**Comment by Nightsd01** [comment]
Hi, we started working on a solution for this last week. Closing this issue as it’s a duplicate
