### ISSUE TITLE
Does SDK capable of batching tag requests?

### ISSUE THREAD

**Issue by bernikowich-cedoni** [OneSignal/OneSignal-iOS-SDK#437]
**Description:**

Hello.
We have app where it's possible to have more then 100 tags on start. According to current SDK implementation I cannot use nor sendTag: neither sendTags:, because both functions will batch all my requests by 5sec delay.
▿ Optional<Error>
  - some : Error Domain=OneSignalError Code=400 "(null)" UserInfo={returned={
    errors =     (
        "Please limit your tag updates to 100 per request"
    );
    success = 0;
}}
(your description here)

**Environment**

Reproducible on iOS11-12, I use Cocoapods.

**Steps to Reproduce Issue:**

Just install SDK and try to send 101 tag.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by bernikowich-cedoni** [comment]
I use following code to resolve this issue for now, but it's possible to reproduce this issue with 100 calls of sendTag: function.

>   fileprivate static func sendTagsInBatches(_ leftTags: [String: String], completion: @escaping ((Error?) -> Void)) {
>     let tagsToSendSlice = leftTags.prefix(80)
>     let tagsToSend = tagsToSendSlice.reduce(into: [String: String]()) { (result, keyValuePair) in
>       let (key, value) = keyValuePair
>       result[key] = value
>     }
>     let leftTags = leftTags.filter({ !tagsToSend.keys.contains($0.key) })
> 
>     OneSignal.sendTags(tagsToSend, onSuccess: { _ in
>       if leftTags.keys.count > 0 {
>         sendTagsInBatches(leftTags, completion: completion)
>       } else {
>         completion(nil)
>       }
>     }, onFailure: { error in
>       completion(error)
>     })
>   }

**Comment by Nightsd01** [comment]
@bernikowich-cedoni Why would you ever want to send 100 tags at a time...? I would suggest that if you need to use _that_ many tags, you might consider revising how & why you are using tags. 

Asides from that, we do send tag updates in batches. You will want to make sure you have your own batching logic however so that you never exceed 100 tags per update.
