### ISSUE TITLE
Xcode 10 Dsymutil warnings

### ISSUE THREAD

**Issue by TarasGordienko** [OneSignal/OneSignal-iOS-SDK#440]
**Description:**
After updating from OneSignal 2.9.0 to 2.9.2 I've got a bunch of warnings in the project (details below)

**Environment**
1. What version of the iOS SDK are you using?
 iOS SDK 2.9.2
2. How did you add the SDK to your project?
cocoapods

**Steps to Reproduce Issue:**
Issue does not appear when making a new project, currently I'm unable to reproduce it on a new project

**Anything else:**

GenerateDSYMFile /Users/me/Library/Developer/Xcode/DerivedData/myApp-eogltgyntwwxgagemkaiwgbesqgh/Build/Products/Debug-iphoneos/myAppDev.app.dSYM /Users/me/Library/Developer/Xcode/DerivedData/myApp-eogltgyntwwxgagemkaiwgbesqgh/Build/Products/Debug-iphoneos/myAppDev.app/myAppDev (in target: myApp)
    cd /Users/me/Documents/projects/myApp/myApp-iOS
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/me/Library/Developer/Xcode/DerivedData/myApp-eogltgyntwwxgagemkaiwgbesqgh/Build/Products/Debug-iphoneos/myAppDev.app/myAppDev -o /Users/me/Library/Developer/Xcode/DerivedData/myApp-eogltgyntwwxgagemkaiwgbesqgh/Build/Products/Debug-iphoneos/myAppDev.app.dSYM

warning: /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
note: while processing /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/Foundation-A3SOD99KJ0S9.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
warning: /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/UserNotifications-1YQ59ILDR3NYI.pcm: No such file or directory
note: while processing /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/UserNotifications-1YQ59ILDR3NYI.pcm
warning: /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/SystemConfiguration-2O070L5BFB5B1.pcm: No such file or directory
note: while processing /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/SystemConfiguration-2O070L5BFB5B1.pcm
warning: /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/Darwin-MI6WZSG1PNOM.pcm: No such file or directory
note: while processing /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/Darwin-MI6WZSG1PNOM.pcm
warning: /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
note: while processing /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/UIKit-2LM3EQU7VVY4O.pcm
warning: /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/ObjectiveC-1KD62J152BYGO.pcm: No such file or directory
note: while processing /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/ObjectiveC-1KD62J152BYGO.pcm
warning: /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/Dispatch-12O7S7HHQXK9N.pcm: No such file or directory
note: while processing /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/Dispatch-12O7S7HHQXK9N.pcm
warning: /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/CommonCrypto-2BKBWM9L7D2GS.pcm: No such file or directory
note: while processing /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/CommonCrypto-2BKBWM9L7D2GS.pcm
warning: /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/CoreFoundation-10I2D2XL7L7X9.pcm: No such file or directory
note: while processing /var/folders/3p/q_b0mn3s5rlgdwch693rmcww0000gn/C/org.llvm.clang.bradhesse/ModuleCache/1GR5JW70E89GN/CoreFoundation-10I2D2XL7L7X9.pcm

**Comment by Nightsd01** [comment]
@TarasGordienko that's quite an interesting warning! Can you try clearing DerivedData and rebuild your project?

If that doesn't remove the error, can you try running `pod deintegrate` and then `pod install` on your project?

**Comment by TarasGordienko** [comment]
@Nightsd01 tried both clearing delivered data and `pod deintegrate`, however warnings still appear

**Comment by damirstuhec** [comment]
Same here @Nightsd01.

**Comment by damirstuhec** [comment]
Started happening with the `2.9.2` version (wasn't happening in `2.9.0`).

**Comment by Nightsd01** [comment]
We've created a [pull request](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/443) to resolve this issue, thanks for reporting!

**Comment by Nightsd01** [comment]
This issue should now be resolved in the 2.9.3 release
