### ISSUE TITLE
Add a way to block app opening when tapping an action button

### ISSUE THREAD

**Issue by jeromecance** [OneSignal/OneSignal-iOS-SDK#441]
**Description:**

Action buttons on iOS have been essentially designed to take action without opening the app. For example the Mail app notifications allow you to Archive/Delete a message without opening the app.

This is the default behaviour when creating notification with action buttons on iOS.

But OneSignal always open the app when an action button is tapped. 

This behaviour is possible by giving the "foreground" option when instantiating a UINotificationAction.

I suspect that your code use this option when creating action buttons at lines 459 and 588 of OneSignal-iOS-SDK/iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m

As a lot of apps use action buttons to take quick actions without opening the app, can we find a solution to override onesignal's default behaviour and prevent the app opening when using action buttons?

**Environment**

iOS

**Comment by Nightsd01** [comment]
Correct, our SDK currently only supports buttons that open the app. We will consider adding support for additional action types for our 3.0 release

**Comment by jeromecance** [comment]
Ok nice, do you already have an estimated delivery date for the 3.0 release?

**Comment by jkasten2** [comment]
@jeromecance We don't have an estimate at this time. However you can use iOS Notification categories directly to achieve this. See Apple docs on creating a `UNNotificationCategory`
https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types

You can then use `ios_category` to use your custom id.
https://documentation.onesignal.com/reference#section-action-buttons

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration

**Comment by Gutyn** [comment]
So a simple archive button can't be done with this because that would open the app? Forgive me if I don't understand the philosophy behind this but it makes absolutely no sense to me.
Looking at the library it seems pretty easy to add a way to stop the button from opening the app, I would be very thankful if you would add this feature. Thank you, great people.

**Comment by Lizard-King101** [comment]
Yea I would also like to know about this functionality as well, seems counter intuitive to how action buttons should work. @rgomezp  if w could get an update on this that would be awesome :) thanks in advance!

**Comment by CardellD** [comment]
I'm with everyone else here - this seems like such a valuable feature that would be simple enough to include.  Not including this removes some of the best benefits of the Action Button.  I don't get it.

**Comment by jkasten2** [comment]
The action for the button has to be defined upfront from my understand of Apple's documentation.
https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types?language=objc

So this means In-addition to SDK changes there will need to be an extra parameter to the `buttons` object on the `https://onesignal.com/api/v1/notifications` endpoint to support this
https://documentation.onesignal.com/reference#action-buttons.

We see this is a useful feature to have built in the SDK but it is possible to implement today by creating and using your own `UNNotificationCategory` noted in https://github.com/OneSignal/OneSignal-iOS-SDK/issues/441#issuecomment-435494112.

This doesn't mean we will never add this, as we do see how it would be help to not have to write extra code for this. However we do recommend using your own category on your notifications today as this is more than a few months out.

**Comment by CardellD** [comment]
We have implemented your recommendation, and the iOS version still forces the app to open (and the phone to be unlocked) when the Action Button is pressed.  The workaround was unsuccessful for us.
