### ISSUE TITLE
Sdk does not build with Carthage

### ISSUE THREAD

**Issue by ckaalund** [OneSignal/OneSignal-iOS-SDK#444]
**Description:**

carthage update fails with this error:
$ carthage update
*** Fetching OneSignal-iOS-SDK
*** Checking out OneSignal-iOS-SDK at "2.9.3"
*** xcodebuild output can be found in /var/folders/03/7150zz0n7mng3blqx_qhc6qc0000gn/T/carthage-xcodebuild.4MmocQ.log
*** Building scheme "OneSignalFramework" in OneSignalSDK.xcworkspace
Failed to write to /Carthage/Build/iOS/OneSignal.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “OneSignal.framework” couldn’t be opened because there is no such file." UserInfo={NSFilePath= /Library/Developer/Xcode/DerivedData/OneSignalSDK-agdlpshjgucdiadmchbxspwantpc/Build/Products/Release-iphoneos/OneSignal.framework, NSUnderlyingError=0x7f8ed9d995b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

I have tried removing all files and starting from new

There is no Release-iphoneos folder in Products. Instead there is a Release-iphonesimulator folder.

**Environment**
cathage v 0.18.1
swift version 4.2.1
xcode verison 10.1

**Comment by Nightsd01** [comment]
@ckaalund I am not able to replicate your issue, installing 2.9.3 with Carthage works fine for me. I notice you are on quite an old version of Carthage (current version is 0.31.2 while your version is 0.18.1), can you try updating to a more recent version of Carthage and try again?

**Comment by ckaalund** [comment]
That did the trick :) I should have checked that, sorry. Thank you for your help
