### ISSUE TITLE
OSNotificationPayload.body crashes in swift in OSHandleNotificationReceivedBlock

### ISSUE THREAD

**Issue by anirudhab2** [OneSignal/OneSignal-iOS-SDK#445]
**Description:**

I am creating a new notification using the REST API (onesignal.com/api/v1/notifications). I am only setting the "headings" field and omitting the "contents" field. Now if I get a notification when app is active, I get a crash in OSHandleNotificationReceivedBlock if I try to access `notification.payload.body`.

I get following crash message in console - 
If I set `OneSignal.inFocusDisplayType = OSNotificationDisplayType.none`
`-[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x2211359a0`
otherwise
`-[NSNull length]: unrecognized selector sent to instance 0x2211359a0`

The crash doesn't happen if I set both fields correctly or omit both of them (`notification.payload.body` is just `nil` if I omit both). Documentation says "contents" is only required unless `content_available = true`, which I am using (https://documentation.onesignal.com/reference#section-notification-content).
I have gone through #117  but this looks like a different issue. 

**Environment**
iOS 12.0, Xcode 10.0, Swift 4.2
OneSignal v2.9.3 via cocoapods

**Steps to Reproduce Issue:**

The crash happens when the app is active and I receive a notification.

My Init looks something like this

                let oneSignalSettings = [kOSSettingsKeyAutoPrompt: false]
		let notificationReceivedBlock: OSHandleNotificationReceivedBlock = { notification in
			guard let payload = notification?.payload else {
				return
			}
			let body = payload.body	// Crashes here
		}
		
		let notificationOpenedBlock: OSHandleNotificationActionBlock = { result in
			
		}
		// Initializing One Signal
		OneSignal.initWithLaunchOptions(launchOptions,
										appId: My_App_Id,
										handleNotificationReceived: notificationReceivedBlock,
										handleNotificationAction: notificationOpenedBlock,
										settings: oneSignalSettings)
		// OSSubscriptionObserver
		OneSignal.add(self)
		OneSignal.inFocusDisplayType = OSNotificationDisplayType.none

My create notification request body that crashes looks like this (I am using postman for testing). Other fields like auth and content-type are setup properly

`{ 
	"app_id": "My_App_Id",
	"include_player_ids": [ "My_Player_Id" ],
	"content_available": true,
	"headings": { 
		"en": "English Title"
	}
}`

While following requests work fine
`{ 
	"app_id": "My_App_Id",
	"include_player_ids": [ "My_Player_Id" ],
	"content_available": true,
	"headings": { 
		"en": "English Title"
	},
	"contents": {
		"en": "English Message"
	}
}`
or 
`{ 
	"app_id": "My_App_Id",
	"include_player_ids": [ "My_Player_Id" ],
	"content_available": true
}`

**Comment by Nightsd01** [comment]
This is because you are not setting the body. You would want to check to see if the body parameter is nil/NSNull. Unfortunately this is an issue with Swift/ObjC bridging.

**Comment by anirudhab2** [comment]
Ahh, suspected that, thanks for your response.
