### ISSUE TITLE
Background refresh and Pushnotifications  - isRegisteredForRemoteNotifications always true

### ISSUE THREAD

**Issue by deekshibellare** [OneSignal/OneSignal-iOS-SDK#45]
[[UIApplication sharedApplication] isRegisteredForRemoteNotifications] always returns true when background refresh is on in settings of the device.
I suspect it is SDK issue. We are using the same approach for other apps to check if the user enabled push or not and it works.

**Comment by jkasten2** [comment]
This is expected behavior with our SDK. Both our 1.0 and 2.0 SDKs register for a remote token when the app starts on iOS 8+ devices. You will need to check `currentNotificationsSettings` to see if the user has  accepted the notifications permission prompt. See issue https://github.com/OneSignal/OneSignal-iOS-SDK/issues/1#issuecomment-115161130 for more details.

**Comment by allaire** [comment]
@jkasten2 Hi,

Just experienced this as well, is this a correct way to detect it?

```swift
    func hasPushNotificationsEnabled() -> Bool {
        if let currentUserNotificationSettings = self.currentUserNotificationSettings() {
            return !currentUserNotificationSettings.types.contains(UIUserNotificationType.None)
        }
        
        return false
    }
```

**Comment by jkasten2** [comment]
@allaire Correct, this could should accurately give you the user's current notification permission for your app.

**Comment by allaire** [comment]
@jkasten2 Thanks! This should probably be added somewhere in the doc. I'm sure this is a common mistake to rely on `isRegisteredForRemoteNotifications` to know if the user has notifications disabled.

**Comment by jkasten2** [comment]
@allaire I just updated our [initWithLaunchOptions](https://documentation.onesignal.com/docs/ios-native-sdk#section--initwithlaunchoptions-) with an iOS 8+ note about this selector. Let me know if you have any additional feedback on this new message.

**Comment by allaire** [comment]
@jkasten2 Rock & Roll, thanks!

On another topic, I also noticed that when you do `setSubscription(true)` to a user where his token is not available `No Push Token` (uninstalled app for exemple), it marks it as true.

I think it makes sense when the Subscription status is a regular `No`, but I don't think that it should set it to `true` if there is some error on why it's set to `No`.

Not sure if I'm being clear enough?

Thanks!
