### ISSUE TITLE
PushToken Always Null

### ISSUE THREAD

**Issue by VictorASebastian** [OneSignal/OneSignal-iOS-SDK#452]
**Description:**

Always getting null for push token registration with Onesignal

**<OSSubscriptionStateChanges:

from: <OSSubscriptionState: userId: (null), pushToken: (null), userSubscriptionSetting: 1, subscribed: 0>,

to:   <OSSubscriptionState: userId: 23813271-9a66-4277-840c-839e5fb762c9, pushToken: (null), userSubscriptionSetting: 1, subscribed: 0>**

>

(your description here)

**Environment**

1.pod 'OneSignal', '~>2.9.3'
2.Cocoapods

**Steps to Reproduce Issue:**

  1. Install iOS SDK version 2.9.3 with Cocoapods into a project
  2. Initialize the SDK in didFinishLaunchingWithOptions:
  3. Attempt to receive a push notification

**Comment by Nightsd01** [comment]
@VictorASebastian are you running on a real device or simulator? iOS Simulators do not allow push notifications and won’t get a push token.

**Comment by VictorASebastian** [comment]
Im running on iPhone 6S..

**Comment by VictorASebastian** [comment]
Hi,
   This solved this issue by changing pod version from  2.1.6 to 2.5.0, after this version, APNS Delegate never fired...However, this pod version's does not support SetEmail feature..But my issue was fixed.

**Comment by Nightsd01** [comment]
You were using....version 2.1.6...? Why are you using such ancient versions? In your original post you said you were using the latest version...?

**Comment by VictorASebastian** [comment]
When I was using latest version.i was always getting APNS delegate not
fired error in onesignal...

**Comment by AmitPandya007** [comment]
> Im running on iPhone 6S and im getting my push token successfully.with
> 
> * (void)application:(UIApplication*)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData*)deviceToken..

Did it gave you the oneSignal Token value???
