### ISSUE TITLE
Disabling kOSSettingsKeyAutoPrompt is always firing registration

### ISSUE THREAD

**Issue by mywaystar** [OneSignal/OneSignal-iOS-SDK#46]
I upgraded to the new SDK and setted kOSSettingsKeyAutoPrompt to false

The registration prompt is now firing after launch. Any workaround? 

Note that this happens in simulator. Not tested with an iPhone.

**Comment by jkasten2** [comment]
@mywaystar Thanks for the report, we will get a fix out of this the beginning for next week. Feel free to use our 1.13.3 version until then.

**Comment by jkasten2** [comment]
@mywaystar Just fixed this in our 2.0.1 release.

**Comment by mywaystar** [comment]
You guys you rock.

![](https://media.giphy.com/media/GK7grZYLG7cs0/giphy.gif)

**Comment by tamarinda** [comment]
Hi, 

This seems to be still happening, I am using version 2.1.16
In the documentation I have found:

> iOS 8.0+ Note
application:didRegisterForRemoteNotificationsWithDeviceToken: will still fire even if kOSSettingsKeyAutoPrompt is set to false. This behavior will happen on iOS 8+ devices.

Is there any workaround to this?

**Comment by markuswinkler** [comment]
Easy workaround is to login only if you already have the permissions:

```
    var pushNotificationTurnedOn : Bool {
        get {
            if let types = UIApplication.sharedApplication().currentUserNotificationSettings()?.types {
                if types.rawValue > 0 {
                    // Application is subscribed to push notifications
                    return true
                } else {
                    // Application is NOT subscribed to push notifications
                    return false
                }
            } else  {
                return false
            }
        }
    }

```
