### ISSUE TITLE
Apps crashed when url or additional data is attached.

### ISSUE THREAD

**Issue by Caizer** [OneSignal/OneSignal-iOS-SDK#47]
Hi, 

Since 2.0 version sdk, (I am using CocoaPod.) 
Whenever url or additional data is attached, App goes crash.

I got following...

-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance

I tried to send notifications from Onesignal.com and my own server via rest api. 
Both got same results. 

I am not sure it's system wide, cause my android version of the app is fine. 

I guess one signal server does not send properly formatted json to APNS server now.

**Comment by jkasten2** [comment]
@Caizer Thanks for the report, we will get a fix out for this next week. OneSignal is still sending the same payload format so feel free to use our 1.13.3 version until then.

**Comment by jkasten2** [comment]
@Caizer I was not able to reproduce a crash when opening a notification with additional data. Can you add what you are setting it to to your issue?

I am able to reproduce the issue when setting a url alone and I am looking into a fix.

**Comment by jkasten2** [comment]
@Caizer Just released 2.0.1 of our SDK which fixes the url crash issue. Was not able to reproduce any issues with additional data but feel free to reopen the issue if there is still an issue for you.
