### ISSUE TITLE
Bitcode

### ISSUE THREAD

**Issue by legranddamien** [OneSignal/OneSignal-iOS-SDK#48]
Hi !
The version 2.0.1 of OneSignal does not works with bitcode enabled.

`bitcode bundle could not be generated because '...../Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/OneSignal(OneSignalTrackIAP.o)' was built without full bit code.`.

**Comment by jkasten2** [comment]
@legranddamien This should be fixed in version 2.0.2. Feel free to reopen the issue it does not.

Thanks.
