### ISSUE TITLE
Prompting for notifications permissions more than once

### ISSUE THREAD

**Issue by ajRiverav** [OneSignal/OneSignal-iOS-SDK#480]
**Description:**

I am using the following code the check if a user's app is subscribed or not:
`// Check if app is subscribed. If not, ask for permissions. 
        let status: OSPermissionSubscriptionState = OneSignal.getPermissionSubscriptionState()

        if !status.subscriptionStatus.subscribed {
            print("**** subscriptionStatus not subscribed")
            // Call when you want to prompt the user to accept push notifications.
            // Only call once and only if you set kOSSettingsKeyAutoPrompt in AppDelegate to false.
            OneSignal.promptForPushNotifications(userResponse: { accepted in
                print("**** User accepted notifications: \(accepted)")
            })
        } else {
            print("**** subscriptionStatus subscribed")
        }`

If the user does not allow notifications the first time the app is used, it was my hope to catch that and ask for the notifications again. I am not sure if this is a onesignal limitation or an apple design. 
Which is one is it?

If it is an apple design, does that mean one has to -somehow- explain to the user how to go to settings-> notifications -> etc...?

**Environment**

1. OneSignal 2.6.2
2. n/a

n/a

**Anything else:**

n/a

**Comment by Nightsd01** [comment]
@ajRiverav This is an iOS restriction - they don't want apps spamming people multiple times for requests to send push notifications, which makes sense.

Here is a common workaround you can use. If a user has denied permission to send push notifications, you can show a popup (UIAlertController) asking them if they have changed their mind, and if they select 'yes', you can call `OneSignal.presentAppSettings()` and this will take them to the iOS Settings page for your app where they can then enable notifications permission.

**Comment by ajRiverav** [comment]
@Nightsd01 I google the func but don't see the equivalent in the latest version. Do you happen to know if there is still a way to call it? I believe one can do it using an Apple API instead of OneSignal's.

**Comment by ajRiverav** [comment]
cf. https://stackoverflow.com/questions/28152526/how-do-i-open-phone-settings-when-a-button-is-clicked

**Comment by Nightsd01** [comment]
@ajRiverav I’m not sure I understand what you mean? The method has been in our SDK for several versions now.

**Comment by ajRiverav** [comment]
@Nightsd01 It is not in the latest API. Do you have a link to it?
This is what I have https://documentation.onesignal.com/docs/ios-native-sdk

**Comment by Nightsd01** [comment]
@ajRiverav it’s right here. https://documentation.onesignal.com/docs/ios-native-sdk#section--presentappsettings-
