### ISSUE TITLE
execute launch url programmatically and not from a notification

### ISSUE THREAD

**Issue by jaybuangan** [OneSignal/OneSignal-iOS-SDK#484]
**Description:**

Is it possible to open a URL using the OneSignal browser but not through opening a message from a notification?  Basically I want to use the same mechanism used to open a browser programmatically so that it stays consistent with opening via an alert.

**Comment by Nightsd01** [comment]
@jaybuangan the OneSignal webview implementation is not publicly accessible from our framework. You could access it at runtime using reflection but that would be unnecessarily complex and dangerous if it were to change in the future. 

Your best route would be to check out our source, it should be pretty easy to just use our [web view controller](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Source/OneSignalWebView.m) in your app.

**Comment by jaybuangan** [comment]
@Nightsd01 Thanks for the suggestion.  How exactly do I use it?  I can only see OneSignal when I import it.

**Comment by Nightsd01** [comment]
@jaybuangan the simplest way would just be to copy and paste the source file I linked. It’s not a public class of our SDK so that’s the simplest approach.

**Comment by jaybuangan** [comment]
Awesome. that seems to have done the job!  thank you!
