### ISSUE TITLE
onOSSubscriptionChanged not being called

### ISSUE THREAD

**Issue by Fyb3roptik** [OneSignal/OneSignal-iOS-SDK#486]
Referencing #358 

onOSSubscriptionChanged is not called at all. I am using an actual device, and the callback is never triggered. I have removed the app and then built the app and i click allow and the callback never gets triggered

**Comment by Nightsd01** [comment]
@Fyb3roptik please add at least _some_ of the details we ask for in the Issue Template....

For example, what version/s of iOS is this issue occurring on? 

Real device or simulator?

Do push notifications actually work even though the subscriptionChanged method never gets called?

And lastly can you please set the OneSignal log level to `verbose` using the `[OneSignal setLogLevel...` function, run your app for 30 seconds, and past a link to it so we can see the output? Please paste a link to pastebin or something not directly in your reply.

**Comment by FVivolo** [comment]
i have the same issue, 
device
IPad Air 2 with 12.1.4
so to describe when the process do setsubscription(yes) and you see in verbose mode in the debug view you receive the information from your server and you have all information, version, apple id, user Id etc. but not triggered for this method, so you go out and restart the application and you get the userid from reading getPermissionSubscriptionState and subsequent reading from status, so after just installed you and do setSubscription get DeviceRegistered with OneSignal: XXXXXXXXXXXX and after that 

https://pastebin.com/index/b6sxcAf5

hope this help to solve this to happen

**Comment by Nightsd01** [comment]
@FVivolo `onOSSubscriptionStateChanged` is only called when the subscription state **changes**. If the user ID does not change for example, then this method does not get called. 

I do not see any registration networking calls in those logs you sent..? Are you sure that you are running on a real device (iOS does not allow push notifications in simulator) and that you are tapping “Accept” for push notifications?

Keep in mind, if you accept push notifications permission, `onOSSubscriptionStateChanged` will get called. But if you restart the app and reopen, the user subscription state is the same and doesn’t change so the method doesn’t get called.

**Comment by FVivolo** [comment]
Hi,

I am running in a real device as I posted in the issue follow the result for the first time (the ipa was not present in the device ) and when I start the set subscription is set to yes

https://pastebin.com/UGTAfSsY


with   the second run and I get the userid from 

https://pastebin.com/wR5SZT0G


BUT using this piece of code

    OSPermissionSubscriptionState* status = [OneSignal getPermissionSubscriptionState];
    isSubscribed = status.subscriptionStatus.subscribed;
    userID = [status.subscriptionStatus.userId copy];
    isPushEnabled = status.permissionStatus.hasPrompted && status.permissionStatus.status == OSNotificationPermissionAuthorized;


I never get these  triggered


#pragma mark OSSubscriptionStateChanges Delegate Method
-(void)onOSSubscriptionChanged:(OSSubscriptionStateChanges *)stateChanges {
    if (stateChanges.from.subscribed &&  !stateChanges.to.subscribed) {
        isSubscribed = NO;
        nError = 1002;  // proprietary code from clickteam runtime
        [ho pushEvent:CNDONERROR withParam:0]; // proprietary code from clickteam runtime
    } else if (!stateChanges.from.subscribed && stateChanges.to.subscribed) {
        isSubscribed = YES;
        if(userID != nil)
           [userID release];
        userID = [NSString stringWithFormat:@"%@", stateChanges.to.userId];
        [ho pushEvent:CNDONSUBS withParam:0]; // proprietary code from clickteam runtime
    }
}

as you may see the delegation are set in the header file

@interface CRunOneSignalApp : CRunExtension <OSPermissionObserver, OSSubscriptionObserver>

Also I have a second problem when the push come from server and the app is offline/background the notification open the application but in this case the OSOpened method is not triggered.

All is set NotificationService, etc. but in this case it fails.


Thanks in advance

Fernando Vivolo



Sent from Mail for Windows 10

**Comment by Fyb3roptik** [comment]
Would a new user who hits allow not be seen as a CHANGE? I need to add player id's to my database for programmatic pushes and when they click Allow I cannot yet see their ID. Your documentation is not clear on what that process entails. What callback SHOULD I use?

**Comment by FVivolo** [comment]
Oh sorry but is funny you have been asking about if I am running in a real device and i have been answering YES is iPAD air 2, and the logs come for it, do you need a video?

**Comment by Fyb3roptik** [comment]
I am using Swift 4, real device, and the latest SDK

**Comment by Nightsd01** [comment]
@FVivolo it is very difficult to read your previous comment as you’re mixing code without using code syntax, could you edit?

@Fyb3roptik yes, a new user hitting “Allow” for the first time is definitely a change in the subscription state. 

Are either of you able to reproduce this problem in one of our example projects in the Examples folder of this repo?

**Comment by Nightsd01** [comment]
@FVivolo Are you sure that you are calling `[OneSignal addSubscriptionObserver:self];` for your observer class? 

Also, can you please use `NSLog` to make sure the subscription observer isn't actually getting called? In most cases it turns out it _is_ getting called but the code inside isn't working correctly.

If neither of those suggestions are able to help, please try running one of our example projects in the `/examples` folder of this repo - replace your App ID and bundle ID to get it working. Does the observer work in there? You will see the subscription status label change.

**Comment by Fyb3roptik** [comment]
The below code is in AppDelegate.swift

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        OneSignal.add(self as? OSSubscriptionObserver)
        let onesignalInitSettings = [kOSSettingsKeyAutoPrompt: false]
        OneSignal.initWithLaunchOptions(launchOptions,
                                        appId: "my-app-id",
                                        handleNotificationAction: nil,
                                        settings: onesignalInitSettings)
        
        OneSignal.inFocusDisplayType = OSNotificationDisplayType.notification;
        
        // Recommend moving the below line to prompt for push after informing the user about
        //   how your app will use them.
        OneSignal.promptForPushNotifications(userResponse: { accepted in
            print("User accepted notifications: \(accepted)")
        })
        
        return true
    }

//  This method will be called when the notification subscription property changes.
    public func onOSSubscriptionChanged(_ stateChanges: OSSubscriptionStateChanges!) {
        if !stateChanges.from.subscribed && stateChanges.to.subscribed {
            print("Subscribed for OneSignal push notifications!")
        }
        print("SubscriptionStateChange: \n\(String(describing: stateChanges))")
        
        //The player id is inside stateChanges. But be careful, this value can be nil if the user has not granted you permission to send notifications.
        if let playerId = stateChanges.to.userId {
            print("Current playerId \(playerId)")
        }
    }
```

**Comment by Fyb3roptik** [comment]
Ok so if I remove the user (it does create the user) and delete the app and reinstall here is what I get

https://pastebin.com/aLPTKKmH

But onOSSubscriptionChanged is still never triggered...so I never receive the player id

**Comment by Nightsd01** [comment]
@Fyb3roptik Your logs seem to only have 4 seconds of data, please give the SDK at least 15 seconds or so. Can you please completely uninstall, then re-install the app and test again and post a link to the logs?

Also - please try using our example project and let me know if the issue occurs there.

**Comment by Fyb3roptik** [comment]
That was after 30 seconds man...

**Comment by Nightsd01** [comment]
@Fyb3roptik the logs cover 17:33:20 to 17:33:24. That’s 4 seconds. Did nothing get printed to the console afterwards?

Also, please **run our example project** and go ahead and see if you can reproduce the issue with it.

**Comment by Fyb3roptik** [comment]
Here is the log after a few mins pass

https://pastebin.com/de1spvGU

**Comment by Fyb3roptik** [comment]
Ok after using the code (which I thought I was using) from the example, it is working. Thanks!
