### ISSUE TITLE
iOS Build Error On Adding Extension

### ISSUE THREAD

**Issue by vmwsree** [OneSignal/OneSignal-iOS-SDK#487]
**Description:**

On Adding OneSignalExtention Service Receives this Build Error , I am not using any Swift based Plugins yet.

**Error Stack:**

`Xcode build done.                                           271.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: warning: 'sqlite3_wal_checkpoint_v2' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'SQLite3' imported from /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabase.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sqlite3.h:8244:16: note: 'sqlite3_wal_checkpoint_v2' has been explicitly marked partial here
    SQLITE_API int sqlite3_wal_checkpoint_v2(
                   ^
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: note: enclose 'sqlite3_wal_checkpoint_v2' in an @available check to silence this warning
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: warning: 'dispatch_queue_set_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/dispatch/queue.h:1352:1: note: 'dispatch_queue_set_specific' has been explicitly marked partial here
    dispatch_queue_set_specific(dispatch_queue_t queue, const void *key,
    ^
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: note: enclose 'dispatch_queue_set_specific' in an @available check to silence this warning
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: warning: 'dispatch_get_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/dispatch/queue.h:1408:1: note: 'dispatch_get_specific' has been explicitly marked partial here
    dispatch_get_specific(const void *key);
    ^
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: note: enclose 'dispatch_get_specific' in an @available check to silence this warning
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: warning: 'sqlite3_wal_checkpoint_v2' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'SQLite3' imported from /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabase.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sqlite3.h:8244:16: note: 'sqlite3_wal_checkpoint_v2' has been explicitly marked partial here
    SQLITE_API int sqlite3_wal_checkpoint_v2(
                   ^
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: note: enclose 'sqlite3_wal_checkpoint_v2' in an @available check to silence this warning
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: warning: 'dispatch_queue_set_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/dispatch/queue.h:1352:1: note: 'dispatch_queue_set_specific' has been explicitly marked partial here
    dispatch_queue_set_specific(dispatch_queue_t queue, const void *key,
    ^
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: note: enclose 'dispatch_queue_set_specific' in an @available check to silence this warning
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: warning: 'dispatch_get_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/dispatch/queue.h:1408:1: note: 'dispatch_get_specific' has been explicitly marked partial here
    dispatch_get_specific(const void *key);
    ^
    /Users/rushil/Downloads/demogorgan/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: note: enclose 'dispatch_get_specific' in an @available check to silence this warning
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    The file “Pods-OneSignalNotificationServiceExtension.release.xcconfig” couldn’t be opened because there is no such file. (/Users/rushil/Downloads/demogorgan/ios/Pods/Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.release.xcconfig)
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/BoringSSL-GRPC'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/FirebaseAuth'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/FirebaseDatabase'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/FirebaseDynamicLinks'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/FirebaseFirestore'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/FirebaseFunctions'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/FirebaseStorage'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/Protobuf'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/TOCropViewController'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/cloud_firestore'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/cloud_functions'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/firebase_auth'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/firebase_core'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/firebase_dynamic_links'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/firebase_storage'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/flutter_webview_plugin'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/gRPC-C++'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/gRPC-Core'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/hello'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/image_cropper'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/image_picker'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/leveldb-library'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/onesignal'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/path_provider'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/share'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/shared_preferences'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/sqflite'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/tts'
    ld: warning: directory not found for option '-L/Users/rushil/Downloads/demogorgan/build/ios/Release-iphoneos/url_launcher'
    ld: library not found for -lBoringSSL-GRPC
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Encountered error while building for device. `

**Comment by Nightsd01** [comment]
@vmwsree Please post your Podfile. I am guessing you added all of your dependencies to the Extension service?

**Comment by vmwsree** [comment]
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
pod 'Firebase/Core'

**Comment by Nightsd01** [comment]
@vmwsree as the error shows, this error is unrelated to our SDK and looks like an error with your other dependencies somehow trying to get linked to the Extension Service. 

If you do not use rich push notifications (images, buttons) and don’t use badge logic, I would suggest the fastest way to solve this problem would be to simply remove the Extension service.

**Comment by Nightsd01** [comment]
You can also try running `pod deintegrate` and then `pod install` and delete your Derived Data folder.

**Comment by Nightsd01** [comment]
@rgomez I would close this issue as he hasn’t responded and it’s been 2 weeks.

**Comment by Nightsd01** [comment]
Still hasn’t responded. Should *definitely* close this issue.

**Comment by Nightsd01** [comment]
Still hasn’t responded, should *definitely* close this issue. @jkasten2

**Comment by rgomezp** [comment]
Closing due to no response
