### ISSUE TITLE
OneSignal.m line 232 +[OneSignal currentPermissionState]

### ISSUE THREAD

**Issue by pabbathiharish** [OneSignal/OneSignal-iOS-SDK#489]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Nightsd01** [comment]
@pabbathiharish......please post the full stack trace you’re seeing along with at least a few more details. I assume you’re seeing a crash? When does it happen? What version of the SDK are you using? Etc.

**Comment by TonyVie** [comment]
Hi !

I've seen same issue in my Crashlytics logs. 
Using OneSignal (2.11.2)

Here is complete stack:
Crashed: com.apple.main-thread
0   objc_msgSend + 16
1   +[OneSignal currentPermissionState] + 6366420
2   +[OneSignal currentSubscriptionState] + 6366956
3   +[OneSignal downloadIOSParamsWithAppId:] + 6375848
4   +[OneSignal initWithLaunchOptions:appId:handleNotificationReceived:handleNotificationAction:settings:] + 6369868
5   +[OneSignal initWithLaunchOptions:appId:handleNotificationAction:settings:] + 6369488
6   -[AppDelegate initOnesignalPushNotifications:launchOptions:] + 296 (AppDelegate.m:296)
7   -[AppDelegate initPushNotifications:launchOptions:] + 283 (AppDelegate.m:283)
8   -[AppDelegate application:didFinishLaunchingWithOptions:] + 83 (AppDelegate.m:83)
