### ISSUE TITLE
Carthage  producing framework only for   arm64 !!!!!!

### ISSUE THREAD

**Issue by ahsanMuzaheed** [OneSignal/OneSignal-iOS-SDK#492]
i followed this instructions:
https://documentation.onesignal.com/docs/carthage-setup

it produced a framework  in this folder (<PROJECT'S DIRECTORY>/Carthage/Build/iOS).

than  we tried to use that framework   in unreal engine.
https://www.unrealengine.com/

and during integration step  unreal failed to add because of framework's  arm64 architecture .

this was the error:

"ld: can't map file, errno=22 file '/Users/ahsanOnly/Desktop/UnrealEngine/Engine/Source/lib/OneSignal.framework' for architecture arm64"

how we can produce a different architecture ?

for example for :
arm7 only

**Comment by jkasten2** [comment]
@ahsanMuzaheed The OneSignal.framework should contain arm7 and arm64 within it's internal OneSignal binary file. It should be about ~14MB for this file if it contains all architectures.
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Versions/A/OneSignal

It is most likely a path issue where the whole file was not found, can you double check the 6 through 10 steps?

Are you seeing this error on both your main target and your extension service?

You can also try the suggestion here:
https://stackoverflow.com/questions/16436333/cant-map-file-errno-22-for-architecture-x86-64

**Comment by rgomezp** [comment]
Closing due to no response
