### ISSUE TITLE
Multiple user added for same device

### ISSUE THREAD

**Issue by sadabios** [OneSignal/OneSignal-iOS-SDK#496]
**Description:**
In my application when i reinstall the app everytime OneSignal create a new user for same device so how can i avoid that issue?

**Environment**
i am using this

pod 'OneSignal', '>=2.6.2', '<3.0'

This is my code 

let notificationReceivedBlock: OSHandleNotificationReceivedBlock = { notification in
            print("Received Notification: \(notification!.payload.notificationID)")
            print("launchURL = \(notification?.payload.launchURL ?? "None")")
            print("content_available = \(notification?.payload.contentAvailable ?? false)")
        }
       
        let notificationOpenedBlock: OSHandleNotificationActionBlock = { result in
            // This block gets called when the user reacts to a notification received
            let payload: OSNotificationPayload? = result?.notification.payload
            setnotificationBool(bool:true)
            let titleAdditional = payload?.additionalData["title"] as! String
            let typeAddidtional = payload?.additionalData["type"] as! String
          
        }
       
        let onesignalInitSettings = [kOSSettingsKeyAutoPrompt: false,
                                     kOSSettingsKeyInAppLaunchURL: true]
       
        OneSignal.initWithLaunchOptions(launchOptions, appId: "my OneSignalID", handleNotificationReceived: notificationReceivedBlock, handleNotificationAction: notificationOpenedBlock, settings: onesignalInitSettings)
        OneSignal.inFocusDisplayType = OSNotificationDisplayType.notification;
        OneSignal.add(self as? OSPermissionObserver)
        OneSignal.add(self as? OSSubscriptionObserver)
        OneSignal.promptForPushNotifications(userResponse: { accepted in
             print("User accepted notifications: \(accepted)")
        })

**Comment by rgomezp** [comment]
Hello @sadabios ,
This is the expected behavior. Why is this an issue for you?

**Comment by rgomezp** [comment]
Closing due to no response
