### ISSUE TITLE
Have an issue when build with Fastlane (related to Cocoapods)

### ISSUE THREAD

**Issue by macbaszii** [OneSignal/OneSignal-iOS-SDK#497]
**Description:**

Got this error when building with xcodebuild using Fastlane

```
[14:34:32]: ▸ Linking OneSignalNotificationServiceExtension
[14:34:32]: ▸ ❌  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1001.0.46.3.0_0' Reader: '1000.11.45.5_0')', using libLTO version 'LLVM version 10.0.0, (clang-1000.11.45.5)' for architecture arm64
[14:34:32]: ▸ ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Environment**
- Xcode 10.1
- Deployment Target 10.2 (in Podfile, main app target, notification extension target)
- OneSignal SDK 2.10.0

**Comment by macbaszii** [comment]
Tried to de-integrate all pods and install it again.

**Comment by rgomezp** [comment]
Hello, 
Could you try setting the deployment target to 10.0?

**Comment by Kshopper93** [comment]
same issue. Did you fixed this?

**Comment by rgomezp** [comment]
@Kshopper93 ,
Try setting the deployment target to 10.0

**Comment by rgomezp** [comment]
Closing due to no response.

**Comment by n-nitchevski** [comment]
I'm getting that issue.
I've already set the Deployment Target of main project and the service extension to 10.0.
But still no luck.

**Comment by n-nitchevski** [comment]
https://stackoverflow.com/a/52988849/8863446
This solution worked for me.

**Comment by rgomezp** [comment]
Awesome. Thanks @n-nitchevski 

**Steps to solve this issue:**

- Build Setting
- Search Enable Bitcode option in Build Options category.
- Select no.
