### ISSUE TITLE
3 App target, Create 3 Service notification ?

### ISSUE THREAD

**Issue by RomainDev25** [OneSignal/OneSignal-iOS-SDK#498]
Hello, I am reading to implement OneSignal in our native application 
https://documentation.onesignal.com/docs/ios-sdk-setup

We have 3 targets for 3 applications in our project.
We need to create 3 OneSignalNotificationServiceExtension ? Embed in each application ?

Thanks in advance.

Romain

**Comment by RomainDev25** [comment]
Ok I close this issue because is not really an issue.

If you have several Target. You can add in podfile for each target 

```
target 'APP1' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
...
...
...
end
target 'APP2' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
...
...
...
end
target 'APP3' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
...
...
...
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end
```

You add in constant or config file - Example Config.h and Add it in header of AppDelegate
#ifdef TARGET_APP1
    #define ONESIGNAL @"xxxxx-xxxx-xxx-xxx-APPID_ONESIGNAL_APP1"
#elif defined TARGET_APP2
    #define ONESIGNAL @"xxxxx-xxxx-xxx-xxx-APPID_ONESIGNAL_APP2"
#elif defined TARGET_APP3
    #define ONESIGNAL @"xxxxx-xxxx-xxx-xxx-APPID_ONESIGNAL_APP3"
#endif

And for the code in AppDelegate

`[OneSignal initWithLaunchOptions:launchOptions
 appId:ONESIGNAL
 handleNotificationAction:nil
 settings:@{kOSSettingsKeyAutoPrompt: @false}];
OneSignal.inFocusDisplayType = OSNotificationDisplayTypeNotification;`

Best.

**Comment by rgomezp** [comment]
@RomainDev25 ,
I'm glad you figured it out. Thanks for your detailed response. Cheers
