### ISSUE TITLE
Rich Notifications Not Working

### ISSUE THREAD

**Issue by sdubeyEpic** [OneSignal/OneSignal-iOS-SDK#500]
Rich notifications and not working on ios 12.1.2 and above. Its working perfectly on ios 10 and 11.
OneSignal sdk in not getting launched. Getting following error in console
Could not start an extension session: error=Error Domain=NSCocoaErrorDomain Code=4097

**Comment by rgomezp** [comment]
Could you please provide some further details? Take a look at our issue template. Also, perhaps a log would be useful.

**Comment by rgomezp** [comment]
Closing due to no response
