### ISSUE TITLE
OSNotificationPayload missing exposed parseWithApns method

### ISSUE THREAD

**Issue by AndreaVitale** [OneSignal/OneSignal-iOS-SDK#506]
**Description:**

I'm creating a new Titanium module because the [previous one](https://github.com/williamrijksen/com.williamrijksen.onesignal) isn't mantained anymore.

Due to Titanium' iOS module lifecycle, when I have to process an opened notification after an app' cold boot, I need to translate what I get from `launchOptions.UIApplicationLaunchOptionsRemoteNotificationKey` in a `OSNotificationPayload`.

What I need is to invoke [this method](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Source/OSNotificationPayload.m#L36) but it isn't exposed inside the `OSNotificationPayload` declaration.

I added `+(instancetype)parseWithApns:(NSDictionary*)message;` after [this line](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L153) and everything is working as expected.

Is there some reason why this cannot be done?

**Environment:**

I'm using OneSignal iOS SDK v2.10.0 installed via Carthage.

**Comment by rgomezp** [comment]
Howdy, 
Thanks for your question. It's a valid request and can be easily done. Look for this in the next release!
