### ISSUE TITLE
Rich Notifications and Action Buttons not working

### ISSUE THREAD

**Issue by vaibhavarora03** [OneSignal/OneSignal-iOS-SDK#510]
**Description:**

I am able to send a rich notification with image content only on iPhone 5s iOS 11.2.2. The other 2 devices tested for the notification are iPhone SE iOS 12.1.2 and iPhone 6s iOS 12.3.1. The notifications with textual data are received but the image is not received on the other 2 devices. 

Moreover, when tried adding Actions buttons in the notification, none of the devices was able to receive action buttons.

**Environment**

iOS sdk used is 2.10.0. sdk added via cocoapods

**Steps to Reproduce Issue:**

1. Install iOS SDK version 2.8.2 with Cocoapods into a project--->>>   pod 'OneSignal', '>= 2.6.2', '< 3.0'
2. Initialize the SDK in didFinishLaunchingWithOptions:
3.Attempted to receive a push notification

**Comment by rgomezp** [comment]
Howdy,
Please make sure you've set up the [extension service](https://documentation.onesignal.com/docs/service-extensions#section-notification-service-extension) correctly

**Comment by vaibhavarora03** [comment]
Yes, the extension service has been integrated correctly. I'm able to receive rich notification on device running ios 11.

**Comment by rgomezp** [comment]
Try uninstalling the app and reinstalling it as well as rebooting the device before testing again

**Comment by vaibhavarora03** [comment]
Tried that several times but didn't work.

**Comment by rgomezp** [comment]
Howdy,
Could you please include your OneSignal logs?

**Comment by SloanHawthorne** [comment]
I am also having the same issue on my iPhone XS Max on the iOS 13 beta 7. No images are being shown only the text.

**Comment by jkasten2** [comment]
@vaibhavarora03 On your OneSignalNotificationServiceExtension target in Xcode can you go to "Build Settings" search for "Other Linker Flags" and add `-ObjC`. Let us know if this fixes the issue with images for you.

The buttons may still have an issue but we still looking into it.

**Comment by rgomezp** [comment]
Closing due to no response
