### ISSUE TITLE
Is it able to show result on dashboard if I send request from postman

### ISSUE THREAD

**Issue by chenkuanhuaian** [OneSignal/OneSignal-iOS-SDK#515]
**Description:**

(your description here)

Hi, I know github issue is mainly for bug report.

But I have read all the documentation that I am able to reach and find nothing for my question.

I would like to know if I send request through postman,

is there any chance that I can check that notification info like click rate in the OneSignal dashboard?

Thank you!

**Comment by rgomezp** [comment]
Yes, you should see it in your dashboard. Cheers!
