### ISSUE TITLE
Blank Screen on Xcode Device Build

### ISSUE THREAD

**Issue by Jaquedeveloper** [OneSignal/OneSignal-iOS-SDK#519]
**Description:**
Error when building for production on Xcode 10.
I've checked and searched for other files referencing the LocalNotification but couldn't find anything.

Related to this issue: [#68](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/68)

White screen on device and the following Error on Console:

```
WARNING: OneSignal has detected that your application delegate implements a deprecated
method (application:didReceiveLocalNotification:). Please note that this method has been
officially deprecated and the OneSignal SDK will no longer call it. You should use
UNUserNotificationCenter instead
WARNING: OneSignal has detected that your application delegate implements a deprecated
method (application:handleActionWithIdentifier:forLocalNotification:completionHandler:).
Please note that this method has been officially deprecated and the OneSignal SDK will no
longer call it. You should use UNUserNotificationCenter instead
```

**Environment**

**Steps to Reproduce Issue:**

1. Followed installation instructions [here](https://documentation.onesignal.com/docs/ionic-sdk-setup#section-5-ios-part-1-required-) and [here too](https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension-recommend-)
2.Build on device through Xcode
3.Run App
4.Splash Screen
5.Blank Screen

**Additional Info:**

The last shown console message is telling that the app is loading the first page which should be correct if it was loading and showing, but it isn't:
`Finished load of: file:///var/containers/Bundle/Application/random-number/AppName.app/www/index.html#/tab/tabname`

Please, Help.
Thank you very much.

**Comment by Nightsd01** [comment]
Hi @Jaquedeveloper the log file is just a warning and wouldn’t have anything to do with a “white screen”...?

Try removing OneSignal from your project and see if the issue still happens. This likely has something to do with some recent change you made or some UI configuration

**Comment by Nightsd01** [comment]
I’d close this.

**Comment by jkasten2** [comment]
@Jaquedeveloper Please provide an example project reproducing the issue if the above does not help and we can take a look.
