### ISSUE TITLE
Error on init (ios 7)

### ISSUE THREAD

**Issue by Pelican43** [OneSignal/OneSignal-iOS-SDK#52]
Hi,

When I try to init onesignal with app id:  [OneSignal initWithLaunchOptions:launchOptions appId:@"xxxxx"];

The app crashes with this message in debug console:

_-[__NSCFConstantString containsString:]: unrecognized selector sent to instance 0x97daa8
2016-08-09 16:31:42.518 xxxxxx[6887:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString containsString:]: unrecognized selector sent to instance 0x97daa8'_ 

This issue occurs only on ios 7. 

; )

Best regards.

**Comment by PasqualePuzio** [comment]
Same issue here. Hope you can fix it ASAP. Thanks :)

**Comment by artemtarassov** [comment]
same here, this issue occurs on iOS 6 too, v 2.0.3

**Comment by Pelican43** [comment]
Hello guys,

The bug seems to be fixed with the last release 2.0.5

Best regards
