### ISSUE TITLE
Somehow [OneSignalAppDelegate oneSignalApplicationDidEnterBackground] calls  AppDelegate.applicationWillEnterForeground

### ISSUE THREAD

**Issue by aharriscrowne** [OneSignal/OneSignal-iOS-SDK#520]
**Description:**

I am trying to resolve a number of crash reports where the stack trace shows the device enter the background, [OneSignalAppDelegate oneSignalApplicationDidEnterBackground] getting called followed immediately by a call to AppDelegate.appWillEnterForeground(_:).  All devices are running on iOS 11, and using version 2.9.5 of OneSignal SDK.  I have not successfully replicated the crash.  When I go into the background, [OneSignalAppDelegate oneSignalApplicationDidEnterBackground] properly calls AppDelegate.appDidEnterBackground(_:).

**Environment**

**Steps to Reproduce Issue:**

**Comment by rgomezp** [comment]
Please follow our issue template
