### ISSUE TITLE
Apple is rejecting OneSignal SDK because UIWebView

### ISSUE THREAD

**Issue by arthurdapaz** [OneSignal/OneSignal-iOS-SDK#522]
**Description:**
Apple is not rejecting Apps that uses directly or indirectly UIWebViews (OneSignal framework, GoogleSignIn sdk, are included because the presence of UIWebViews that are deprecated since now)

**Environment**

Swift 5 (target: iOS 10.0), latest OneSignal framework

**Steps to Reproduce Issue:**

1.  Send new App for TestFlight that uses OneSignal iOS SDK
2. Wait for automatic app review
3. Boom. Rejected

**Anything else:**

Didn`t find any branch dealing with this issue

**Comment by inkly** [comment]
Same here

**Comment by jkasten2** [comment]
@arthurdapaz @inkly Thanks for reporting, a fix has been merge in and will be included in the next release

**Comment by Aarbel** [comment]
do you have any infos when the next release will be available ?

**Comment by prabhashibuddhima** [comment]
Hi, 

I'm facing the same problem. How can I fix it?

**Comment by jkasten2** [comment]
This fix was included in [OneSignal-iOS-SDK 2.10.2](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.10.2) released Sep. 3 2019.
