### ISSUE TITLE
About email: URGENT & IMPORT iOS 13 Update Changes

### ISSUE THREAD

**Issue by itsector-esanti** [OneSignal/OneSignal-iOS-SDK#529]
Hello guys,

I have been received an email with subject is: "URGENT & IMPORT iOS 13 Update Changes"

So, I would like to know if I have 2.8.4 version, Do I need to update the SDK via cocoapods to 2.10.2 just? Or, do I need to migrate some code?

Thank you!

**Comment by r00li** [comment]
I have one question regarding this email as well... it's not entirely clear if this only applies to the apps that will be built with the new version of the iOS SDK, or if iOS 13 breaks this for current apps already on the appstore.

**Comment by itsector-esanti** [comment]
Could you help us @mikechoch?

**Comment by rgomezp** [comment]
Hello all,
If you would like to avoid any issues, you will want to update the SDK and ship a new build asap. iOS 13 _will_ indeed break the push-token retrieval technique for existing app builds that have not made the change. Releasing an update asap is the best way to ensure the transition is made smoothly.

**Comment by r00li** [comment]
@rgomezp Thanks for the reply. In that case we will update the app as soon as possible. 

We did test our app on a device running iOS 13 beta and push notifications were working fine. But if I understand this, the issue is with push token retrieval? So users that have the app already installed should still be ok (unless their push token changes)?

**Comment by rgomezp** [comment]
That's right. Existing users won't be impacted. This would just impact new subscribers.

**Comment by rgomezp** [comment]
@geshub ,
You have to make sure to build the app with the latest XCode version

**Comment by ldco2016** [comment]
@geshub , to be clear, when updating OneSignal to work with iOS 13, we also need to update Xcode to version 11?

If so, is that possible with High Sierra 10.13.6

**Comment by jkasten2** [comment]
In general we always recommend updating to the latest SDK to ensure you have the latest maintenance updates and bug fixes.

Specifically for this token issue if you build your app with Xcode 11 you will need to make sure to update the [OneSignal-iOS-SDK 2.10.1](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.10.1) or newer.

The OneSignal-iOS-SDK 2.10.0 and older still works on iOS 13 devices if your app was build with Xcode 10 or older. [Apple will still allow you to ship new app updates until April 2020 at which point you must update to Xcode 11.](https://developer.apple.com/app-store/submissions/)
