### ISSUE TITLE
_CGAffineTransformIdentity and _CGAffineTransformMakeScale symbols not found

### ISSUE THREAD

**Issue by skuske** [OneSignal/OneSignal-iOS-SDK#531]
**Description:**
Error during build. See screenshot:

<img width="794" alt="Bildschirmfoto 2019-09-10 um 07 50 22" src="https://user-images.githubusercontent.com/12996815/64587441-b0bdcb80-d39f-11e9-9322-24e0c61d2d78.png">

**Environment**

1. v2.11.0
2. Added manually, Xcode 11 Beta 7

**Steps to Reproduce Issue:**

  1. Install iOS SDK version v2.11.0 manually
  2. Initialize the SDK in didFinishLaunchingWithOptions:
  3. Build

** What I tried:

Cleaning build folder, deleting Derived Data folder, restarted Xcode. Nothing helps.

I went back to 2.10.2 and the issue disappeared. However, in 2.10.2 there are all those [warnings](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/525), and still no fix for them. This really sucks, sorry, as we get new issues with every release.

**Comment by mikechoch** [comment]
I could not reproduce this issue using CocoaPods and the build error is related to a new framework we added into the SDK with this release called `CoreGraphics.framework`. I assume since you did the update manually it missed adding this framework somehow.

Can you tell me your exact steps to add OneSignal v2.11.0 manually?

I highly recommend using CocoaPods over manually adding or updating any dependencies.

**Comment by skuske** [comment]
Well, I copied the new framework and pasted it into my project folder, overwriting the old version. Then the error appeared. I then cleaned the project, deleted the DerivedData folder, restarted Xcode, re-build. No luck.

I then added the `CoreGraphics.framework` to my project. No change. Still the same error.

I don't know what else to try.

**Comment by mikechoch** [comment]
Your other option is using CocoaPods, as I have not seen this issue (and cannot reproduce it), but for some reason your project is not including `CoreGraphics.framework`, which is where `CGAffineTransformIdentity` and `CGAffineTransformMakeScale` come from. 

Our documentation shows you how to use CocoaPods and it is very easy to follow the setup guide:
[OneSignal iOS SDK Setup Guide](https://documentation.onesignal.com/docs/ios-sdk-setup)

**Comment by fatsjohonimahnn** [comment]
@skuske Can you please email support@onesignal.com so we can send you an updated OneSignal.framework file for you to test?

**Comment by skuske** [comment]
Just emailed support. Thanks.

**Comment by ReneMarquez** [comment]
same thing happened to me trying to update sdk manually using the instructions on the react native sdk setup:

[https://documentation.onesignal.com/docs/react-native-sdk-setup#section-manually-updating-ios-onesignalnativesdk](url)

**Comment by rgomezp** [comment]
@ReneMarquez ,
Could you please update your react-native SDK too 3.4.1?

**Comment by skuske** [comment]
@fatsjohonimahnn, @rgomezp 

Is there any news? The framework I received from support did not solve the problem and since then I have not heard anything and have not received any other suggestions to solve the problem.

**Comment by rgomezp** [comment]
Please try updating to 3.4.1 and try again @skuske

**Comment by skuske** [comment]
@rgomezp

I am not using Cocoapods! I need a solution for those who add the framework manually.

**Comment by rgomezp** [comment]
@skuske ,
You don't need to use Cocoapods for the solution to work. Simply update the npm package and run a clean-build
