### ISSUE TITLE
Mismatched User Environment on iOS 13.1

### ISSUE THREAD

**Issue by Vuong-Dao** [OneSignal/OneSignal-iOS-SDK#535]
**Description:**

Hi there
I did update the latest iOS SDK (2.11.0) and when I ran it on my device iOS 13.1 (GM), I got this problem
```
Mismatched User Environment (Production)
Apple returned a BadDeviceToken error. Some users are tied to a different environment from your sending environment.

This warning occurred 1 time, last occurring less than 20 seconds ago.

Affected users: 6a7f3338-de27-4691-b71a-b64055f7d1ae
```
More details about env
1. iOS SDK: 2.11.0
2. XCode Version 11.0 (11A420a)
3. I'm sure that my certificates are still valid for both Sandbox and Production

**Comment by rgomezp** [comment]
Can you please try to re-upload your certs?

**Comment by Vuong-Dao** [comment]
Yes. It worked with the new certs.
Thanks for your help @rgomezp
