### ISSUE TITLE
Crash when opening text notification

### ISSUE THREAD

**Issue by PasqualePuzio** [OneSignal/OneSignal-iOS-SDK#54]
Hi,

as you can see from this stacktrace http://crashes.to/s/71adf86cef9 OneSignal's SDK is causing a crash whenever a user tries to open a notification.

Could you please fix it ASAP?

Thanks

**Comment by JKalash** [comment]
Hi,

Looking in tot he issue. Which version of the OneSignal SDK are you using?

**Comment by PasqualePuzio** [comment]
2.0.1

**Comment by JKalash** [comment]
This issue has been resolved in later releases of the SDK.
