### ISSUE TITLE
Crash when sending inApp to test device

### ISSUE THREAD

**Issue by pclemente** [OneSignal/OneSignal-iOS-SDK#542]
**Description:**

When sending an in App message to a test device, the App crashes

**Environment**

We are using the latest version of the SDK (2.11.1) installed via Cocoapods

**Steps to Reproduce Issue:**

1. Install the SDK via cocoapods
2. Initialise OneSignal following the documentation
3. Add a test device
4. Create an in-App message via the dashbaord and tap on "Test on preview device"
5. When viewing the message in the App, tap on the X to close it and the App crashes

**Anything else:**

this is the crash stacktrace

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1ba063278 __exceptionPreprocess
1  libobjc.A.dylib                0x1b9d8c0a4 objc_exception_throw
2  CoreFoundation                 0x1b9f66f94 -[NSOrderedSet initWithSet:copyItems:]
3  UIKitCore                      0x1be073520 -[UIResponder doesNotRecognizeSelector:]
4  CoreFoundation                 0x1ba067350 ___forwarding___
5  CoreFoundation                 0x1ba06910c _CF_forwarding_prep_0
6  MyApp                      0x102476530 -[OSMessagingController messageViewControllerWasDismissed] + 299 (OSMessagingController.m:299)
7  MyApp                      0x10249445c __72-[OSInAppMessageViewController dismissCurrentInAppMessage:withVelocity:]_block_invoke.257 + 434 (OSInAppMessageViewController.m:434)
8  UIKitCore                      0x1be4beaf4 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:]
9  UIKitCore                      0x1be493000 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:]
10 UIKitCore                      0x1be493508 -[UIViewAnimationState animationDidStop:finished:]
11 QuartzCore                     0x1c09d4f7c CA::Layer::run_animation_callbacks(void*)
12 libdispatch.dylib              0x1b9d311cc _dispatch_client_callout
13 libdispatch.dylib              0x1b9d143e0 _dispatch_main_queue_callback_4CF$VARIANT$armv81
14 CoreFoundation                 0x1b9fe0c74 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
15 CoreFoundation                 0x1b9fdbc68 __CFRunLoopRun
16 CoreFoundation                 0x1b9fdb16c CFRunLoopRunSpecific
17 GraphicsServices               0x1c3e13328 GSEventRunModal
18 UIKitCore                      0x1be045d0c UIApplicationMain
19 MyApp                      0x1022332a0 main + 23 (Tag.swift:23)
20 libdyld.dylib                  0x1b9e66424 start

**Comment by ReneMarquez** [comment]
same issue, I upgraded the sdk manually as the onesignal guide says (I don't know if that method is still valid) and if you have the app opened and send a In-App message to that device from the onesignal page, it crashes; if you have the app in the background, it succesfully displays a notification that says something like "Tap this notification to display the in app message" and if you do, the app opens and displays the In App message correctly

**Comment by mikechoch** [comment]
This ended up being a more in depth issue. Will be fixed in the next minor release.

**Comment by pclemente** [comment]
@mikechoch is there an ETA on the next release? Thanks!

**Comment by jkasten2** [comment]
@pclemente @ReneMarquez Thanks for reporting. This is now released in 2.11.2
https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.11.2

**Comment by pclemente** [comment]
@jkasten2 this issue is still happening in version 2.11.2

**Comment by ReneMarquez** [comment]
> @jkasten2 this issue is still happening in version 2.11.2

did you run pod install after installing newest react-native-onesignal version?
I'm testing right now and its not crashing anymore

**Comment by pclemente** [comment]
@jkasten2 I'm using the iOS native SDK. It's exactly the same crash as before. I've tried running pod install to no avail

**Comment by rgomezp** [comment]
This will be resolved in the next release. Cheers

**Comment by jkasten2** [comment]
This is now fixed in the 2.12.0 release
https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.12.0
