### ISSUE TITLE
VoIP push notification not appeared in device.

### ISSUE THREAD

**Issue by KishanVyas** [OneSignal/OneSignal-iOS-SDK#547]
**Description:**

I followed the same steps of OneSignal documents. But when I am sending VoIP notification using CURL command by passing separate VoIP app's player id, I am not getting VoIP push notification. But when I am using "Pusher" app to send VoIP notification, I am receiving VoIP notification.

**Environment**
1. I am using iOS 11.2.6 and OneSignal Latest Version.
2. Using CocoaPods.

**Comment by caglarcakar** [comment]
I am having the same problem since latest updates. Voip push is working at production but there is a problem at sandbox pushes. As you said, it is working with the Pusher app.

**Comment by rgomezp** [comment]
Please follow our issue template. Thanks

**Comment by KishanVyas** [comment]
@rgomezp , I mentioned above which iOS version I am using. I am not getting VoIP push notification in iOS 11.2.6 in Development mode.

**Comment by jfishman1** [comment]
1 - Make sure the push token from pushkit is valid and uploaded to a separate OneSignal app via our [API Add A Device POST call ](https://documentation.onesignal.com/reference#add-a-device)

You must use a push kit registered push token and upload it to OneSignal via our API Add a device call. A normal push token from our SDK does not work with voip.

2 - Make sure you uploaded a VOIP PUSH CERTIFICATE from Apple. See #2 on this page: https://documentation.onesignal.com/docs/voip-notifications

3 - If you are still having issues, you need to turn on logging (use our setLogLevel method to VERBOSE) for your app and share with us the following:

1 - specifically where you get the pushkit push token and what it is
2 - the API call you use to register the device with OneSIgnal using that push token
3 - the call you make to this device to send the voip push
4 - the log from the device when it receives this voip push notification.

**Comment by rgomezp** [comment]
@KishanVyas ,
I understand. Can you explain how you're using PushKit (e.g: what are you using it for?)

**Comment by rgomezp** [comment]
Closing due to no response
