### ISSUE TITLE
OneSignal.presentAppSettings() does not exist

### ISSUE THREAD

**Issue by cesarcarlos75** [OneSignal/OneSignal-iOS-SDK#548]
**Description:**

I am trying to present the app settings but when I use OneSignal.presentAppSettings(), I get "Type 'OneSignal' has no member 'presentAppSettings'". I am importing OneSignal at the top. I did a search and there is no presentAppSetings function anywhere in the code.

**Environment**

1. What version of the iOS SDK are you using? >= 2.6.2 <3
2. How did you add the SDK to your project (eg. cocoapods) Cocoapods

**Steps to Reproduce Issue:**

1. Install iOS SDK with Cocoapods and Podfile pod 'OneSignal', '>= 2.6.2', '< 3.0'
2.Initialize the SDK in didFinishLaunchingWithOptions:
3.Add a button in a view with the code 
OneSignal.presentAppSettings()
and add import OneSignal at the top

**Comment by rgomezp** [comment]
Howdy,
I am not seeing the same results when searching. Take a look [here](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/72cb08ed24e8be4f3ad0e9c95c00e7dd575808a1/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L763)

**Comment by rgomezp** [comment]
Closing due to no response
