### ISSUE TITLE
Question: WatchOS 6 independent app

### ISSUE THREAD

**Issue by lechuckcaptain** [OneSignal/OneSignal-iOS-SDK#556]
**Description:**
It's not 100% clear from the documentation if the SDK support also WatchOS 6 [independent app](https://developer.apple.com/documentation/watchkit/creating_independent_watchos_apps) 
(without a companion iOS app).

A similar question has been raised also on #159 but closed due to inactivity. With the introduction of independent app I think the topic has increased its importance.

**Comment by rgomezp** [comment]
As mentioned in that issue, there is no Watch-specific methods or settings currently

**Comment by lechuckcaptain** [comment]
@rgomezp does this mean that it's possible to use the OneSignal-iOS-SDK with complete functionalities into a Watch OS independent app without any iOS companing app?

**Comment by rgomezp** [comment]
Correct @lechuckcaptain

**Comment by lechuckcaptain** [comment]
Unfortunately what I need is an explicit support of WatchOS independent app, without any iOS installation. 

Based on @jkasten2 answer, is there any available workaround (maybe doing some manual works) in order to use OneSignal for sending notification to WatchOS independent apps?

**Comment by jkasten2** [comment]
@lechuckcaptain Since it isn't built into this SDK you could call `WKExtension registerForRemoteNotifications` from your app and setup the `WKExtensionDelegate` noted above to get the APNs token from the watch. Then make a [REST API POST to /players](https://onesignal.com/api/v1/players) call to register the device with OneSignal. Once the device is registered you can send push notifications from OneSignal to watch directly.

**Comment by owenzhao** [comment]
An independent Apple Watch app means that the app must still work without iOS companion app.  

That means SDK should allow register device on watchOS extension side, which doesn't support on current OneSignal SDK.

I asked a question on this in today's Zoom meeting by OneSignal. The answer is no. But OneSignal will provide it if developers want it badly.

So provide your needs here. 😉😉😉😉😉😉😉😉

**Comment by rgomezp** [comment]
Thanks for the question. Will close the issue for now. Let us know if you have further questions or concerns

**Comment by SwiftiSwift** [comment]
Any update ?

**Comment by NathaSuleSM** [comment]
Any Update on Independent watch app Push notification?

**Comment by ramakrishnantag** [comment]
Any Update on Independent watch app Push notification?

**Comment by dwburns** [comment]
+1 request to add standalone watch support

**Comment by valeriolg** [comment]
+1
