### ISSUE TITLE
WKWebView [Process] kill() returned unexpected error 1

### ISSUE THREAD

**Issue by rgomezp** [OneSignal/OneSignal-iOS-SDK#563]
**Description:**
This is not an issue with OneSignal. But rather, it's a bug in WebKit (or the underlying OS itself). And no, it was not fixed in 13.2 release. 

Read more:
- https://stackoverflow.com/questions/58321114/why-i-get-the-console-warning-process-kill-returned-unexpected-error-1-when
- https://bugs.webkit.org/show_bug.cgi?id=202173
- https://www.mail-archive.com/webkit-changes@lists.webkit.org/msg146193.html

**Environment**
iOS 13.2

**Steps to Reproduce Issue:**

1. Send notification with URL
2. Click the notification to open WebView
3. Drag down the WebView

**Anything else:**

```

error 16:02:01.405102-0800 MyApp kill() returned unexpected error 1
error 16:02:01.405478-0800 MyApp kill() returned unexpected error 1
error 16:02:01.406075-0800 MyApp kill() returned unexpected error 1
error 16:02:01.406235-0800 MyApp kill() returned unexpected error 1
error 16:02:01.412492-0800 MyApp kill() returned unexpected error 1
error 16:02:01.414901-0800 MyApp kill() returned unexpected error 1
error 16:02:01.427866-0800 MyApp kill() returned unexpected error 1
error 16:02:01.428078-0800 MyApp kill() returned unexpected error 1
error 16:02:01.470858-0800 MyApp kill() returned unexpected error 1
error 16:02:01.470901-0800 MyApp kill() returned unexpected error 1
error 16:02:01.470959-0800 MyApp kill() returned unexpected error 1
error 16:02:01.471025-0800 MyApp kill() returned unexpected error 1
```

**Comment by jkasten2** [comment]
Closing and locking this issue, this will just be used for reference.
