### ISSUE TITLE
Carthage Task failed with exit code 65:

### ISSUE THREAD

**Issue by huahengling** [OneSignal/OneSignal-iOS-SDK#566]
**Description:**

I encountered error while trying to build OneSignalSDK. Below is the error message from the terminal 
```
*** Building scheme "OneSignal-Dynamic" in OneSignalSDK.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/heng/Documents/GetIT/Carthage/Checkouts/OneSignal-iOS-SDK/iOS_SDK/OneSignalSDK.xcworkspace -scheme OneSignal-Dynamic -configuration Release -derivedDataPath /Users/heng/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2_11B52/OneSignal-iOS-SDK/2.12.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/16/76y0qtj54xz99thllhw0x4z80000gn/T/OneSignal-iOS-SDK SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/heng/Documents/GetIT/Carthage/Checkouts/OneSignal-iOS-SDK)
```
from the log, 
```
The following build commands failed:
	CompileC /Users/heng/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2_11B52/OneSignal-iOS-SDK/2.12.0/Build/Intermediates.noindex/ArchiveIntermediates/OneSignal-Dynamic/IntermediateBuildFilesPath/OneSignal.build/Release-iphoneos/OneSignalFramework.build/Objects-normal/x86_64h/OSUniqueOutcomeNotification.o Source/OSUniqueOutcomeNotification.m normal x86_64h objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```
**Environment**

1. OneSignal-iOS-SDK at "2.12.0" using carthage
2. Xcode 11.2, I have multiple version of xcode installed in my mac 
3. Mac OS Catalina

**Steps to Reproduce Issue:**

I have older version of onesignal SDK
1. carthage update --platform ios

**Comment by makoni** [comment]
Same for me

**Comment by callo90** [comment]
same in here, any updates?

**Comment by rgomezp** [comment]
Thanks for your patience while we work to resolve this. In the meantime, you can either:
1) use a previous version of the SDK
2) switch to Cocoapods

Cheers

**Comment by knbmedia** [comment]
Same for me (sdk 11.2.0 on Mojave, xCode 11.2.1, Carthage 0.34.0).
Previous SDK version 2.11.2 works.

**Comment by rgomezp** [comment]
Howdy,
We believe to have identified the issue. The problem seems to be that Carthage only supports dynamic frameworks. Our last release builds the framework statically. We will have to provide an alternate build-script in the Dynamic framework target to support Carthage users.

Thanks for your patience while we resolve.
