### ISSUE TITLE
Not compiling for simulator

### ISSUE THREAD

**Issue by animeshp** [OneSignal/OneSignal-iOS-SDK#575]
**Description:**
No symbols found error when running app on simulator.

> Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_OneSignal", referenced from:
      objc-class-ref in NotificationService.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Environment**

1. OneSignal iOS SDK v2.12.2
2. Added OneSignal SDK using Cocoapods

**Steps to Reproduce Issue:**

1. Install iOS SDK version 2.12.2 with Cocoapods into a project using ``pod 'OneSignal', '>= 2.12.2', '< 3.0'``
2. Try to run the app. The app doesn't compile fully and throws the error written in description.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@animeshp The latest OneSignal build does not have `i386` for the simulator. This is something we will be fixing, however I recommend switching over only use `x86_64` for your simulator builds. Apple will most likely be dropping `i386` in the future.

**Comment by animeshp** [comment]
@jkasten2  These are the current settings for my project. Anything else needs to be changed?

<img width="699" alt="Screen Shot 2019-12-10 at 2 44 29 PM" src="https://user-images.githubusercontent.com/4133494/70575648-cdfb6500-1b5b-11ea-9ca5-acf8d113e816.png">

**Comment by jkasten2** [comment]
@animeshp The error specific points to `NotificationService`. I recommend checking that target too.

Which iOS sim device are you using and what version of Xcode?

**Comment by animeshp** [comment]
I checked that target too. I'm using `iPhone 11 Pro (iOS 13.2.2)` and `Xcode v11.2.1`. But same issue happens for any other simulator device for older iOS versions too.
