### ISSUE TITLE
OSSubscriptionStateChanges always return null in Swift 4

### ISSUE THREAD

**Issue by zanohikaru7** [OneSignal/OneSignal-iOS-SDK#581]
**Description:**

Hi, I am using Device iPad, iPhone XS Max, Simulator, Why does OSSubscriptionStateChanges always return null? I am trying to get my userId/playerId. I did some research about this. One of the support of OneSignal says that it's because of the ISP. Is there any way to get the playerId? Thanks! 

**Environment**
1. What version of the iOS SDK are you using? - 'OneSignal', '>= 2.6.2', '< 3.0'
2. How did you add the SDK to your project (eg. cocoapods) - Cocoapods

**Steps to Reproduce Issue:**

  1. Install iOS SDK version '>= 2.6.2', '< 3.0' with Cocoapods into a project
  2. Initialize the SDK in didFinishLaunchingWithOptions:
  3. Re-install the app and debug it and found out that OSSubscriptionStateChanges is returning blank.

**Anything else:**

N/A

**Comment by mikechoch** [comment]
You should be using `OneSignal.getPermissionSubscriptionState.subscriptionStatus.userId` to obtain the user id. The `OSSubscriptionStateChanges` will only be populated with values that have caused a change on to the device being used. 

Make sure the user is registering on the OneSignal dashboard also.
