### ISSUE TITLE
How to generate mobileprovision for OneSignal extension

### ISSUE THREAD

**Issue by rok5ek** [OneSignal/OneSignal-iOS-SDK#582]
**Description:**
I'm trying to generate a .mobileprovision for OneSignal extension. Currently I generated a new certificate with the https://onesignal.com/provisionator, my new certificate with was generated with type "Apple Push Services". How can I now create a provisioning profile for OneSignal extension?

(your description here)

**Environment**

1. Version 2.13.2

**Steps to Reproduce Issue:**

1. Create certificate with https://onesignal.com/provisionator

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
Duplicate of https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/187
