### ISSUE TITLE
Hi Team  I have integrated OneSignal 15 Days Back and it was working fine in Both iOS and Android till 24th of Dec But now (26th Dec) its not working in iOS, Is any changes done by OneSignal Team or Apply did some changes in the Push Notification.? 

### ISSUE THREAD

**Issue by do-lokesh** [OneSignal/OneSignal-iOS-SDK#585]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by mikechoch** [comment]
We will need a lot more detail to help you out here. Please fill in the template you commented. What is not working? Do you have any log files?

**Comment by rgomezp** [comment]
Closing due to no response
