### ISSUE TITLE
iOS 13 Push Token issue

### ISSUE THREAD

**Issue by priyankastridhyatech** [OneSignal/OneSignal-iOS-SDK#587]
**Description:**

Hello 
I am working on Xcode 11.2.1 swift 4.0 and  while running the application i am getting device token like this 

userID = {length=32,bytes=0xb932afbf1cb757fed3375c57f30e403e...077c7d158020df42}

I want token in string formate which i am getting in  lower 13 version 

(your description here)

**Environment**

target 'project name' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OneSignal'
  # Pods for projectname

target 'NotificationService'

  use_frameworks!
  pod 'OneSignal'

  
end

**Comment by mikechoch** [comment]
Make sure you are using the newest OneSignal SDK, try running `pod update` or `pod install`
The latest OneSignal SDK (as of this comment) is `2.12.3`, but the iOS 13 Push Token issue was fixed and released in `2.10.1`.
