### ISSUE TITLE
Error ITMS-90680 "Invalid directory" for OneSignalNotificationServiceExtension.appex

### ISSUE THREAD

**Issue by otymartin** [OneSignal/OneSignal-iOS-SDK#589]
@JKalash
**Description:**
While archiving my build I get the App Store error
```Error ITMS-90680 "Invalid director" The bundle Payload/ProjectName.app/OneSignalNotificationServiceExtension.appex is not contained in a correctly named directory. It should be under "Plugins"```

**1. What version of the iOS SDK are you using?**
Im using 2.12.13
**2. How did you add the SDK to your project (eg. cocoapods)**
Installed using Cocoapods

**Steps to Reproduce Issue:**

Archive your release build to the App Store - error will come while archiving.

**Comment by jkasten2** [comment]
@otymartin From a search it looks like you have "Copy Bundle Resources" set. See the answer to fix.
https://stackoverflow.com/a/57896447/1244574

**Comment by otymartin** [comment]
@jkasten2 saw that earlier, rearchiving to see if its fixed

**Comment by otymartin** [comment]
@jkasten2 I can confirm that this is the solution.

Thanks :)
