### ISSUE TITLE
userSubscriptionSetting in OSSubscription.m is initialized with wrong value since 2.12.1

### ISSUE THREAD

**Issue by soaa** [OneSignal/OneSignal-iOS-SDK#596]
**Description:**
OneSignal.setSubscription code was changed since 2.12.1 to save UserDefaults.ONESIGNAL_SUBSCRIPTION value with type of boolean.
But due to the unchanged initialization implementation in OSSubscription.m,   _userSubscriptionSetting always has a false value after the setSubscription status once changed.

**Environment**
1. iOS SDK version: 2.12.1 ~

**Steps to Reproduce Issue:**
  1. Install iOS SDK version 2.12.1 or later with Cocoapods into a project
  2. Initialize the SDK in didFinishLaunchingWithOptions:
  3. in app, setSubscription to true or false whatever
  4. cold restart app
  5. subscriptionStatus.subscribed of getPermissionSubscriptionStatus() will always return false whatever you choose in step 3

Actually, when setSubscription called the server-side data is updated correctly, but the problem is userSubscriptionSetting is initialized with only client data which UserDefaults.ONESIGNAL_SUBSCRIPTION value compared to nil. But since SDK 2.12.1, UserDefaults.ONESIGNAL_SUBSCRIPTION value cannot be a **nil** anymore, so userSubscriptionSetting always has false value.

Because I'm not an expert of objective-c language, instead of making pull-request of code, I send a link of code causing the issue.

https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Source/OSSubscription.m#L50

**Comment by mikechoch** [comment]
This should be fixed in release `2.12.5`
