### ISSUE TITLE
Subscribed user has their OneSignal subscription status changed to ’User manually opted out’ whenever restarting my app

### ISSUE THREAD

**Issue by elviva404** [OneSignal/OneSignal-iOS-SDK#603]
**Description:**

I have an app with two environments, **Production(Prod)** and **Development(Dev)**, they both have their respective schemes and individual One Signal accounts.

Everything was working perfectly when working on Dev, after switching to production, I started noticing all subscribed users had their subscribed status changed to User manually opted out.

No Code changes had been made in transitioning from dev to Prod. The code is 100% identical. I have spent days trying to find a solution, no headway has been made.

The following are checks we have done in attempts to resolve/investigate the issue.

1. Checking whether we were manually calling setSubscription(false) when i start the app.
2. Checking whether our code manually disables notifications when killing the app.

**Environment**

**Steps to Reproduce Issue:**

1. I set OneSignal.setSubscription(true) when user turns UISwitch On
2. I check dashboard and observe the subscription status is changed to `subscribed`
3. I kill the app and restart it 
4. I check the dashboard and observe that the subscription status has been changed to `User manually opted out`

**Anything else:**
N/A
(crash stacktraces, as well as any other information here)

**Comment by labradon** [comment]
I second this. I observe the exact same issue in my application. Whenever I restart the app, OneSignal unsubscribes the user. The only workaround I found is to manually run `OneSignal.setSubscription(subscribed)` every time the app is launched, where `subscribed` checks wether the user has allowed push notifications in the system settings.

**Comment by labradon** [comment]
This seems to be related to #596  and is fixed in [2.12.5](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.12.5).

**Comment by elviva404** [comment]
Thanks a lot @labradon, updating to 2.12.5 resolved the issue. Thanks for the other answer.

**Comment by RameshTigeen** [comment]
OneSignal.setSubscription(subscribed) 

is deprecated still I have issue
