### ISSUE TITLE
Crash in registerUser

### ISSUE THREAD

**Issue by pcki11** [OneSignal/OneSignal-iOS-SDK#605]
**Description:**
The app crashed in production with the supplied stack trace. Happens not very often, cannot reproduce in debug.

**Environment**
OneSignal SDK version: 2.12.4
Device details from crash report:
Model: iPhone 6
RAM free: 115.8 MB
Disk free: 13.5 GB
Operating System
Version: 12.4.4 (16G140)
Jailbroken: No

**Steps to Reproduce Issue:**
Sometimes crashes on app launch in production, but does not crash in debug, so no precise steps to reproduce.

**Anything else:**
Stack trace:
```
0 libdispatch.dylib dispatch_async$VARIANT$mp + 216
1 libdispatch.dylib dispatch_async$VARIANT$mp + 56
2 app +[OneSignal registerUser] + 337968
3 app __31+[OneSignal updateDeviceToken:]_block_invoke + 336588
4 app __69-[OneSignalNotificationSettingsIOS10 getNotificationPermissionState:]_block_invoke_2 + 430352
5 app __91-[OneSignalUNUserNotificationCenter onesignalGetNotificationSettingsWithCompletionHandler:]_block_invoke + 456932
```

SDK setup code:
```swift
        let onesignalInitSettings = [kOSSettingsKeyAutoPrompt: false]
        OneSignal.initWithLaunchOptions(launchOptions, appId: appId, handleNotificationAction: { _ in
        }, settings: onesignalInitSettings)
        OneSignal.inFocusDisplayType = OSNotificationDisplayType.notification
        OneSignal.add(self)
```
onOSSubscriptionChanged is implemented, but does not do anything special

**Comment by rgomezp** [comment]
Is this only happening on iPhone 6 models? How widespread is the issue?

It's tough to resolve without being able to reproduce.

**Comment by pcki11** [comment]
Happens on iPhone 6+ as well, but with the same version of iOS - 12.4.4. We do not have a lot of users with this OS/device combination, so it is not so critical for us, just thought I'd share the stack trace with you.

**Comment by WClouds** [comment]
Meet the same issue on iphone 6s, ios 11.4.1

**Comment by rgomezp** [comment]
Thanks for your patience while we work to resolve

**Comment by rgomezp** [comment]
Howdy!
Has anyone here been able to reproduce?

**Comment by rgomezp** [comment]
Howdy,
This issue hasn't come up again and we weren't able to reproduce. We'd be happy to re-open if this is still an issue for folks. Cheers
