### ISSUE TITLE
Swiping down to close launch URL notification content causes app to become unresponsive

### ISSUE THREAD

**Issue by starchey** [OneSignal/OneSignal-iOS-SDK#606]
**Description:**

When a push notification is sent with a Launch URL, after the user taps on the notification, our app opens, and a browser view is presented modally with a done button and the URL page displayed (We're not doing anything custom here, this is presented by OneSignal). If the user presses the done button, the browser view closes, and everything works as normal. The user is also able to drag/swipe downward on the modal view, which also closes the browser view, but if they close it using this method, the app becomes unresponsive. The reason for this is an empty view controller persists that sits on top of all the app views.

**Environment**

We are using version 2.12.5 of the OneSignal iOS SDK through cocoapods. We observed this issue on version 2.10.2 and updated to see if that resolved the issue, but we're still able to reproduce.

**Steps to Reproduce Issue:**

1. Install iOS SDK version 2.12.5 with Cocoapods into a project
2. Initialize the SDK in didFinishLaunchingWithOptions:

```
let onesignalInitSettings = [kOSSettingsKeyAutoPrompt: false]
        
OneSignal.initWithLaunchOptions(launchOptions,
                                appId: Config.oneSignalAppId,
                                handleNotificationAction: nil,
                                settings: onesignalInitSettings)

OneSignal.inFocusDisplayType = OSNotificationDisplayType.notification
```

3. App should have a UITabBarController as its rootViewController
4. Put app in background
5. Send a push notification to this device with a Launch URL set
6. Tap on notification to open URL in app
7. After browser modal opens, swipe/drag down to close browser view

Notice at this point the app becomes unresponsive.

**Anything else:**

We tested on various iPhones running iOS 13 flavors and can reproduce 100% of the time on our live app. While testing, after swiping to close the browser window, I paused the execution of the app in Xcode and opened the Debug View Hierarchy tool, and noticed that there is a UIViewController with an empty UIView on top of all the app views that must be blocking all user interaction.

**Comment by rgomezp** [comment]
Thanks for your patience while we review the PR. Cheers

**Comment by FRizzonelli** [comment]
@rgomezp Any ETA on the merge? Encountered same problem. I'd like to try the fix, but I'm working with your React-native package, and it's kind of difficult to link the repo with autolink to a fixed version of your native iOS SDK.

**Comment by rgomezp** [comment]
Thanks for your patience. We will get this out as soon as we can. Cheers

**Comment by sebastienkb** [comment]
+1, we noticed this bug on our production app yesterday and contacted support.
Eager for the update :)

**Comment by starchey** [comment]
We noticed this is still happening with the 2.14.3 update. After the update, the first webView modal you dismiss doesn't cause an issue, but the subsequent one puts you back in the non-responsive state.
