### ISSUE TITLE
Please add a module.modulemap file to your framework file in cocoapods

### ISSUE THREAD

**Issue by roblav96** [OneSignal/OneSignal-iOS-SDK#61]
Modify your `OneSignal.framework` file look like this:
https://github.com/roblav96/nativescript-onesignal/tree/master/platforms/ios/OneSignal.framework
`OneSignal.framework/Modules/module.modulemap`
```
framework module OneSignal {
	umbrella header "OneSignal.h"
	export *
	module * { export * }
}
```
You might not have to add the `Info.plist` file, but xcode wouldn't build without it when I tried.

## WHY?
To make it compatible with [NativeScript](https://www.nativescript.org/).

**Comment by JKalash** [comment]
https://github.com/OneSignal/OneSignal-iOS-SDK/commit/fd228c48e24f4fa11976f1589d686f3639407ac6

**Comment by roblav96** [comment]
Yay :D
