### ISSUE TITLE
Creating Notification with REST API  - click not registered.

### ISSUE THREAD

**Issue by magicry** [OneSignal/OneSignal-iOS-SDK#610]
**Description:**

I use the REST API to send push notification to IOS devices, this works fine and users receive notification. Issue is that when the notification is clicked, it loads app then puts it out of focus immediately.   

When looking at delivery data inside onesignal, it is not registering the notification click at all. Even though all my testers clicked on it. 

**Environment**
unsure of SDK, however was already integrated through WebviewGold.

please see below code im using  - 

```
<?php
	function sendMessage(){
		$content = array(
			"en" => 'Testing new push to specific users '
			);
		
		$fields = array(
			'app_id' => "app id ",
						'data' => array("foo" => "bar"),
						'include_player_ids' => array("player ID here "),
			'contents' => $content
		);
		
		$fields = json_encode($fields);
    	print("\nJSON sent:\n");
    	print($fields);
		
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, "https://onesignal.com/api/v1/notifications");
		curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json; charset=utf-8'));
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
		curl_setopt($ch, CURLOPT_HEADER, FALSE);
		curl_setopt($ch, CURLOPT_POST, TRUE);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);

		$response = curl_exec($ch);
		curl_close($ch);
		
		return $response;
	}
	
	$response = sendMessage();
	$return["allresponses"] = $response;
	$return = json_encode( $return);
	
	print("\n\nJSON received:\n");
	print($return);
	print("\n");
?>
```

**Comment by rgomezp** [comment]
This wouldn't be an issue with the REST API command but rather most likely the way you are handling the click on the client.

How are you handling the click/open client-side?

**Comment by rgomezp** [comment]
Closing due to no response
