### ISSUE TITLE
OneSignalClient not logging innerJson when error is not nil

### ISSUE THREAD

**Issue by saibotsivad** [OneSignal/OneSignal-iOS-SDK#614]
My apologies for the informal nature of this issue, I'm not really an iOS developer, just trying to track down issues in our architecture and spotted an issue that I believe is in `OneSignalClient.m`.

**Description:**

When getting an error back from the API through the SDK, the error does not include the JSON object.

For example, sometimes when failing to register tags, the `error.localizedDescription` is simply `OneSignalError error 400.`

**Anything else:**

I believe this is an error in the code in [OneSignalClient.m](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Source/OneSignalClient.m#L341)

```
if (innerJson != nil && error == nil) {
  // log json
else if (error != nil)
  // log error number
else
  // log nil
```

But if `innerJson != nil` and `error != nil` (for example when the API returns an error status code, but also returns a JSON body) it won't log the `innerJson`.

This does not appear to be intentional, although perhaps I'm missing context? In any case, the lack of `innerJson` makes the error logs in our application less useful.

**Comment by rgomezp** [comment]
Thanks for catching this. This is low priority. I will leave it open nevertheless until we can resolve. 

I also invite the open-source community to contribute to expedite the process!

**Comment by jkasten2** [comment]
@saibotsivad Thanks for reporting. This has now been fixed in the PR above. It will be included in the next release.

**Comment by saibotsivad** [comment]
Thank you!!! And thanks @0xLeif for the PR! 🎉
