### ISSUE TITLE
Critical Alert Authorisation Option

### ISSUE THREAD

**Issue by marchbold** [OneSignal/OneSignal-iOS-SDK#615]
**Description:**

Attempting to request authorisation for critical alerts currently seems impossible. 

**Environment**

Using version v2.12.5 and I'm adding the code directly to our project. 

**Steps to Reproduce Issue:**

1. Setup an application and get approval for critical alerts
2. Add the entitlements

```xml
<key>com.apple.developer.usernotifications.critical-alerts</key>
<true/>
```

3. Call `promptForPushNotificationsWithUserResponse`  
4. Doesn't add the `UNAuthorizationOptionCriticalAlert` auth option to the auth request
5. *Cannot receive critical alerts*

**Anything else:**

I believe some changes need to be made to the [`promptForNotifications`](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L136-L160) function to add `UNAuthorizationOptionCriticalAlert` to the `UNAuthorizationOptions options` before calling `UNUserNotificationCenter requestAuthorizationWithOptions`.

**Workaround**

Manage the authorisation process manually.

**Comment by rgomezp** [comment]
Thanks for bringing this up and your patience while we investigate and see whether adding this enhancement is feasible.

**Comment by rgomezp** [comment]
We will continue tracking this request internally but will close here. Thanks for your patience and understanding

**Comment by marchbold** [comment]
How will I be notified when this is corrected?

**Comment by rgomezp** [comment]
Howdy,
Subscribe to this thread to get updates. Cheers

**Comment by micbis** [comment]
Any news on this one?

**Comment by ikheeteric** [comment]
Any fixes?
