### ISSUE TITLE
One Signal - disable your UNUserNotificationCenterDelegate 

### ISSUE THREAD

**Issue by REPTILEHAUS** [OneSignal/OneSignal-iOS-SDK#618]
Im trying to add One Signal to an Ionic Capacitor app,

Capacitor already has its own functionality for receiving push notifications built in and I would like to use their event listeners for convenience and upgradeability. I logged an issue here with capacitor but they suggest I ask you guys https://github.com/ionic-team/capacitor/issues/2441#issuecomment-588259366 

Is it possible to not use your delegate (UNUserNotificationCenterDelegate) so that the notifications are received using Capacitor's ?

**Comment by rgomezp** [comment]
Take a look at this thread here: https://github.com/OneSignal/react-native-onesignal/issues/605

**Comment by jkasten2** [comment]
@REPTILEHAUS I left a comment on the issue you opened with Capacitor  https://github.com/ionic-team/capacitor/issues/2441#issuecomment-591238438. I recommended a set of possible solutions to be comparability with not just OneSignal but any SDK that uses the  `UNUserNotificationCenterDelegate `.

As far as work around you could:
1. Make your own personal fork of https://github.com/ionic-team/capacitor
   - Remove the if check here https://github.com/ionic-team/capacitor/blob/a0bcf5c62cc7b7ab7881236d75e3d1b8e281575f/ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift#L13
   - Downside is that you will have to merge or rebase your fork to get updates for capacitor
 2. Fork https://github.com/ionic-team/capacitor but implement [one of the suggestions I made](ionic-team/capacitor#2441 (comment))
    - Make a PR back to the main repo afterwards.
    - Downside is more upfront work but if they accept your PR you can keep using the main releases.
3. Use alternative plugins to capacitor
    - Sorry don't have any suggestions here.
4. Wait until Capacitor resolves the compatibility issue.
