### ISSUE TITLE
Fastlane issues with OneSignalNotificationServiceExtension

### ISSUE THREAD

**Issue by REPTILEHAUS** [OneSignal/OneSignal-iOS-SDK#621]
Issues with using Fastlane for deployment - creating the `OneSignalNotificationServiceExtension` results in 2 targets in the project and running fastlane results in the folllowing errors

* its an ionic capacitor project 

```
▸ Copying Keyboard.h
▸ Copying DefaultPlugins.h
▸ Copying Capacitor.h
▸ Copying CAPPluginMethod.h
▸ Copying CAPPluginCall.h
▸ Copying CAPPlugin.h
▸ Copying CAPBridgedPlugin.h
▸ Copying Capacitor-umbrella.h
▸ Linking OneSignalNotificationServiceExtension

❌  ld: framework not found Pods_OneSignalNotificationServiceExtension
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by REPTILEHAUS** [comment]
@rgomezp any reason why it’s closed ?

**Comment by jkasten2** [comment]
@REPTILEHAUS We will need more details to help with this issue.

1. Please double check you have following all OneSignal steps correctly for iOS
https://documentation.onesignal.com/docs/ionic-sdk-setup#section-5-i-os-part-1-required

2. Does Capacitor use Fastlane? Or you using it directly?

3. Can you try to build without Fastlane? It isn't clear if your project was building fine before running it through Fastlane

4. Did you add the `--workspace` param per Fastlanes docs?
https://docs.fastlane.tools/actions/build_ios_app/#usage

5. Please provide any other information you can such as exact command run to build and full logs.

**Comment by REPTILEHAUS** [comment]
Hey @jkasten2 sorry this notification slipped by me. 
This issue was directly related to the fact that there was a mismatch between the xcode deployment targets in my app and the onesignalextentionservice, although I have managed to get past that I am still having issues with the integration, maybe you can shed some light on this for me, to answer your questions:

Please double check you have following all OneSignal steps correctly for iOS
https://documentation.onesignal.com/docs/ionic-sdk-setup#section-5-i-os-part-1-required
- This is not applicable, this is an Ionic/Capacitor app so I am working directly with native code for iOS, I am trying to avoid cordova at all costs.

Does Capacitor use Fastlane? Or you using it directly?
- I am using it directly 

Can you try to build without Fastlane? It isn't clear if your project was building fine before running it through Fastlane
- I was able to build the project before adding the `OneSignalNotificationServiceExtension`, adding it caused this issue and also the issue with multiple targets in one app which is now causing issues with fastlane

Did you add the --workspace param per Fastlanes docs?
https://docs.fastlane.tools/actions/build_ios_app/#usage
- yes I had done that also


when I add a OneSignalNotificationServiceExtension as per your iOS documentation it creates 2 targets in the app, fastlane only seems to want to build one target at a time, Im not sure how to incorporate 2 targets into one app and build, I can run the app no problem in xcode though but as its in a simulator its not much use for testing notifications. 

I have an issue open over there too https://github.com/fastlane/fastlane/issues/16088

**Comment by REPTILEHAUS** [comment]
Closing as it looks like this flag option solves my build issues `export_xcargs: "-allowProvisioningUpdates",`

**Comment by jkasten2** [comment]
@REPTILEHAUS Good to hear you were able to solve this issue, and for the detail in case someone else runs into this Fastlane issue in the future.

**Comment by REPTILEHAUS** [comment]
Yep, happy to report my app is receiving notifications on the native side, I can pop an alert box. Just need to work out how to pass that alert data onto Capacitors own event handlers to be processed by the hybrid side of things.

**Comment by REPTILEHAUS** [comment]
Ive removed some upload to S3 logic and slack but If anyone needs it this is my fastfile:

```
default_platform :ios

platform :ios do
  
  before_all do

    cocoapods(
      podfile: "App",
      use_bundle_exec: false
      )
    
  end

  desc "Build adhoc app"
  lane :beta do
    
    # version = get_version_number
    version = get_version_number(
        xcodeproj: "App.xcodeproj",
        target: "App"
      )    

    build_app(workspace: "App.xcworkspace", 
    export_xcargs: "-allowProvisioningUpdates",
    scheme: "App", 
    export_method: "ad-hoc") 

  end
 
end
```
