### ISSUE TITLE
Add SPM Support

### ISSUE THREAD

**Issue by Ganesh623** [OneSignal/OneSignal-iOS-SDK#625]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
Duplicate, SPM is Swift Package Manager, please see the open issue https://github.com/OneSignal/OneSignal-iOS-SDK/issues/179
