### ISSUE TITLE
some App Delegate methods overrides not called if located in the middle of the inheritance hierarchy

### ISSUE THREAD

**Issue by GeraldDOW** [OneSignal/OneSignal-iOS-SDK#63]
Let's say you have your App Delegate instance of C that derives from B that conforms to UIApplicationDelegate.
The following overrides are never called if located in B (and C does not override any of these methods):
applicationWillResignActive
applicationDidBecomeActive
applicationWillEnterForeground
applicationDidEnterBackground

Current work around:
override these methods in C and call superclass implementation.

Tested with release 2.0.11

**Comment by JKalash** [comment]
Hi,

Just tested the following and it works:

`AppDelegate` class (B) conforms to `UIApplicationDelegate`.
It overrides: 

`- (void)applicationWillResignActive:(UIApplication *)application;
- (void)applicationDidEnterBackground:(UIApplication *)application;
- (void)applicationWillEnterForeground:(UIApplication *)application;
- (void)applicationDidBecomeActive:(UIApplication *)application;
- (void)applicationWillTerminate:(UIApplication *)application;
`

`SubAppDelegate` class (C) inherits from `AppDelegate`. We specify the instance of `SubAppDelegate` to bet the UIApplication's delegate by returning:
`UIApplicationMain(argc, argv, nil, NSStringFromClass([SubAppDelegate class]));` in the main function.
`SubAppDelegate` overrides:

`-(void) application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData*)deviceToken;
-(void) application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error;
-(void) application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo;
- (void)application:(UIApplication *)application handleActionWithIdentifier:(nullable NSString *)identifier forRemoteNotification:(NSDictionary *)userInfo withResponseInfo:(NSDictionary *)responseInfo completionHandler:(void(^)())completionHandler;
- (void)application:(UIApplication *)application handleActionWithIdentifier:(nullable NSString *)identifier forRemoteNotification:(NSDictionary *)userInfo completionHandler:(void(^)())completionHandler;
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler;
`

Placed logging methods on all of the above AppDelegate methods. They all get called when the app is cold started, placed into background then brought back into foreground as the expected app lifecycle.

Let me know how your implementation differs.

Thanks,
J

**Comment by JKalash** [comment]
Output as copied from the console:

> 2016-08-25

 13:56:49.965432 OneSignal[788:548288] !-! applicationDidBecomeActive

> 2016-08-25

 13:56:49.985666 OneSignal[788:548288] !-! didRegisterForRemoteNotificationsWithDeviceToken

> 2016-08-25

 13:57:05.860211 OneSignal[788:548288] !-! applicationWillResignActive

> 2016-08-25

 13:57:06.387816 OneSignal[788:548288] !-! applicationDidEnterBackground

> 2016-08-25

 13:57:09.221040 OneSignal[788:548288] !-! applicationWillEnterForeground

> 2016-08-25

 13:57:10.142757 OneSignal[788:548288] !-! applicationDidBecomeActive

**Comment by onmyway133** [comment]
@JKalash How about `didReceiveRemoteNotification`? Does it get called too when you touch on push notification alert?

**Comment by 3xtc** [comment]
Hi is there still people active that know this stuff ? I’m stuck.. I have made a popup for my app, unfortunately the app doesn’t respond to “applicationDidBecomeActive”.. as it runs in scenes I believe. Any chance anyone would know what I could hook instead to show my pop up when open the app , as it’s not working with “applicationDidBecomeActive”.. please any help would appreciate
