### ISSUE TITLE
App badge counter doesn't get reset on app open from home screen

### ISSUE THREAD

**Issue by ndemie** [OneSignal/OneSignal-iOS-SDK#631]
**Description:**
I've been debugging this issue with support (thanks for everything so far Jon) for a while now but we haven't come to anything yet that might be the cause of this problem.

With our app we have the problem that the notification count does not get reset to 0 when opening the app from the home screen.

The counter DOES correctly get reset when:
- Opening the app from a push notification in the notification center or banner.
- Receiving a push notification while the app is active using displaytype "OSNotificationDisplayTypeNone"

App Groups, entitlements and Info.plists are set up correctly as verified by support. We're able to receive rich notifications without issue as well as read the player_id and app_id from the extension as described in the debug article on your website (https://documentation.onesignal.com/docs/service-extensions#section-troubleshooting-the-i-os-notification-service-extension).

We're at a total loss now what the issue could be.

**Environment**
SDK version: 2.12.6
Installation method: Cocoapods
Xcode version: 11.3
Swift version: 5

**Steps to Reproduce Issue:**
See mentioned above. As support hasn't seen this before I'm not sure this is 100% reproducible for every project. 

**Anything else:**
See video to see the problem with your own eyes: https://imgur.com/gGa43xo

**Comment by ndemie** [comment]
Problem solved. It had to do with the fact that our application within OneSignal was quite old and certain configuration on the back-end side (server side badge updates) was disabled. 

I'd advise adding this to your debugging/FAQ/support database and preferably dashboard settings as this took ages to figure out.

**Comment by lutluthfi** [comment]
@ndemie Hi, I face the same issue with yours. How did you solve this issue by having a certain configuration on the back-end side? What is the certain configuration on the back-end side?
