### ISSUE TITLE
OneSignal and Turbolinks pods not compatible with each other?

### ISSUE THREAD

**Issue by lucfg** [OneSignal/OneSignal-iOS-SDK#632]
**Description:**

We've been working with the SDK for a while and decided to update the OneSignal pod to solve other minor problems with an application I have been working on.

After updating the pod (from 2.10.0 to 2.12.6), I've encountered the following error:

```
<unknown>:0: error: reference to 'Session' is ambiguous

/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:214:29: note: candidate found by name lookup is 'Session'
typedef NS_ENUM(NSUInteger, Session) {

Turbolinks/Turbolinks.framework/Headers/Turbolinks-Swift.h:210:12: note: candidate found by name lookup is 'Session'
@interface Session : NSObject
```

What we understand of the problem is that both the OneSignal and the Turbolinks pods have a **Session** type declared, which Xcode takes as an error we cannot fix.

**Environment**

OneSignal SDK version 2.12.6 (using cocoapods)
Turbolinks version 3.0.0
Xcode 11.3.1
Using Swift

**Comment by jkasten2** [comment]
@lucfg Thanks for reporting. As a temporary work around you could delete these `Session` from either `OneSignal.h` or `Turbolinks-Swift.h` if you don't need to read this value from on or the other.

As a permanent solution OneSignal and/or Turbolinks will need to rename this enum. This is something we will do in our next major release, however we don't have a timeline on when this will be available.

https://github.com/OneSignal/OneSignal-iOS-SDK/blob/2.12.6/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L214

**Comment by emawby** [comment]
This issue will be fixed in the next beta release cut but could be gotten with the current version of the Major_Release_3.0.0 branch!

**Comment by summera** [comment]
@jkasten2 can this not be backported to version 2? I need version 2.13.0 or greater to get around OneSignal/OneSignal-iOS-SDK#554 but I can't update due to this issue and I'd like to avoid a major version upgrade.
