### ISSUE TITLE
Hiding one particular notification.

### ISSUE THREAD

**Issue by demon9733** [OneSignal/OneSignal-iOS-SDK#646]
**Description:**

I'm writing a messenger application. And just like in any messenger, I want to omit showing "New message" notification for that chat you are currently in. Unfortunately, I'm not able to do that with OneSignal framework so far.

The closest solution I got is the following:

1. Initially set `OneSignal.inFocusDisplayType` to `.none`.
2. Handle the received push notification and determine, whether to show it or not.
3. If yes, create UNNotificationRequest and re-enable `inFocusDisplayType` for a moment, and then set it to `.none` again:
```
let identifier = UUID().uuidString
let request = UNNotificationRequest(identifier: identifier, content: content, trigger: nil)

OneSignal.inFocusDisplayType = .notification
UNUserNotificationCenter.current().add(request) { _ in
    OneSignal.inFocusDisplayType = .none
}
```

The only downside of this approach is that `handleNotificationAction` closure is being called automatically, without any interaction with the banner.

If you have a proper way of omitting one particular notification, or at least a workaround for my approach, please let me know :)

**Environment**

1. I use iOS SDK version: 2.13.0
2. I tried CocoaPods integration, as well as direct `.framework` file integration.

**Comment by mikechoch** [comment]
We are currently working on a major release for Android and iOS SDKs that will allow functionality like this! Be on the look out for the next major release!

**Comment by demon9733** [comment]
That's awesome! Can you provide at least a rough estimate for the release date?

**Comment by jkasten2** [comment]
@demon9733 We don't have a release date at this time however you can implement the iOS API delegate [`userNotificationCenter(_:willPresent:withCompletionHandler:)`](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter) which provides a `completionHandler` you can call to do this. If call `completionHandler`  in it then it will override whatever `OneSignal.inFocusDisplayType` is set to.

**Comment by demon9733** [comment]
From my understanding, this delegate function is used by your framework, so I can't safely do somthing like: `UNUserNotificationCenter.current().delegate = NotificationsManager.shared`, because the related logic (`inFocusDisplayType` and tapping the banner) may break.

**Comment by demon9733** [comment]
In the end, I ended up with the following (temporary, until you push the next release) solution:

1. Luckily, none of the notifications that I receive contain `title`. Only the `message`.
2. All the messages I create with the `UNNotificationRequest` do have the title.
3. While creating the request, I also override the UNUserNotificationCenter's delegate:
```
// everything happens in my `NotificationManager` class
let identifier = UUID().uuidString
let request = UNNotificationRequest(identifier: identifier, content: content, trigger: nil)

UNUserNotificationCenter.current().delegate = self
UNUserNotificationCenter.current().add(request, withCompletionHandler: nil)
```

4. `NotificationManager` conform the UNUserNotificationCenterDelegate protocol and filters the notifications to show and avoids showing duplicate messages (both from OneSignal and my own):

```
extension NotificationsManager: UNUserNotificationCenterDelegate {

    func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        willPresent notification: UNNotification,
        withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {

        guard notification.request.content.title.trimmed.nullable != nil else {
            completionHandler([])
            return
        }

        completionHandler([.alert, .badge, .sound])
    }

    func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        didReceive response: UNNotificationResponse,
        withCompletionHandler completionHandler: @escaping () -> Void) {

        let payload = response.notification.request.content.userInfo
        NotificationsManager.shared.handleOpenedNotification(with: payload)
    }
}
```

**Comment by demon9733** [comment]
Just in case someone needs it, here's the complete function to show the local notification instead of the incoming one:

```
private func showLocalNotification(title: String?, message: String?, payload: [AnyHashable: Any]) {

    let content = UNMutableNotificationContent().then {
        $0.title = title ?? ""
        $0.body = message ?? ""
        $0.sound = .default
        $0.userInfo = payload
    }

    let identifier = UUID().uuidString
    let request = UNNotificationRequest(identifier: identifier, content: content, trigger: nil)

    UNUserNotificationCenter.current().delegate = self
    UNUserNotificationCenter.current().add(request, withCompletionHandler: nil)

    onMainThread(delay: 5) {
        // This line avoids showing the notification in the Notification Center history for the privacy reasons.
        // Remove if you don't need it.
        UNUserNotificationCenter.current().removeDeliveredNotifications(withIdentifiers: [identifier])
    }
}
```
P.S. Don't forget to set the initial `OneSignal.inFocusDisplayType` to `.none`.

**Comment by jkasten2** [comment]
@demon9733 You can safely set `UNUserNotificationCenter.current().delegate` and both yours and OneSignal's implementation will be called. This is because OneSignal swizzle this is a safe way.

`notification.request.content.title` is a fraggle way to detect if it is from OneSignal or not. Recommend adding your own flag to the payload so you can tell if it is your notification.

**Comment by demon9733** [comment]
@jkasten2 I tried setting `UNUserNotificationCenter.current().delegate` to my class, and both OneSignal's and mine notifications were presented.

But having a flag is indeed a better approach. Thank!

Nevertheless, I can't wait your next major release :)
