### ISSUE TITLE
UIScene / SwiftUI Compatibility - SceneDelegate

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-iOS-SDK#647]
### iOS API behavior change
`UIApplicationDelegate`'s background / foreground events no longer fire if a `UIWindowSceneDelegate` is set up.
This includes the following selectors:

* `applicationDidBecomeActive`
* `applicationWillResignActive`
* `applicationDidEnterBackground`
* `applicationWillEnterForeground`

#### iOS API Inconsistencies
However oddly enough, `NSNotificationCenter` events such as `UIApplicationDidBecomeActiveNotification` still fire even if a `Scene` is being used. Since this seems like an oversight on Apple's part that might change in the future so this behavior should not be relied on.

### Resulting OneSignal SDK Issues
This results in the 2.13.0 OneSignal-iOS-SDK no longer knowing when the app goes in and out of focus which breaks a number of things:
Some of these are
* Session counts
* Session time
* IAMs not showing in some cases
* Possible other issues

### Overview of SDK changes
OneSignal should stop swizzling [`UIApplicationDelegate` background / foreground selectors](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/2.13.0/iOS_SDK/OneSignalSDK/Source/UIApplicationDelegate+OneSignal.m#L107-L116):

These should be replaced with `NSNotificationCenter` events instead. Such as `UISceneDidEnterBackgroundNotification` when a scene is used and it's matching `UIApplicationDidEnterBackgroundNotification` if it is not.

### SceneDelegate Detection
Both `UIScene` and `UIApplication` `NSNotificationCenter` events should be setup by the OneSignal unconditionally. However due to the "iOS API Inconsistencies" section noted above we do need to detect if a sense is setup when a `UIApplication` event is fired and if so ignore it as the matching `UIScene` will also fire.

Note: iOS 13 does not require a SceneDelegate be used so checking if the device is on iOS 13 won't work to know if we should use `UIScene*Notification` or `UIApplication*Notification`.

## References
* [StackOverflow - iOS 13 has a new way of sending app lifecycle events](https://stackoverflow.com/questions/56508764/app-delegate-methods-arent-being-called-in-ios-13)
* [Apple Docs - Lifecycle UIScene Notifications](https://developer.apple.com/documentation/uikit/uiscene?language=objc#3198950)
* [Apple Docs - Lifecycle UIApplication Notifications](https://developer.apple.com/documentation/uikit/uiapplicationdelegate?language=objc#1656902)

**Comment by emawby** [comment]
Fixed and released in 2.15.2
