### ISSUE TITLE
Manually reset badge number (iOS)

### ISSUE THREAD

**Issue by AhmedOsamaOsman** [OneSignal/OneSignal-iOS-SDK#65]
I use OneSignal_disable_badge_clearing to take the control of reseting badge number but i'm facing a problem, let me describe it step by step:
- The applicationBadgeNumber is 4.
- I set the applicationBadgeNumber to 0 after specific scenario.
- When i send a notification from server side with incremental badge number option the applicationBadgeNumber is 5.

So how can i change the badge number on server side after i set applicationBadgeNumber ?

**Comment by onmyway133** [comment]
@AhmedOsamaOsman Hi, I think it is the same as https://github.com/OneSignal/OneSignal-iOS-SDK/issues/57

**Comment by jkasten2** [comment]
@AhmedOsamaOsman @onmyway133 I am closing this issue to consolidate it with #57

**Comment by Ankush-Redapple** [comment]
Please follow https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup in detail.

> The name of your app group should be group.{your_bundle_id}.onesignal. So for example, if your application's bundle identifier is com.test.app, your app group name should be group.com.test.app.onesignal.
> 
> [Assign the group to both target](https://files.readme.io/9e17c8c-OneSignal_Xcode_app_groups_capabilites.png).
> 
> 1. Open your Info.plist file and add a new OneSignal_app_groups_key as a String type.
> 2. Enter the group name you checked in the last step as it's value.
> 3. Make sure to do the same for the Info.plist under the OneSignalNotificationServiceExtension folder.
