### ISSUE TITLE
'OSLastNotification.h' file not found

### ISSUE THREAD

**Issue by AlirezaSN** [OneSignal/OneSignal-iOS-SDK#654]
Hi, i forked the repo and add my own podspec. when i pushed the podspec, i got a fatal error that **'OSLastNotification.h' file not found**. i searched this header file and i didn't find it in Source folder. did i miss something?

#### OneSignal forked version:
- 2.12.x (or higher)

#### Environment:
- CocoaPods : 1.9.1
- Ruby : ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
- RubyGems : 3.1.2
- Host : Mac OS X 10.15.4 (19E266)
- Xcode : 11.4 (11E146)

#### My podspec file:
```ruby
Pod::Spec.new do |s|
    s.name         = "XXXXX"
    s.version      = "2.12.6"
    s.summary      = "XXXX"
    s.homepage     = "https://onesignal.com"
    s.license      = { :type => 'MIT', :file => 'LICENSE' }
    s.author       = { "X" => "X@X.X" }
    s.source       = { :git => "X", :tag => s.version.to_s }
    
    s.platform     = :ios, "10.0"
    s.requires_arc = true
    
    s.source_files = "iOS_SDK/OneSignalSDK/Source/**/*{h,m,swift}"
    s.framework    = 'SystemConfiguration', 'UIKit', 'UserNotifications', 'WebKit', 'CoreGraphics'
end
```

One more to say, please write a document for building new version of framework via shell scripts (build_fat_framework and build_dynamic_framework). i got strange build errors and cannot find any proper solution on community.

Thanks a lot.

**Comment by rgomezp** [comment]
Howdy @AlirezaSN ,
Simply run the shell script: https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/build_fat_framework.sh

**Comment by AlirezaSN** [comment]
Thanks :)
i added script environment variables in **user defined variables** section in Xcode and also add a run script in build phase **(bin/sh build_fat_framework.sh)**, but as i said, i got strange errors. i don't have any screenshots from errors right now, i try to attach one ASAP. it was about something like accessing a locked database 🧐

**Comment by rgomezp** [comment]
Howdy,
I'd like to make some progress on this issue. Would you please provide more information?

**Comment by AlirezaSN** [comment]
Hi, sorry for latency :)
for my first issue(**'OSLastNotification.h' file not found**), the error is:
```
In file included from /var/folders/lh/d8fj88vx7q91cdxzpffmjbjm0000gn/T/CocoaPods-Lint-20200428-3027-1ky4ns3-OneSignal/Pods/OneSignal/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationData.m:31:
    /var/folders/lh/d8fj88vx7q91cdxzpffmjbjm0000gn/T/CocoaPods-Lint-20200428-3027-1ky4ns3-OneSignal/Pods/OneSignal/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationData.h:28:9: fatal error: 'OSLastNotification.h' file not found
    #import "OSLastNotification.h"
            ^~~~~~~~~~~~~~~~~~~~~~
    2 warnings and 1 error generated.
```
i pasted the error from **pod repo push** command verbose outputs & wrote down my podspec file in my first comment.


----
 

for my second issue(**building fat framework**), i attached error and run script here:

<img width="1001" alt="Screen Shot 1399-02-09 at 19 35 32" src="https://user-images.githubusercontent.com/11287106/80504088-f9a2ae80-8987-11ea-902b-2e60d6bd0f9a.png">

<img width="980" alt="Screen Shot 1399-02-09 at 19 48 08" src="https://user-images.githubusercontent.com/11287106/80505168-391dca80-8989-11ea-8444-ecdd93ef192c.png">

Thanks 👋

**Comment by rgomezp** [comment]
Howdy,
Apologies for the delay on my side this time. Were you able to resolve this?

**Comment by AlirezaSN** [comment]
You're Welcome
Actually, i didn't work on that 😬

**Comment by rgomezp** [comment]
Howdy,
Just so you're aware, we will be making the switch to use XCFramework in the future. Would you like to leave this issue open for now?

**Comment by AlirezaSN** [comment]
Sound's Great. Ok, no problem 👍

**Comment by rgomezp** [comment]
Howdy @AlirezaSN , 
I'm going to close this for now since we have many open iOS issues now. Once we migrate to XCFrameworks, feel free to reopen this or a new issue if you continue seeing this. Cheers
