### ISSUE TITLE
Ionic v5 Action Buttons not working

### ISSUE THREAD

**Issue by siliconswampio** [OneSignal/OneSignal-iOS-SDK#657]
**Description:**
Having an issue getting Action buttons working. I tested to see if I could add an image to the Test Push notification as well and was not getting the image so it leaves me to believe its an issue with the OneSignalNotificationServiceExtension witch is getting and error a `Could not build module 'OneSignal'` on the line `#import <OneSignal/OneSignal.h>`

<img width="793" alt="Screen Shot 2020-04-30 at 1 20 03 PM" src="https://user-images.githubusercontent.com/60610025/80741052-07bb1100-8ae7-11ea-8661-b7940e3df623.png">

I followed along with [Ionic Setup guide](https://documentation.onesignal.com/docs/ionic-sdk-setup) and did everything as well as updating some of the reference code that is supplied. im not sure if this might be where the issue starts from as the documentation states "Open NotificationService.m or NotificationService.swift" in witch there is only `NotificationViewController.m` 

<img width="270" alt="Screen Shot 2020-04-30 at 1 20 36 PM" src="https://user-images.githubusercontent.com/60610025/80741214-4650cb80-8ae7-11ea-8259-ce27f136a84c.png">

I do have pods installed correctly as by the documentation.

<img width="577" alt="Screen Shot 2020-04-30 at 1 20 17 PM" src="https://user-images.githubusercontent.com/60610025/80741321-713b1f80-8ae7-11ea-8954-3ca505140435.png">

I also have all the Linked dependencies setup as well

<img width="629" alt="Screen Shot 2020-04-30 at 1 21 08 PM" src="https://user-images.githubusercontent.com/60610025/80741401-916ade80-8ae7-11ea-96c7-1f8a91bd3bed.png">

Normal push notifications do work just do not have action buttons

**Environment**
xcode: 11.1
cordova: 9.0.0 (cordova-lib@9.0.1)
ionic: 5.4.1

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience.

Here is our documentation regarding [Action Buttons](https://documentation.onesignal.com/docs/action-buttons) and [Service Extension](https://documentation.onesignal.com/docs/service-extensions). There are various nuances so please ensure you have followed all the instructions.

Also, please try running `pod deintegrate && pod install` to make sure the library is added correctly. Cheers

**Comment by rgomezp** [comment]
Closing due to no response
