### ISSUE TITLE
Does the SDK automatically register with OneSignal after an update?

### ISSUE THREAD

**Issue by michelalbers** [OneSignal/OneSignal-iOS-SDK#66]
Hi,

we want to roll out OneSignal as part of an application update and move from our current push provider to OneSignal. The question is if the standard ```initWithLaunchingOptions``` approach registers automatically with OneSignal after an app update. We experience some trouble here and my guess is that the device "thinks" that its already registered for push notifications and does not register again.

Am I right?

best,
Michel

**Comment by JKalash** [comment]
Hi,

The device registers with Apple whenever you have the autoPrompt set to true (default value) as soon as you do the call to OneSignal's `initWithLaunchOptions`. Updating an app is no different. As soon as you open the updated app and the init method gets called, OneSignal will attempt to register with Apple.

**Comment by michelalbers** [comment]
Thanks for clarifying :)
