### ISSUE TITLE
Silent Notification Displayed on iPhone

### ISSUE THREAD

**Issue by chenzeyu** [OneSignal/OneSignal-iOS-SDK#669]
**Description:**

Our server send out silent notifications, i.e. ```content-available``` is ```true```, however the notification was displayed on iPhone, which is quite weird as it is shown on OneSignal Dashboard that the notifications were set to have content-available = true.

**Environment**

SDK Version: 2.13.1
iOS Version: 13.4.1
Installed via cocoapods 1.9.1

**Steps to Reproduce Issue:**

1. Send a remote silent notification via REST API
2. Notification gets displayed on iPhone

**Anything else:**

Notification Records:

https://app.onesignal.com/apps/ac4e31de-e969-4ce6-993e-9e72413f86a8/notifications/f95d4c6b-e24a-4289-8581-404841137d2c

https://app.onesignal.com/apps/ac4e31de-e969-4ce6-993e-9e72413f86a8/notifications/50aa6805-6f4c-4a36-8efa-f70175b52abe

https://app.onesignal.com/apps/ac4e31de-e969-4ce6-993e-9e72413f86a8/notifications/82c178b2-44aa-4bbc-855a-a673d5ba9b67

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
Have you set up the Notification Service Extension in your app? If not, please make sure to do so.

Take a look at our documentation [here](https://documentation.onesignal.com/v5.0/docs/silent-notifications#setup-and-send-background-notifications).

**Comment by rgomezp** [comment]
Closing due to no response
