### ISSUE TITLE
Inorrect OSNotificationOpenedResult documentation

### ISSUE THREAD

**Issue by Talkless** [OneSignal/OneSignal-iOS-SDK#67]
[iOS](https://documentation.onesignal.com/docs/ios-sdk-api#OSNotificationOpenResult) documentation mentions `OSNotificationOpenResult`, though 2.1.0 `OneSignal.h` has:
`@interface OSNotificationOpen**ed**Result : NSObject`

**Comment by JKalash** [comment]
fixed
