### ISSUE TITLE
crash: uialertview is deprecated and unavailable for UIScene based applications, please use UIAlertController

### ISSUE THREAD

**Issue by gg4race** [OneSignal/OneSignal-iOS-SDK#671]
**Description:**

Ever since I upgraded my iphone to 13.5 (then had to upgrade Xcode to 11.5), I started getting this error  "uialertview is deprecated and unavailable for UIScene based applications, please use UIAlertController". I don't think the problem existed before the update but am not 100% sure.

This causes a crash when a notification is sent while the receiver has the app open.

**Environment**

1. What version of the iOS SDK are you using? - 2.13.1
2. How did you add the SDK to your project - cocoapods

**Steps to Reproduce Issue:**

1. open the app with oneSignal installed
2. send a push to this user while the above user still has the app open

**Anything else:**

(crash stacktraces, as well as any other information here)

<img width="771" alt="Screenshot 2020-05-24 20 06 31" src="https://user-images.githubusercontent.com/15722963/82774957-1ac9b400-9dfb-11ea-966a-a3fc3374c27b.png">

**Comment by rgomezp** [comment]
Howdy,
Thanks for raising this. The issue should now be fixed as of `2.14.1`.

Enjoy!
