### ISSUE TITLE
After losing my mind I finally found the solution: "background fetch" mode must be enabled on Signing & Capabilities tab.

### ISSUE THREAD

**Issue by tahayasinkoksal** [OneSignal/OneSignal-iOS-SDK#684]
Thanks buddy, she started working when she did what she said.

After losing my mind I finally found the solution: "background fetch" mode must be enabled on Signing & Capabilities tab. 

<img width="404" alt="Schermata 2020-01-04 alle 18 12 12" src="https://user-images.githubusercontent.com/2759198/71769195-2d138600-2f1e-11ea-8b17-81382f3cb87a.png">

This works on iPhone 8 with iOS 13.3 and the "APNs delegate never fired" has disappeared

<img width="970" alt="Schermata 2020-01-04 alle 18 18 35" src="https://user-images.githubusercontent.com/2759198/71769235-a9a66480-2f1e-11ea-9fa6-f86a0f517de8.png">

_Originally posted by @nikiman in https://github.com/OneSignal/OneSignal-iOS-SDK/issues/503#issuecomment-570802762_

**Comment by rgomezp** [comment]
Thank you for the workaround. Cheers

**Comment by chillok** [comment]
Doesn't work here.
