### ISSUE TITLE
version 2.14.0 attachment issue

### ISSUE THREAD

**Issue by MattiaConfalonieri** [OneSignal/OneSignal-iOS-SDK#686]
I have read that in version 2.14.0
you add: 
**File Type Detection Improvements
Improved source of truth for push notification attachment file type detection**
Wath is this exactly? Because after update media are not showed in iOS. 

I tried to send a notification as usual with attachment image from url
https://parsefiles.back4app.com/WjW8TWDmbTRBSA5iXFHkV8o18iCiE1tyerBrfs1x/abb4df850e90072354cd926ea9d7e65e_0TFpEkC.jpeg

Image are dropped, same with other source...

**Comment by MattiaConfalonieri** [comment]
Any answer about this?

**Comment by keyhuihk01** [comment]
it should be related to https://github.com/OneSignal/OneSignal-iOS-SDK/issues/680
upgrade to 2.14.1 to fix it

**Comment by jkasten2** [comment]
@MattiaConfalonieri 

The detection order was changed in PR #670 to the following until a supported format is found.
1. `filename` query param
2. MIME type
3. url.pathExtension
4. A new fallback of doing a reverse order query param check for any valid extension.

It should be detected as `jpeg`, same as your the url as it ends in `.jpeg`.
See the Chrome screenshot for the `content-type` the URL is proving.
![image](https://user-images.githubusercontent.com/645861/84345139-6604f600-ab61-11ea-915e-b69af0af80f1.png)

It is possible there something being mis-detected here in the 3.14.0 release still, we will see if we can reproduce with your exact URL.

**Comment by rgomezp** [comment]
Closing due to no response
