### ISSUE TITLE
How to handle different bundle ids for different environments?

### ISSUE THREAD

**Issue by maitham** [OneSignal/OneSignal-iOS-SDK#689]
Hey,
I'm looking to understand how to setup our project to use Onesignal. We currently have an app with two environments each with their own bundle id for example com.app.app.debug and com.app.app . What's the best way to get the app up and running for both bundle Ids. Currently using the suggested docs we get the following error: 

`error: Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.
`
Which makes sense as we setup the app using com.app.app bundle identifier and are trying to run the app in debug mode. I can't seem to find any docs on this?

**Comment by jkasten2** [comment]
@maitham The `Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.` is most likely coming from the `OneSignalNotificationServiceExtension` target in your Xcode project. You will need a different `OneSignalNotificationServiceExtension` for each iOS bundle id you have. You can use the same `NotificationService.m` file for each of your two NSE targets however.

**Comment by maitham** [comment]
Yep, ended up doing this and having separate App IDs for diff environments
