### ISSUE TITLE
Please make the "Close" button localizable

### ISSUE THREAD

**Issue by ovolab** [OneSignal/OneSignal-iOS-SDK#693]
The in-app notification alert has a "Close" button that cannot be localized by the app. This is because the user-facing string "Close" is hard-coded in OneSignalDialogController.m and it is not wrapped in an `NSLocalizedString()` macro as it should. The fix for this is trivial: just replace this line in `OneSignalDialogController.m`:

```[self presentDialogWithTitle:payload.title withMessage:payload.body withActions:actionTitles cancelTitle:@"Close" withActionCompletion:^(int tappedActionIndex) {```

with this:

```[self presentDialogWithTitle:payload.title withMessage:payload.body withActions:actionTitles cancelTitle:NSLocalizedString(@"Close", @"Close button") withActionCompletion:^(int tappedActionIndex) {```

Please make sure the OneSignal SDK is localizable. It is important for markets outside of the USA.

**Comment by rgomezp** [comment]
Thank you for the request. I will close the issue but rest assured we continue tracking this request internally. Cheers
