### ISSUE TITLE
In-App messages are not coming if notification permission is turned off

### ISSUE THREAD

**Issue by iducool** [OneSignal/OneSignal-iOS-SDK#700]
**Description:**

During my testing, I found that In-App messages are not coming if notification permission is turned off. As soon as I enable notification permission in iOS, it starts working.

**Environment**
- Xamarin Classic
- SDK version - 3.9.0
- SDK is added using Nuget Package.
- Tried on iOS 12 as well as iOS 13

**Steps to Reproduce Issue:**
  1. Integrate Nuget Package and follow instructions per platform.
  2. On start-up OS will ask you permissions.  Allow all permissions.
  3. Send In-App message.
  4. You will see it in App.
  5. Go to Settings and Turned off permission for Push notification.
  6. Come to app and wait so, SDK can update status to OneSignal[In user listing screen of OneSignal Dashboard when you see that user has un-subscribed then go to next step]
 7. Now send In-App message, you will not get into app.

**Comment by mikechoch** [comment]
@iducool Are you referring to IAM previews or live IAMs?

**Comment by iducool** [comment]
@mikechoch Our app is live and I can not test anything on Live because it will be delivered to everybody and cause headache for all people. I have marked few devices as Test Devices and I have tried out "Send to Test Device" option from console.

**Comment by mikechoch** [comment]
@iducool the "Send to Device" feature relies on notifications to send the IAM as it is a preview for instantaneous delivery and easier testing. You should set the IAM live as normal live IAMs are gathered through a network request rather than a notification payload.

**Comment by rgomezp** [comment]
Closing due to no response.
