### ISSUE TITLE
Badge number is not increasing

### ISSUE THREAD

**Issue by SVasilev** [OneSignal/OneSignal-iOS-SDK#702]
**Description:**
Hello there and thanks for the great package!
I am using Unity 2019.3.1f1
I currently have similar problems described in #392 

The notifications I receive do not show any images or media, so it seems that I have issues with the extension service.
I cannot find anything related to the extension service in the logs even though my log level is `VERBOSE` (for both console and visual)

Is there a way to get additional logs or check the status of the `OneSignalNotificationServiceExtension`?

**Note**: I am compiling the project on Windows (I don't have a Mac) and I am using this asset: https://assetstore.unity.com/packages/tools/utilities/ios-project-builder-for-windows-15522
I haven't had any problems with this asset and I have already released an AR game with it, so I know it should work
When the build is started I get:
```
pbxprojparse: warning: XCConfigurationList '683745CDA608C1508087970D''s key 'defaultConfigurationName' not found, defaulting to 'Release'
Building the dependency project UnityFramework...
pbxprojparse: warning: XCConfigurationList '683745CDA608C1508087970D''s key 'defaultConfigurationName' not found, defaulting to 'Release'
Notice: automatically using extra entitlements found in Unity-iPhone\Unity-iPhone.entitlements, even though no CODE_SIGN_ENTITLEMENTS key is specified in the Xcode project file.
```
But I don't think this is related, because Everything else except images and badge number increment works

**Environment**
1. What version of the iOS SDK are you using? - 2.14.2
2. How did you add the SDK to your project? - Added as unity package

**Comment by rgomezp** [comment]
Howdy,
Did you already take a look at our [badges troubleshooting page](https://documentation.onesignal.com/docs/badges#ios-badges-troubleshooting)?

**Comment by SVasilev** [comment]
Hello,
Thanks for the reply! It seems that I will need to borrow my friend's Mac again, build in XCode, and then see what are the differences in the .ipa and what has to be changed.
No worries, though, the issue is not critical for now, because it seems that the push notifications are working in the general use case :)
If the issue becomes critical in my scenario I will build on a Mac and will get back to you if I need any help!
You may close the issue for now. I will reopen if I need help.
Thanks again!
