### ISSUE TITLE
Receive in app notification data, when app is in foreground, on a device which muted notification from device setting 

### ISSUE THREAD

**Issue by mohamadilk** [OneSignal/OneSignal-iOS-SDK#706]
**Description:**
I am trying to receive notification data while app is in foreground, but user manually disabled notification for the app. i have set "OneSignal.inFocusDisplayType = OSNotificationDisplayType.none", as I don't want to show anything to user, but I still need notification data to update state of the app, but don't get any data in OSHandleNotificationReceivedBlock callback. I believe it's an issue with iOS SDK because this works fine on android, by the way I'm not sure if it's iOS limitation or not. any thought on this issue?

**Environment**
Xcode 11.4.1
iOS 13.4.1
Latest OneSignal SDK

**Steps to Reproduce Issue:**
  1. Install iOS SDK latest version with Cocoapods into a project
  2. Implemented OSHandleNotificationReceivedBlock
  3. Initialize the SDK in didFinishLaunchingWithOptions:
  4. set "OneSignal.inFocusDisplayType" to "OSNotificationDisplayType.none"
  5. Disable app notification from settings
  5. Attempt to receive a push notification

  Result -> OSHandleNotificationReceivedBlock not called

**Comment by emawby** [comment]
Hello, are you trying to use a silent notification to update the application or does the notification contain content? Silent notifications are not affected by the push permission from settings, but non-silent alerts will not be delivered.
If you want to send a silent notification the notification must not contain any alert content (title, subtitle, etc.), a sound, or a badge update.

**Comment by mohamadilk** [comment]
@emawby Thank you for the response, actually i want to send a notification that does not show anything to the user, but update some states in the application, i tried everything in oneSignal dashboard, including not setting anything for title, subtitle and message, enabling/disabling CONTENT AVAILABLE, adding/removing some ADDITIONAL DATA, but still don't get any notification while user muted notifications from settings

I also found this answer in stackoverflow that says its not possible trough oneSignal:
[StackOverflow Answer](https://stackoverflow.com/a/41014230/3868228)
"Actually it is possible to do it but not with OneSignal.

Apple push notification does support push on the background, That means even if user doesn't grant access to notification it would just not show on his screen when he gets one. With OneSignal the issue is that the system doesn't send a push to users who have disabled push notifications. That means that your notification won't ever reach your app because it won't ever be sent through Apple Push Service."

**Comment by emawby** [comment]
@mohamadilk That is correct we do not support sending silent notifications to unsubscribed users currently

**Comment by rgomezp** [comment]
Closing issue. Note we are continuing to track internally.
