### ISSUE TITLE
Crashing at OSChannelTracker currentSessionInfluence

### ISSUE THREAD

**Issue by saadaamir** [OneSignal/OneSignal-iOS-SDK#709]
Crashlytics have reported a lot of crashes related to the below for several of our users.  

Please Let me know if you folks need more info from my side.

OneSignal iOS sdk Version 2.14.0
```
OSChannelTracker.m - Line 148

[OSChannelTracker currentSessionInfluence] + 148

Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]
keyboard_arrow_up

```

**Comment by Jeasmine** [comment]
Hello @saadaamir there was a fix https://github.com/OneSignal/OneSignal-iOS-SDK/commit/03a8b7dabc00de30a0d4ad13ca7e07f8b6f4f8e0 regarding this issue, can you upgrade to 2.14.2 or 2.14.3? Hope that helps!

**Comment by saadaamir** [comment]
Cool, will update the sdk. Thanks 🙏🏻

**Comment by rgomezp** [comment]
@saadaamir ,
Is it safe to close this issue?

Cheers

**Comment by saadaamir** [comment]
Yes please. Thanks
