### ISSUE TITLE
No known class method for selector initWithLaunchOptions:appid

### ISSUE THREAD

**Issue by ketan2409** [OneSignal/OneSignal-iOS-SDK#72]
onesignal library added to xcode by cocoapods. 

![screen shot 2016-09-06 at 3 37 17 pm](https://cloud.githubusercontent.com/assets/19226393/18270006/6ecdd3a0-7448-11e6-9f76-2e727c477437.png)

**Comment by JKalash** [comment]
Did you make sure to open the workspace instead of the project?

**Comment by ralphcorleone** [comment]
I got the same problem!

**Comment by JKalash** [comment]
Which version of the SDK are you using? You may be using the 1.* version of the SDK and calling this method which is part of the 2.* version of the SDK. Make sure to run a `pod update` on the root of your project directory to get the latest version of OneSignal's iOS SDK.

**Comment by fernando-sendMail** [comment]
I had the same problem and I had to create an instance for this class

`[[OneSignal alloc] initWithLaunchOptions:launchOptions appId:@"..."];`

**Comment by jkasten2** [comment]
@fernando-sendMail This is only valid for our 1.X SDK. All selectors are static on the 2.X SDK versions.

**Comment by fernando-sendMail** [comment]
@jkasten2 I see, I followed this tutorial: https://documentation.onesignal.com/docs/ios-sdk-setup
so, instead of installing 1.13.3 I should do 2.x.x?

**Comment by jkasten2** [comment]
@fernando-sendMail  `1.13.3` should only be used if you are using react native noted by it's instructions. You should leave of the version otherwise.

**Comment by crisecheverria** [comment]
You should add this line:
//Add this line
#import <OneSignal/OneSignal.h>
