### ISSUE TITLE
Push notifications disappearing from lock screen not all some in between 

### ISSUE THREAD

**Issue by ChinjuJames12** [OneSignal/OneSignal-iOS-SDK#723]
I have noticed some of push notifications are disappearing automatically from Notification Center not all received pushes will disappear some in between pushes are only disappearing Some may disappear after few minutes some will disappear when get a new push.App is a news app so it will get more than 30 notifications per day but 10 to 15 notifications in it are disappearing from Notification Center even iam not opening the app in between.Iam using onesignal Sdk version 2.15.1 and my devices are iPhone 11 with iOS 13.6 and iPad mini with iOS 13.6.I got an iOS 12 device and notifications are working fine in it No disappearing issue.

Thank you

**Comment by rgomezp** [comment]
Howdy,

Please follow our issue template and provide the full details or consider reaching out through our official support channel at OneSignal.com for these types of issues. Thank you.
