### ISSUE TITLE
iOS Push Notification containing only numbers causes a crash

### ISSUE THREAD

**Issue by CarlsCorrea** [OneSignal/OneSignal-iOS-SDK#727]
**Description:**
Calling postNotification with a number: "contents":{"en":"123456789123456789"} causes a crash.

**Environment**

1. What version of the iOS SDK are you using?
2.14.3
1. How did you add the SDK to your project (eg. cocoapods)
Pods

**Steps to Reproduce Issue:**
just call postNotification with a number: "contents":{"en":"123456789123456789"}

I am sending a string in body but receiving back a NSNumber, here is the stack trace:
![](https://user-images.githubusercontent.com/1944681/90414586-e25b0e80-e0a7-11ea-8d78-eec28dc80d6d.png)

Look at the body in payload...
![](https://user-images.githubusercontent.com/1944681/90390601-8aaaac00-e083-11ea-9792-0df92f0d3884.png)

I found a question about it with no correct answer
https://stackoverflow.com/questions/42096843/ios-push-notification-containing-only-numbers-is-not-displayed

**Comment by rgomezp** [comment]
Howdy,
Thank you for the question. I suspect this has to do with the fact the value is much bigger than can be stored in a simple `long`. If you test with `2147483647` do you still get the crash?

We may need to force any value to be of type `NSString` @emawby

**Comment by rgomezp** [comment]
@CarlsCorrea ,
Hmm. Weird that it still crashes with that value. I would have thought that was the issue. Did you test with even smaller number values as well?

**Comment by CarlsCorrea** [comment]
Yes, I tested... I sent a number and received a string.

**Comment by emawby** [comment]
@CarlsCorrea does this still happen when using the major version 3.0.0+ of the SDK?
