### ISSUE TITLE
Error linking OneSignal to a Swift project

### ISSUE THREAD

**Issue by BabyAzerty** [OneSignal/OneSignal-iOS-SDK#73]
Using Xcode 7.xlatest and Swift 2.2, I tried to install OneSignal (v2.1.3) with **Carthage** and **manually**, but I always get

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_OneSignal", referenced from:
      type metadata accessor for __ObjC.OneSignal in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

as soon as I add in my AppDelegate

```swift
import OneSignal

// Inside didFinishLaunching
OneSignal.initWithLaunchOptions(launchOptions, appId: "my-key")
```

However, I can build the app if I don't write any OneSignal code anywhere.

**Comment by almassapargali** [comment]
Same here.

**Comment by almassapargali** [comment]
I've also tried to use Bridging Header instead of import to no avail.

**Comment by TofPlay** [comment]
Same here

**Comment by TofPlay** [comment]
Any news about this issue?

**Comment by TofPlay** [comment]
Tested with release 2.1.5 same issue 😢

**Comment by TofPlay** [comment]
Hi @JKalash can you help us?

**Comment by TofPlay** [comment]
Fount it 😀

To be compatible with Carthage I change **OneSignal-Dynamic** like this 

**On General**
![image](https://cloud.githubusercontent.com/assets/1082222/18487340/190aff26-79f5-11e6-9e19-65f9d5a84fcc.png)

**On the Build Settings**
![image](https://cloud.githubusercontent.com/assets/1082222/18487286/ed17e622-79f4-11e6-8a92-e219cbd56430.png)

**On the Build Phase**
![image](https://cloud.githubusercontent.com/assets/1082222/18487231/b418864c-79f4-11e6-9b1e-c6d14983227c.png)

To try you can change the `Cartfile` and point to my version:
```
github "TofPlay/OneSignal-iOS-SDK" "master"
```

**Comment by JKalash** [comment]
Thanks for pointing that out. Fixing this now!

**Comment by JKalash** [comment]
[Fixed](https://github.com/OneSignal/OneSignal-iOS-SDK/commit/3181d25fe23d8067cb4bb99dbd2196deb96f4afd) 🎉
Make sure to run a carthage update to reflect the changes.
