### ISSUE TITLE
Is it possible to turn on and off different notifications for different things in one app? (iOS, Android)

### ISSUE THREAD

**Issue by DmytroSobko** [OneSignal/OneSignal-iOS-SDK#732]
For notifications for Android/iOS is it possible to turn on and off different notifications for different things in one app?

For example, we send notifications to the user using OneSignal service.

The first one if the user has not visited the application for a long time and another notification when there is a promotion in the store. So we have two different notifications.

Is it possible for the user to be able to turn off one of these notifications (manually in the app settings) and the other to work, or we can only turn off notifications completely?

**Comment by jfishman1** [comment]
Thank you for reaching out. As this is a product related question and not an SDK or technical issue, please reach out to our support team using support@onesignal.com email or our intercom chat within the onesignal.com dashboard or documentation in the bottom right corner.

To answer your question:

Android provides notification categories that users can turn on/off at the app settings level: https://documentation.onesignal.com/docs/android-notification-categories

For iOS or doing something within your own custom app settings, you can use OneSignal Data Tags to create your own custom categories to allow users to opt-in or out of certain notifications: https://documentation.onesignal.com/docs/add-user-data-tags

Further, if you want to use OneSignal's In-App Message feature, you can tag users through buttons or images clicked within the IAM: https://documentation.onesignal.com/docs/sending-in-app-messages

Then leverage OneSignal [segments](https://documentation.onesignal.com/docs/segmentation) or [api filters](https://documentation.onesignal.com/reference/create-notification#send-to-users-based-on-filters) to target users based on these tag categories.
