### ISSUE TITLE
import OneSignal ! No such module 'OneSignal'

### ISSUE THREAD

**Issue by teytag** [OneSignal/OneSignal-iOS-SDK#738]
My Xcode version: 11.3.1
OneSignal IOS SDK: 2.15.3

![Ekran Resmi 2020-09-07 18 28 03](https://user-images.githubusercontent.com/6927098/92402479-4bc6be00-f138-11ea-8ffb-9f0784892681.png)
![Ekran Resmi 2020-09-07 18 28 20](https://user-images.githubusercontent.com/6927098/92402484-4e291800-f138-11ea-8505-9cb089fa6bbe.png)

**Comment by rgomezp** [comment]
Howdy,
Please make sure to follow our issue template when opening a new issue so we can properly assist you. Thank you.
