### ISSUE TITLE
Framework Not Found error with new xcode 12

### ISSUE THREAD

**Issue by hishak** [OneSignal/OneSignal-iOS-SDK#743]
**Description:**
Apple just released xcode 12.  Clean build ends in an **Error**:
ld: framework not found Pods__OneSignalAppName_
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Environment**

1. Podfile version 2.13.1
1. Added using cocoapods 1.9.3 and 1.10 beta

**Steps to Reproduce Issue:**

1.  Open working project in new xcode version 12.
1.  Run "Clean Build Folder"
1.  Select 'Run' button to compile and run the app

**Anything else:**
The framework shows in Frameworks, Libraries, and Embedded Content for Target.
The framework shows in red in the workspace manifest along with OneSignalNotificationServiceExtension framework.

Tried running:
1.
pod deintegrate
pod update

No change, same result, except now I am at OneSignal version 2.15.3!

2.
Change Framework Search path to 'recursive'.
No change, still same error.

3.  Tried installing cocoapods 1.9.3 and 1.10 beta.
No change, still same error using either version.

**Comment by hishak** [comment]
Solved by adding **arm64** to Excluded Architectures (EXCLUDED_ARCHS) in the Project settings.  Looks like we need to do this until the SDK supports arm64.
![Screen Shot 2020-09-20 at 20 49 56](https://user-images.githubusercontent.com/10100514/93726335-7dea0e00-fb83-11ea-8022-ae50b354d88c.png)

**Comment by sethmills21** [comment]
This is important stuff, might want to send an email to iOS developers

**Comment by sethmills21** [comment]
Racked my brain on this for a couple hours today
