### ISSUE TITLE
Building for iOS Simulator, but linking in object file built for iOS.

### ISSUE THREAD

**Issue by albertputrapurnama** [OneSignal/OneSignal-iOS-SDK#744]
**Description:**
Cocoapod build failed on XCode 12.0. The build runs perfectly fine on XCode, but it failed when doing `pod lib lint` which is using the tool `xcodebuild`. The error is the following:

```
 ld: in /var/folders/7z/kbh9ck0s7k18scystzfy6hpw0000gn/T/CocoaPods-Lint-20200918-69109-xx8o5m-Cotter/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/var/folders/7z/kbh9ck0s7k18scystzfy6hpw0000gn/T/CocoaPods-Lint-20200918-69109-xx8o5m-Cotter/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have searched for answers, there are multiple promising solutions, but none of them works for me:

1. https://developer.apple.com/forums/thread/656509

Please let me know if there are any additional information I can give, like stack trace, additional environment details, etc.

**Environment**

1. What version of the iOS SDK are you using? **2.5.13**
1. How did you add the SDK to your project? **Cocoapods**
1. XCode version: XCode 12.0
1. Cocoapod version: 1.9.3

**Steps to Reproduce Issue:**

1. Clone my open source project, using `git clone https://github.com/cotterapp/ios-sdk.git`
1. `cd ios-sdk`
1. `pod lib lint --verbose` to see the error I'm getting.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by lieferbaer** [comment]
Exactly same issue for me. I hang on to it too.

**Comment by haroldh17** [comment]
Same for me too!

**Comment by sethmills21** [comment]
anyone figured this out?

**Comment by albertputrapurnama** [comment]
@sethmills21 I've reached out to OneSignal team at the dashboard. However, there's no answers to this yet

**Comment by haroldh17** [comment]
I figured this out on my end but I don’t know if it will help. 
I set the scheme to Run > debug. For some reason it was set to release. So when I was trying to run on my phone it was working but not on the simulator. 

I’m using React native.  Let me know if it helps.

**Comment by gdeglin** [comment]
This appears to be due to a Cocoapods compatibility issue with XCode 12, as mentioned in the issue here https://github.com/CocoaPods/CocoaPods/issues/10059.

Please try the recommendation in that thread to work around this for now:

> add x86_64 to VALID_ARCH if need to run app on simulator, e.g., x86_64 arm64 arm64e

**Comment by sethmills21** [comment]
@gdeglin! thanks for the link. I'm still seeing weird stuff while uploading: 

![image](https://user-images.githubusercontent.com/7932883/94141921-79e81580-fe3b-11ea-987b-6d338122e275.png)

And it sort of looks specific to the OS pod and extension?

Knew I should have waited a few weeks for Xcode12 update haha

**Comment by sethmills21** [comment]
Thanks for the response George, added that line and doing some more debugging now ✅

Seth Miller | CEO

e: seth@rapchat.me ( seth@rapchat.me )

p: 614-634-2357

https://instagram.com/rapchatapp ( https://instagram.com/rapchatapp )

https://rapchat.me ( https://rapchat.me )

**Comment by albertputrapurnama** [comment]
This has worked for me

https://stackoverflow.com/a/63955114

Closing this issue. Thanks @gdeglin !

**Comment by cclaflin89** [comment]
I'm building the project for iOS simulator on Silicon M1. Excluding arm64 architecture for the simulator seems not an appropriate solution for me. Any idea on this?

**Comment by Rahulbhutani97** [comment]
@cclaflin89 me too face same issue with M1 silicon any ideas ??

**Comment by cclaflin89** [comment]
@Rahulbhutani97 OneSignalXCFramework 3.2.0 released last week worked for me.

**Comment by Rahulbhutani97** [comment]
how can i do that please help

**Comment by rgomezp** [comment]
>how can i do that please help

In your Podfile, set the pod name to `OneSignalXCFramework` and the version to `3.2.1`

**Comment by Rahulbhutani97** [comment]
No its done :)

**Comment by juandelcano** [comment]
Hi, how did you solve this problem? I've tried with adding excluded archs for arm64. But it's still the same. Thanks

**Comment by Rahulbhutani97** [comment]
By using this

OneSignalXCFramework 3.2.0 released last week worked for me.

**Comment by MujtabaFR** [comment]
using OneSignalXCFramework fixed the issue

-------------------
Another solution for **M1 Macs**: running Xcode under **Rossetta** will fix the issue (only temporary workaround)
```
1 - With Xcode closed (Important) Go to finder -> Applications
2 - Right Click on Xcode and select "Get Info"
3 - On the info panel check "Open using Rosetta"
4 - Double Click in the bottom large preview of the info panel.
```
** This will cause major decrease in speed and performance in Xcode and simulator

**Comment by aasamson** [comment]
is using OneSignalXCFramework even though it is not M1 solved the issue? I can't build in my QAT environment.

ld: in /Users/ai/Documents/perahub-ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/ai/Documents/perahub-ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ospaarmann** [comment]
I was able to solve it by changing the build settings for the `OneSignalNotificationServiceExtension` in Xcode. In Architecture I set "Build Active Architecture Only" to `Yes` for `Debug` and `Release`.

<img width="758" alt="Screenshot 2021-07-29 at 18 39 15" src="https://user-images.githubusercontent.com/308086/127531634-92d7ce1e-16d0-4e57-81f9-59ffb6526afe.png">

This StackOverflow thread is also related: https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios/63955114#63955114

**Comment by Tenfleques** [comment]
> > how can i do that please help
> 
> In your Podfile, set the pod name to `OneSignalXCFramework` and the version to `3.2.1`

target 'OneSignalNotificationServiceExtension' do
#   pod 'OneSignal', '>= 3.0', '< 4.0'
  pod 'OneSignalXCFramework'
end

worked on M1

**Comment by ricsantos** [comment]
Using the `OneSignalXCFramework` in the extension part of the Podfile does fix the `building for iOS Simulator, but linking in object file built for iOS` build error, however it produces this warning:

```
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/.../DerivedData/.../Debug-iphonesimulator/XCFrameworkIntermediates/OneSignal/OneSignal.framework/OneSignal
```

**Comment by Sifatsb** [comment]
Error (Xcode): In /Users/noob/Documents/Flutter/OutSide Projects/Shakib/Project-3/texibooking/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/noob/Documents/Flutter/OutSide Projects/Shakib/Project-3/texibooking/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


I am not getting any solution. Anyone can help me to solve this?

**Comment by afa7789** [comment]
same issue.
