### ISSUE TITLE
Updating to iOS SDK 2.0 

### ISSUE THREAD

**Issue by zoufishanmehdi** [OneSignal/OneSignal-iOS-SDK#75]
I installed pod 'OneSignal' as per iOS SDK installation instructions in the documentation. However, I'm only able to use older methods meant for the previous version, not 2.0. How can I upgrade to iOS SDK 2.0 and use the latest methods for receiving notifications listed in the documentation? Thanks

**Comment by JKalash** [comment]
Hi there,

The 2.* versions of the SDK run the methods listed in the dfocumentation. Make sure to check the **OneSignal.h** file and make sure that the method names, classes and constants defined in it match what's in the API Reference page of our documentation.
