### ISSUE TITLE
OneSignal User ID is returning <importlib._bootstrap.__NSCFString object at 0x1293ced10> even when the subscribed status is returning True

### ISSUE THREAD

**Issue by RustyRyan98** [OneSignal/OneSignal-iOS-SDK#757]
Description:

One Signal User ID is returning NSCFString object instead of the value

Environment:

1. im using pod 'OneSignal', '>= 2.11.2', '< 3.0' 
1. I used CocoaPods but im writing the code in python using Kivy's pyobjus framework (There is no SDK for kivy)

Steps to Reproduce Issue:

  Example:

1. Im successfully initialised OneSignal and the Player ID is showing on the OneSignal Dashboard
1. When I type ```onesignal_object.getPermissionSubscriptionState().subscriptionStatus.userId```
1. it returns ```<importlib._bootstrap.__NSCFString object at 0x1293ced10>```
1. Although subscription status is True

I would appreciate any assistance, when I first initialised it returns the result of the OSRegisterUser and it shows success and returns 1 and I can see the userID there as the key "id" but when I try to print the userId it returns  ```<importlib._bootstrap.__NSCFString object at 0x1293ced10>``` and the same for pushToken.

**Comment by emawby** [comment]
Hello we are not familiar with the Kivy framework but based on their documentation I don't believe there is an actually an issue. NSCFString is the internal class and I believe can be treated as an NSString.
In the documentation I notice this

>>> first_key_value = dictionary.objectForKey_(objc_str('first_key'))
>>> second_key_value = dictionary.objectForKey_(objc_str('second_key'))
>>> print first_key_value
>>> print second_key_value
>>> This will output:
>>> <__main__.__NSCFString object at 0x101025d10>
>>> <__main__.__NSArrayI object at 0x101169290>
So, say you want to call the UTF8String method of the NSString object that resides in the ‘first_key’, you can simply
call:
str_val = first_key_value.UTF8String()
print 'String value is: {0}'.format(str_val)
This will output:
>>> String value is: string value of first key

**Comment by emawby** [comment]
Closing for now please let us know if this is still an issue
