### ISSUE TITLE
iOS 14 / App Clip installation steps

### ISSUE THREAD

**Issue by basememara** [OneSignal/OneSignal-iOS-SDK#773]
The documentation says that a [Notification Service Extension is needed](https://documentation.onesignal.com/docs/ios-sdk-setup), also the [`Add a device`](https://documentation.onesignal.com/reference/add-a-device) endpoint says not to use it. Is there documentation about App Clip integration and known issues?

**Comment by emawby** [comment]
Hello [here](https://dash.readme.com/project/onesignal/v7.0/docs/app-clip-support) is the documentation for App Clip support

**Comment by basememara** [comment]
It takes me to a login page. Is this an internal documentation work-in-progress?

**Comment by rgomezp** [comment]
The wrong link was shared out @basememara , fixed!
