### ISSUE TITLE
[ATTENTION] - OneSignal.sendTag ERROR

### ISSUE THREAD

**Issue by joaomirandas** [OneSignal/OneSignal-iOS-SDK#78]
I was trying set 

> _OneSignal.sendTag("key", value: "value")_

And i don't know how i need set this, i ever receive errors of XCODE, about any propriety, sendTag, getTag, i think this library was corrupted. 
Used Xcode 7.3.1 and Swift 2~3 i don't remember now. someone can help me?!

See this pic showing a kind of error.
![captura de tela 2016-09-11 as 21 02 04](https://cloud.githubusercontent.com/assets/4155129/18421548/55ebdf48-7863-11e6-8fb6-887ce06b1fd6.png)

**Comment by JKalash** [comment]
Hi there,

Was unable to reproduce the following issue. Seems to me like its a `type optional` issue. Could you try replacing your code with:

`let tagKey : String! = "key"
let tagVal : String! = "val"
OneSignal.sendTag(tagKey, value: tagVal)`

**Comment by joaomirandas** [comment]
Woowww, it`s so good be responded, Thank you so much..
But i have one more question, you have any ideia to use this -->
```
OneSignal.getTags({ (tags) in
  print(tags)
})
```
i tried but ever receive a lot of erros about " OneSignalFailureBlock onFailure(Optional) "

**Comment by JKalash** [comment]
Glad it worked! 🎉
The above method works properly as you do not need to pass success / optional block. If it does not work you should have a look at implementing the following [method](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignal/OneSignal.h#L238) and pass `nil` blocks
