### ISSUE TITLE
Failed to build for MacCatalyst

### ISSUE THREAD

**Issue by elai950** [OneSignal/OneSignal-iOS-SDK#787]
**Description:**

I'm using the latest SDK from OneSignal and when I building the project I receiving an error:
`building for Mac Catalyst, but linking in object file built for iOS Simulator`

**Environment**

1. OneSignal SDK - 2.15.4
1. Installed using cocoapods

**Steps to Reproduce Issue:**

1. Install iOS SDK with Cocoapods into project
1. Configure as described in documents
1. Try to build for Mac OS

**Comment by emawby** [comment]
@elai950 Hello, for Mac Catalyst you will need to use the XCFramework version of the SDK. See the documentation [here](https://documentation.onesignal.com/docs/using-onesignals-xcframework-for-mac-catalyst)
