### ISSUE TITLE
incoming pushing dont trigger didReceiveNotificationRequest in a Notification Extension

### ISSUE THREAD

**Issue by ARFAOUI** [OneSignal/OneSignal-iOS-SDK#79]
trying to build my own UI when receiving a Push on iOS 10, I'm using Pusher ( https://github.com/noodlewerk/NWPusher ) to build and send payloads to APNS in my Dev environment. everything is working fine and didReceiveNotificationRequest is being called in the notification extension.

my payload in Pusher is the following : 
{"aps":{

"alert":{
      "title": "This is an iOS 10 Push!",
      "subtitle": "Notification subtitle is displayed when you 3D touch",
      "body": "this is the push body displayed when you 3D touch the notification popup"
    },
	"mutable-content":1,
	"content-available" : 1 },
"customInfo" : {
	"title" : "This is our push title in the advanced screen",
	"imageLink" : "http://cms.geteve.de/assets/looksimages/150922-FischgraetenFake-Cynthia-Nathalie-01-Step-1.jpg",
	"intro" : "Haare gut durchkämen. Dann einen seitlichen Zopf binden und am oberen Ende eine Lücke bilden",
	"contentSlug" : "perfekte-rote-lippen",
	"video" : "http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4"
}
}

**Switched to OneSignal**, I receive normal pushes but when I set the mutable-content to true, the didReceiveRemoteNotification in my appdelegate is called but the Notification extension don't!

If you can investigate this and will be great if you add a new target to the example project with support to Notification service extension + Notification content.

**Comment by JKalash** [comment]
Hi there,

Are you sure the extension is not getting called? Tried testing with your pasted payload but was not able to reproduce the issue.

**Debugging**

Make sure your phone is the target device in XCode then go to `Debug -> Attach to process by pID or name` and attach to your service extension. Place a breakpoint in the `didReceive` method and send the notification. Let me know what happens.

**Comment by JKalash** [comment]
We will also modify our example code to have a `UNNotificationServiceExtension` target as you suggested.

**Comment by ARFAOUI** [comment]
I already did the debbuging you mentioned in your comment before posting the issue. my Notification service is never called when receiving a payload from OneSignal with mutable-content, it's only didReceiveRemoteNotification in the my appdelegate.

**Comment by JKalash** [comment]
We updated our SDK (2.1.8) with the added example. You should try running the example project and see if it works. If it does, cross-matching with your project to see why the extension is not waking up should be straight-forward.

**Comment by ARFAOUI** [comment]
Used your example to test the service, still not being triggered using OneSignal but works If I use Pusher Mac App, could you please paste here the payload you are sending to APNS ? I want to test it from my side if possible.

**Comment by JKalash** [comment]
Sure! This is a sample payload.

`{
`    aps =     {
`        alert =         {
`            body = "Crazy Body";
`            subtitle = "Minor Subtitle";
`            title = "Awesome Title";
`        };
`        "mutable-content" = 1;
`        sound = default;
`    };
`    custom =     {
`        a =         {
`            actionButtons =             (
`           );
`            actionSelected = "com.apple.UNNotificationDefaultActionIdentifier";
`        };
`        i = "ee2d6142-3c26-491e-a5c3-f4d86a6bf01c";
`    };
`}

**Comment by JKalash** [comment]
Support for UNNOtificationServiceExtension exists as of 2.1.10.

**Comment by jinghanx** [comment]
@ARFAOUI Just wanna check if you have that fixed, as I am running into the same issue

**Comment by jkasten2** [comment]
To clarify, in commit 147a3ac296098493a85b39358785b2a5f58cc924 we added a `mutableContent` flag to `OSNotification` in our 2.1.1 SDK.

This flag can be used to know if your `UNNotificationServiceExtension` should of been fired for the notification that was just opened.

If you set `mutable_content` to `true` on our REST API or dashboard make sure to omit setting any action buttons or iOS 10 attachments as our back end will omit the mutable content flag.
