### ISSUE TITLE
No such module 'OneSignal' after trying Archive Mac Catalyst

### ISSUE THREAD

**Issue by PietroMessineo** [OneSignal/OneSignal-iOS-SDK#794]
Hi guys,

I followed the instructions for the XCFramework (https://documentation.onesignal.com/docs/using-onesignals-xcframework-for-mac-catalyst) and I was able to run my iOS App with Catalyst on my Mac. However, when I tried to Archive it, it's always saying to me **No such module 'OneSignal'** from the NotificationService.swift file. 

I'm using Xcode 12.2, with OneSignal XCFramework '2.15.4' downloaded using CocoaPods.

I also tried `pod deintegrate && pod install` but no luck, I still have the same issue. 

Thank you very much!

**Comment by emawby** [comment]
Hello try making sure you have the correct variant for the Mac. See a similar forum thread [here](https://developer.apple.com/forums/thread/120542)

Closing since this is not a OneSignal issue

**Comment by PietroMessineo** [comment]
Hi @emawby, 

I had a look to the thread that you shared but unfortunately it's not helping. You can have a look to my log after trying to manual archive it: https://pastebin.com/raw/3a2Tzbav 

Any idea? 

All the other frameworks are compiling but not OneSignal.
