### ISSUE TITLE
Unable to install on physical device

### ISSUE THREAD

**Issue by shalinipk** [OneSignal/OneSignal-iOS-SDK#801]
**Description:**

Unable to install app via XCode on physical device after integrating with One Signal SDK.

**Environment**

mac OS 10.15.6
XCode 11.7
iPhone SE 14.2
One-Signal-iOS-SDK version 2.15.4 installed via carthage

**Steps to Reproduce Issue:**

Hello, I am totally new to OneSignal & Notification Extensions. Please help.

Followed steps listed here - https://documentation.onesignal.com/docs/ios-sdk-setup - to integrate with One Signal iOS SDK
When I try to install on my phone, seeing this error

"Unable to install <appname>"

Details

Domain: com.apple.dt.MobileDeviceErrorDomain

## Code: -402620388
No code signature found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388

**Anything else:**

I am able to install app if I switch to a different branch - so I am guessing something is messed up wrt Notification Service Extensions.

**Comment by emawby** [comment]
Hello this seems to be an issue with embedding/signing of something embedded in your app. Is the OneSignal framework being Embedded & signed? For both the Notification Service Extension target and the app target?

![image](https://user-images.githubusercontent.com/13123372/99438572-d3634280-28c8-11eb-83b7-46bdeb23fd1a.png)

**Comment by shalinipk** [comment]
Thank you for your response. I see OneSignal.framework Embed & Sign for both app target & notification service extension target. I also see this for my app target - OneSignalNotificationServiceExtension.appex -> Embed without Signing

could that be causing issues ? can i remove OneSignalNotificationServiceExtension.appex  ? Thanks!
<img width="519" alt="Screen Shot 2020-11-17 at 12 08 25 PM" src="https://user-images.githubusercontent.com/8920346/99442218-e3c9ec00-28cd-11eb-8542-e1733e9a0ddd.png">

**Comment by emawby** [comment]
@shalinipk Do not remove the extension service but you can trying changing those embed settings to see if the issue is resolved.

**Comment by shalinipk** [comment]
@emawby Thank you for your help. I see only 2 options for the appex file -  Do not embed & Embed without signing

If I choose Do not embed, the file gets removed.



<img width="673" alt="Screen Shot 2020-11-17 at 12 55 18 PM" src="https://user-images.githubusercontent.com/8920346/99449664-b0d72680-28d4-11eb-97ab-b04e4ee46f3b.png">

**Comment by emawby** [comment]
Trying changing the options for the OneSignal.framework

**Comment by shalinipk** [comment]
Right now, OneSignal.framework is set to Embed & Sign. What shall i change it to ?

**Comment by shalinipk** [comment]
@emawby , I wanted to give you an update on this one. I rebooted my laptop as a last resort. Fortunately, I am able to install the app now. (it crashes upon launch on the physical device - because it fails to pickup some frameworks, but I don't think that's anything to do with OneSignal as such. Quite likely, some build settings/framework paths are messed up)

I feel guilty about taking up your time, my apologies. Next time, I will be sure to try out rebooting everything I can get a hold of - before I bother anyone.
