### ISSUE TITLE
Unable to install OneSignal with SPM

### ISSUE THREAD

**Issue by brennobemoura** [OneSignal/OneSignal-iOS-SDK#802]
**Description:**

Setting up OneSignup in the iOS project, SPM keeps trying to download it and get stuck.

**Environment**

Minimum SDK: iOS 12.4
Added by: SPM
Running: macOS 11.0.1, Xcode 12.2

**Steps to Reproduce Issue:**

1. Add OneSignal using SPM on project settings.
1. Choose the latest version.
1. Now, the loading bar will not finish.

**Anything else:**

Nothing to report.

**Comment by emawby** [comment]
Hello, I have seen the download take a long time but it always eventually finished for me. I will look into it, but this doesn't seem like an issue with the OneSignal SDK at first glance

**Comment by brennobemoura** [comment]
Maybe it was some problem with my internet. I will try later ✌️. At least I could use it with cocoapods 😄
