### ISSUE TITLE
iOS SDK Major Release 3.0.0 - Beta!

### ISSUE THREAD

**Issue by emawby** [OneSignal/OneSignal-iOS-SDK#803]
Hello,
The iOS Native major release version 3 is now in Beta!

This version includes many exciting changes including an overall simplification of the API as well as many of the underlying native improvements and bug fixes.

[Some key changes already in Beta](https://documentation.onesignal.com/docs/30-api-reference-ios):

Better notification control while app is in foreground
App Clip Support
Simplified Initialization
Nullability annotations for Swift

Why you should start migrating now
Most importantly, we want to give you the opportunity to voice your opinion and provide feedback so that we can make changes as needed to better suit your implementation.

Furthermore, it is always beneficial to get a head start on migrating your implementation to ensure a smooth transition. As we continue improving OneSignal, being fully migrated to the latest version of the SDK will help minimize potential issues and ensure you can focus on providing value to your customers, improving your business, and creating a delightful messaging experience.

To begin migrating your app to version 3, read our migration guide [here](https://documentation.onesignal.com/docs/step-by-step-ios-native-2x-to-300-upgrade-guide). Regarding this guide, please let us know if anything could be clarified or communicated better.

[Releases Page](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.0.0-beta3)

We are looking forward to hearing from you.

Enjoy!

**Comment by cnordvik** [comment]
@emawby Is https://github.com/OneSignal/OneSignal-iOS-SDK/issues/502 fixed in 3.0.0? We still have issues with it after a year and I'm sure a lot other apps have as well but they are probably not aware that it is the SDK that is causing the missing notifications 🙂

**Comment by jkasten2** [comment]
@cnordvik I believe this is still an issue in 3.0.0. I have reopened issue #502 and we will into confirming with 3.0.0 and follow up with a fix if it is indeed still an issue.

**Comment by jkasten2** [comment]
OneSignal-iOS-SDK 3.0.0 Beta 5 is now available!
https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.0.0-beta5

**Comment by halilyuce** [comment]
what about this? 

![image](https://user-images.githubusercontent.com/29376592/101682204-60d32600-3a74-11eb-885c-8bfbd9eb5edb.png)

**Comment by jkasten2** [comment]
@halilyuce The OneSignal initialization changed in the OneSignal-iOS-SDK 3.0.0 version. Please see this migration page on how change your code to for the new API.
https://documentation.onesignal.com/docs/mobile-2020-api-migration-guide

**Comment by rgomezp** [comment]
Out of Beta
---

Version 3 of the SDK is no longer in Beta. Please see the [migration guide](https://documentation.onesignal.com/docs/mobile-2020-api-migration-guide) regarding how to upgrade.

Enjoy!

**Comment by halilyuce** [comment]
@jkasten2  and @rgomezp thanks for the information guys. I recommend if you have permission to change it, review that migration guide to be a little bit more clear :) I missed **'from to this'** section, it can be more clear. Thanks in advance :)
