### ISSUE TITLE
ionic ios app rejected from appstore - deprecated API usage

### ISSUE THREAD

**Issue by prabhashibuddhima** [OneSignal/OneSignal-iOS-SDK#810]
**Description:**

After I add one signal to my ionic app, Appstore is rejecting my app due to Deprecated API Usage: New apps that use UIWebView are no longer accepted.

**Steps to Reproduce Issue:**

1. npm install
1. sudo gem install cocoapods
1. pod repo update
1. ionic cordova platform add ios@5.1.0
1. ionic cordova prepare ios
1. cordova build ios

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by emawby** [comment]
Hello, this issue should be on the [Cordova repo](https://github.com/OneSignal/OneSignal-Cordova-SDK). I also did not think that we were using UIWebView in the latest version of the Cordova SDK. Can you provide more information showing that it is OneSignal that is causing the issue? Closing please move this to the correct repository
