### ISSUE TITLE
[Question] App privacy details

### ISSUE THREAD

**Issue by KDederichs** [OneSignal/OneSignal-iOS-SDK#816]
**Description:**

So starting december 8th we need to declare those nice and fancy privacy labels:
https://developer.apple.com/app-store/app-privacy-details/

Any chance of getting a list of things you'd need to check based on OneSignal (if any)?

**Comment by mpillar** [comment]
Hello @KDederichs! We are preparing a blog post and supporting documentation on this topic. Please stay tuned, we will update here when this is ready. We will have this prepared before December 8th.

**Comment by mpillar** [comment]
Hi @KDederichs, our blog post on this subject is live. Here it is: https://onesignal.com/blog/apple-app-privacy/

The post links to our supporting documentation. For convenience, here is a link to those docs: https://documentation.onesignal.com/docs/apple-app-privacy-requirements

If you have any additional questions that are not covered by these materials feel free to ping us. Cheers!
