### ISSUE TITLE
Does XCFramework version support new ARM based Mac?

### ISSUE THREAD

**Issue by josephktcheung** [OneSignal/OneSignal-iOS-SDK#818]
**Description:**

Hi, we integrated XCFramework version of OneSignal iOS SDK and it worked on an Intel CPU Macbook, however it didn't work on new ARM based Mac e.g. Mac Mini. Are we missing anything while setting this up?

**Environment**

1. Version: 2.16.0 XCFramework
1. Cocoapods

**Steps to Reproduce Issue:**

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
>it didn't work on new ARM based Mac


Thank you. Can you please provide more information? What about the integration didn't work?

**Comment by emawby** [comment]
@josephktcheung What architecture are you building the mac version for?

**Comment by nputnam-hu** [comment]
Hi — I'm also receiving encountering this problem. I'm working off of my M1 Macbook Pro, and my xcode build is erroring with this message:

```
ld: in /Users/noahputnam/airr/airr-app/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/noahputnam/airr/airr-app/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My build is targeting arm64. From googling around, it seems like other extensions are having similar issues: [here](https://github.com/firebase/firebase-ios-sdk/issues/6520) is a thread from firebase. Here's my OneSignal install from the Podfile: 

```
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
```

Let me know if there's any information I'm missing out on.

**Comment by Erumaru** [comment]
Same here with cocoapods

**Comment by trevinwisaksana** [comment]
Hi,

I'm using OneSignal version 2.15.0 and I am having the same issue when I try to build on the simulator. I think OneSignal needs to add support arm64 simulators. 

To help you get a better understanding of what we need here is the folder inside OneSignal vs another third-party dependency (Crisp) that uses XCFramework.

<img width="760" alt="Screen Shot 2020-12-15 at 21 44 23" src="https://user-images.githubusercontent.com/20000813/102229810-c0bb4800-3f1e-11eb-94e3-f39b5c9e95c8.png">

<img width="757" alt="Screen Shot 2020-12-15 at 21 44 36" src="https://user-images.githubusercontent.com/20000813/102229833-c4e76580-3f1e-11eb-9518-ea9f8e923e9c.png">

Notice that OneSignal doesn't have arm64 simulator like Crisp.xcframework. It does have arm64 to be built on a device but not an arm64 simulator which is present on the M1 Macs. 

This is why I'm getting this error message:
`missing required architecture arm64 in file /Users/johnappleseed/Library/Developer/Xcode/DerivedData/AppName-gfokweabokxwszhigttygwyfrajj/Build/Products/Development-iphonesimulator/OneSignal.framework/OneSignal (2 slices)`

**Comment by emawby** [comment]
Hello we are working on this and it should be available in the next release. In the mean time are you able to run Xcode in Rosetta?

**Comment by cclaflin89** [comment]
Does XCFramework support M1 iPhone simulator now?
