### ISSUE TITLE
Specs satisfying the `OneSignal, OneSignal (~> 2.0)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by chapayGhub** [OneSignal/OneSignal-iOS-SDK#82]
Hey 
By default cocoapod install only 1.13 version
when I seted version manually I got next error:
```
[!] Unable to satisfy the following requirements:

- `OneSignal` required by `Podfile`
- `OneSignal (~> 2.0)` required by `Podfile`

Specs satisfying the `OneSignal, OneSignal (~> 2.0)` dependency were found, but they required a higher minimum deployment target.
```

My pod file started from
```
platform :ios, '8.0'
use_frameworks!
....
```

Please assist

**Comment by chapayGhub** [comment]
cocoapods version 1.0.1

<img width="719" alt="screen shot 2016-09-15 at 11 42 26" src="https://cloud.githubusercontent.com/assets/878464/18543654/89d75cfa-7b39-11e6-85a7-4a5503ad1330.png">

I runned `pod search OneSignal` with next result
<img width="1251" alt="screen shot 2016-09-15 at 11 42 17" src="https://cloud.githubusercontent.com/assets/878464/18543658/920006f2-7b39-11e6-84e5-0beb1cd37413.png">

**Comment by JKalash** [comment]
You should not set any version requirement. You may hjave downloaded our SDK long time ago which is why you're still on the 1.* version of the SDK. Instead, keep your podfile as: **pod 'OneSignal'** and run a **pod update** to get the latest version.
