### ISSUE TITLE
App is limited to a maximum of 10 tags on a given player error when sending 10 tags

### ISSUE THREAD

**Issue by revolter** [OneSignal/OneSignal-iOS-SDK#830]
**Description:**

Even though I'm sending exactly 10 tags, I'm seeing an error in the console.

**Environment**

Version: 2.16.0
Method: CocoaPods

**Steps to Reproduce Issue:**

```objc
[OneSignal sendTags:@{
	@"user_id": userId,
	@"purchase_state": purchaseState,
	@"mother_language": motherLanguage,
	@"target_language": targetLanguage,
	@"score": @(currentScore).stringValue,
	@"difficulty": difficultyLevelName,
	@"notifications": @(areNotificationsEnabled).stringValue,
	@"ab": abGroup,
	@"development": @(isDevelopmentBuild).stringValue,
	@"updated_at": @(updatedAt).stringValue
}];
```

**Anything else:**

(crash stacktraces, as well as any other information here)

```
2020-12-10 18:21:45.651738+0200 <redacted>[5415:1514189] VERBOSE: HTTP Request (OSRequestSendTagsToServer) with URL: https://api.onesignal.com/players/<redacted>, with parameters: {
  "net_type" : 0,
  "app_id" : "<redacted>",
  "tags" : {
    "development" : "1",
    "score" : "11676",
    "mother_language" : "fr",
    "target_language" : "es",
    "difficulty" : "intermediate",
    "user_id" : "<redacted>",
    "ab" : "even",
    "updated_at" : "1607617299",
    "purchase_state" : "subscription",
    "notifications" : "0"
  }
}
```

```
2020-12-10 18:21:45.901696+0200 <redacted>[5415:1514191] VERBOSE: network response (OSRequestSendTagsToServer): {
    errors =     (
        "App is limited to a maximum of 10 tags on a given player"
    );
    success = 0;
}
```

**Comment by tyang1** [comment]
Hi @revolter,
Thank you for providing the details and reaching out.
The issue may very likely be that you are targeting specific device that already has tag(s), and adding 10 more tags would reach over the tag limit as the error indicated.

Could you please reach out to our support team using support@onesignal.com email or our intercom chat within the onesignal.com dashboard or documentation in the bottom right corner?

Feel free to share this github link when you open the ticket, we would be happy to further assist.
