### ISSUE TITLE
[Crash] -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (OSIndirectNotification) for key (NS.objects)

### ISSUE THREAD

**Issue by MinakovPavel** [OneSignal/OneSignal-iOS-SDK#833]
**Description:**

I have a lot of crashes in firebase Crashlytics from OneSignal SDK

**Environment**

It is still reproduce with 2.16.0 OneSignal SDK version

**Steps to Reproduce Issue:**

Fatal Exception: NSInvalidUnarchiveOperationException
*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (OSIndirectNotification) for key (NS.objects) because no class named "OSIndirectNotification" was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target). If the class was renamed, use setClassName:forClass: to add a class translation mapping to NSKeyedUnarchiver

**Comment by emawby** [comment]
@MinakovPavel This issue was due to a faulty migration of a class stored in NSUserDefaults. This should be fixed in the latest versions of OneSignal

**Comment by marcosnovaesq** [comment]
aparently it got back on 3.10.1. Anyone? https://github.com/OneSignal/OneSignal-iOS-SDK/issues/1098
