### ISSUE TITLE
iOS - In-App Message "push prompt" is never sent to SDK

### ISSUE THREAD

**Issue by Andrewpk** [OneSignal/OneSignal-iOS-SDK#840]
**Description:**

Using the documentation available, setup a new project using Xcode 12 and the In-App Messaging "push prompt" for iOS and watch it never show up any devices.

**Environment**

1. Xcode 12.2. iOS deployment target 13.0
1. Swift Package Manager - OneSignal version 3.0.1

**Steps to Reproduce Issue:**

1. Install iOS SDK.
1. Initialize the SDK in didFinishLaunchingWithOptions:
1. Follow OneSignal's provided tutorial describing how to setup iOS In-App "Push Prompt"
1. Active IAM will never get shown on any device.

**Anything else:**
OneSignal.m around line 1819:
`if (results[@"push"][@"in_app_messages"]) {`
This never evaluates to true. The payload upon app start/resume usually looks something like this:

```
{
    push =     {
        id = "SOME-UUID";
        success = 1;
    };
}
```

When sending the IAM to a test device, it works fine. I've tried updating the SDK, followed all of the guidelines support gave me regarding the IAM, etc., and it never shows up. I'm using a single certificate for sandbox + production APNS, and I'm not using the new `App` protocol struct (I'm still using an `AppDelegate`).

This is one of the primary reasons to use IAM in my opinion and it's been broken for months.

**Comment by Andrewpk** [comment]
Update:

Removed `In-App Trigger` as seen here:

![](https://files.readme.io/167091c-Screen_Shot_2020-04-15_at_2.58.22_PM.png)

And just did "on app open" and I started seeing production users getting the IAM.
The entire time I never saw the IAM show up on my test device though.
```
+ (void)receivedInAppMessageJson:(NSArray<NSDictionary *> *)messagesJson {
    let messages = [NSMutableArray new];

    if (messagesJson) {
```

`messagesJson` was nil throughout on my test device.

**Comment by emawby** [comment]
@Andrewpk I apologize for the late response. If `if (results[@"push"][@"in_app_messages"]) {` never evaluates to true then it means that the IAM was deemed ineligible for that user (the user isn't a part of the included segment for the IAM). If you are still having this issue I would double check what segments are enabled for the IAMs

**Comment by emawby** [comment]
Closing for now. If this is still an issue please feel free to reopen
