### ISSUE TITLE
setLaunchOptions is not a function - Nativescript implementation

### ISSUE THREAD

**Issue by markosole** [OneSignal/OneSignal-iOS-SDK#844]
**Description:**
I am trying to run OneSignal on NativeScript app. Since plugins for Nativescript have not been updated and not supported by new iOS 14, I have to find a way to make it work.

**Environment**

1. iOS 14.2
2.Xcode 12
1. Onesignal SDK version 3.0.x

**Steps to Reproduce Issue:**

`
    // TnsOneSignal.setLaunchOptions(launchOptions);
    TnsOneSignal.setAppId("xxxxxxxxxxx-xxxxxxxxxxx-xxxxx-xxxxxx-xxxxxxx");

`
When I run this as above, I get error> **appId set, but please call setLaunchOptions(launchOptions) to complete OneSignal init!**

When I uncomment top line, I get error> **Error:  TypeError: TnsOneSignal.setLaunchOptions is not a function**

Can someone tell me what should I pass as **launchOptions** parameter, or how can I override it if possible. 
If I could create array (javascript) and pass it, but I have no clue what goes there as parameter.

Thanks for any help

**Anything else:**

Nothing more

**Comment by jkasten2** [comment]
@markosole Which of the two to NativeScript SDKs are you using?
https://documentation.onesignal.com/docs/nativescript-sdk-setup

If you can create a Github issue on their repo the original author might be able to help you there. You can also link the issue here after you create it and we can take a look.

**Comment by markosole** [comment]
Hi thanks for reply, I am using plugin which became outdated and is over 6 months now. I've forked it and added extra description for implementing on iOS 14. I've got it working and as you are aware Apple changed few bits and old approach does not work any more for new iOS. 
You can check it out here: [](https://github.com/markosole/nativescript-onesignal)

There is no other plugins in the wild which works on NativeScript, that I am aware of. Maybe could help others if you add link above to your documentation pages.

**Comment by jkasten2** [comment]
@markosole I am not familiar enough with NativeScript or the code base nativescript-onesignal to know where this method call gets bound to native Objective-C or Swift `TnsOneSignal.setLaunchOptions(launchOptions);`. If NativeScript does some kind of auto binding you might just be able to call `TnsOneSignal.initWithLaunchOptions(launchOptions)` instead as OneSignal-iOS-SDK does not have a `setLaunchOptions` method.

I noticed you have the following in your in your [README.md](https://github.com/markosole/nativescript-onesignal/blame/e9ecfb657e140513d42362c5d8dc212fb95a746f/README.md#L55):
```TypeScript
TnsOneSignal.initWithLaunchOptions({ kOSSettingsKeyAutoPrompt: true, kOSSettingsKeyInAppLaunchURL: true, kOSSettingsKeyInFocusDisplayOption: 2, kOSSettingsKeyProvidesAppNotificationSettings: true });
```

However I am guessing it should just be `TnsOneSignal.initWithLaunchOptions(launchOptions)` if NativeScript is doing some kind of auto-binding as noted above.

I recommend checking out the migration guides for the OneSignal native iOS which will help you with the `kOSSettingsKey*` flags and other changes:
https://documentation.onesignal.com/docs/mobile-2020-api-migration-guide

**Comment by markosole** [comment]
That is true, those bindings have changed and there is number of parameters expected on call.
`TnsOneSignal.initWithLaunchOptions(launchOptions)`
This does not work, launchOptions is not defined or does not contain all params needed (the exact list I've put there). I did try different combinations and this one worked and I left it as it is.

I am not that good in TS and it took me some time to figure out even that. :) There were many changes and this was best I could do in short period of time. It would be worth of creating completely new plugin for this. Things are changing rapidly and it's hard to keep up with Apple.

**Comment by jkasten2** [comment]
`launchOptions` the OneSignal SDK needs is actually the raw value iOS gives from `didFinishLaunchingWithOptions`.

The `kOSSettingsKey*` you are looking for are now setters on `OneSignal`.

Checkout Step 3 in the OneSignal iOS 2.x.x to 3.x.x migration guide:
https://documentation.onesignal.com/docs/step-by-step-ios-native-2x-to-300-upgrade-guide#step-3---update-onesignal-initialization-code

**Comment by markosole** [comment]
Thanks for direct URL, I will check it out. It's good to know as a new features are available in OneSignal 3, like in app messages etc. I've noticed that Notification permission prompt has been changed and I tried using new method (where I can configure how message is displayed) but it did not work. I'll have to dig into this deeper.

**Comment by rgomezp** [comment]
Is it okay to close this issue @markosole ?

**Comment by markosole** [comment]
@rgomezp yes sure.
