### ISSUE TITLE
Why I can't use presentAppSettings methdo in swift？

### ISSUE THREAD

**Issue by spirit-jsb** [OneSignal/OneSignal-iOS-SDK#846]
Why I can't use presentAppSettings methdo in swift？

1. What version of the iOS SDK are you using?
3.0.1
1. How did you add the SDK to your project (eg. cocoapods)
Swift Package Manager

In iOS_SDK/OneSignalSDK/Source/OneSignal.h WHT IT HAVE NOT presentAppSettings METHOD!!!!

**Comment by rgomezp** [comment]
Howdy,
The method no longer exists in version 3 of the SDK. Please take a look at our migration guide for more info: https://documentation.onesignal.com/docs/30-api-reference-ios#removed-methods

Thank you

**Comment by emawby** [comment]
See the documentation for `promptForPushNotificationsWithUserResponse:fallbackToSettings:` in the iOS SDK Reference [here](https://documentation.onesignal.com/docs/ios-native-sdk)
