### ISSUE TITLE
Documentation bug: iOS Prompting

### ISSUE THREAD

**Issue by iOSDevil** [OneSignal/OneSignal-iOS-SDK#847]
**Description:**
Version 7 of the documentation regarding prompting for APNS permission is not properly linked: https://documentation.onesignal.com/docs/ios-native-sdk#ios-push-prompting

**Environment**
SDK version 3.0.1
Cocoapods: 	pod 'OneSignal'

**Steps to Reproduce Issue:**
Read the documentation as provided by: https://documentation.onesignal.com/docs/ios-native-sdk#ios-push-prompting
(this bookmark also doesn't work).
Scroll down to "iOS Prompting"
Hyperlink "promptForPushNotificationsWithUserResponse" does not navigate to another part of the docs

Search for "promptForPushNotificationsWithUserResponse" within documentation and find:
https://documentation.onesignal.com/docs/ios-push-opt-in-prompt

The following objective-c code is suggested:
OSPermissionSubscriptionState* status = [OneSignal getPermissionSubscriptionState];
if (status.permissionStatus.hasPrompted == false) {
  [OneSignal addTrigger:@"prompt_ios" withValue:@"true"]
}

[OneSignal getPermissionSubscriptionState] results in error: "No known class method for getPermissionSubscriptionState"

**Comment by l-bimba** [comment]
I am also getting 

- Cannot find type 'OSPermissionSubscriptionState' in scope
- Type 'OneSignal' has no member 'setSubscription'
- Cannot find 'kOSSettingsKeyAutoPrompt' in scope

and etc. 

Having these errors after pod updates.

**Comment by iOSDevil** [comment]
That's what lead me to go through the documentation which turned out to be wrong, hence the bug 👍 
This is the code I swapped in:
    OSDeviceState *deviceState = [OneSignal getDeviceState];
    OSNotificationPermission osPermissions = deviceState.notificationPermissionStatus; // user id if user is registered, otherwise null
    if(osPermissions == OSNotificationPermissionDenied) {
        // do something
    } else {
        // do something else
    }

**Comment by rgomezp** [comment]
Howdy,
Thanks for opening the issue. Can you please also include which page links to that old URL?

The reason is the new major release includes many changes to the SDK, some of which _ARE_ breaking. Please make sure to review the migration guide carefully and update your code accordingly.


Cheers

[Migration Reference](https://documentation.onesignal.com/docs/mobile-2020-api-migration-guide)
---

**Comment by iOSDevil** [comment]
Breaking changes I found a way around.

The repro steps are valid.

Also, if you start at: https://documentation.onesignal.com/docs and scroll to the "Messaging Guides / Sending in-app messages / iOS Push Opt-In Prompt" you will find the Objective-C code is wrong:
OSPermissionSubscriptionState* status = [OneSignal getPermissionSubscriptionState];
if (status.permissionStatus.hasPrompted == false) {
  [OneSignal addTrigger:@"prompt_ios" withValue:@"true"]
}

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience. 

The [reference](https://documentation.onesignal.com/docs/ios-push-opt-in-prompt#trigger-the-prompt) has since been updated.

Enjoy!
