### ISSUE TITLE
How to disable "Would you like to open website?" alert?

### ISSUE THREAD

**Issue by bark1n9** [OneSignal/OneSignal-iOS-SDK#852]
Description:
Since 3.0, when a Launch URL is set on notification, OneSignal asks user if they want to open the website. Is there a way to disable this?

Environment
iOS: 3.1.0 SDK
CocoaPods

Steps to Reproduce Issue:
1- Set Launch URL when sending a notification.
2- Tap on the notification on device.
3- OneSignal will ask user "Would you like to open website?".

**Comment by bark1n9** [comment]
No one?

**Comment by KestasVenslauskas** [comment]
Same issue here

**Comment by rgomezp** [comment]
Duplicate of #777
