### ISSUE TITLE
Can't archive Mac catalyst app

### ISSUE THREAD

**Issue by Maxsix74** [OneSignal/OneSignal-iOS-SDK#860]
**Description:**
Can build and run with any iOS simulator and with My Mac. App runs shiny.
Can build and archive with any iOS Device (arm64) and send to Apple with no problem
Can't build and archive for any Mac (Apple Silicon, Intel) and can't send the app to Apple.

**Environment**
Xcode 12.3
cocoapods installed with --pre flag

on target 'app' podFile
pod 'OneSignalXCFramework', :git => 'https://github.com/OneSignal/OneSignal-iOS-SDK.git', :tag => '3.1.0'

target 'OneSignalNotificationServiceExtension' do
pod 'OneSignalXCFramework', :git => 'https://github.com/OneSignal/OneSignal-iOS-SDK.git', :tag => '3.1.0'
end

**Steps to Reproduce Issue:**
Just install in any app and try to archive it with Product -> Archive with "Any Mac" target setup.

**Comment by jkasten2** [comment]
@Maxsix74 I believe we have address this issue in the following release:
https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.2.0

Let us know if you are still seeing issues after updating.

**Comment by Maxsix74** [comment]
I’m sorry, but I’ve already migrate to FCM Firebase (and redone all support API for mine apps).

Good luck.
