### ISSUE TITLE
facing code sign failed with no zero digit

### ISSUE THREAD

**Issue by nomicool** [OneSignal/OneSignal-iOS-SDK#868]
code sign failed unabke to build chain self root of singer one onesignal profile
![Screenshot (109)](https://user-images.githubusercontent.com/25566185/106951789-068fd200-6752-11eb-93aa-60253d359cfe.png)

**Comment by jkasten2** [comment]
@nomicool It looks like Xcode wasn't able to sign the Notification Service Extension target you added. I recommend trying to enable "Automatically manage signing" on it and select your team to try to fix this issue.
![image](https://user-images.githubusercontent.com/645861/110612855-72949a00-8145-11eb-881c-714d7bc47545.png)

**Comment by rgomezp** [comment]
Closing due to no response
