### ISSUE TITLE
Version 2.1.10 is returning nil pushToken on IdsAvailable:

### ISSUE THREAD

**Issue by brunodelgado** [OneSignal/OneSignal-iOS-SDK#87]
After updating for 2.1.10 the class method `IdsAvailable:` is returning `pushToken` nil. 
It registers the user because `userId` is returning correctly but the user cannot receive push notifications once `pushToken` is not being sent.

<img width="811" alt="screen shot 2016-09-21 at 20 55 49" src="https://cloud.githubusercontent.com/assets/598889/18733021/fe0a6640-803d-11e6-8e2e-93e3d5d760c3.png">

Returning to version 2.1.9 everything works fine.

**Comment by JKalash** [comment]
Hi there,

How did you download our SDK? Try adding the following to your project's Other Linker Flags: **-ObjC** and let me know if it works for you.

**Comment by brunodelgado** [comment]
I'm using Cocoapods. It was already previous set -ObjC in the Other Linker Flags.
Using version 2.1.9 works as expected...

**Comment by 942v** [comment]
I'm seeing this also

**Comment by jawwad** [comment]
I'm experiencing this as well

**Comment by JKalash** [comment]
Can you check to make sure that you have the **Push Notification** _capability_ is turned on within your target. Also was the version upgrade assisted with an upgrade to Xcode 8?

**Comment by JKalash** [comment]
Another thing, could you output the error's _localizedDescription_ that is returned within the **_didFailToRegisterForRemoteNotifications_** ?

**Comment by JKalash** [comment]
Fixed as of [2.1.11](https://github.com/OneSignal/OneSignal-iOS-SDK/commit/2c0202648f9f1b1e42e7d8e17fbd3c0314f830e0)

**Comment by brunodelgado** [comment]
Just made some tests with the same configuration:

**2.1.09** 👍 

**2.1.10** 👎 

**2.1.11** 👍 

Good job!
