### ISSUE TITLE
[2.1.11] Custom Notification Sound Not Working !

### ISSUE THREAD

**Issue by Gorhom** [OneSignal/OneSignal-iOS-SDK#88]
since i updated my phone to iOS 10, i notice that my app notification sound is no longer the custom one i set! however, it only works when i deploy a new build then i have to restart the phone! 

this issue appears since version 2.1.10

thanks

**Comment by JKalash** [comment]
Hi there,

I tried reproducing the error but was not able to. You should:
- Make sure that the sound file is in the correct format. Try:
`afconvert -f caff -d LEI16@44100 -c 1 input.wav output.caf`
Make sure to replace the input and output with their proper name and extension.

Also, you should make sure the file s within the **copy bundle resources** phase of your app to make sure it's included in your target.
