### ISSUE TITLE
Notifications with repeating collapse_id duplicates on Apple Watch

### ISSUE THREAD

**Issue by ksloginov** [OneSignal/OneSignal-iOS-SDK#881]
**Description:**
I've noticed, that if you send a notification to your app, while the notification with same collapse_id hasn't been cleaned from Apple Watch's screen yet - notification arrives twice (or even 3 times in some occasions)

**Environment**
SDK: 2.16.1
Installation: SPM

**Steps to Reproduce Issue:**

1. Send yourself a message while watching at your Apple Watch.
 

```
curl -i -X POST \
   -H "Content-Type:application/json" \
   -H "Authorization:Basic <Your token>" \
   -d \
'{
  "app_id": "<Your app id>",
  "include_ios_tokens": [
    <your device token>
  ],
  "collapse_id": "1",
  "ios_category": "NEWS_CATEGORY",
  "apns_alert": {
    "loc-key": "OneSignal 🟢",
    "loc-args" : []
  },

  "contents": {
    "en": "OneSignal 🟢"
  },

  "ios_sound": "news.caf",
  "data": {}
}' \
 'https://onesignal.com/api/v1/notifications'
```

1. Send a message with the same collapse_id (to be sure that you're getting an updated notification - you could f.ex. change the text), w/o removing/closing the notification from the step 1.

**Result:**
The same, updated notification appears twice in a row (See the video!)
https://user-images.githubusercontent.com/1670172/108064132-896f3180-705c-11eb-9480-743313ec6ab7.mov

**Expected:**
Updated notification shows up once

**Comment by ksloginov** [comment]
Extra fun-fact: if you add a Service Extension into the app and this particular message has an `UNNotificationAttachment` attachment-thumbnail, instead of 2 repeats, it will be 3-4.

**Comment by emawby** [comment]
@ksloginov Is this only occurring on Apple Watch? This is an odd one and I am wondering if it is something with Apple Watch OS.

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by ksloginov** [comment]
@emawby  yes, only on AW. If it's AW OS issue or not - hard to say 😃 : I'd expect it to be more widely discussed if it was a common issue?
