### ISSUE TITLE
Still cannot build for iOS Simulator on M1 mac

### ISSUE THREAD

**Issue by halpz** [OneSignal/OneSignal-iOS-SDK#885]
when can we expect this to work? I will have to choose another product if this is not possible soon

**Comment by rgomezp** [comment]
Duplicate of #864

**Comment by halpz** [comment]
> Duplicate of #864

these issues are both closed, but are still present

**Comment by halpz** [comment]
they are also different issues, one related to intel haswell the other related to arm64 (M1)

**Comment by jasperblues** [comment]
I still can't build for iOS simulator, without excluding ARM64 for Simulator builds. And I have not enabled Mac Catalyst.
