### ISSUE TITLE
Carthage update - Xcode build timeout while trying to read OneSignalDemo.xcodeproj

### ISSUE THREAD

**Issue by pvcary** [OneSignal/OneSignal-iOS-SDK#886]
**Description:**

I am trying to run a Carthage update to 0.37 from 0.34 but each time I get the following error:

`*** Downloading OneSignal-iOS-SDK.framework binary at "3.2.1 Release"
xcodebuild timed out while trying to read OneSignalDemo.xcodeproj :sob:`

I'm using Xcode 12.4, with version 6.0 of the iOS SDK.

**Environment**

**Steps to Reproduce Issue:**

1. Run `carthage update --platform iOS`
1. Get timeout message each time
1. 

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by lesterfri** [comment]
I'm having the same issue with carthage version 0.37.0
`carthage update --platform iOS OneSignal-iOS-SDK  --use-xcframeworks --no-use-binaries`

Output:
`xcodebuild timed out while trying to read OneSignalDemo.xcodeproj 😭`

**Comment by shalinipk** [comment]
Rebooting Mac resolved the issue for me

**Comment by rgomezp** [comment]
Please give @shalinipk 's solution a try.

Enjoy!

**Comment by lesterfri** [comment]
That didn't work for me. Still seeing the same issue.

**Comment by emawby** [comment]
I am able to reproduce this but unfortunately I think it is a [bug with carthage](https://github.com/Carthage/Carthage/issues/3148), because we have our developer app in the same GitHub repo. I will keep an eye out for workarounds/a fix from carthage for this. I apologize for the inconvenience.
