### ISSUE TITLE
Notification badge count not incrementing correctly

### ISSUE THREAD

**Issue by GZaccaroni** [OneSignal/OneSignal-iOS-SDK#888]
**Description:**
Notification badge count not incrementing correctly

**Environment**

1. What version of the iOS SDK are you using? 3.2.0
1. How did you add the SDK to your project? cocoapods

**Steps to Reproduce Issue:**

1. A notification arrives. You do not open it. The badge reads 1.
1. Open and close the app without opening the notification. The badge goes back to zero.
1. Second notification arrives. The badge reads 2.
1. Open notification. The badge returns to 0.
1. Third notification arrives. The badge goes up to 3.

**Comment by rgomezp** [comment]
Howdy,
How are you currently handling badges?

This sounds like a good issue to reach out to our support channel at OneSignal.com about.

In any case, please see our reference for more information on [badge behavior](https://documentation.onesignal.com/docs/badges#ios-badge-behavior).

**Comment by GZaccaroni** [comment]
`OneSignal_disable_badge_clearing` is not enabled.

**Comment by ruanlinos** [comment]
Same issue here, I have checked everything, info.plist and the entitlements several times, they all match the tutorial proposed by Onesignal. I send a notification, it leaves the badge as 1, I enter the app, it clears the counter, I send another notification, it leaves the badge as 2 and the right would be 1.

**Comment by SidiBecker** [comment]
> Same issue here, I have checked everything, info.plist and the entitlements several times, they all match the tutorial proposed by Onesignal. I send a notification, it leaves the badge as 1, I enter the app, it clears the counter, I send another notification, it leaves the badge as 2 and the right would be 1.

I have the same issue!

**Comment by fabriciosautner** [comment]
same problem

**Comment by emawby** [comment]
Also can you please verify that your App Groups are setup correctly. It could be that your NSE and main App are not sharing an App group which means that the badge number won't be cleared properly from NSUserDefaults

**Comment by emawby** [comment]
closing for now. Please let us know if you are still experiencing this issue
