### ISSUE TITLE
No such module 'OneSignal' in Storyboard

### ISSUE THREAD

**Issue by cclaflin89** [OneSignal/OneSignal-iOS-SDK#889]
I'm getting this error in storyboard when refreshing designable views. But I can run the app without any issue.

OneSignal SDK version is 3.1.1 and running on silicon m1.

Right now I'm not able to see any custom designable views in storyboard.

![image](https://user-images.githubusercontent.com/39384394/109141712-462b5780-771b-11eb-8fc1-b5d8545a0a1f.png)

**Comment by emawby** [comment]
Hello that version of the SDK had an issue on M1 macs is this fixed on the latest version?

**Comment by rgomezp** [comment]
Closing due to no response
