### ISSUE TITLE
Cancel button localization

### ISSUE THREAD

**Issue by duduBaiao** [OneSignal/OneSignal-iOS-SDK#89]
Hi!

There is a way to localize the "Close" button caption?

It seems that this is not simple thing to do on static libraries, but if you create a bundle, we can just include a translated one in our apps.

**Comment by JKalash** [comment]
Hi there,

We currently do not offer support for cancel button localization. Alternatively, you could pass within the init settings:
**kOSSettingsKeyInFocusDisplayOption : @(None)**
and override the `OSHandleNotificationReceivedBlock` to display your custom `UIAlertView` instead.

Thanks.
