### ISSUE TITLE
Linking fails on M1 Mac 

### ISSUE THREAD

**Issue by iOSDevil** [OneSignal/OneSignal-iOS-SDK#902]
**Description:**
When building an iOS app (on latest Xcode on an M1 Mac) which uses Cocoapods the build fails with the following message:

ld: in /Users/**_/Dev/App/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/_**/Dev/App/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Environment**
M1 Mac
Xcode 12.4
cocoa pod usage: pod 'OneSignal'

The same project builds on an Intel Mac

**Comment by m-s-helala** [comment]
same here 😔

**Comment by jfishman1** [comment]
You will want to use OneSignal's XCFramework SDK: https://documentation.onesignal.com/docs/using-onesignals-xcframework-for-mac-catalyst

**Comment by iOSDevil** [comment]
Thanks! That works for me.
Had another issue with cocoapods updating but used: arch -x86_64 pod install

**Comment by mivewi** [comment]
It sadly does not work for me.

When I do:
pod install --repo-update

Terminal says:
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a target named `OneSignalNotificationServiceExtension` in project `App.xcodeproj`, did find `App`.

This is the content of my podfile:
platform :ios, '12.1'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CapacitorStorage', :path => '../../node_modules/@capacitor/storage'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsResources', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  # Add your Pods here
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end

**Comment by eugenedw** [comment]
Same here:

```
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a target named `OneSignalNotificationServiceExtension` in project `App.xcodeproj`, did find `App`.
```

Any thoughts on how to resolve?

**Comment by AlexDjenkov** [comment]
Why is this closed, since OneSignal still doesn't work with M1 and fails to link?

**Comment by BabyGeek** [comment]
I am on a Mac m1 using OneSignalXCFramework only and still not able to launch simulator because when I do it error "No module 'OneSignal' found" appears in my NotificationService.

Any ideas to help? I would like to be able to test the app on Previews and Simulators for responsiveness purposes.

Also the app is for iOS only

Here is my podFile

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'
use_frameworks!

project 'bearwww-ios',
  'Debug (Staging)' => :debug


target 'bearwww-ios' do
	pod 'Alamofire', '~> 5.5'
	pod 'KeychainAccess'
	pod 'Instabug'
	pod 'PromiseKit', '~> 6.15.3'
	pod 'Mantis', '~> 1.7.1'
	pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '7.1.3'
        pod 'SDWebImageSwiftUI'
        pod 'SDWebImageWebPCoder'
	pod "youtube-ios-player-helper"
	pod 'DailymotionPlayerSDK'
        pod "SwiftUIRefresh"
        pod 'SwiftDate'
	pod 'GoogleMaps'
	pod 'GooglePlaces'
        pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
        pod 'Purchases'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end
```

**Comment by emawby** [comment]
This line removes the arm64 architecture for simulators, which is the architecture your M1 mac is using for the simulator. `config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"`

**Comment by BabyGeek** [comment]
No, I have tried already and it didn't fix the error even after cleaning errors, deintegrate et re installing
