### ISSUE TITLE
UNNotificationServiceExtension

### ISSUE THREAD

**Issue by 942v** [OneSignal/OneSignal-iOS-SDK#91]
My UNNotificationServiceExtension never gets called.

If I don't send a URL in the Media field the notification the extension works but as soon as I add a valid URL the Service extension isn't called.

**Comment by JKalash** [comment]
Hi there,

Thank you for contacting OneSignal. We currently do not support sending both media alongside mutable-attachment. If you are simply trying to display a remote notification with Media attachment then you should not pass mutable-content flag as our SDK will automatically display the attachment for you. If you would like to make use of your UNNotificationServiceExtension then you should pass mutable-content and the URL in the additionalData field to fetch the remote media inside the extension.

Also you should make sure the update to the latest version of the iOS SDK (2.1.12) to make sure everything works properly.
