### ISSUE TITLE
Unable to get Push Token with Swift 3

### ISSUE THREAD

**Issue by stefolog** [OneSignal/OneSignal-iOS-SDK#92]
I have a project that we migrated to swift 3. Since then all devices appear as (No Push Token) in the All Users dashboard.

Tested with pod version: 2.1.10

**TL;DR**
There is difference between Data.description and NSData.description and the description property is used to convert the PushToken to String.

**Several tests:**
1. Checking idsAvailable:
```
        OneSignal.idsAvailable({ (userId, pushToken) in
            print(userId)
            print(pushToken)
        })
```
**Result:** pushToken is always nil.

2. Checking if application:didRegisterForRemoteNotificationsWithDeviceToken is called with proper token:
```
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        print("DEVICE TOKEN = \(deviceToken)")
    }
```
**Result:** deviceToken is not nil, so the configuration looks OK.

**Findings**
In your implementation, you are converting the token to string by using NSData.description method. This method returns string in the format: <..hex..>
However, using swift 3 application:didRegisterForRemoteNotificationsWithDeviceToken receives **Data** as parameter, and Data.description returns number of contained bytes (e.g. "32 bytes").

So my best guess is there is issue converting from Data to NSData or the other way around, and actually your code is trying to use "32 bytes" as token.

**Workaround**
For now I managed to fix the issue by registering the token myself in user defaults:
```
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {      
        UserDefaults.standard.set(deviceToken.hexDescription, forKey: "GT_DEVICE_TOKEN")
    }
```
And this is the extension for hexDescription
```
extension Data {
    var hexDescription: String {
        return reduce("") {$0 + String(format: "%02x", $1)}
    }
}
```

**Comment by JKalash** [comment]
Hi there,

You should upgrade to the latest [2.1.15](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.1.15) version as the no push token issue is due to a swizzling failure because of the -ObjC flag presence / absence. Let me know if that works for you.
