### ISSUE TITLE
Setting badge number within iOS app

### ISSUE THREAD

**Issue by zoufishanmehdi** [OneSignal/OneSignal-iOS-SDK#94]
Hi, push notifications are being created server side and then the iOS app receives them. How can I increment badge number each time a notification is received and clear it once the user clicks on the notification? I know you're supposed to use 'ios_badgeType' to "Increase" and 'ios_badgeCount' to 1, but it's not clear where this is set (i.e. method) within the app. Thanks!

**Comment by JKalash** [comment]
Hi there,

These are parameters that should be passed to the [Create Notification API](https://documentation.onesignal.com/reference#create-notification). Notifications are cleared when the user selects notifications by our SDK by setting the badge count to 0.
