### ISSUE TITLE
Unable to sign app

### ISSUE THREAD

**Issue by MrBenFTW** [OneSignal/OneSignal-iOS-SDK#945]
**Description:**
The app builds and runs perfectly, but when I go to submit it to the AppStore Xcode gives me this error:
`Code signing "NotificationService.appex" failed.`

**Environment**

I am using Xcode 12.5
I am building from iOS 13.0
I am using OneSignal 3.5.2
One signal is installed from Swift Package Manager

**Steps to Reproduce Issue:**

1. Archive the project
2. Distribute app to AppStore
3.
![image](https://user-images.githubusercontent.com/27426792/121782122-fc6a5e00-cb9f-11eb-9234-2e4097027af2.png)

**Anything else:**

(crash stacktraces, as well as any other information here)
[Aesther_2021-06-12_4-59-52.552 pm.xcdistributionlogs.zip](https://github.com/OneSignal/OneSignal-iOS-SDK/files/6642502/Aesther_2021-06-12_4-59-52.552.pm.xcdistributionlogs.zip)

I have tried deleting the extension and making a new one.

**Comment by emawby** [comment]
Hello! Does the app build and run only to a simulator or does it also build and run to a physical device? What is under the code signing section of the NotificationService target for your project?

**Comment by MrBenFTW** [comment]
It seems the issue is with MacOS Monterey and Xcode 13.
