### ISSUE TITLE
iOS 14 VOIP push notification not getting

### ISSUE THREAD

**Issue by shraddha-patel-1891** [OneSignal/OneSignal-iOS-SDK#946]
Hello all,

Currently, we are using Onesignal for push notifications. As per the apple update need an http/2 server for VOIP push notification so as per guideline we enabled http/2 support in our server but from one signal side failed to deliver the notification. So we need support for this.
Before ios 14 all things are working perfectly.
Anyone has an idea related to this then please help us.

Thank You.

**Comment by emawby** [comment]
Hello thank you for reporting. Can you please provide more information on the failure. Is the OneSignal dashboard reporting failed delivery? Does it only fail delivery to iOS 14 devices or does it fail to deliver to all devices?

**Comment by shraddha-patel-1891** [comment]
![Screenshot 2021-07-09 at 10 33 13 AM](https://user-images.githubusercontent.com/25505688/125025883-1add4f80-e0a1-11eb-978a-9468a400d916.png)

Faced in ios 14 only

**Comment by emawby** [comment]
@shraddha-patel-1891 is there a specific error message you are getting?

**Comment by shraddha-patel-1891** [comment]
@emawby 
Thank you for your answer.
We got a 2 solution from one signal support team like below
1. every time the app open need to set subscription 1 using SDK method
2.Add notification_type = 1 in add device API

**Comment by colurewebteam** [comment]
@shraddha-patel-1891  hi can you please let me know which method you used for a subscription? and how you solved this particular issue? I am having the same issue with VoIP push.

**Comment by shraddha-patel-1891** [comment]
Hi @colurewebteam 

we used the below method

func onOSSubscriptionChanged(_ stateChanges: OSSubscriptionStateChanges!) {
        if !stateChanges.from.isSubscribed && stateChanges.to.isSubscribed  {
            print("Subscribed for OneSignal push notifications!")
            // get player ID
            
            apns_onesig_playerid = stateChanges.to.userId!
            
            
            print("apns_onesig_playerid----> \(apns_onesig_playerid)")
            
        }
        print("SubscriptionStateChange: \n\(stateChanges)")
    }
    
    
    @colurewebteam  you can also use the below API
    https://documentation.onesignal.com/reference/add-a-device
    
    in this one parameter notification_type  so in which you can pass value 1.
    
Thank you.
