### ISSUE TITLE
[Crash] - OSPlayerTags deleteTags EXC_BREAKPOINT 0x00000001f4871234

### ISSUE THREAD

**Issue by susslik** [OneSignal/OneSignal-iOS-SDK#954]
**Description:**

There are crashes in our project Firebase Crashlytics linked to OneSignal SDK.

-[OSPlayerTags deleteTags:] + 4380570008

Crashed: rxswift.queue.DispatchQoS(qosClass: Dispatch.DispatchQoS.QoSClass.utility, relativePriority: 0)
EXC_BREAKPOINT 0x00000001f4871234

**Environment**
1. iOS 14.3, 14.5, 14.6, 14.7, 15.0;
2. CocoaPods
3.  OneSignal (3.5.2)

**Steps to Reproduce Issue:**
Sometimes after OneSignal.deleteTag("tag") called.

**Crash stacktrace:**
Crashed: rxswift.queue.DispatchQoS(qosClass: Dispatch.DispatchQoS.QoSClass.utility, relativePriority: 0)
0  libsystem_platform.dylib       0x1f4871234 _os_unfair_lock_corruption_abort + 36
1  libsystem_platform.dylib       0x1f486f148 _os_unfair_lock_lock_slow + 320
2  CoreFoundation                 0x1a8c55eb8 _cow_copy + 56
3  CoreFoundation                 0x1a8c00a8c -[__NSDictionaryM mutableCopyWithZone:] + 156
4  CoreFoundation                 0x1a8bf2800 +[NSDictionary dictionaryWithDictionary:] + 44
5  App                            0x1033ab198 -[OSPlayerTags deleteTags:] + 4380570008
6  App                            0x10339bfdc +[OneSignal deleteTags:onSuccess:onFailure:] + 4380508124
7  App                            0x10339bb74 +[OneSignal deleteTag:] + 4380506996

**Keys**
crash_info_entry_0                 BUG IN CLIENT OF LIBPLATFORM: os_unfair_lock is corrupt

**Comment by emawby** [comment]
Moved this stack trace to #953 and closing this as a duplicate
