### ISSUE TITLE
[Crash] OSPlayerTags deleteTags - SIGABRT ABORT 0x00000001bb41084c

### ISSUE THREAD

**Issue by susslik** [OneSignal/OneSignal-iOS-SDK#955]
**Description**

There are crashes in our project Firebase Crashlytics linked to OneSignal SDK.

-[OSPlayerTags deleteTags:] + 4336939652

Crashed: com.apple.main-thread
SIGABRT ABORT 0x00000001bb41084c

**Environment**

iOS 14.3, 14.5, 14.6, 14.7, 15.0;
CocoaPods
OneSignal (3.5.2)
Steps to Reproduce Issue:
Sometimes after OneSignal.deleteTag("tag") called.

**Crash stacktrace:**

Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x1bb41084c __pthread_kill + 8
1  libsystem_pthread.dylib        0x1d7c569e8 pthread_kill + 212
2  libsystem_c.dylib              0x19829f8f4 abort + 100
3  libsystem_malloc.dylib         0x19e955030 _malloc_put + 554
4  libsystem_malloc.dylib         0x19e9552a4 malloc_zone_error + 100
5  libsystem_malloc.dylib         0x19e955314 nanov2_allocate_from_block$VARIANT$armv81.cold.1 + 36
6  libsystem_malloc.dylib         0x19e93bb94 nanov2_find_block_and_allocate$VARIANT$armv81 + 498
7  libsystem_malloc.dylib         0x19e93ae24 nanov2_allocate$VARIANT$armv81 + 124
8  libsystem_malloc.dylib         0x19e93b314 nanov2_calloc$VARIANT$armv81 + 148
9  libsystem_malloc.dylib         0x19e94aaa4 _malloc_zone_calloc + 80
10 CoreFoundation                 0x18f4fdef4 _cow_create + 28
11 CoreFoundation                 0x18f4add28 -[__NSDictionaryM mutableCopyWithZone:] + 68
12 CoreFoundation                 0x18f4a0568 +[NSDictionary dictionaryWithDictionary:] + 40
13 App                            0x10080b284 -[OSPlayerTags deleteTags:] + 4336939652
14 App                            0x1007fbfdc +[OneSignal deleteTags:onSuccess:onFailure:] + 4336877532
15 App                            0x1007fbb74 +[OneSignal deleteTag:] + 4336876404

**Keys:**
crash_info_entry_0    abort() called
crash_info_entry_1     App(3668,0x101293880) malloc: Heap corruption detected, free list is damaged at 0x2813a3100 *** Incorrect guard value: 81733227642880
crash_info_entry_2     BUG IN CLIENT OF LIBPLATFORM: Unlock of an os_unfair_lock not owned by current thread

**Comment by emawby** [comment]
Moved this stack trace to #953 and closing this as a duplicate
