### ISSUE TITLE
[Crash] OSPlayerTags addTags - EXC_BREAKPOINT 0x00000001d5555234 

### ISSUE THREAD

**Issue by susslik** [OneSignal/OneSignal-iOS-SDK#956]
**Description**

There are crashes in our project Firebase Crashlytics linked to OneSignal SDK.

-[OSPlayerTags addTags:] + 4311904216

Crashed: com.apple.main-thread
EXC_BREAKPOINT 0x00000001d5555234

**Environment**

iOS 14.3, 14.5, 14.6, 14.7, 15.0;
CocoaPods
OneSignal (3.5.2)

**Steps to Reproduce Issue:**
Sometimes after OneSignal.deleteTag("tag") called.

**Crash stacktrace**
0  libsystem_platform.dylib       0x1d5555234 _os_unfair_lock_corruption_abort + 36
1  libsystem_platform.dylib       0x1d5553148 _os_unfair_lock_lock_slow + 320
2  CoreFoundation                 0x189939eb8 _cow_copy + 56
3  CoreFoundation                 0x1898e4a8c -[__NSDictionaryM mutableCopyWithZone:] + 156
4  CoreFoundation                 0x1898d6800 +[NSDictionary dictionaryWithDictionary:] + 44
5  App                            0x102ba6fd8 -[OSPlayerTags addTags:] + 4311904216
6  App                            0x102ba6f3c -[OSPlayerTags setTagsToSend:] + 4311904060
7  App                            0x102ba6ee0 -[OSPlayerTags addTagsToSend:] + 4311903968
8  App                            0x102b96f40 +[OneSignal sendTags:onSuccess:onFailure:] + 4311838528
9  App                            0x102b98008 +[OneSignal deleteTags:onSuccess:onFailure:] + 4311842824
10 App                            0x102b97b74 +[OneSignal deleteTag:] + 4311841652

**Keys**
crash_info_entry_0                         BUG IN CLIENT OF LIBPLATFORM: os_unfair_lock is corrupt

**Comment by emawby** [comment]
Moved this stack trace to #953 and closing this as a duplicate
