### ISSUE TITLE
[Crash] OneSignalExtensionBadgeHandler appGroupName - EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x000000016d163fe0

### ISSUE THREAD

**Issue by susslik** [OneSignal/OneSignal-iOS-SDK#957]
**Description**

There are crashes in our project Firebase Crashlytics linked to OneSignal SDK.

+[OneSignalExtensionBadgeHandler appGroupName] + 4341456640

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x000000016d163fe0

**Environment**

iOS 12.5, 14.3, 14.5, 14.6, 14.7, 15.0;
CocoaPods
OneSignal (3.5.2)

**Steps to Reproduce Issue**
Unable to reproduce by myself, but have a lot of reports at Crashlytics and Xcode organizer

**Crash stacktrace**
Crashed: com.apple.main-thread
0  libsystem_malloc.dylib         0x1a4476d64 nanov2_allocate_from_block + 8
1  libsystem_malloc.dylib         0x1a4475f40 nanov2_malloc + 64
2  libsystem_malloc.dylib         0x1a447a9a0 _malloc_zone_malloc + 152
3  CoreFoundation                 0x194e0b7e4 __CFStrAllocateMutableContents + 100
4  CoreFoundation                 0x194e0b070 __CFStringChangeSizeMultiple + 608
5  CoreFoundation                 0x194e05874 __CFStringAppendBytes + 708
6  CoreFoundation                 0x194df5160 __CFStringAppendFormatCore + 7524
7  CoreFoundation                 0x194df7284 _CFStringCreateWithFormatAndArgumentsReturningMetadata + 164
8  Foundation                     0x1960b66a4 +[NSString stringWithFormat:] + 76
9  App                            0x10312df00 +[OneSignalExtensionBadgeHandler appGroupName] + 4341456640
10 App                            0x103129c38 -[OneSignalUserDefaults getSharedUserDefault] + 4341439544
11 App                            0x103129bb4 +[OneSignalUserDefaults initShared] + 4341439412
12 App                            0x1030f9bd8 -[OSRemoteParamController isPrivacyConsentRequired] + 4341242840
13 App                            0x1030e0d18 +[OneSignal requiresUserPrivacyConsent] + 4341140760
14 App                            0x1030e0bbc +[OneSignal shouldLogMissingPrivacyConsentErrorWithMethodName:] + 4341140412
15 App                            0x10310e510 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 4341327120
16 App                            0x10310e658 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 4341327448
17 App                            0x10310e658 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 4341327448
18 App                            0x10310e658 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 4341327448
19 App                            0x10310e658 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 4341327448
20 App                            0x10310e658 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 4341327448
21 App                            0x10310e658 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 4341327448
22 App                            0x10310e658 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 4341327448
23 App                            0x10310e658 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 4341327448
24 App                            0x10310e658 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 4341327448
25 App                            0x10310e658 -[OneSignalUNUserNotificationCenter onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 4341327448
26 App                            0x102c09208 specialized NotificationService.process(response:from:with:) + 4336062984 (<compiler-generated>:4336062984)
27 App                            0x102bc1d7c closure #1 in AppModel.hideLaunchScreen(_:delay:) + 4335771004 (<compiler-generated>:4335771004)
28 App                            0x102bf6a44 thunk for @escaping @callee_guaranteed () -> () + 4335987268 (<compiler-generated>:4335987268)
29 libdispatch.dylib              0x194a41a84 _dispatch_call_block_and_release + 32
30 libdispatch.dylib              0x194a4381c _dispatch_client_callout + 20
31 libdispatch.dylib              0x194a51c70 _dispatch_main_queue_callback_4CF + 884
32 CoreFoundation                 0x194dd0398 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
33 CoreFoundation                 0x194dca270 __CFRunLoopRun + 2524
34 CoreFoundation                 0x194dc9360 CFRunLoopRunSpecific + 600
35 GraphicsServices               0x1ac407734 GSEventRunModal + 164
36 UIKitCore                      0x197844584 -[UIApplication _run] + 1072
37 UIKitCore                      0x197849df4 UIApplicationMain + 168
38 App                            0x102ba780c main + 23 (AppDelegate.swift:23)
39 libdyld.dylib                  0x194a85cf8 start + 4

**Comment by emawby** [comment]
Moved this stack trace to #953  and closing this as a duplicate
