### ISSUE TITLE
pod 'OneSignal' not installing latest version

### ISSUE THREAD

**Issue by alexandre-g** [OneSignal/OneSignal-iOS-SDK#96]
Hi, probably not an issue with OneSignal, but as others might face it, asking here:

When I specify `pod 'OneSignal'` in podfile and do a pod install, the version `- OneSignal (2.1.10)` is installed (can see in podfile.lock)

When I try to specify the version explicitly by `pod 'OneSignal', '2.1.15'` it fails to resolve, even though I can see it on cocoapods.org.

What am I doing wrong?

**Comment by JKalash** [comment]
Hi there,

You should run a **pod update** in order to get the latest version of our SDK (currently 2.1.16 as you can see [here](https://github.com/CocoaPods/Specs/blob/master/Specs/OneSignal/2.1.16/OneSignal.podspec.json) and [here](https://cocoapods.org/pods/OneSignal)).
