### ISSUE TITLE
'sharedApplication' is unavailable: not available on iOS (App Extension)

### ISSUE THREAD

**Issue by aregler** [OneSignal/OneSignal-iOS-SDK#965]
**Description:**

Since Xcode 13 beta 3 Swift Packages now require, that code referencing APIs annotated as unavailable for use in app extensions must now themselves be annotated as unavailable for use in application.

source: https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes

**Environment**

- Xcode 13 beta 3/4
- OneSignal added via SPM

**Steps to Reproduce Issue:**

1. Install the most actual Xcode 13 beta
2. Open the `xcodeproj` file from the OneSignal example project (or the attached one)
3. Add OneSignal via SPM
4. Correct the import statement for the appclip
5. compile the app

For simplicity the following steps are already performed in the following project. 
[OneSignalDevApp.zip](https://github.com/OneSignal/OneSignal-iOS-SDK/files/6890641/OneSignalDevApp.zip)

**Comment by chrysanthemun** [comment]
same issue

**Comment by emawby** [comment]
@aregler Thank you for the report I am investigating!

**Comment by emawby** [comment]
@aregler In the meantime you can try using our OneSignal-XCFramework swift package instead (it doesn't appear to have this issue in my testing). It is the same SDK, but is distributed as a binary XCFramework instead of being built on demand.

**Comment by aregler** [comment]
@emawby Didn't even notice that there's a XCFramework version of OS. But yeah no issues using the XCFramework 👌🏻 
Thank you 🙏🏻

**Comment by emawby** [comment]
The XCFramework Swift Package lives in a different GitHub Repository that can be found [here](https://github.com/OneSignal/OneSignal-XCFramework)

**Comment by aregler** [comment]
Hey @emawby! The XCFramework works well in the iOS simulator, but it doesn't on a device.
I separated the PushService into its own framework and embedded the static lib there.
The following error shows up when running the app on device:

> dyld: Library not loaded: @rpath/OneSignal.framework/OneSignal
  Referenced from: /private/var/containers/Bundle/Application/../myapp.app/Frameworks/PushNotificationService.framework/PushNotificationService
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/../myapp.app/Frameworks/PushNotificationService.framework/Frameworks/OneSignal.framework/OneSignal: code signature in (/private/var/containers/Bundle/Application/../myapp.app/Frameworks/PushNotificationService.framework/Frameworks/OneSignal.framework/OneSignal) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

I stumbled across https://stackoverflow.com/questions/58822981/signing-embedded-framework-not-working-in-xcode-11-2-1, but i am not sure if that's the same thing. In my understanding the OneSignal framework should still be a static lib. But it doesn't seem to be?

So i guess i need to wait for the fixed non-xc version.
Thanks for your help and have a nice day! ☀️

**Comment by emawby** [comment]
@aregler Apple's latest beta (13 beta 5) reverted the requirement that caused this issue in the non-XCFramework version so that version should not have the original issue. Regarding the XCFrameworks issue, they are odd and when archived usually show up as frameworks although the target is a library in our Package.swift

> You don’t need to annotate code as unavailable for use in application extensions if it references APIs annotated as unavailable for use in application extensions. This reverts a requirement that Xcode 13 Beta 3 introduced. (80615922) (FB9332020)
