### ISSUE TITLE
Sometimes getting error "No user with this id found" from setExternalUserId method and no notifications.

### ISSUE THREAD

**Issue by fanij** [OneSignal/OneSignal-iOS-SDK#966]
**Description:**
Sometimes application is not receiving notifications and in the log is printed:

```
Request <OSRequestUpdateExternalUserId: 0x2800085a0> fail result error Error Domain=OneSignalError Code=400 "(null)" UserInfo={returned={
    errors =     (
        "No user with this id found"
    );
}}
```

Testing multiple times, most of the time everything is ok, and at random times we get the above error and no notifications.

**Environment**
1. OneSignal (3.6.0) version of SDK
2. added to project with cocoapods

**Steps to Reproduce Issue:**

  1. Install iOS SDK version 3.6.0 with Cocoapods into a project
  2. Initialize the SDK in didFinishLaunchingWithOptions:
  3. Set appID in setAppId method.
  4. Set userID in setExternalUserId method. 
  5. Result: Sometimes not getting notifications and the log is showing error: 
  
```
  Request <OSRequestUpdateExternalUserId: 0x2800085a0> fail result error Error Domain=OneSignalError Code=400 "(null)" UserInfo={returned={
    errors =     (
        "No user with this id found"
    );
  }}
```

**Anything else:**

Testing with setting multiple appID-s, and getting the same error: 
  1. Install iOS SDK version 3.6.0 with Cocoapods into a project
  2. Initialize the SDK in didFinishLaunchingWithOptions:
  3. Set appID in setAppId method.
  4. Set userID in setExternalUserId method. 
  5. Set another appID in setAppId method.
  6. Set another userID in setExternalUserId method. 
  7. Result: Sometimes not getting notifications and log is showing same error from above.

**Comment by emawby** [comment]
@fanij Thank you for the report I am investigating! In the meantime you can try using moving the setExternalUserId call to inside of the [`onOSSubscriptionChanged`](https://documentation.onesignal.com/docs/sdk-reference#addsubscriptionobserver-method) method when the new state's userID isn't nil.

**Comment by fanij** [comment]
Thanks for the quick response!

I tested 'onOSSubscriptionChanged' method and got the following result:

In cases when everything is OK I call 'setAppId' method, and then 'onOSSubscriptionChanged' is called with SubscriptionStateChange (stateChanges.to.isSubscribed) is true.

But sometimes I call 'setAppId' method, and 'onOSSubscriptionChanged' is never called. I wait some time but is not called.
In those cases if I call setExternalUserId I get the error: 

```
Request <OSRequestUpdateExternalUserId: 0x2800085a0> fail result error Error Domain=OneSignalError Code=400 "(null)" UserInfo={returned={
    errors =     (
        "No user with this id found"
    );
  }}
```

This is my current initialization code (it is called in didFinishLaunchingWithOptions AppDelegate method):

```
static func oneSignalInit( launchOptions: [UIApplicationLaunchOptionsKey: Any]?){
        
#if DEBUG
        OneSignal.setLogLevel(.LL_VERBOSE, visualLevel: .LL_NONE)
#endif
        let osNotificationOpenedBlock: OSNotificationOpenedBlock = { result in
            let payload = result.notification.rawPayload

            if let additionalData = result.notification.additionalData {
                // proccessOneSignalNotification
            }
        }

        OneSignal.initWithLaunchOptions(launchOptions)
        OneSignal.setNotificationOpenedHandler(osNotificationOpenedBlock)
    }
```

After user logges in we call prompt accept notifications:
     

```
OneSignal.promptForPushNotifications(userResponse: { accepted in      
           
        })
```



We use more than one AppId. 
After a user selects a partner we call 'setAppId' method.
After that when the user made a login we call 'setExternalUserId' method.

**Comment by emawby** [comment]
@fanij Gotcha in the cases where `onOSSubscriptionChanged` is never called do you get either/both of the following lines in the log with verbose logging on: 
`Firing registerForRemoteNotifications`
`INFO: Device Registered with Apple:`

**Comment by emawby** [comment]
@fanij Thank you for the log. I see the issue and will work on a fix for this!

**Comment by emawby** [comment]
@fanji From the reproduction steps you provided in seems like your app is trying to use different App ids within the same App (which means different users as far as OneSignal is aware) for your different partners. This is a workflow that OneSignal isn't handling well right now and will not be a simple change, but it is on our radar.

How likely is it that your users will be logging in and out between the partners. If it is a case where they select a partner on initial install and never change it then this issue should not affect your customers.
