### ISSUE TITLE
Missing checks for NULL returned by malloc(3)

### ISSUE THREAD

**Issue by patrickhartling** [OneSignal/OneSignal-iOS-SDK#967]
**Description:**

A scan of our application code, including the OneSignal iOS SDK, resulted in the identification of two missing return value checks:

 1. Line 333 of `OneSignalLocation.m`
 1. Line 115 of `OneSignalSelectorHelpers.m`

In both cases, memory is being allocated dynamically, but there is no check for the return value being `NULL`. For reference, the report includes a callout to [CWE-252](https://cwe.mitre.org/data/definitions/252.html) and to [OWASP](https://owasp.org/www-community/Improper_Error_Handling) with respect to both.

**Environment**
1. SDK version 3.2.1 through 3.6.0
2. Added to project using Carthage
3. Build with Xcode 12.4

**Steps to Reproduce Issue:**
N/A

**Anything else:**
We have not seen any crashes related to either case.

**Comment by emawby** [comment]
@patrickhartling Thank you for the report I will get a fix for these two spots
