### ISSUE TITLE
Error Flutter Android Studio MAC OneSignalSDK/Framework

### ISSUE THREAD

**Issue by duartemcmarques** [OneSignal/OneSignal-iOS-SDK#974]
hello, can anyone help me?

I'm trying to run an application for testing but it always gives an error I've reinstalled the pod's

Run:

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           30,4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    ld: in /Users/username/fluxnews-210/codecanyon-24569377-fluxnews-fluxnews-flutter-mobile-app-for-wordpress/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/username/fluxnews-210/codecanyon-24569377-fluxnews-fluxnews-flutter-mobile-app-for-wordpress/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

**Comment by emawby** [comment]
@duartemcmarques Hello, are you using [OneSignal's Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK)? If not please try that SDK. If you are please provide your version and podfile

**Comment by duartemcmarques** [comment]
Hy,
It's ok, it was some error related to the pod.
I do a pod deintegrate and install  cocoapods with dependences and it worked

Thank you!
