### ISSUE TITLE
.framework file is not available

### ISSUE THREAD

**Issue by kamendo** [OneSignal/OneSignal-iOS-SDK#98]
Hello, do you have only pods and carthage support?
My project does not use any of them, where can I find the .framework file?

**Comment by JKalash** [comment]
Hi @kamendo 

You can clone our repo and find the .framework through `iOS_SDK/Frameworks` as you can see [here](https://github.com/OneSignal/OneSignal-iOS-SDK/tree/master/iOS_SDK/Framework/OneSignal.framework).
