### ISSUE TITLE
erorr LC_VERSION_MIN_IPHONEOS  from appstore by email

### ISSUE THREAD

**Issue by yousifk** [OneSignal/OneSignal-iOS-SDK#986]
I get this email after i use  onesignal_flutter: ^3.2.2

<html>
<body>

 
--
 
Dear Developer,We identified one or more issues with a recent submission for App Store review for your app, "Storeak Admin" 1.2.1 (121). Please correct the following issues, then upload again.ITMS-90512: Invalid sdk value - The value provided for the sdk portion of LC_VERSION_MIN_IPHONEOS in Runner.app/Frameworks/OneSignal.framework/OneSignal is 15.0 which is greater than the maximum allowed value of 14.7.Best regards,The App Store Team

</body>
</html>

**Comment by emawby** [comment]
@yousifk Thank you for reporting I am investigating

**Comment by youssefali424** [comment]
the same issue started happening with the last update 3 days ago, all good except on the app store review

**Comment by emawby** [comment]
My guess is that the binary was built using the beta Xcode 13 build tools and this automatically sets the min version to 15 despite the build settings specifying iOS 9.0

**Comment by youssefali424** [comment]
had the same guess then built it through Xcode 12.5 same issue happened, how it is automatically adding min version ?

**Comment by emawby** [comment]
@youssefali424 did you rebuild the OneSignal framework itself or just your App?

**Comment by youssefali424** [comment]
rebuild both and clearing pods and making sure the deployment target for one signal is far less than 15, btw I uploaded a version 4 days ago with no issue at all it started happening with 3.6.2, I will try to downgrade it later by specifically using lower version and try
