### ISSUE TITLE
Unreachable

### ISSUE THREAD

**Issue by onmyway133** [OneSignal/OneSignal-iOS-SDK#99]
Hi, when sending a push using OneSignal, you show `Unreachable` in the push notification result page

> Notifications failed to be delivered to this number of devices because the device has uninstalled your app or unsubscribed from notifications

Sometimes this is not correct. Because in those cases we can send push directly with that device token to APNS using Restful, Parse or other testing tools.

Hope you can look into this. Thanks

**Comment by JKalash** [comment]
Hi @onmyway133 

We're taking a look in to the issue. Will get back to you with more.

**Comment by JKalash** [comment]
Hi @onmyway133 

This looks like an issue with us incrementing the wrong counter for the dashboard when we get a "bad topic" or "disallowed topic" error. The devices don't get marked as unreachable. This does raise the question of why the topic is incorrect. VOIP app? Maybe you used the VOIP API? We have a regular cert.

**Comment by onmyway133** [comment]
@JKalash Hi, thanks for your prompt reply. What do you mean by `topic`? We don't use any VOIP API

**Comment by jkasten2** [comment]
@onmyway133 The `DeviceTokenNotForTopic` error from Apple's APNs server mean the bundle id on the .p12 push certificate do  not match the app's bundle id.
https://documentation.onesignal.com/docs/mismatched-bundle-id

There are VoIP push notification, these are only obtained through `PushKit` so this most likely does not apply to your app.

I recommend contacting OneSignal support directly with some player_ids and push tokens you are seeing this issue with so they can check it on your account.

Thanks.

**Comment by onmyway133** [comment]
@jkasten2 Hi, thanks for replying. But my problem is it works for a while, then stops working. If it is because of bundle ID, then it should be consistently not working, right?

**Comment by jkasten2** [comment]
@onmyway133 Are you uninstalling your app then reinstalling it? You will get a new push token each time this happens and the old one will stop working. You can contact OneSignal support with your player_ids and they can verify this.
