### ISSUE TITLE
-[OSInAppMessage initWithCoder:]: unrecognized selector sent to instance 0x2830b92d0

### ISSUE THREAD

**Issue by hikky2014** [OneSignal/OneSignal-iOS-SDK#996]
sdk version: 3.7.0
Crashed when launching the app,  -[OSInAppMessage initWithCoder:]: unrecognized selector issue

CoreFoundation 	___exceptionPreprocess + 216
libobjc.A.dylib          _objc_exception_throw + 56
CoreFoundation 	-[NSOrderedSet initWithSet:copyItems:]
CoreFoundation 	____forwarding___ + 1440
CoreFoundation 	__CF_forwarding_prep_0 + 92
Foundation 		__decodeObjectBinary + 2284
Foundation 		-[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 680
Foundation 		-[NSArray(NSArray) initWithCoder:] + 172
Foundation 		__decodeObjectBinary + 2284
Foundation 		__decodeObject + 176
CoreFoundation 	-[NSKeyedUnarchiver decodeObjectForKey:] + 172
Foundation 		+[NSKeyedUnarchiver unarchiveObjectWithData:] + 80
MyApp 			-[OneSignalUserDefaults getSavedCodeableDataForKey:defaultValue:] + 160
MyApp 			-[OSMessagingController init] + 188
MyApp			+[OSMessagingController sharedInstance]_block_invoke + 60
libdispatch.dylib     __dispatch_client_callout + 16
libdispatch.dylib     __dispatch_once_callout + 28

MyApp			+[OSMessagingController sharedInstance] + 112
MyApp			-[OneSignalLifecycleObserver didBecomeActive] + 148
CoreFoundation 	___CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
UIKitCore 		_UIApplicationMain + 164
MyApp			main (main.m:14)
libdyld.dylib 	        _start + 4

**Comment by emawby** [comment]
@hikky2014 Thank you for reporting this issue, we are in the process of fixing this internally. Are you able to reproduce this issue? It would need to be when upgrading to a version with 3.7.0 on a device that was previously on a version lower than 3.7.0 and that had received In App Messages

**Comment by hikky2014** [comment]
> @hikky2014 Thank you for reporting this issue, we are in the process of fixing this internally. Are you able to reproduce this issue? It would need to be when upgrading to a version with 3.7.0 on a device that was previously on a version lower than 3.7.0 and that had received In App Messages

yeah,  This problem occurs when upgrading SDK from a lower version(3.5.x) to 3.7.0，after upgrading the old app

**Comment by emawby** [comment]
@hikky2014 Are you able to reproduce the issue? Was this crash reported from a crash reporting tool or did you experience it?
